"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.config = void 0;
var _styledComponents = /*#__PURE__*/require("@salutejs/plasma-new-hope/styled-components");
var _templateObject, _templateObject2, _templateObject3, _templateObject4, _templateObject5, _templateObject6, _templateObject7, _templateObject8, _templateObject9, _templateObject10, _templateObject11, _templateObject12, _templateObject13, _templateObject14, _templateObject15, _templateObject16, _templateObject17, _templateObject18;
function _taggedTemplateLiteral(strings, raw) { if (!raw) { raw = strings.slice(0); } return Object.freeze(Object.defineProperties(strings, { raw: { value: Object.freeze(raw) } })); }
var config = exports.config = {
  defaults: {
    view: 'default',
    focused: 'true',
    size: 'm'
  },
  variations: {
    view: {
      "default": /*#__PURE__*/(0, _styledComponents.css)(_templateObject || (_templateObject = /*#__PURE__*/_taggedTemplateLiteral(["\n                ", ": var(--inverse-text-primary);\n                ", ": var(--surface-solid-default);\n                ", ": var(--inverse-text-primary);\n                ", ": color-mix(\n                    in srgb,\n                    var(--inverse-text-primary),\n                    var(--surface-solid-default) 85%\n                );\n                ", ": var(--inverse-text-primary);\n                ", ": color-mix(\n                    in srgb,\n                    var(--inverse-text-primary),\n                    var(--surface-solid-default) 80%\n                );\n            "])), _styledComponents.buttonTokens.buttonColor, _styledComponents.buttonTokens.buttonBackgroundColor, _styledComponents.buttonTokens.buttonColorHover, _styledComponents.buttonTokens.buttonBackgroundColorHover, _styledComponents.buttonTokens.buttonColorActive, _styledComponents.buttonTokens.buttonBackgroundColorActive),
      primary: /*#__PURE__*/(0, _styledComponents.css)(_templateObject2 || (_templateObject2 = /*#__PURE__*/_taggedTemplateLiteral(["\n                ", ": var(--on-dark-text-primary);\n                ", ": var(--surface-accent);\n                ", ": var(--on-dark-text-primary);\n                ", ": color-mix(in srgb, var(--text-primary), var(--surface-accent) 85%);\n                ", ": var(--on-dark-text-primary);\n                ", ": color-mix(in srgb, var(--text-primary), var(--surface-accent) 80%);\n            "])), _styledComponents.buttonTokens.buttonColor, _styledComponents.buttonTokens.buttonBackgroundColor, _styledComponents.buttonTokens.buttonColorHover, _styledComponents.buttonTokens.buttonBackgroundColorHover, _styledComponents.buttonTokens.buttonColorActive, _styledComponents.buttonTokens.buttonBackgroundColorActive),
      secondary: /*#__PURE__*/(0, _styledComponents.css)(_templateObject3 || (_templateObject3 = /*#__PURE__*/_taggedTemplateLiteral(["\n                ", ": var(--text-primary);\n                ", ": var(--surface-transparent-secondary);\n                ", ": var(--text-primary);\n                ", ": color-mix(\n                    in srgb,\n                    var(--inverse-text-primary),\n                    var(--surface-transparent-secondary) 85%\n                );\n                ", ": var(--text-primary);\n                ", ": color-mix(\n                    in srgb,\n                    var(--inverse-text-primary),\n                    var(--surface-transparent-secondary) 80%\n                );\n            "])), _styledComponents.buttonTokens.buttonColor, _styledComponents.buttonTokens.buttonBackgroundColor, _styledComponents.buttonTokens.buttonColorHover, _styledComponents.buttonTokens.buttonBackgroundColorHover, _styledComponents.buttonTokens.buttonColorActive, _styledComponents.buttonTokens.buttonBackgroundColorActive),
      clear: /*#__PURE__*/(0, _styledComponents.css)(_templateObject4 || (_templateObject4 = /*#__PURE__*/_taggedTemplateLiteral(["\n                ", ": var(--text-primary);\n                ", ": var(--surface-clear);\n                ", ": var(--text-primary);\n                ", ": color-mix(in srgb, var(--text-primary), var(--surface-clear) 95%);\n                ", ": var(--text-primary);\n                ", ": color-mix(in srgb, var(--text-primary), var(--surface-clear) 90%);\n            "])), _styledComponents.buttonTokens.buttonColor, _styledComponents.buttonTokens.buttonBackgroundColor, _styledComponents.buttonTokens.buttonColorHover, _styledComponents.buttonTokens.buttonBackgroundColorHover, _styledComponents.buttonTokens.buttonColorActive, _styledComponents.buttonTokens.buttonBackgroundColorActive),
      success: /*#__PURE__*/(0, _styledComponents.css)(_templateObject5 || (_templateObject5 = /*#__PURE__*/_taggedTemplateLiteral(["\n                ", ": var(--on-dark-text-primary);\n                ", ": var(--surface-positive);\n                ", ": var(--on-dark-text-primary);\n                ", ": color-mix(\n                    in srgb,\n                    var(--inverse-text-primary),\n                    var(--surface-positive) 85%\n                );\n                ", ": var(--on-dark-text-primary);\n                ", ": color-mix(in srgb, var(--text-primary), var(--surface-positive) 85%);\n            "])), _styledComponents.buttonTokens.buttonColor, _styledComponents.buttonTokens.buttonBackgroundColor, _styledComponents.buttonTokens.buttonColorHover, _styledComponents.buttonTokens.buttonBackgroundColorHover, _styledComponents.buttonTokens.buttonColorActive, _styledComponents.buttonTokens.buttonBackgroundColorActive),
      warning: /*#__PURE__*/(0, _styledComponents.css)(_templateObject6 || (_templateObject6 = /*#__PURE__*/_taggedTemplateLiteral(["\n                ", ": var(--on-dark-text-primary);\n                ", ": var(--surface-warning);\n                ", ": var(--on-dark-text-primary);\n                ", ": color-mix(\n                    in srgb,\n                    var(--inverse-text-primary),\n                    var(--surface-warning) 85%\n                );\n                ", ": var(--on-dark-text-primary);\n                ", ": color-mix(in srgb, var(--text-primary), var(--surface-warning) 85%);\n            "])), _styledComponents.buttonTokens.buttonColor, _styledComponents.buttonTokens.buttonBackgroundColor, _styledComponents.buttonTokens.buttonColorHover, _styledComponents.buttonTokens.buttonBackgroundColorHover, _styledComponents.buttonTokens.buttonColorActive, _styledComponents.buttonTokens.buttonBackgroundColorActive),
      critical: /*#__PURE__*/(0, _styledComponents.css)(_templateObject7 || (_templateObject7 = /*#__PURE__*/_taggedTemplateLiteral(["\n                ", ": var(--on-dark-text-primary);\n                ", ": var(--surface-negative);\n                ", ": var(--on-dark-text-primary);\n                ", ": color-mix(\n                    in srgb,\n                    var(--inverse-text-primary),\n                    var(--surface-negative) 85%\n                );\n                ", ": var(--on-dark-text-primary);\n                ", ": color-mix(in srgb, var(--text-primary), var(--surface-negative) 85%);\n            "])), _styledComponents.buttonTokens.buttonColor, _styledComponents.buttonTokens.buttonBackgroundColor, _styledComponents.buttonTokens.buttonColorHover, _styledComponents.buttonTokens.buttonBackgroundColorHover, _styledComponents.buttonTokens.buttonColorActive, _styledComponents.buttonTokens.buttonBackgroundColorActive)
    },
    size: {
      l: /*#__PURE__*/(0, _styledComponents.css)(_templateObject8 || (_templateObject8 = /*#__PURE__*/_taggedTemplateLiteral(["\n                ", ": 3.5rem;\n                ", ": 1.5rem;\n                ", ": 0.875rem;\n\n                ", ": var(--plasma-typo-body-l-font-family);\n                ", ": var(--plasma-typo-body-l-font-size);\n                ", ": var(--plasma-typo-body-l-font-style);\n                ", ": var(--plasma-typo-body-l-bold-font-weight);\n                ", ": var(--plasma-typo-body-l-letter-spacing);\n                ", ": var(--plasma-typo-body-l-line-height);\n            "])), _styledComponents.buttonTokens.buttonHeight, _styledComponents.buttonTokens.buttonPadding, _styledComponents.buttonTokens.buttonRadius, _styledComponents.buttonTokens.buttonFontFamily, _styledComponents.buttonTokens.buttonFontSize, _styledComponents.buttonTokens.buttonFontStyle, _styledComponents.buttonTokens.buttonFontWeight, _styledComponents.buttonTokens.buttonLetterSpacing, _styledComponents.buttonTokens.buttonLineHeight),
      lr: /*#__PURE__*/(0, _styledComponents.css)(_templateObject9 || (_templateObject9 = /*#__PURE__*/_taggedTemplateLiteral(["\n                ", ": 3.5rem;\n\n                ", ": var(--plasma-typo-body-l-font-family);\n                ", ": var(--plasma-typo-body-l-font-size);\n                ", ": var(--plasma-typo-body-l-font-style);\n                ", ": var(--plasma-typo-body-l-bold-font-weight);\n                ", ": var(--plasma-typo-body-l-letter-spacing);\n                ", ": var(--plasma-typo-body-l-line-height);\n            "])), _styledComponents.buttonTokens.buttonHeight, _styledComponents.buttonTokens.buttonFontFamily, _styledComponents.buttonTokens.buttonFontSize, _styledComponents.buttonTokens.buttonFontStyle, _styledComponents.buttonTokens.buttonFontWeight, _styledComponents.buttonTokens.buttonLetterSpacing, _styledComponents.buttonTokens.buttonLineHeight),
      m: /*#__PURE__*/(0, _styledComponents.css)(_templateObject10 || (_templateObject10 = /*#__PURE__*/_taggedTemplateLiteral(["\n                ", ": 3rem;\n                ", ": 1.25rem;\n                ", ": 0.75rem;\n\n                ", ": var(--plasma-typo-body-m-font-family);\n                ", ": var(--plasma-typo-body-m-font-size);\n                ", ": var(--plasma-typo-body-m-font-style);\n                ", ": var(--plasma-typo-body-m-bold-font-weight);\n                ", ": var(--plasma-typo-body-m-letter-spacing);\n                ", ": var(--plasma-typo-body-m-line-height);\n            "])), _styledComponents.buttonTokens.buttonHeight, _styledComponents.buttonTokens.buttonPadding, _styledComponents.buttonTokens.buttonRadius, _styledComponents.buttonTokens.buttonFontFamily, _styledComponents.buttonTokens.buttonFontSize, _styledComponents.buttonTokens.buttonFontStyle, _styledComponents.buttonTokens.buttonFontWeight, _styledComponents.buttonTokens.buttonLetterSpacing, _styledComponents.buttonTokens.buttonLineHeight),
      mr: /*#__PURE__*/(0, _styledComponents.css)(_templateObject11 || (_templateObject11 = /*#__PURE__*/_taggedTemplateLiteral(["\n                ", ": 3rem;\n\n                ", ": var(--plasma-typo-body-m-font-family);\n                ", ": var(--plasma-typo-body-m-font-size);\n                ", ": var(--plasma-typo-body-m-font-style);\n                ", ": var(--plasma-typo-body-m-bold-font-weight);\n                ", ": var(--plasma-typo-body-m-letter-spacing);\n                ", ": var(--plasma-typo-body-m-line-height);\n            "])), _styledComponents.buttonTokens.buttonHeight, _styledComponents.buttonTokens.buttonFontFamily, _styledComponents.buttonTokens.buttonFontSize, _styledComponents.buttonTokens.buttonFontStyle, _styledComponents.buttonTokens.buttonFontWeight, _styledComponents.buttonTokens.buttonLetterSpacing, _styledComponents.buttonTokens.buttonLineHeight),
      s: /*#__PURE__*/(0, _styledComponents.css)(_templateObject12 || (_templateObject12 = /*#__PURE__*/_taggedTemplateLiteral(["\n                ", ": 2.5rem;\n                ", ": 1rem;\n                ", ": 0.625rem;\n\n                ", ": var(--plasma-typo-body-s-font-family);\n                ", ": var(--plasma-typo-body-s-font-size);\n                ", ": var(--plasma-typo-body-s-font-style);\n                ", ": var(--plasma-typo-body-s-bold-font-weight);\n                ", ": var(--plasma-typo-body-s-letter-spacing);\n                ", ": var(--plasma-typo-body-s-line-height);\n            "])), _styledComponents.buttonTokens.buttonHeight, _styledComponents.buttonTokens.buttonPadding, _styledComponents.buttonTokens.buttonRadius, _styledComponents.buttonTokens.buttonFontFamily, _styledComponents.buttonTokens.buttonFontSize, _styledComponents.buttonTokens.buttonFontStyle, _styledComponents.buttonTokens.buttonFontWeight, _styledComponents.buttonTokens.buttonLetterSpacing, _styledComponents.buttonTokens.buttonLineHeight),
      sr: /*#__PURE__*/(0, _styledComponents.css)(_templateObject13 || (_templateObject13 = /*#__PURE__*/_taggedTemplateLiteral(["\n                ", ": 2.5rem;\n\n                ", ": var(--plasma-typo-body-s-font-family);\n                ", ": var(--plasma-typo-body-s-font-size);\n                ", ": var(--plasma-typo-body-s-font-style);\n                ", ": var(--plasma-typo-body-s-bold-font-weight);\n                ", ": var(--plasma-typo-body-s-letter-spacing);\n                ", ": var(--plasma-typo-body-s-line-height);\n            "])), _styledComponents.buttonTokens.buttonHeight, _styledComponents.buttonTokens.buttonFontFamily, _styledComponents.buttonTokens.buttonFontSize, _styledComponents.buttonTokens.buttonFontStyle, _styledComponents.buttonTokens.buttonFontWeight, _styledComponents.buttonTokens.buttonLetterSpacing, _styledComponents.buttonTokens.buttonLineHeight),
      xs: /*#__PURE__*/(0, _styledComponents.css)(_templateObject14 || (_templateObject14 = /*#__PURE__*/_taggedTemplateLiteral(["\n                ", ": 2rem;\n                ", ": 0.75rem;\n                ", ": 0.5rem;\n\n                ", ": var(--plasma-typo-body-xs-font-family);\n                ", ": var(--plasma-typo-body-xs-font-size);\n                ", ": var(--plasma-typo-body-xs-font-style);\n                ", ": var(--plasma-typo-body-xs-bold-font-weight);\n                ", ": var(--plasma-typo-body-xs-letter-spacing);\n                ", ": var(--plasma-typo-body-xs-line-height);\n            "])), _styledComponents.buttonTokens.buttonHeight, _styledComponents.buttonTokens.buttonPadding, _styledComponents.buttonTokens.buttonRadius, _styledComponents.buttonTokens.buttonFontFamily, _styledComponents.buttonTokens.buttonFontSize, _styledComponents.buttonTokens.buttonFontStyle, _styledComponents.buttonTokens.buttonFontWeight, _styledComponents.buttonTokens.buttonLetterSpacing, _styledComponents.buttonTokens.buttonLineHeight),
      xsr: /*#__PURE__*/(0, _styledComponents.css)(_templateObject15 || (_templateObject15 = /*#__PURE__*/_taggedTemplateLiteral(["\n                ", ": 2rem;\n\n                ", ": var(--plasma-typo-body-xs-font-family);\n                ", ": var(--plasma-typo-body-xs-font-size);\n                ", ": var(--plasma-typo-body-xs-font-style);\n                ", ": var(--plasma-typo-body-xs-bold-font-weight);\n                ", ": var(--plasma-typo-body-xs-letter-spacing);\n                ", ": var(--plasma-typo-body-xs-line-height);\n            "])), _styledComponents.buttonTokens.buttonHeight, _styledComponents.buttonTokens.buttonFontFamily, _styledComponents.buttonTokens.buttonFontSize, _styledComponents.buttonTokens.buttonFontStyle, _styledComponents.buttonTokens.buttonFontWeight, _styledComponents.buttonTokens.buttonLetterSpacing, _styledComponents.buttonTokens.buttonLineHeight),
      xxs: /*#__PURE__*/(0, _styledComponents.css)(_templateObject16 || (_templateObject16 = /*#__PURE__*/_taggedTemplateLiteral(["\n                ", ": 1.5rem;\n                ", ": 0.625rem;\n                ", ": 0.375rem;\n\n                ", ": var(--plasma-typo-body-xs-font-family);\n                ", ": var(--plasma-typo-body-xs-font-size);\n                ", ": var(--plasma-typo-body-xs-font-style);\n                ", ": var(--plasma-typo-body-xs-bold-font-weight);\n                ", ": var(--plasma-typo-body-xs-letter-spacing);\n                ", ": var(--plasma-typo-body-xs-line-height);\n            "])), _styledComponents.buttonTokens.buttonHeight, _styledComponents.buttonTokens.buttonPadding, _styledComponents.buttonTokens.buttonRadius, _styledComponents.buttonTokens.buttonFontFamily, _styledComponents.buttonTokens.buttonFontSize, _styledComponents.buttonTokens.buttonFontStyle, _styledComponents.buttonTokens.buttonFontWeight, _styledComponents.buttonTokens.buttonLetterSpacing, _styledComponents.buttonTokens.buttonLineHeight)
    },
    disabled: {
      "true": /*#__PURE__*/(0, _styledComponents.css)(_templateObject17 || (_templateObject17 = /*#__PURE__*/_taggedTemplateLiteral(["\n                ", ": 0.4;\n            "])), _styledComponents.buttonTokens.buttonDisabledOpacity)
    },
    focused: {
      "true": /*#__PURE__*/(0, _styledComponents.css)(_templateObject18 || (_templateObject18 = /*#__PURE__*/_taggedTemplateLiteral(["\n                ", ": var(--surface-accent);\n            "])), _styledComponents.buttonTokens.buttonFocusColor)
    }
  }
};