import { TokenType } from '../../../types';

export const shapeTokens: Array<TokenType> = [
    {
        type: 'shape',
        name: 'round.xxs',
        tags: ['round', 'xxs'],
        displayName: 'roundXxs',
        description: 'borderRadius xxs',
        enabled: true,
    },
    {
        type: 'shape',
        name: 'round.xs',
        tags: ['round', 'xs'],
        displayName: 'roundXs',
        description: 'borderRadius xs',
        enabled: true,
    },
    {
        type: 'shape',
        name: 'round.s',
        tags: ['round', 's'],
        displayName: 'roundS',
        description: 'borderRadius s',
        enabled: true,
    },
    {
        type: 'shape',
        name: 'round.m',
        tags: ['round', 'm'],
        displayName: 'roundM',
        description: 'borderRadius m',
        enabled: true,
    },
    {
        type: 'shape',
        name: 'round.l',
        tags: ['round', 'l'],
        displayName: 'roundL',
        description: 'borderRadius l',
        enabled: true,
    },
    {
        type: 'shape',
        name: 'round.xl',
        tags: ['round', 'xl'],
        displayName: 'roundXl',
        description: 'borderRadius xl',
        enabled: true,
    },
    {
        type: 'shape',
        name: 'round.xxl',
        tags: ['round', 'xxl'],
        displayName: 'roundXxl',
        description: 'borderRadius xxl',
        enabled: true,
    },
];
