export const classes = {
    timePickerstretched: 'sdds-core-time-picker-stretched',
    timePickerSuccess: 'sdds-core-time-picker-success',
    timePickerError: 'sdds-core-time-picker-error',
    timePickerEdited: 'sdds-core-time-picker-edited',
    timePickerRoot: 'sdds-core-time-picker-root',
    timePickerGridRoot: 'sdds-core-time-picker-grid-root',
    timeColumnLabel: 'sdds-core-time-picker-column-label',
    timeItemActive: 'sdds-core-time-picker-item-active',
    timePickerFullWidth: 'sdds-core-time-picker-full-width',
    timePickerFixed: 'sdds-core-time-picker-fixed',
    timePickerActive: 'sdds-core-time-picker-active',
    timeColumnActive: 'sdds-core-time-picker-column-active',
    timeColumn: 'sdds-core-time-picker-column',
    timeColumnScrolling: 'sdds-core-time-picker-column-scrolling',
    scrollbarVisible: 'sdds-core-time-picker-scrollbar-visible',
    timePickerPlacementRight: 'sdds-core-time-picker-placement-right',
};

export const tokens = {
    width: '--sdds-core-time-picker-width',

    background: '--sdds-core-time-picker_range-background',
    backgroundError: '--sdds-core-time-picker_range-background-error',
    backgroundSuccess: '--sdds-core-time-picker_range-background-success',
    backgroundReadOnly: '--sdds-core-time-picker_range-background-readonly',
    borderRadius: '--sdds-core-time-picker_range-border-radius',
    borderWidth: '--sdds-core-time-picker_range-border-width',
    borderColor: '--sdds-core-time-picker_range-border-color',
    borderColorHover: '--sdds-core-time-picker_range-border-color-hover',
    borderColorFocus: '--sdds-core-time-picker_range-border-color-focus',
    borderColorError: '--sdds-core-time-picker_range-border-color-error',
    borderColorSuccess: '--sdds-core-time-picker_range-border-color-success',

    leftContentMargin: '--sdds-core-time-picker_range__left-content-margin',
    rightContentMargin: '--sdds-core-time-picker_range__right-content-margin',

    labelColor: '--sdds-core-time-picker__label-color',
    labelColorReadOnly: '--sdds-core-time-picker__label-color-readonly',
    labelOffset: '--sdds-core-time-picker__label-offset',

    labelFontFamily: '--sdds-core-time-picker__label-font-family',
    labelFontStyle: '--sdds-core-time-picker__label-font-style',
    labelFontSize: '--sdds-core-time-picker__label-font-size',
    labelFontWeight: '--sdds-core-time-picker__label-font-weight',
    labelLetterSpacing: '--sdds-core-time-picker__label-letter-spacing',
    labelLineHeight: '--sdds-core-time-picker__label-line-height',

    labelInnerFontFamily: '--sdds-core-time-picker-placement_inner__label-font-family',
    labelInnerFontStyle: '--sdds-core-time-picker-placement_inner__label-font-style',
    labelInnerFontSize: '--sdds-core-time-picker-placement_inner__label-font-size',
    labelInnerFontWeight: '--sdds-core-time-picker-placement_inner__label-font-weight',
    labelInnerLetterSpacing: '--sdds-core-time-picker-placement_inner__label-letter-spacing',
    labelInnerLineHeight: '--sdds-core-time-picker-placement_inner__label-line-height',

    labelInnerPadding: '--sdds-core-time-picker-placement_inner__label-padding',
    contentLabelInnerPadding: '--sdds-core-time-picker-placement_inner__content-padding',

    indicatorColor: '--sdds-core-time-picker__indicator-color',

    indicatorSize: '--sdds-core-time-picker__indicator-size',
    indicatorSizeOuter: '--sdds-core-time-picker__indicator-size-outer',
    indicatorPlacement: '--sdds-core-time-picker__indicator-placement',
    indicatorPlacementRight: '--sdds-core-time-picker__indicator-placement-right',
    indicatorOuterPlacement: '--sdds-core-time-picker__indicator-placement-outer',
    indicatorOuterPlacementRight: '--sdds-core-time-picker__indicator-placement-outer-right',

    textFieldColor: '--sdds-core-time-picker-textfield-color',
    textFieldPlaceholderColorFocus: '--sdds-core-timepicker-textfield__placeholder-color-focus',
    textFieldFocusColor: '--sdds-core-time-picker-textfield-focus-color',
    textFieldPlaceholderColor: '--sdds-core-time-picker-textfield-placeholder-color',
    textFieldCaretColor: '--sdds-core-time-picker-textfield-caret-color',

    textFieldBackgroundColor: '--sdds-core-time-picker-textfield-background-color',
    textFieldBackgroundColorHover: '--sdds-core-time-picker-textfield-background-color-hover',
    textFieldBackgroundColorFocus: '--sdds-core-time-picker-textfield-background-color-focus',
    textFieldBackgroundErrorColor: '--sdds-core-time-picker-textfield-background-color-error',
    textFieldBackgroundErrorColorHover: '--sdds-core-time-picker-textfield-background-color-error-hover',
    textFieldBackgroundErrorColorFocus: '--sdds-core-time-picker-textfield-background-color-error-focus',
    textFieldBackgroundSuccessColor: '--sdds-core-time-picker-textfield-background-color-success',
    textFieldBackgroundSuccessColorHover: '--sdds-core-time-picker-textfield-background-color-success-hover',
    textFieldBackgroundSuccessColorFocus: '--sdds-core-time-picker-textfield-background-color-success-focus',
    textFieldBackgroundEditedColor: '--sdds-core-time-picker-textfield-background-color-edited',
    textFieldBackgroundEditedColorHover: '--sdds-core-time-picker-textfield-background-color-edited-hover',
    textFieldBackgroundEditedColorFocus: '--sdds-core-time-picker-textfield-background-color-edited-focus',

    textFieldBorderColor: '--sdds-core-time-picker-textfield-border-color',
    textFieldBorderColorHover: '--sdds-core-time-picker-textfield-border-color-hover',
    textFieldBorderColorFocus: '--sdds-core-time-picker-textfield-border-color-focus',
    textFieldBorderColorError: '--sdds-core-time-picker-textfield-border-color-error',
    textFieldBorderColorErrorHover: '--sdds-core-time-picker-textfield-border-color-error-hover',
    textFieldBorderColorErrorFocus: '--sdds-core-time-picker-textfield-border-color-error-focus',
    textFieldBorderColorSuccess: '--sdds-core-time-picker-textfield-border-color-success',
    textFieldBorderColorSuccessHover: '--sdds-core-time-picker-textfield-border-color-success-hover',
    textFieldBorderColorSuccessFocus: '--sdds-core-time-picker-textfield-border-color-success-focus',
    textFieldBorderColorEdited: '--sdds-core-time-picker-textfield-border-color-edited',
    textFieldBorderColorEditedHover: '--sdds-core-time-picker-textfield-border-color-edited-hover',
    textFieldBorderColorEditedFocus: '--sdds-core-time-picker-textfield-border-color-edited-focus',
    textFieldBoxShadow: '--sdds-core-time-picker-textfield-box-shadow',

    textFieldDividerColor: '--sdds-core-time-picker-textfield-divider-color',
    textFieldDividerColorHover: '--sdds-core-time-picker-textfield-divider-color-hover',
    textFieldDividerColorFocus: '--sdds-core-time-picker-textfield-divider-color-focus',
    textFieldDividerColorReadOnly: '--sdds-core-time-picker-textfield-divider-color-readonly',
    textFieldDividerColorError: '--sdds-core-time-picker-textfield-divider-color-error',
    textFieldDividerColorSuccess: '--sdds-core-time-picker-textfield-divider-color-success',
    textFieldDividerColorEdited: '--sdds-core-time-picker-textfield-divider-color-edited',
    textFieldDividerWidth: '--sdds-core-time-picker-textfield-divider-width',

    textFieldColorReadOnly: '--sdds-core-time-picker-textfield-color-readonly',
    textFieldBackgroundColorReadOnly: '--sdds-core-time-picker-textfield-background-color-readonly',
    textFieldBorderColorReadOnly: '--sdds-core-time-picker-textfield-border-color-readonly',
    textFieldPlaceholderColorReadOnly: '--sdds-core-time-picker-textfield-placeholder-color-readonly',

    textFieldHeight: '--sdds-core-time-picker-textfield-height',
    textFieldBorderWidth: '--sdds-core-time-picker-textfield-border-width',
    textFieldBorderRadius: '--sdds-core-time-picker-textfield-border-radius',
    textFieldPadding: '--sdds-core-time-picker-textfield-padding',
    textFieldLeftContentMargin: '--sdds-core-time-picker-textfield__left-content-margin',
    textFieldRightContentMargin: '--sdds-core-time-picker-textfield__right-content-margin',
    textFieldRightContentWithHintMargin: '--plasma-time-picker--textfield__right-content-with-hint-margin',

    textFieldContentRightWrapperGap: '--plasma-time-picker-content-right-wrapper-gap',
    textFieldContentRightWrapperMargin: '--plasma-time-picker-content-right-wrapper-margin',

    textFieldFontFamily: '--sdds-core-time-picker-textfield-font-family',
    textFieldFontStyle: '--sdds-core-time-picker-textfield-font-style',
    textFieldFontSize: '--sdds-core-time-picker-textfield-font-size',
    textFieldFontWeight: '--sdds-core-time-picker-textfield-font-weight',
    textFieldLetterSpacing: '--sdds-core-time-picker-textfield-letter-spacing',
    textFieldLineHeight: '--sdds-core-time-picker-textfield-line-height',

    textFieldTextBeforeColor: '--sdds-core-time-picker-textfield__before-text-color',
    textFieldTextAfterColor: '--sdds-core-time-picker-textfield__after-text-color',
    textFieldTextBeforeMargin: '--sdds-core-time-picker-textfield__before-text-margin',
    textFieldTextAfterMargin: '--sdds-core-time-picker-textfield__after-text-margin',
    textFieldContentSlotColor: '--sdds-core-time-picker-textfield__content-color',
    textFieldContentSlotColorHover: '--sdds-core-time-picker-textfield__content-color-hover',
    textFieldContentSlotColorActive: '--sdds-core-time-picker-textfield__content-color-active',
    textFieldContentRightSlotColor: '--sdds-core-time-picker-textfield__content-right-color',
    textFieldContentRightSlotColorHover: '--sdds-core-time-picker-textfield__content-right-color-hover',
    textFieldContentSlotRightOpacityReadOnly: '--sdds-core-time-picker-textfield-right-content-opacity-readonly',

    readOnlyOpacity: '--sdds-core-time-picker-textfield-readonly-opacity',

    /* токены для leftHelper */
    leftHelperColor: '--sdds-core-time-picker__left-helper-color',
    leftHelperColorError: '--sdds-core-time-picker__left-helper-color-error',
    leftHelperColorSuccess: '--sdds-core-time-picker__left-helper-color-success',
    leftHelperColorEdited: '--sdds-core-time-picker__left-helper-color-edited',
    leftHelperColorReadOnly: '--sdds-core-time-picker__left-helper-color-readonly',
    leftHelperOffset: '--sdds-core-time-picker__left-helper-offset',
    leftHelperFontFamily: '--sdds-core-time-picker__left-helper-font-family',
    leftHelperFontStyle: '--sdds-core-time-picker__left-helper-font-style',
    leftHelperFontSize: '--sdds-core-time-picker__left-helper-font-size',
    leftHelperFontWeight: '--sdds-core-time-picker__left-helper-font-weight',
    leftHelperLetterSpacing: '--sdds-core-time-picker__left-helper-letter-spacing',
    leftHelperLineHeight: '--sdds-core-time-picker__left-helper-line-height',

    /* токены для hint */
    hintMargin: '--sdds-core-time-picker-hint-margin',
    hintTargetSize: '--sdds-core-time-picker-hint-target-size',
    hintCustomIconTargetSize: '--sdds-core-time-picker-hint-custom-icon-target-size',
    hintIconColor: '--sdds-core-time-picker-hint-icon-color',
    hintInnerLabelPlacementOffset: '--sdds-core-time-picker-hint-inner-label-placement-offset',

    hintTooltipPaddingTop: '--sdds-core-time-picker-hint-tooltip-padding-top',
    hintTooltipPaddingRight: '--sdds-core-time-picker-hint-tooltip-padding-right',
    hintTooltipPaddingBottom: '--sdds-core-time-picker-hint-tooltip-padding-bottom',
    hintTooltipPaddingLeft: '--sdds-core-time-picker-hint-tooltip-padding-left',
    hintTooltipMinHeight: '--sdds-core-time-picker-hint-tooltip-min-height',
    hintTooltipBackgroundColor: '--sdds-core-time-picker-hint-tooltip-background-color',
    hintTooltipBoxShadow: '--sdds-core-time-picker-hint-tooltip-box-shadow',
    hintTooltipBorderRadius: '--sdds-core-time-picker-hint-tooltip-border-radius',
    hintTooltipColor: '--sdds-core-time-picker-hint-tooltip-color',
    hintTooltipTextFontFamily: '--sdds-core-time-picker-hint-tooltip-text-font-family',
    hintTooltipTextFontSize: '--sdds-core-time-picker-hint-tooltip-text-font-size',
    hintTooltipTextFontStyle: '--sdds-core-time-picker-hint-tooltip-text-font-style',
    hintTooltipTextFontWeight: '--sdds-core-time-picker-hint-tooltip-text-font-weight',
    hintTooltipTextFontLetterSpacing: '--sdds-core-time-picker-hint-tooltip-text-font-letter-spacing',
    hintTooltipTextFontLineHeight: '--sdds-core-time-picker-hint-tooltip-text-font-line-height',
    hintTooltipContentLeftMargin: '--sdds-core-time-picker-hint-tooltip-content-left-margin',
    hintTooltipArrowMaskWidth: '--sdds-core-time-picker-hint-tooltip-arrow-mask-width',
    hintTooltipArrowMaskHeight: '--sdds-core-time-picker-hint-tooltip-arrow-mask-height',
    hintTooltipArrowMaskImage: '--sdds-core-time-picker-hint-tooltip-arrow-mask-image',
    hintTooltipArrowBackground: '--sdds-core-time-picker-hint-tooltip-arrow-background',
    hintTooltipArrowHeight: '--sdds-core-time-picker-hint-tooltip-arrow-height',
    hintTooltipArrowEdgeMargin: '--sdds-core-time-picker-hint-tooltip-arrow-edge-margin',

    /** Прозрачность для всего компонента в состоянии disabled */
    disabledOpacity: '--sdds-core-time-picker-disabled-opacity',

    dropdownMarginTop: '--sdds-core-time-picker-dropdown-margin-top',

    timePickerShadow: '--sdds-core-time-picker-ui-box-shadow',
    timePickerBackground: '--sdds-core-time-picker-ui-background',
    timePickerBorderRadius: '--sdds-core-time-picker-ui-border-radius',
    timePickerWidth: '--sdds-core-time-picker-ui-width',
    timePickerPadding: '--sdds-core-time-picker-ui-padding',

    columnHeight: '--sdds-core-time-picker-column-height',

    itemHeight: '--sdds-core-time-picker-item-height',
    itemBorderRadius: '--sdds-core-time-picker-item-border-radius',
    itemPadding: '--sdds-core-time-picker-item-padding',
    itemBackgroundHover: '--sdds-core-time-picker-item-hover-background',
    itemBackgroundActive: '--sdds-core-time-picker-item-active-background',
    itemFocusColor: '--sdds-core-time-picker-item-focus-color',

    itemFontFamily: '--sdds-core-time-picker-item-font-family',
    itemFontStyle: '--sdds-core-time-picker-item-font-style',
    itemFontSize: '--sdds-core-time-picker-item-font-size',
    itemFontWeight: '--sdds-core-time-picker-item-font-weight',
    itemLetterSpacing: '--sdds-core-time-picker-item-letter-spacing',
    itemLineHeight: '--sdds-core-time-picker-item-line-height',

    scrollbarWidth: '--sdds-core-time-picker-scrollbar-width',
    scrollbarColor: '--sdds-core-time-picker-scrollbar-color',
    scrollbarTrackColor: '--sdds-core-time-picker-scrollbar-track-color',
    scrollbarMargin: '--sdds-core-time-picker-scrollbar-margin',
};
