export const classes = {
    timePickerstretched: 'plasma-time-picker-stretched',
    timePickerSuccess: 'plasma-time-picker-success',
    timePickerError: 'plasma-time-picker-error',
    timePickerRoot: 'plasma-time-picker-root',
    timeColumnLabel: 'plasma-time-picker-column-label',
    timeItemActive: 'plasma-time-picker-item-active',
    timePickerFullWidth: 'plasma-time-picker-full-width',
    timePickerActive: 'plasma-time-picker-active',
    timeColumnActive: 'plasma-time-picker-column-active',
    timeColumn: 'plasma-time-picker-column',
    timeColumnScrolling: 'plasma-time-picker-column-scrolling',
    scrollbarVisible: 'plasma-time-picker-scrollbar-visible',
    timePickerPlacementRight: 'plasma-time-picker-placement-right',
};

export const tokens = {
    width: '--plasma-time-picker-width',

    background: '--plasma-time-picker_range-background',
    backgroundError: '--plasma-time-picker_range-background-error',
    backgroundSuccess: '--plasma-time-picker_range-background-success',
    backgroundReadOnly: '--plasma-time-picker_range-background-readonly',
    borderRadius: '--plasma-time-picker_range-border-radius',
    borderWidth: '--plasma-time-picker_range-border-width',
    borderColor: '--plasma-time-picker_range-border-color',
    borderColorHover: '--plasma-time-picker_range-border-color-hover',
    borderColorFocus: '--plasma-time-picker_range-border-color-focus',
    borderColorError: '--plasma-time-picker_range-border-color-error',
    borderColorSuccess: '--plasma-time-picker_range-border-color-success',

    leftContentMargin: '--plasma-time-picker_range__left-content-margin',
    rightContentMargin: '--plasma-time-picker_range__right-content-margin',

    labelColor: '--plasma-time-picker__label-color',
    labelColorReadOnly: '--plasma-time-picker__label-color-readonly',
    labelOffset: '--plasma-time-picker__label-offset',

    labelFontFamily: '--plasma-time-picker__label-font-family',
    labelFontStyle: '--plasma-time-picker__label-font-style',
    labelFontSize: '--plasma-time-picker__label-font-size',
    labelFontWeight: '--plasma-time-picker__label-font-weight',
    labelLetterSpacing: '--plasma-time-picker__label-letter-spacing',
    labelLineHeight: '--plasma-time-picker__label-line-height',

    labelInnerFontFamily: '--plasma-time-picker-placement_inner__label-font-family',
    labelInnerFontStyle: '--plasma-time-picker-placement_inner__label-font-style',
    labelInnerFontSize: '--plasma-time-picker-placement_inner__label-font-size',
    labelInnerFontWeight: '--plasma-time-picker-placement_inner__label-font-weight',
    labelInnerLetterSpacing: '--plasma-time-picker-placement_inner__label-letter-spacing',
    labelInnerLineHeight: '--plasma-time-picker-placement_inner__label-line-height',

    labelInnerPadding: '--plasma-time-picker-placement_inner__label-padding',
    contentLabelInnerPadding: '--plasma-time-picker-placement_inner__content-padding',

    indicatorColor: '--plasma-time-picker__indicator-color',

    indicatorSize: '--plasma-time-picker__indicator-size',
    indicatorSizeOuter: '--plasma-time-picker__indicator-size-outer',
    indicatorPlacement: '--plasma-time-picker__indicator-placement',
    indicatorPlacementRight: '--plasma-time-picker__indicator-placement-right',
    indicatorOuterPlacement: '--plasma-time-picker__indicator-placement-outer',
    indicatorOuterPlacementRight: '--plasma-time-picker__indicator-placement-outer-right',

    textFieldColor: '--plasma-time-picker-textfield-color',
    textFieldPlaceholderColorFocus: '--plasma-timepicker-textfield__placeholder-color-focus',
    textFieldFocusColor: '--plasma-time-picker-textfield-focus-color',
    textFieldPlaceholderColor: '--plasma-time-picker-textfield-placeholder-color',
    textFieldCaretColor: '--plasma-time-picker-textfield-caret-color',

    textFieldBackgroundColor: '--plasma-time-picker-textfield-background-color',
    textFieldBackgroundColorHover: '--plasma-time-picker-textfield-background-color-hover',
    textFieldBackgroundColorFocus: '--plasma-time-picker-textfield-background-color-focus',
    textFieldBackgroundErrorColor: '--plasma-time-picker-textfield-background-color-error',
    textFieldBackgroundErrorColorHover: '--plasma-time-picker-textfield-background-color-error-hover',
    textFieldBackgroundErrorColorFocus: '--plasma-time-picker-textfield-background-color-error-focus',
    textFieldBackgroundSuccessColor: '--plasma-time-picker-textfield-background-color-success',
    textFieldBackgroundSuccessColorHover: '--plasma-time-picker-textfield-background-color-success-hover',
    textFieldBackgroundSuccessColorFocus: '--plasma-time-picker-textfield-background-color-success-focus',

    textFieldBorderColor: '--plasma-time-picker-textfield-border-color',
    textFieldBorderColorHover: '--plasma-time-picker-textfield-border-color-hover',
    textFieldBorderColorFocus: '--plasma-time-picker-textfield-border-color-focus',
    textFieldBorderColorError: '--plasma-time-picker-textfield-border-color-error',
    textFieldBorderColorErrorHover: '--plasma-time-picker-textfield-border-color-error-hover',
    textFieldBorderColorErrorFocus: '--plasma-time-picker-textfield-border-color-error-focus',
    textFieldBorderColorSuccess: '--plasma-time-picker-textfield-border-color-success',
    textFieldBorderColorSuccessHover: '--plasma-time-picker-textfield-border-color-success-hover',
    textFieldBorderColorSuccessFocus: '--plasma-time-picker-textfield-border-color-success-focus',
    textFieldBoxShadow: '--plasma-time-picker-textfield-box-shadow',

    textFieldColorReadOnly: '--plasma-time-picker-textfield-color-readonly',
    textFieldBackgroundColorReadOnly: '--plasma-time-picker-textfield-background-color-readonly',
    textFieldBorderColorReadOnly: '--plasma-time-picker-textfield-border-color-readonly',
    textFieldPlaceholderColorReadOnly: '--plasma-time-picker-textfield-placeholder-color-readonly',

    textFieldHeight: '--plasma-time-picker-textfield-height',
    textFieldBorderWidth: '--plasma-time-picker-textfield-border-width',
    textFieldBorderRadius: '--plasma-time-picker-textfield-border-radius',
    textFieldPadding: '--plasma-time-picker-textfield-padding',
    textFieldLeftContentMargin: '--plasma-time-picker-textfield__left-content-margin',
    textFieldRightContentMargin: '--plasma-time-picker-textfield__right-content-margin',
    textFieldFontFamily: '--plasma-time-picker-textfield-font-family',
    textFieldFontStyle: '--plasma-time-picker-textfield-font-style',
    textFieldFontSize: '--plasma-time-picker-textfield-font-size',
    textFieldFontWeight: '--plasma-time-picker-textfield-font-weight',
    textFieldLetterSpacing: '--plasma-time-picker-textfield-letter-spacing',
    textFieldLineHeight: '--plasma-time-picker-textfield-line-height',

    textFieldTextBeforeColor: '--plasma-time-picker-textfield__before-text-color',
    textFieldTextAfterColor: '--plasma-time-picker-textfield__after-text-color',
    textFieldTextBeforeMargin: '--plasma-time-picker-textfield__before-text-margin',
    textFieldTextAfterMargin: '--plasma-time-picker-textfield__after-text-margin',
    textFieldContentSlotColor: '--plasma-time-picker-textfield__content-color',
    textFieldContentRightSlotColor: '--plasma-time-picker-textfield__content-right-color',
    textFieldContentRightSlotColorHover: '--plasma-time-picker-textfield__content-right-color-hover',

    /** Прозрачность для всего компонента в состоянии disabled */
    disabledOpacity: '--plasma-time-picker-disabled-opacity',

    dropdownMarginTop: '--plasma-time-picker-dropdown-margin-top',

    timePickerBackground: '--plasma-time-picker-ui-background',
    timePickerBorderRadius: '--plasma-time-picker-ui-border-radius',
    timePickerWidth: '--plasma-time-picker-ui-width',
    timePickerPadding: '--plasma-time-picker-ui-padding',

    columnHeight: '--plasma-time-picker-column-height',

    itemHeight: '--plasma-time-picker-item-height',
    itemBorderRadius: '--plasma-time-picker-item-border-radius',
    itemPadding: '--plasma-time-picker-item-padding',
    itemBackgroundHover: '--plasma-time-picker-item-hover-background',
    itemBackgroundActive: '--plasma-time-picker-item-active-background',

    itemFontFamily: '--plasma-time-picker-item-font-family',
    itemFontStyle: '--plasma-time-picker-item-font-style',
    itemFontSize: '--plasma-time-picker-item-font-size',
    itemFontWeight: '--plasma-time-picker-item-font-weight',
    itemLetterSpacing: '--plasma-time-picker-item-letter-spacing',
    itemLineHeight: '--plasma-time-picker-item-line-height',

    scrollbarWidth: '--plasma-time-picker-scrollbar-width',
    scrollbarColor: '--plasma-time-picker-scrollbar-color',
    scrollbarTrackColor: '--plasma-time-picker-scrollbar-track-color',
    scrollbarMargin: '--plasma-time-picker-scrollbar-margin',
};
