// Generated by robots, do not change this manually!

/** Основной цвет текста */
export const textPrimaryHover = 'var(--text-primary-hover, #FFFFFF93)';

/** Основной цвет текста */
export const textPrimaryActive = 'var(--text-primary-active, #FFFFFFC4)';

/** Основной цвет текста */
export const textPrimary = 'var(--text-primary, #FFFFFFF5)';

/** Основной цвет текста */
export const textPrimaryBrightness = 'var(--text-primary-brightness, #FFFFF6FF)';

/** Вторичный цвет текста */
export const textSecondaryHover = 'var(--text-secondary-hover, #FFFFFFFF)';

/** Вторичный цвет текста */
export const textSecondaryActive = 'var(--text-secondary-active, #FFFFFFAB)';

/** Вторичный цвет текста */
export const textSecondary = 'var(--text-secondary, #FFFFFF8F)';

/** Третичный цвет текста */
export const textTertiaryHover = 'var(--text-tertiary-hover, #FFFFFFFF)';

/** Третичный цвет текста */
export const textTertiaryActive = 'var(--text-tertiary-active, #FFFFFF56)';

/** Третичный цвет текста */
export const textTertiary = 'var(--text-tertiary, #FFFFFF47)';

/** Сплошной наборный текст */
export const textParagraphHover = 'var(--text-paragraph-hover, #FFFFFF7A)';

/** Сплошной наборный текст */
export const textParagraphActive = 'var(--text-paragraph-active, #FFFFFFA3)';

/** Сплошной наборный текст */
export const textParagraph = 'var(--text-paragraph, #FFFFFFCC)';

/** Цвет успеха */
export const textPositiveHover = 'var(--text-positive-hover, #2ACB47FF)';

/** Цвет успеха */
export const textPositiveActive = 'var(--text-positive-active, #1F9835FF)';

/** Цвет успеха */
export const textPositive = 'var(--text-positive, #24B23E)';

/** Цвет предупреждения */
export const textWarningHover = 'var(--text-warning-hover, #FF8442FF)';

/** Цвет предупреждения */
export const textWarningActive = 'var(--text-warning-active, #FF5D05FF)';

/** Цвет предупреждения */
export const textWarning = 'var(--text-warning, #FF7024)';

/** Цвет ошибки */
export const textNegativeHover = 'var(--text-negative-hover, #FF475AFF)';

/** Цвет ошибки */
export const textNegativeActive = 'var(--text-negative-active, #FF0A23FF)';

/** Цвет ошибки */
export const textNegative = 'var(--text-negative, #FF293E)';

/** Акцентный цвет Афины */
export const textAccentAthenaHover = 'var(--text-accent-athena-hover, #66BCF5FF)';

/** Акцентный цвет Афины */
export const textAccentAthenaActive = 'var(--text-accent-athena-active, #0E8ADDFF)';

/** Акцентный цвет Афины */
export const textAccentAthena = 'var(--text-accent-athena, #199AF0)';

/** Акцентный цвет Джой */
export const textAccentJoyHover = 'var(--text-accent-joy-hover, #E4BDFFFF)';

/** Акцентный цвет Джой */
export const textAccentJoyActive = 'var(--text-accent-joy-active, #B84DFFFF)';

/** Акцентный цвет Джой */
export const textAccentJoy = 'var(--text-accent-joy, #C46BFF)';

/** Акцентный цвет B2E-ассистента */
export const textAccentB2EHover = 'var(--text-accent-b2-e-hover, #2ACB47FF)';

/** Акцентный цвет B2E-ассистента */
export const textAccentB2EActive = 'var(--text-accent-b2-e-active, #1F9835FF)';

/** Акцентный цвет B2E-ассистента */
export const textAccentB2E = 'var(--text-accent-b2-e, #24B23E)';

/** Акцентный цвет бренда */
export const textAccentBrandHover = 'var(--text-accent-brand-hover, #A3C3FFFF)';

/** Акцентный цвет бренда */
export const textAccentBrandActive = 'var(--text-accent-brand-active, #337AFFFF)';

/** Акцентный цвет бренда */
export const textAccentBrand = 'var(--text-accent-brand, #528EFF)';

/** Акцентный цвет */
export const textAccentMainHover = 'var(--text-accent-main-hover, #2ACB47FF)';

/** Акцентный цвет */
export const textAccentMainActive = 'var(--text-accent-main-active, #1F9835FF)';

/** Акцентный цвет */
export const textAccentMain = 'var(--text-accent-main, #24B23E)';

/** Основной цвет текста на темном фоне */
export const onDarkTextPrimaryHover = 'var(--on-dark-text-primary-hover, #FFFFFF93)';

/** Основной цвет текста на темном фоне */
export const onDarkTextPrimaryActive = 'var(--on-dark-text-primary-active, #FFFFFFC4)';

/** Основной цвет текста на темном фоне */
export const onDarkTextPrimary = 'var(--on-dark-text-primary, #FFFFFFF5)';

/** Основной цвет текста на темном фоне */
export const onDarkTextPrimaryBrightness = 'var(--on-dark-text-primary-brightness, #FFFFF6FF)';

/** Вторичный цвет текста на темном фоне */
export const onDarkTextSecondaryHover = 'var(--on-dark-text-secondary-hover, #FFFFFFFF)';

/** Вторичный цвет текста на темном фоне */
export const onDarkTextSecondaryActive = 'var(--on-dark-text-secondary-active, #FFFFFFAB)';

/** Вторичный цвет текста на темном фоне */
export const onDarkTextSecondary = 'var(--on-dark-text-secondary, #FFFFFF8F)';

/** Третичный цвет текста на темном фоне */
export const onDarkTextTertiaryHover = 'var(--on-dark-text-tertiary-hover, #FFFFFFFF)';

/** Третичный цвет текста на темном фоне */
export const onDarkTextTertiaryActive = 'var(--on-dark-text-tertiary-active, #FFFFFF56)';

/** Третичный цвет текста на темном фоне */
export const onDarkTextTertiary = 'var(--on-dark-text-tertiary, #FFFFFF47)';

/** Сплошной наборный текст на темном фоне */
export const onDarkTextParagraphHover = 'var(--on-dark-text-paragraph-hover, #FFFFFF7A)';

/** Сплошной наборный текст на темном фоне */
export const onDarkTextParagraphActive = 'var(--on-dark-text-paragraph-active, #FFFFFFA3)';

/** Сплошной наборный текст на темном фоне */
export const onDarkTextParagraph = 'var(--on-dark-text-paragraph, #FFFFFFCC)';

/** Цвет успеха на темном фоне */
export const onDarkTextPositiveHover = 'var(--on-dark-text-positive-hover, #2ACB47FF)';

/** Цвет успеха на темном фоне */
export const onDarkTextPositiveActive = 'var(--on-dark-text-positive-active, #1F9835FF)';

/** Цвет успеха на темном фоне */
export const onDarkTextPositive = 'var(--on-dark-text-positive, #24B23E)';

/** Цвет предупреждения на темном фоне */
export const onDarkTextWarningHover = 'var(--on-dark-text-warning-hover, #FF8442FF)';

/** Цвет предупреждения на темном фоне */
export const onDarkTextWarningActive = 'var(--on-dark-text-warning-active, #FF5D05FF)';

/** Цвет предупреждения на темном фоне */
export const onDarkTextWarning = 'var(--on-dark-text-warning, #FF7024)';

/** Цвет ошибки на темном фоне */
export const onDarkTextNegativeHover = 'var(--on-dark-text-negative-hover, #FF475AFF)';

/** Цвет ошибки на темном фоне */
export const onDarkTextNegativeActive = 'var(--on-dark-text-negative-active, #FF0A23FF)';

/** Цвет ошибки на темном фоне */
export const onDarkTextNegative = 'var(--on-dark-text-negative, #FF293E)';

/** Акцентный цвет Афины на темном */
export const onDarkTextAccentAthenaHover = 'var(--on-dark-text-accent-athena-hover, #66BCF5FF)';

/** Акцентный цвет Афины на темном */
export const onDarkTextAccentAthenaActive = 'var(--on-dark-text-accent-athena-active, #0E8ADDFF)';

/** Акцентный цвет Афины на темном */
export const onDarkTextAccentAthena = 'var(--on-dark-text-accent-athena, #199AF0)';

/** Акцентный цвет Джой на темном фоне */
export const onDarkTextAccentJoyHover = 'var(--on-dark-text-accent-joy-hover, #E4BDFFFF)';

/** Акцентный цвет Джой на темном фоне */
export const onDarkTextAccentJoyActive = 'var(--on-dark-text-accent-joy-active, #B84DFFFF)';

/** Акцентный цвет Джой на темном фоне */
export const onDarkTextAccentJoy = 'var(--on-dark-text-accent-joy, #C46BFF)';

/** Акцентный цвет B2E-ассистента на темном фоне */
export const onDarkTextAccentB2EHover = 'var(--on-dark-text-accent-b2-e-hover, #2ACB47FF)';

/** Акцентный цвет B2E-ассистента на темном фоне */
export const onDarkTextAccentB2EActive = 'var(--on-dark-text-accent-b2-e-active, #1F9835FF)';

/** Акцентный цвет B2E-ассистента на темном фоне */
export const onDarkTextAccentB2E = 'var(--on-dark-text-accent-b2-e, #24B23E)';

/** Акцентный цвет бренда на темном фоне */
export const onDarkTextAccentBrandHover = 'var(--on-dark-text-accent-brand-hover, #A3C3FFFF)';

/** Акцентный цвет бренда на темном фоне */
export const onDarkTextAccentBrandActive = 'var(--on-dark-text-accent-brand-active, #337AFFFF)';

/** Акцентный цвет бренда на темном фоне */
export const onDarkTextAccentBrand = 'var(--on-dark-text-accent-brand, #528EFF)';

/** Акцентный цвет на темном фоне */
export const onDarkTextAccentMainHover = 'var(--on-dark-text-accent-main-hover, #2ACB47FF)';

/** Акцентный цвет на темном фоне */
export const onDarkTextAccentMainActive = 'var(--on-dark-text-accent-main-active, #1F9835FF)';

/** Акцентный цвет на темном фоне */
export const onDarkTextAccentMain = 'var(--on-dark-text-accent-main, #24B23E)';

/** Основной цвет текста на светлом фоне */
export const onLightTextPrimaryHover = 'var(--on-light-text-primary-hover, #08080893)';

/** Основной цвет текста на светлом фоне */
export const onLightTextPrimaryActive = 'var(--on-light-text-primary-active, #080808C4)';

/** Основной цвет текста на светлом фоне */
export const onLightTextPrimary = 'var(--on-light-text-primary, #080808F5)';

/** Основной цвет текста на светлом фоне */
export const onLightTextPrimaryBrightness = 'var(--on-light-text-primary-brightness, #171717FF)';

/** Вторичный цвет текста на светлом фоне */
export const onLightTextSecondaryHover = 'var(--on-light-text-secondary-hover, #080808FF)';

/** Вторичный цвет текста на светлом фоне */
export const onLightTextSecondaryActive = 'var(--on-light-text-secondary-active, #080808AB)';

/** Вторичный цвет текста на светлом фоне */
export const onLightTextSecondary = 'var(--on-light-text-secondary, #0808088F)';

/** Третичный цвет текста на светлом фоне */
export const onLightTextTertiaryHover = 'var(--on-light-text-tertiary-hover, #080808FF)';

/** Третичный цвет текста на светлом фоне */
export const onLightTextTertiaryActive = 'var(--on-light-text-tertiary-active, #08080856)';

/** Третичный цвет текста на светлом фоне */
export const onLightTextTertiary = 'var(--on-light-text-tertiary, #08080847)';

/** Сплошной наборный текст на светлом фоне */
export const onLightTextParagraphHover = 'var(--on-light-text-paragraph-hover, #0808087A)';

/** Сплошной наборный текст на светлом фоне */
export const onLightTextParagraphActive = 'var(--on-light-text-paragraph-active, #080808A3)';

/** Сплошной наборный текст на светлом фоне */
export const onLightTextParagraph = 'var(--on-light-text-paragraph, #080808CC)';

/** Цвет успеха на светлом фоне */
export const onLightTextPositiveHover = 'var(--on-light-text-positive-hover, #1EB83AFF)';

/** Цвет успеха на светлом фоне */
export const onLightTextPositiveActive = 'var(--on-light-text-positive-active, #15842AFF)';

/** Цвет успеха на светлом фоне */
export const onLightTextPositive = 'var(--on-light-text-positive, #1A9E32)';

/** Цвет предупреждения на светлом фоне */
export const onLightTextWarningHover = 'var(--on-light-text-warning-hover, #FB7223FF)';

/** Цвет предупреждения на светлом фоне */
export const onLightTextWarningActive = 'var(--on-light-text-warning-active, #DC5304FF)';

/** Цвет предупреждения на светлом фоне */
export const onLightTextWarning = 'var(--on-light-text-warning, #FA5F05)';

/** Цвет ошибки на светлом фоне */
export const onLightTextNegativeHover = 'var(--on-light-text-negative-hover, #FF475AFF)';

/** Цвет ошибки на светлом фоне */
export const onLightTextNegativeActive = 'var(--on-light-text-negative-active, #FF0A23FF)';

/** Цвет ошибки на светлом фоне */
export const onLightTextNegative = 'var(--on-light-text-negative, #FF293E)';

/** Акцентный цвет Афины на светлом фоне */
export const onLightTextAccentAthenaHover = 'var(--on-light-text-accent-athena-hover, #50B1F2FF)';

/** Акцентный цвет Афины на светлом фоне */
export const onLightTextAccentAthenaActive = 'var(--on-light-text-accent-athena-active, #0F7BC2FF)';

/** Акцентный цвет Афины на светлом фоне */
export const onLightTextAccentAthena = 'var(--on-light-text-accent-athena, #118CDF)';

/** Акцентный цвет Джой на светлом фоне */
export const onLightTextAccentJoyHover = 'var(--on-light-text-accent-joy-hover, #D7A4F9FF)';

/** Акцентный цвет Джой на светлом фоне */
export const onLightTextAccentJoyActive = 'var(--on-light-text-accent-joy-active, #A93BF1FF)';

/** Акцентный цвет Джой на светлом фоне */
export const onLightTextAccentJoy = 'var(--on-light-text-accent-joy, #B559F3)';

/** Акцентный цвет B2E-ассистента на светлом фоне */
export const onLightTextAccentB2EHover = 'var(--on-light-text-accent-b2-e-hover, #1EB83AFF)';

/** Акцентный цвет B2E-ассистента на светлом фоне */
export const onLightTextAccentB2EActive = 'var(--on-light-text-accent-b2-e-active, #15842AFF)';

/** Акцентный цвет B2E-ассистента на светлом фоне */
export const onLightTextAccentB2E = 'var(--on-light-text-accent-b2-e, #1A9E32)';

/** Акцентный цвет бренда на светлом фоне */
export const onLightTextAccentBrandHover = 'var(--on-light-text-accent-brand-hover, #90B6FEFF)';

/** Акцентный цвет бренда на светлом фоне */
export const onLightTextAccentBrandActive = 'var(--on-light-text-accent-brand-active, #216EFDFF)';

/** Акцентный цвет бренда на светлом фоне */
export const onLightTextAccentBrand = 'var(--on-light-text-accent-brand, #3F81FD)';

/** Акцентный цвет на светлом фоне */
export const onLightTextAccentMainHover = 'var(--on-light-text-accent-main-hover, #1EB83AFF)';

/** Акцентный цвет на светлом фоне */
export const onLightTextAccentMainActive = 'var(--on-light-text-accent-main-active, #15842AFF)';

/** Акцентный цвет на светлом фоне */
export const onLightTextAccentMain = 'var(--on-light-text-accent-main, #1A9E32)';

/** Инвертированный основной цвет текста */
export const inverseTextPrimaryHover = 'var(--inverse-text-primary-hover, #08080893)';

/** Инвертированный основной цвет текста */
export const inverseTextPrimaryActive = 'var(--inverse-text-primary-active, #080808C4)';

/** Инвертированный основной цвет текста */
export const inverseTextPrimary = 'var(--inverse-text-primary, #080808F5)';

/** Инвертированный основной цвет текста */
export const inverseTextPrimaryBrightness = 'var(--inverse-text-primary-brightness, #171717FF)';

/** Инвертированный вторичный цвет текста */
export const inverseTextSecondaryHover = 'var(--inverse-text-secondary-hover, #080808FF)';

/** Инвертированный вторичный цвет текста */
export const inverseTextSecondaryActive = 'var(--inverse-text-secondary-active, #080808AB)';

/** Инвертированный вторичный цвет текста */
export const inverseTextSecondary = 'var(--inverse-text-secondary, #0808088F)';

/** Инвертированный третичный цвет текста */
export const inverseTextTertiaryHover = 'var(--inverse-text-tertiary-hover, #080808FF)';

/** Инвертированный третичный цвет текста */
export const inverseTextTertiaryActive = 'var(--inverse-text-tertiary-active, #08080856)';

/** Инвертированный третичный цвет текста */
export const inverseTextTertiary = 'var(--inverse-text-tertiary, #08080847)';

/** Инвертированный cплошной наборный текст */
export const inverseTextParagraphHover = 'var(--inverse-text-paragraph-hover, #0808087A)';

/** Инвертированный cплошной наборный текст */
export const inverseTextParagraphActive = 'var(--inverse-text-paragraph-active, #080808A3)';

/** Инвертированный cплошной наборный текст */
export const inverseTextParagraph = 'var(--inverse-text-paragraph, #080808CC)';

/** Основной непрозрачный фон поверхности/контрола */
export const surfaceSolidPrimaryHover = 'var(--surface-solid-primary-hover, #1C1C1CFF)';

/** Основной непрозрачный фон поверхности/контрола */
export const surfaceSolidPrimaryActive = 'var(--surface-solid-primary-active, #121212FF)';

/** Основной непрозрачный фон поверхности/контрола */
export const surfaceSolidPrimary = 'var(--surface-solid-primary, #171717)';

/** Основной непрозрачный фон поверхности/контрола */
export const surfaceSolidPrimaryBrightness = 'var(--surface-solid-primary-brightness, #252525FF)';

/** Вторичный непрозрачный фон поверхности/контрола */
export const surfaceSolidSecondaryHover = 'var(--surface-solid-secondary-hover, #303030FF)';

/** Вторичный непрозрачный фон поверхности/контрола */
export const surfaceSolidSecondaryActive = 'var(--surface-solid-secondary-active, #212121FF)';

/** Вторичный непрозрачный фон поверхности/контрола */
export const surfaceSolidSecondary = 'var(--surface-solid-secondary, #262626)';

/** Третичный непрозрачный фон поверхности/контрола */
export const surfaceSolidTertiaryHover = 'var(--surface-solid-tertiary-hover, #404040FF)';

/** Третичный непрозрачный фон поверхности/контрола */
export const surfaceSolidTertiaryActive = 'var(--surface-solid-tertiary-active, #303030FF)';

/** Третичный непрозрачный фон поверхности/контрола */
export const surfaceSolidTertiary = 'var(--surface-solid-tertiary, #363636)';

/** Основной фон для карточек */
export const surfaceSolidCardHover = 'var(--surface-solid-card-hover, #1C1C1CFF)';

/** Основной фон для карточек */
export const surfaceSolidCardActive = 'var(--surface-solid-card-active, #121212FF)';

/** Основной фон для карточек */
export const surfaceSolidCard = 'var(--surface-solid-card, #171717)';

/** Основной фон для карточек */
export const surfaceSolidCardBrightness = 'var(--surface-solid-card-brightness, #252525FF)';

/** Непрозрачный фон поверхности/контрола по умолчанию */
export const surfaceSolidDefaultHover = 'var(--surface-solid-default-hover, #FFFFFFFF)';

/** Непрозрачный фон поверхности/контрола по умолчанию */
export const surfaceSolidDefaultActive = 'var(--surface-solid-default-active, #FFFFFFFF)';

/** Непрозрачный фон поверхности/контрола по умолчанию */
export const surfaceSolidDefault = 'var(--surface-solid-default, #FFFFFFFF)';

/** Основной прозрачный фон поверхности/контрола */
export const surfaceTransparentPrimaryHover = 'var(--surface-transparent-primary-hover, #FFFFFF1F)';

/** Основной прозрачный фон поверхности/контрола */
export const surfaceTransparentPrimaryActive = 'var(--surface-transparent-primary-active, #FFFFFF0A)';

/** Основной прозрачный фон поверхности/контрола */
export const surfaceTransparentPrimary = 'var(--surface-transparent-primary, #FFFFFF0F)';

/** Вторичный прозрачный фон поверхности/контрола */
export const surfaceTransparentSecondaryHover = 'var(--surface-transparent-secondary-hover, #FFFFFF3D)';

/** Вторичный прозрачный фон поверхности/контрола */
export const surfaceTransparentSecondaryActive = 'var(--surface-transparent-secondary-active, #FFFFFF0F)';

/** Вторичный прозрачный фон поверхности/контрола */
export const surfaceTransparentSecondary = 'var(--surface-transparent-secondary, #FFFFFF1F)';

/** Третичный прозрачный фон поверхности/контрола */
export const surfaceTransparentTertiaryHover = 'var(--surface-transparent-tertiary-hover, #FFFFFF52)';

/** Третичный прозрачный фон поверхности/контрола */
export const surfaceTransparentTertiaryActive = 'var(--surface-transparent-tertiary-active, #FFFFFF24)';

/** Третичный прозрачный фон поверхности/контрола */
export const surfaceTransparentTertiary = 'var(--surface-transparent-tertiary, #FFFFFF33)';

/** Прозрачный фон для карточек */
export const surfaceTransparentCardHover = 'var(--surface-transparent-card-hover, #FFFFFF1F)';

/** Прозрачный фон для карточек */
export const surfaceTransparentCardActive = 'var(--surface-transparent-card-active, #FFFFFF0A)';

/** Прозрачный фон для карточек */
export const surfaceTransparentCard = 'var(--surface-transparent-card, #FFFFFF0F)';

/** Прозрачный фон для карточек */
export const surfaceTransparentCardBrightness = 'var(--surface-transparent-card-brightness, #FFFFFFFF)';

/** Фон поверхности/контрола без заливки */
export const surfaceClearHover = 'var(--surface-clear-hover, #00000000)';

/** Фон поверхности/контрола без заливки */
export const surfaceClearActive = 'var(--surface-clear-active, #00000000)';

/** Фон поверхности/контрола без заливки */
export const surfaceClear = 'var(--surface-clear, #00000000)';

/** Цвет фона поверхности/контрола успех */
export const surfacePositiveHover = 'var(--surface-positive-hover, #1DAF37FF)';

/** Цвет фона поверхности/контрола успех */
export const surfacePositiveActive = 'var(--surface-positive-active, #18952FFF)';

/** Цвет фона поверхности/контрола успех */
export const surfacePositive = 'var(--surface-positive, #1A9E32)';

/** Цвет фона поверхности/контрола предупреждение */
export const surfaceWarningHover = 'var(--surface-warning-hover, #FB7223FF)';

/** Цвет фона поверхности/контрола предупреждение */
export const surfaceWarningActive = 'var(--surface-warning-active, #F05B05FF)';

/** Цвет фона поверхности/контрола предупреждение */
export const surfaceWarning = 'var(--surface-warning, #FA5F05)';

/** Цвет фона поверхности/контрола ошибка */
export const surfaceNegativeHover = 'var(--surface-negative-hover, #FF475AFF)';

/** Цвет фона поверхности/контрола ошибка */
export const surfaceNegativeActive = 'var(--surface-negative-active, #FF1F35FF)';

/** Цвет фона поверхности/контрола ошибка */
export const surfaceNegative = 'var(--surface-negative, #FF293E)';

/** Акцентный цвет поверхности/контролла Афины */
export const surfaceAccentAthenaHover = 'var(--surface-accent-athena-hover, #1798EEFF)';

/** Акцентный цвет поверхности/контролла Афины */
export const surfaceAccentAthenaActive = 'var(--surface-accent-athena-active, #1086D5FF)';

/** Акцентный цвет поверхности/контролла Афины */
export const surfaceAccentAthena = 'var(--surface-accent-athena, #118CDF)';

/** Акцентный цвет поверхности/контролла Джой */
export const surfaceAccentJoyHover = 'var(--surface-accent-joy-hover, #C275F5FF)';

/** Акцентный цвет поверхности/контролла Джой */
export const surfaceAccentJoyActive = 'var(--surface-accent-joy-active, #B14FF3FF)';

/** Акцентный цвет поверхности/контролла Джой */
export const surfaceAccentJoy = 'var(--surface-accent-joy, #B559F3)';

/** Акцентный цвет поверхности/контролла B2E-ассистента */
export const surfaceAccentB2EHover = 'var(--surface-accent-b2-e-hover, #1DAF37FF)';

/** Акцентный цвет поверхности/контролла B2E-ассистента */
export const surfaceAccentB2EActive = 'var(--surface-accent-b2-e-active, #18952FFF)';

/** Акцентный цвет поверхности/контролла B2E-ассистента */
export const surfaceAccentB2E = 'var(--surface-accent-b2-e, #1A9E32)';

/** Акцентный цвет поверхности/контролла бренда */
export const surfaceAccentBrandHover = 'var(--surface-accent-brand-hover, #5D95FDFF)';

/** Акцентный цвет поверхности/контролла бренда */
export const surfaceAccentBrandActive = 'var(--surface-accent-brand-active, #357BFDFF)';

/** Акцентный цвет поверхности/контролла бренда */
export const surfaceAccentBrand = 'var(--surface-accent-brand, #3F81FD)';

/** Цвет баббла сообщения от пользователя */
export const surfaceSpeechBubbleSentHover = 'var(--surface-speech-bubble-sent-hover, #08080866)';

/** Цвет баббла сообщения от пользователя */
export const surfaceSpeechBubbleSentActive = 'var(--surface-speech-bubble-sent-active, #08080838)';

/** Цвет баббла сообщения от пользователя */
export const surfaceSpeechBubbleSent = 'var(--surface-speech-bubble-sent, #08080847)';

/** Цвет баббла сообщения от ассистента */
export const surfaceSpeechBubbleReceivedHover = 'var(--surface-speech-bubble-received-hover, #FFFFFF1F)';

/** Цвет баббла сообщения от ассистента */
export const surfaceSpeechBubbleReceivedActive = 'var(--surface-speech-bubble-received-active, #FFFFFF0A)';

/** Цвет баббла сообщения от ассистента */
export const surfaceSpeechBubbleReceived = 'var(--surface-speech-bubble-received, #FFFFFF0F)';

/** Фон для скелетона */
export const surfaceSkeletonHover = 'var(--surface-skeleton-hover, #FFFFFFFF)';

/** Фон для скелетона */
export const surfaceSkeletonActive = 'var(--surface-skeleton-active, #FFFFFFFF)';

/** Акцентный цвет поверхности/контролла */
export const surfaceAccentMainHover = 'var(--surface-accent-main-hover, #1DAF37FF)';

/** Акцентный цвет поверхности/контролла */
export const surfaceAccentMainActive = 'var(--surface-accent-main-active, #18952FFF)';

/** Акцентный цвет поверхности/контролла */
export const surfaceAccentMain = 'var(--surface-accent-main, #1A9E32)';

/** Основной непрозрачный фон поверхности/контрола на темном фоне */
export const onDarkSurfaceSolidPrimaryHover = 'var(--on-dark-surface-solid-primary-hover, #1C1C1CFF)';

/** Основной непрозрачный фон поверхности/контрола на темном фоне */
export const onDarkSurfaceSolidPrimaryActive = 'var(--on-dark-surface-solid-primary-active, #121212FF)';

/** Основной непрозрачный фон поверхности/контрола на темном фоне */
export const onDarkSurfaceSolidPrimary = 'var(--on-dark-surface-solid-primary, #171717)';

/** Основной непрозрачный фон поверхности/контрола на темном фоне */
export const onDarkSurfaceSolidPrimaryBrightness = 'var(--on-dark-surface-solid-primary-brightness, #252525FF)';

/** Вторичный непрозрачный фон поверхности/контрола на темном */
export const onDarkSurfaceSolidSecondaryHover = 'var(--on-dark-surface-solid-secondary-hover, #303030FF)';

/** Вторичный непрозрачный фон поверхности/контрола на темном */
export const onDarkSurfaceSolidSecondaryActive = 'var(--on-dark-surface-solid-secondary-active, #212121FF)';

/** Вторичный непрозрачный фон поверхности/контрола на темном */
export const onDarkSurfaceSolidSecondary = 'var(--on-dark-surface-solid-secondary, #262626)';

/** Третичный непрозрачный фон поверхности/контрола на темном фоне */
export const onDarkSurfaceSolidTertiaryHover = 'var(--on-dark-surface-solid-tertiary-hover, #404040FF)';

/** Третичный непрозрачный фон поверхности/контрола на темном фоне */
export const onDarkSurfaceSolidTertiaryActive = 'var(--on-dark-surface-solid-tertiary-active, #303030FF)';

/** Третичный непрозрачный фон поверхности/контрола на темном фоне */
export const onDarkSurfaceSolidTertiary = 'var(--on-dark-surface-solid-tertiary, #363636)';

/** Основной фон для карточек на темном фоне */
export const onDarkSurfaceSolidCardHover = 'var(--on-dark-surface-solid-card-hover, #1C1C1CFF)';

/** Основной фон для карточек на темном фоне */
export const onDarkSurfaceSolidCardActive = 'var(--on-dark-surface-solid-card-active, #121212FF)';

/** Основной фон для карточек на темном фоне */
export const onDarkSurfaceSolidCard = 'var(--on-dark-surface-solid-card, #171717)';

/** Основной фон для карточек на темном фоне */
export const onDarkSurfaceSolidCardBrightness = 'var(--on-dark-surface-solid-card-brightness, #252525FF)';

/** Непрозрачный фон поверхности/контрола по умолчанию на темном фоне */
export const onDarkSurfaceSolidDefaultHover = 'var(--on-dark-surface-solid-default-hover, #FFFFFFFF)';

/** Непрозрачный фон поверхности/контрола по умолчанию на темном фоне */
export const onDarkSurfaceSolidDefaultActive = 'var(--on-dark-surface-solid-default-active, #FFFFFFFF)';

/** Непрозрачный фон поверхности/контрола по умолчанию на темном фоне */
export const onDarkSurfaceSolidDefault = 'var(--on-dark-surface-solid-default, #FFFFFFFF)';

/** Основной прозрачный фон поверхности/контрола на темном фоне */
export const onDarkSurfaceTransparentPrimaryHover = 'var(--on-dark-surface-transparent-primary-hover, #FFFFFF1F)';

/** Основной прозрачный фон поверхности/контрола на темном фоне */
export const onDarkSurfaceTransparentPrimaryActive = 'var(--on-dark-surface-transparent-primary-active, #FFFFFF0A)';

/** Основной прозрачный фон поверхности/контрола на темном фоне */
export const onDarkSurfaceTransparentPrimary = 'var(--on-dark-surface-transparent-primary, #FFFFFF0F)';

/** Вторичный прозрачный фон поверхности/контрола на темном фоне */
export const onDarkSurfaceTransparentSecondaryHover = 'var(--on-dark-surface-transparent-secondary-hover, #FFFFFF3D)';

/** Вторичный прозрачный фон поверхности/контрола на темном фоне */
export const onDarkSurfaceTransparentSecondaryActive = 'var(--on-dark-surface-transparent-secondary-active, #FFFFFF0F)';

/** Вторичный прозрачный фон поверхности/контрола на темном фоне */
export const onDarkSurfaceTransparentSecondary = 'var(--on-dark-surface-transparent-secondary, #FFFFFF1F)';

/** Третичный прозрачный фон поверхности/контрола на темном фоне */
export const onDarkSurfaceTransparentTertiaryHover = 'var(--on-dark-surface-transparent-tertiary-hover, #FFFFFF52)';

/** Третичный прозрачный фон поверхности/контрола на темном фоне */
export const onDarkSurfaceTransparentTertiaryActive = 'var(--on-dark-surface-transparent-tertiary-active, #FFFFFF24)';

/** Третичный прозрачный фон поверхности/контрола на темном фоне */
export const onDarkSurfaceTransparentTertiary = 'var(--on-dark-surface-transparent-tertiary, #FFFFFF33)';

/** Прозрачный фон для карточек на темном фоне */
export const onDarkSurfaceTransparentCardHover = 'var(--on-dark-surface-transparent-card-hover, #FFFFFF1F)';

/** Прозрачный фон для карточек на темном фоне */
export const onDarkSurfaceTransparentCardActive = 'var(--on-dark-surface-transparent-card-active, #FFFFFF0A)';

/** Прозрачный фон для карточек на темном фоне */
export const onDarkSurfaceTransparentCard = 'var(--on-dark-surface-transparent-card, #FFFFFF0F)';

/** Прозрачный фон для карточек на темном фоне */
export const onDarkSurfaceTransparentCardBrightness = 'var(--on-dark-surface-transparent-card-brightness, #FFFFFFFF)';

/** Цвет фона поверхности/контрола успех на темном фоне */
export const onDarkSurfacePositiveHover = 'var(--on-dark-surface-positive-hover, #1DAF37FF)';

/** Цвет фона поверхности/контрола успех на темном фоне */
export const onDarkSurfacePositiveActive = 'var(--on-dark-surface-positive-active, #18952FFF)';

/** Цвет фона поверхности/контрола успех на темном фоне */
export const onDarkSurfacePositive = 'var(--on-dark-surface-positive, #1A9E32)';

/** Цвет фона поверхности/контрола предупреждение на темном */
export const onDarkSurfaceWarningHover = 'var(--on-dark-surface-warning-hover, #FB7223FF)';

/** Цвет фона поверхности/контрола предупреждение на темном */
export const onDarkSurfaceWarningActive = 'var(--on-dark-surface-warning-active, #F05B05FF)';

/** Цвет фона поверхности/контрола предупреждение на темном */
export const onDarkSurfaceWarning = 'var(--on-dark-surface-warning, #FA5F05)';

/** Цвет фона поверхности/контрола ошибка на темном */
export const onDarkSurfaceNegativeHover = 'var(--on-dark-surface-negative-hover, #FF475AFF)';

/** Цвет фона поверхности/контрола ошибка на темном */
export const onDarkSurfaceNegativeActive = 'var(--on-dark-surface-negative-active, #FF1F35FF)';

/** Цвет фона поверхности/контрола ошибка на темном */
export const onDarkSurfaceNegative = 'var(--on-dark-surface-negative, #FF293E)';

/** Акцентный цвет поверхности/контролла Афины */
export const onDarkSurfaceAccentAthenaHover = 'var(--on-dark-surface-accent-athena-hover, #1798EEFF)';

/** Акцентный цвет поверхности/контролла Афины */
export const onDarkSurfaceAccentAthenaActive = 'var(--on-dark-surface-accent-athena-active, #1086D5FF)';

/** Акцентный цвет поверхности/контролла Афины */
export const onDarkSurfaceAccentAthena = 'var(--on-dark-surface-accent-athena, #118CDF)';

/** Акцентный цвет поверхности/контролла Джой */
export const onDarkSurfaceAccentJoyHover = 'var(--on-dark-surface-accent-joy-hover, #C275F5FF)';

/** Акцентный цвет поверхности/контролла Джой */
export const onDarkSurfaceAccentJoyActive = 'var(--on-dark-surface-accent-joy-active, #B14FF3FF)';

/** Акцентный цвет поверхности/контролла Джой */
export const onDarkSurfaceAccentJoy = 'var(--on-dark-surface-accent-joy, #B559F3)';

/** Акцентный цвет поверхности/контролла B2E-ассистента */
export const onDarkSurfaceAccentB2EHover = 'var(--on-dark-surface-accent-b2-e-hover, #1DAF37FF)';

/** Акцентный цвет поверхности/контролла B2E-ассистента */
export const onDarkSurfaceAccentB2EActive = 'var(--on-dark-surface-accent-b2-e-active, #18952FFF)';

/** Акцентный цвет поверхности/контролла B2E-ассистента */
export const onDarkSurfaceAccentB2E = 'var(--on-dark-surface-accent-b2-e, #1A9E32)';

/** Акцентный цвет поверхности/контролла бренда */
export const onDarkSurfaceAccentBrandHover = 'var(--on-dark-surface-accent-brand-hover, #5D95FDFF)';

/** Акцентный цвет поверхности/контролла бренда */
export const onDarkSurfaceAccentBrandActive = 'var(--on-dark-surface-accent-brand-active, #357BFDFF)';

/** Акцентный цвет поверхности/контролла бренда */
export const onDarkSurfaceAccentBrand = 'var(--on-dark-surface-accent-brand, #3F81FD)';

/** Акцентный цвет поверхности/контролла */
export const onDarkSurfaceAccentMainHover = 'var(--on-dark-surface-accent-main-hover, #1DAF37FF)';

/** Акцентный цвет поверхности/контролла */
export const onDarkSurfaceAccentMainActive = 'var(--on-dark-surface-accent-main-active, #18952FFF)';

/** Акцентный цвет поверхности/контролла */
export const onDarkSurfaceAccentMain = 'var(--on-dark-surface-accent-main, #1A9E32)';

/** Основной непрозрачный фон поверхности/контрола на светлом */
export const onLightSurfaceSolidPrimaryHover = 'var(--on-light-surface-solid-primary-hover, #FAFAFAFF)';

/** Основной непрозрачный фон поверхности/контрола на светлом */
export const onLightSurfaceSolidPrimaryActive = 'var(--on-light-surface-solid-primary-active, #F0F0F0FF)';

/** Основной непрозрачный фон поверхности/контрола на светлом */
export const onLightSurfaceSolidPrimary = 'var(--on-light-surface-solid-primary, #F5F5F5)';

/** Основной непрозрачный фон поверхности/контрола на светлом */
export const onLightSurfaceSolidPrimaryBrightness = 'var(--on-light-surface-solid-primary-brightness, #F6F6F6FF)';

/** Вторичный непрозрачный фон поверхности/контрола на светлом */
export const onLightSurfaceSolidSecondaryHover = 'var(--on-light-surface-solid-secondary-hover, #F7F7F7FF)';

/** Вторичный непрозрачный фон поверхности/контрола на светлом */
export const onLightSurfaceSolidSecondaryActive = 'var(--on-light-surface-solid-secondary-active, #E8E8E8FF)';

/** Вторичный непрозрачный фон поверхности/контрола на светлом */
export const onLightSurfaceSolidSecondary = 'var(--on-light-surface-solid-secondary, #ECECEC)';

/** Третичный непрозрачный фон поверхности/контрола на светлом */
export const onLightSurfaceSolidTertiaryHover = 'var(--on-light-surface-solid-tertiary-hover, #E8E8E8FF)';

/** Третичный непрозрачный фон поверхности/контрола на светлом */
export const onLightSurfaceSolidTertiaryActive = 'var(--on-light-surface-solid-tertiary-active, #D9D9D9FF)';

/** Третичный непрозрачный фон поверхности/контрола на светлом */
export const onLightSurfaceSolidTertiary = 'var(--on-light-surface-solid-tertiary, #DDDDDD)';

/** Основной фон для карточек на светлом фоне */
export const onLightSurfaceSolidCardHover = 'var(--on-light-surface-solid-card-hover, #FFFFFFFF)';

/** Основной фон для карточек на светлом фоне */
export const onLightSurfaceSolidCardActive = 'var(--on-light-surface-solid-card-active, #FFFFFFFF)';

/** Основной фон для карточек на светлом фоне */
export const onLightSurfaceSolidCard = 'var(--on-light-surface-solid-card, #FFFFFFFF)';

/** Основной фон для карточек на светлом фоне */
export const onLightSurfaceSolidCardBrightness = 'var(--on-light-surface-solid-card-brightness, #FFFFFFFF)';

/** Непрозрачный фон поверхности/контрола по умолчанию на светлом фоне */
export const onLightSurfaceSolidDefaultHover = 'var(--on-light-surface-solid-default-hover, #0D0D0DFF)';

/** Непрозрачный фон поверхности/контрола по умолчанию на светлом фоне */
export const onLightSurfaceSolidDefaultActive = 'var(--on-light-surface-solid-default-active, #030303FF)';

/** Непрозрачный фон поверхности/контрола по умолчанию на светлом фоне */
export const onLightSurfaceSolidDefault = 'var(--on-light-surface-solid-default, #080808)';

/** Основной прозрачный фон поверхности/контрола на светлом */
export const onLightSurfaceTransparentPrimaryHover = 'var(--on-light-surface-transparent-primary-hover, #08080812)';

/** Основной прозрачный фон поверхности/контрола на светлом */
export const onLightSurfaceTransparentPrimaryActive = 'var(--on-light-surface-transparent-primary-active, #08080803)';

/** Основной прозрачный фон поверхности/контрола на светлом */
export const onLightSurfaceTransparentPrimary = 'var(--on-light-surface-transparent-primary, #08080808)';

/** Вторичный прозрачный фон поверхности/контрола на светлом фоне */
export const onLightSurfaceTransparentSecondaryHover = 'var(--on-light-surface-transparent-secondary-hover, #0808081F)';

/** Вторичный прозрачный фон поверхности/контрола на светлом фоне */
export const onLightSurfaceTransparentSecondaryActive =
    'var(--on-light-surface-transparent-secondary-active, #0808080A)';

/** Вторичный прозрачный фон поверхности/контрола на светлом фоне */
export const onLightSurfaceTransparentSecondary = 'var(--on-light-surface-transparent-secondary, #0808080F)';

/** Третичный прозрачный фон поверхности/контрола на светлом фоне */
export const onLightSurfaceTransparentTertiaryHover = 'var(--on-light-surface-transparent-tertiary-hover, #0808083D)';

/** Третичный прозрачный фон поверхности/контрола на светлом фоне */
export const onLightSurfaceTransparentTertiaryActive = 'var(--on-light-surface-transparent-tertiary-active, #0808080F)';

/** Третичный прозрачный фон поверхности/контрола на светлом фоне */
export const onLightSurfaceTransparentTertiary = 'var(--on-light-surface-transparent-tertiary, #0808081F)';

/** Прозрачный цвет поверхности/контролла на светлом фоне */
export const onLightSurfaceTransparentDeepHover = 'var(--on-light-surface-transparent-deep-hover, #080808C2)';

/** Прозрачный цвет поверхности/контролла на светлом фоне */
export const onLightSurfaceTransparentDeepActive = 'var(--on-light-surface-transparent-deep-active, #08080894)';

/** Прозрачный цвет поверхности/контролла на светлом фоне */
export const onLightSurfaceTransparentDeep = 'var(--on-light-surface-transparent-deep, #080808A2)';

/** Прозрачный фон для карточек на светлом фоне */
export const onLightSurfaceTransparentCardHover = 'var(--on-light-surface-transparent-card-hover, #FFFFFFFF)';

/** Прозрачный фон для карточек на светлом фоне */
export const onLightSurfaceTransparentCardActive = 'var(--on-light-surface-transparent-card-active, #FFFFFFFF)';

/** Прозрачный фон для карточек на светлом фоне */
export const onLightSurfaceTransparentCard = 'var(--on-light-surface-transparent-card, #FFFFFFFF)';

/** Прозрачный фон для карточек на светлом фоне */
export const onLightSurfaceTransparentCardBrightness = 'var(--on-light-surface-transparent-card-brightness, #FFFFFFFF)';

/** Цвет фона поверхности/контрола успех на светлом фоне */
export const onLightSurfacePositiveHover = 'var(--on-light-surface-positive-hover, #1DAF37FF)';

/** Цвет фона поверхности/контрола успех на светлом фоне */
export const onLightSurfacePositiveActive = 'var(--on-light-surface-positive-active, #18952FFF)';

/** Цвет фона поверхности/контрола успех на светлом фоне */
export const onLightSurfacePositive = 'var(--on-light-surface-positive, #1A9E32)';

/** Цвет фона поверхности/контрола предупреждение на светлом */
export const onLightSurfaceWarningHover = 'var(--on-light-surface-warning-hover, #FB7223FF)';

/** Цвет фона поверхности/контрола предупреждение на светлом */
export const onLightSurfaceWarningActive = 'var(--on-light-surface-warning-active, #F05B05FF)';

/** Цвет фона поверхности/контрола предупреждение на светлом */
export const onLightSurfaceWarning = 'var(--on-light-surface-warning, #FA5F05)';

/** Цвет фона поверхности/контрола ошибка на светлом фоне */
export const onLightSurfaceNegativeHover = 'var(--on-light-surface-negative-hover, #FF475AFF)';

/** Цвет фона поверхности/контрола ошибка на светлом фоне */
export const onLightSurfaceNegativeActive = 'var(--on-light-surface-negative-active, #FF1F35FF)';

/** Цвет фона поверхности/контрола ошибка на светлом фоне */
export const onLightSurfaceNegative = 'var(--on-light-surface-negative, #FF293E)';

/** Акцентный цвет поверхности/контролла Афины на светлом фоне */
export const onLightSurfaceAccentAthenaHover = 'var(--on-light-surface-accent-athena-hover, #1798EEFF)';

/** Акцентный цвет поверхности/контролла Афины на светлом фоне */
export const onLightSurfaceAccentAthenaActive = 'var(--on-light-surface-accent-athena-active, #1086D5FF)';

/** Акцентный цвет поверхности/контролла Афины на светлом фоне */
export const onLightSurfaceAccentAthena = 'var(--on-light-surface-accent-athena, #118CDF)';

/** Акцентный цвет поверхности/контролла Джой на светлом */
export const onLightSurfaceAccentJoyHover = 'var(--on-light-surface-accent-joy-hover, #C275F5FF)';

/** Акцентный цвет поверхности/контролла Джой на светлом */
export const onLightSurfaceAccentJoyActive = 'var(--on-light-surface-accent-joy-active, #B14FF3FF)';

/** Акцентный цвет поверхности/контролла Джой на светлом */
export const onLightSurfaceAccentJoy = 'var(--on-light-surface-accent-joy, #B559F3)';

/** Акцентный цвет поверхности B2E-ассистента на светлом */
export const onLightSurfaceAccentB2EHover = 'var(--on-light-surface-accent-b2-e-hover, #1DAF37FF)';

/** Акцентный цвет поверхности B2E-ассистента на светлом */
export const onLightSurfaceAccentB2EActive = 'var(--on-light-surface-accent-b2-e-active, #18952FFF)';

/** Акцентный цвет поверхности B2E-ассистента на светлом */
export const onLightSurfaceAccentB2E = 'var(--on-light-surface-accent-b2-e, #1A9E32)';

/** Акцентный цвет поверхности/контролла бренда на светлом */
export const onLightSurfaceAccentBrandHover = 'var(--on-light-surface-accent-brand-hover, #5D95FDFF)';

/** Акцентный цвет поверхности/контролла бренда на светлом */
export const onLightSurfaceAccentBrandActive = 'var(--on-light-surface-accent-brand-active, #357BFDFF)';

/** Акцентный цвет поверхности/контролла бренда на светлом */
export const onLightSurfaceAccentBrand = 'var(--on-light-surface-accent-brand, #3F81FD)';

/** Акцентный цвет поверхности/контролла на светлом фоне */
export const onLightSurfaceAccentMainHover = 'var(--on-light-surface-accent-main-hover, #1DAF37FF)';

/** Акцентный цвет поверхности/контролла на светлом фоне */
export const onLightSurfaceAccentMainActive = 'var(--on-light-surface-accent-main-active, #18952FFF)';

/** Акцентный цвет поверхности/контролла на светлом фоне */
export const onLightSurfaceAccentMain = 'var(--on-light-surface-accent-main, #1A9E32)';

/** Первичный фон */
export const backgroundPrimary = 'var(--background-primary, #000000FF)';

/** Первичный фон */
export const backgroundPrimaryBrightness = 'var(--background-primary-brightness, #0F0FFFFF)';

/** Вторичный фон */
export const backgroundSecondary = 'var(--background-secondary, #171717)';

/** Цвет фона паранжи светлый на темном фоне */
export const onDarkOverlaySoft = 'var(--on-dark-overlay-soft, #0000008F)';

/** Цвет фона паранжи темный на темном фоне */
export const onDarkOverlayHard = 'var(--on-dark-overlay-hard, #000000EB)';

/** Оверлей с блюром */
export const onDarkOverlayBlur = 'var(--on-dark-overlay-blur, #26262647)';

/** Градиент Афины */
export const textGradientAthenaHover = 'var(--text-gradient-athena-hover, #CCCCCCFF)';

/** Градиент Афины */
export const textGradientAthenaActive = 'var(--text-gradient-athena-active, #E6E6E6FF)';

/** Градиент Афины */
export const textGradientAthena =
    'var(--text-gradient-athena, linear-gradient(93.97deg, #52BAFFFF 6.49%, #ADADFFFF 93.51%))';

/** Градиент Джой */
export const textGradientJoyHover = 'var(--text-gradient-joy-hover, #CCCCCCFF)';

/** Градиент Джой */
export const textGradientJoyActive = 'var(--text-gradient-joy-active, #E6E6E6FF)';

/** Градиент Джой */
export const textGradientJoy = 'var(--text-gradient-joy, linear-gradient(93.97deg, #FD9C68FF 6.49%, #F391E2FF 93.51%))';

/** Градиент B2E-ассистента */
export const textGradientB2EHover = 'var(--text-gradient-b2-e-hover, #CCCCCCFF)';

/** Градиент B2E-ассистента */
export const textGradientB2EActive = 'var(--text-gradient-b2-e-active, #E6E6E6FF)';

/** Градиент B2E-ассистента */
export const textGradientB2E = 'var(--text-gradient-b2-e, linear-gradient(89.83deg, #24B23EFF 0%, #1CC9C9FF 100%))';

/** Градиент бренда */
export const textGradientBrandHover = 'var(--text-gradient-brand-hover, #CCCCCCFF)';

/** Градиент бренда */
export const textGradientBrandActive = 'var(--text-gradient-brand-active, #E6E6E6FF)';

/** Градиент бренда */
export const textGradientBrand = 'var(--text-gradient-brand, linear-gradient(89.83deg, #528EFFFF 0%, #04C6C9FF 100%))';

/** Градиент */
export const textGradientMainHover = 'var(--text-gradient-main-hover, #CCCCCCFF)';

/** Градиент */
export const textGradientMainActive = 'var(--text-gradient-main-active, #E6E6E6FF)';

/** Градиент */
export const textGradientMain = 'var(--text-gradient-main, linear-gradient(89.83deg, #24B23EFF 0%, #1CC9C9FF 100%))';

/** Градиент Афины на темном фоне */
export const onDarkTextGradientAthenaHover = 'var(--on-dark-text-gradient-athena-hover, #CCCCCCFF)';

/** Градиент Афины на темном фоне */
export const onDarkTextGradientAthenaActive = 'var(--on-dark-text-gradient-athena-active, #E6E6E6FF)';

/** Градиент Афины на темном фоне */
export const onDarkTextGradientAthena =
    'var(--on-dark-text-gradient-athena, linear-gradient(93.97deg, #52BAFFFF 6.49%, #ADADFFFF 93.51%))';

/** Градиент Джой на темном фоне */
export const onDarkTextGradientJoyHover = 'var(--on-dark-text-gradient-joy-hover, #CCCCCCFF)';

/** Градиент Джой на темном фоне */
export const onDarkTextGradientJoyActive = 'var(--on-dark-text-gradient-joy-active, #E6E6E6FF)';

/** Градиент Джой на темном фоне */
export const onDarkTextGradientJoy =
    'var(--on-dark-text-gradient-joy, linear-gradient(93.97deg, #FD9C68FF 6.49%, #F391E2FF 93.51%))';

/** Градиент B2E-ассистента на темном фоне */
export const onDarkTextGradientB2EHover = 'var(--on-dark-text-gradient-b2-e-hover, #CCCCCCFF)';

/** Градиент B2E-ассистента на темном фоне */
export const onDarkTextGradientB2EActive = 'var(--on-dark-text-gradient-b2-e-active, #E6E6E6FF)';

/** Градиент B2E-ассистента на темном фоне */
export const onDarkTextGradientB2E =
    'var(--on-dark-text-gradient-b2-e, linear-gradient(89.83deg, #24B23EFF 0%, #1CC9C9FF 100%))';

/** Градиент бренда на темном фоне */
export const onDarkTextGradientBrandHover = 'var(--on-dark-text-gradient-brand-hover, #CCCCCCFF)';

/** Градиент бренда на темном фоне */
export const onDarkTextGradientBrandActive = 'var(--on-dark-text-gradient-brand-active, #E6E6E6FF)';

/** Градиент бренда на темном фоне */
export const onDarkTextGradientBrand =
    'var(--on-dark-text-gradient-brand, linear-gradient(89.83deg, #528EFFFF 0%, #04C6C9FF 100%))';

/** Градиент на темном фоне */
export const onDarkTextGradientMainHover = 'var(--on-dark-text-gradient-main-hover, #CCCCCCFF)';

/** Градиент на темном фоне */
export const onDarkTextGradientMainActive = 'var(--on-dark-text-gradient-main-active, #E6E6E6FF)';

/** Градиент на темном фоне */
export const onDarkTextGradientMain =
    'var(--on-dark-text-gradient-main, linear-gradient(89.83deg, #24B23EFF 0%, #1CC9C9FF 100%))';

/** Градиент Афины на светлом фоне */
export const onLightTextGradientAthenaHover = 'var(--on-light-text-gradient-athena-hover, #CCCCCCFF)';

/** Градиент Афины на светлом фоне */
export const onLightTextGradientAthenaActive = 'var(--on-light-text-gradient-athena-active, #E6E6E6FF)';

/** Градиент Афины на светлом фоне */
export const onLightTextGradientAthena =
    'var(--on-light-text-gradient-athena, linear-gradient(89.83deg, #118CDFFF 0%, #7A7AFFFF 100%))';

/** Градиент Джой на светлом фоне */
export const onLightTextGradientJoyHover = 'var(--on-light-text-gradient-joy-hover, #CCCCCCFF)';

/** Градиент Джой на светлом фоне */
export const onLightTextGradientJoyActive = 'var(--on-light-text-gradient-joy-active, #E6E6E6FF)';

/** Градиент Джой на светлом фоне */
export const onLightTextGradientJoy =
    'var(--on-light-text-gradient-joy, linear-gradient(89.83deg, #FCA349FF 0%, #FF52C5FF 100%))';

/** Градиент B2E-ассистента на светлом фоне */
export const onLightTextGradientB2EHover = 'var(--on-light-text-gradient-b2-e-hover, #CCCCCCFF)';

/** Градиент B2E-ассистента на светлом фоне */
export const onLightTextGradientB2EActive = 'var(--on-light-text-gradient-b2-e-active, #E6E6E6FF)';

/** Градиент B2E-ассистента на светлом фоне */
export const onLightTextGradientB2E =
    'var(--on-light-text-gradient-b2-e, linear-gradient(89.83deg, #24B23EFF 0%, #00A4D1FF 100%))';

/** Акцентный цвет бренда на светлом фоне */
export const onLightTextGradientBrandHover = 'var(--on-light-text-gradient-brand-hover, #CCCCCCFF)';

/** Акцентный цвет бренда на светлом фоне */
export const onLightTextGradientBrandActive = 'var(--on-light-text-gradient-brand-active, #E6E6E6FF)';

/** Акцентный цвет бренда на светлом фоне */
export const onLightTextGradientBrand =
    'var(--on-light-text-gradient-brand, linear-gradient(93.97deg, #3E79F0FF 6.49%, #27C6E5FF 93.51%))';

/** Градиент на светлом фоне */
export const onLightTextGradientMainHover = 'var(--on-light-text-gradient-main-hover, #CCCCCCFF)';

/** Градиент на светлом фоне */
export const onLightTextGradientMainActive = 'var(--on-light-text-gradient-main-active, #E6E6E6FF)';

/** Градиент на светлом фоне */
export const onLightTextGradientMain =
    'var(--on-light-text-gradient-main, linear-gradient(89.83deg, #24B23EFF 0%, #00A4D1FF 100%))';

/** Фон для скелетона */
export const surfaceSkeleton =
    'var(--surface-skeleton, linear-gradient(90deg, #FFFFFF00 0%, #FFFFFF03 17.19%, #FFFFFF0D 40.24%, #FFFFFF0F 51.17%, #FFFFFF0D 62.12%, #FFFFFF03 82.81%, #FFFFFF00 100%))';

/** dark surface default surfaceGradientMainHover */
export const surfaceGradientMainHover = 'var(--surface-gradient-main-hover, #FFFFFFFF)';

/** dark surface default surfaceGradientMainActive */
export const surfaceGradientMainActive = 'var(--surface-gradient-main-active, #FFFFFFFF)';

/** dark surface default surfaceGradientMain */
export const surfaceGradientMain =
    'var(--surface-gradient-main, linear-gradient(89.83deg, #24B23EFF 0%, #00A4D1FF 100%))';

/** Фон для скелетона */
export const surfaceSkeletonGradient =
    'var(--surface-skeleton-gradient, linear-gradient(90deg, #FFFFFF17 0%, #FFFFFF14 6.25%, #FFFFFF0D 12.5%, #FFFFFF03 25%, #FFFFFF0D 37.5%, #FFFFFF14 43.75%, #FFFFFF17 50%, #FFFFFF14 56.25%, #FFFFFF0D 62.5%, #FFFFFF03 75%, #FFFFFF0D 87.5%, #FFFFFF14 93.75%, #FFFFFF17 100%))';

/** Фон для скелетона */
export const surfaceSkeletonGradientHover = 'var(--surface-skeleton-gradient-hover, #FFFFFFFF)';

/** Фон для скелетона */
export const surfaceSkeletonGradientActive = 'var(--surface-skeleton-gradient-active, #FFFFFFFF)';

/** Яркий фон для скелетона */
export const surfaceSkeletonDeepGradient =
    'var(--surface-skeleton-deep-gradient, linear-gradient(90deg, #FFFFFF5C 0%, #FFFFFF52 6.25%, #FFFFFF33 12.5%, #FFFFFF0A 25%, #FFFFFF33 37.5%, #FFFFFF52 43.75%, #FFFFFF5C 50%, #FFFFFF14 56.25%, #FFFFFF33 62.5%, #FFFFFF0A 75%, #FFFFFF33 87.5%, #FFFFFF52 93.75%, #FFFFFF5C 100%))';

/** Яркий фон для скелетона */
export const surfaceSkeletonDeepGradientHover = 'var(--surface-skeleton-deep-gradient-hover, #FFFFFFFF)';

/** Яркий фон для скелетона */
export const surfaceSkeletonDeepGradientActive = 'var(--surface-skeleton-deep-gradient-active, #FFFFFFFF)';

/** dark surface onDark surfaceGradientMainHover */
export const onDarkSurfaceGradientMainHover = 'var(--on-dark-surface-gradient-main-hover, #FFFFFFFF)';

/** dark surface onDark surfaceGradientMainActive */
export const onDarkSurfaceGradientMainActive = 'var(--on-dark-surface-gradient-main-active, #FFFFFFFF)';

/** dark surface onDark surfaceGradientMain */
export const onDarkSurfaceGradientMain =
    'var(--on-dark-surface-gradient-main, linear-gradient(89.83deg, #24B23EFF 0%, #00A4D1FF 100%))';

/** Фон для скелетона */
export const onDarkSurfaceSkeletonGradient =
    'var(--on-dark-surface-skeleton-gradient, linear-gradient(90deg, #FFFFFF17 0%, #FFFFFF14 6.25%, #FFFFFF0D 12.5%, #FFFFFF03 25%, #FFFFFF0D 37.5%, #FFFFFF14 43.75%, #FFFFFF17 50%, #FFFFFF14 56.25%, #FFFFFF0D 62.5%, #FFFFFF03 75%, #FFFFFF0D 87.5%, #FFFFFF14 93.75%, #FFFFFF17 100%))';

/** Фон для скелетона */
export const onDarkSurfaceSkeletonGradientHover = 'var(--on-dark-surface-skeleton-gradient-hover, #FFFFFFFF)';

/** Фон для скелетона */
export const onDarkSurfaceSkeletonGradientActive = 'var(--on-dark-surface-skeleton-gradient-active, #FFFFFFFF)';

/** Яркий фон для скелетона */
export const onDarkSurfaceSkeletonDeepGradient =
    'var(--on-dark-surface-skeleton-deep-gradient, linear-gradient(90deg, #FFFFFF5C 0%, #FFFFFF52 6.25%, #FFFFFF33 12.5%, #FFFFFF0A 25%, #FFFFFF33 37.5%, #FFFFFF52 43.75%, #FFFFFF5C 50%, #FFFFFF14 56.25%, #FFFFFF33 62.5%, #FFFFFF0A 75%, #FFFFFF33 87.5%, #FFFFFF52 93.75%, #FFFFFF5C 100%))';

/** Яркий фон для скелетона */
export const onDarkSurfaceSkeletonDeepGradientHover = 'var(--on-dark-surface-skeleton-deep-gradient-hover, #FFFFFFFF)';

/** Яркий фон для скелетона */
export const onDarkSurfaceSkeletonDeepGradientActive =
    'var(--on-dark-surface-skeleton-deep-gradient-active, #FFFFFFFF)';

/** dark surface onLight surfaceGradientMainHover */
export const onLightSurfaceGradientMainHover = 'var(--on-light-surface-gradient-main-hover, #FFFFFFFF)';

/** dark surface onLight surfaceGradientMainActive */
export const onLightSurfaceGradientMainActive = 'var(--on-light-surface-gradient-main-active, #FFFFFFFF)';

/** dark surface onLight surfaceGradientMain */
export const onLightSurfaceGradientMain =
    'var(--on-light-surface-gradient-main, linear-gradient(89.83deg, #24B23EFF 0%, #00A4D1FF 100%))';

/** Фон для скелетона */
export const onLightSurfaceSkeletonGradient =
    'var(--on-light-surface-skeleton-gradient, linear-gradient(90deg, #08080817 0%, #08080814 6.25%, #0808080D 12.5%, #08080803 25%, #0808080D 37.5%, #08080814 43.75%, #08080817 50%, #08080814 56.25%, #0808080D 62.5%, #08080803 75%, #0808080D 87.5%, #08080814 93.75%, #08080817 100%))';

/** Фон для скелетона */
export const onLightSurfaceSkeletonGradientHover = 'var(--on-light-surface-skeleton-gradient-hover, #FFFFFFFF)';

/** Фон для скелетона */
export const onLightSurfaceSkeletonGradientActive = 'var(--on-light-surface-skeleton-gradient-active, #FFFFFFFF)';

/** Яркий фон для скелетона */
export const onLightSurfaceSkeletonDeepGradient =
    'var(--on-light-surface-skeleton-deep-gradient, linear-gradient(90deg, #0808085C 0%, #08080852 6.25%, #08080833 12.5%, #0808080A 25%, #08080833 37.5%, #08080852 43.75%, #0808085C 50%, #08080814 56.25%, #08080833 62.5%, #0808080A 75%, #08080833 87.5%, #08080852 93.75%, #0808085C 100%))';

/** Яркий фон для скелетона */
export const onLightSurfaceSkeletonDeepGradientHover =
    'var(--on-light-surface-skeleton-deep-gradient-hover, #FFFFFFFF)';

/** Яркий фон для скелетона */
export const onLightSurfaceSkeletonDeepGradientActive =
    'var(--on-light-surface-skeleton-deep-gradient-active, #FFFFFFFF)';

/** Фон для скелетона */
export const inverseSurfaceSkeletonGradient =
    'var(--inverse-surface-skeleton-gradient, linear-gradient(90deg, #08080817 0%, #08080814 6.25%, #0808080D 12.5%, #08080803 25%, #0808080D 37.5%, #08080814 43.75%, #08080817 50%, #08080814 56.25%, #0808080D 62.5%, #08080803 75%, #0808080D 87.5%, #08080814 93.75%, #08080817 100%))';

/** Фон для скелетона */
export const inverseSurfaceSkeletonGradientHover = 'var(--inverse-surface-skeleton-gradient-hover, #FFFFFFFF)';

/** Фон для скелетона */
export const inverseSurfaceSkeletonGradientActive = 'var(--inverse-surface-skeleton-gradient-active, #FFFFFFFF)';

/** Яркий фон для скелетона */
export const inverseSurfaceSkeletonDeepGradient =
    'var(--inverse-surface-skeleton-deep-gradient, linear-gradient(90deg, #0808085C 0%, #08080852 6.25%, #08080833 12.5%, #0808080A 25%, #08080833 37.5%, #08080852 43.75%, #0808085C 50%, #08080814 56.25%, #08080833 62.5%, #0808080A 75%, #08080833 87.5%, #08080852 93.75%, #0808085C 100%))';

/** Яркий фон для скелетона */
export const inverseSurfaceSkeletonDeepGradientHover = 'var(--inverse-surface-skeleton-deep-gradient-hover, #FFFFFFFF)';

/** Яркий фон для скелетона */
export const inverseSurfaceSkeletonDeepGradientActive =
    'var(--inverse-surface-skeleton-deep-gradient-active, #FFFFFFFF)';

/** Фон для модальной шторки */
export const backgroundModalSheet =
    'var(--background-modal-sheet, linear-gradient(180deg, #FFFFFF1A 0%, #01B6FF00 50%),#080808FF)';

/** Фон Афины на мобиле */
export const backgroundMobileAssistantAthena =
    'var(--background-mobile-assistant-athena, linear-gradient(336.9deg, #143787FF 0%, #08080800 64.95%),radial-gradient(66.53% 100% at 73.33% 100%, #6E05C170 0%, #3513951A 99.69%),linear-gradient(180.03deg, #08080800 50%, #193F9869 99.97%),linear-gradient(270deg, #270F6B4D 0%, #08080800 100%),#080808FF)';

/** Фон Джой на мобиле */
export const backgroundMobileAssistantJoy =
    'var(--background-mobile-assistant-joy, linear-gradient(336.9deg, #FF9C653D 0%, #08080800 64.95%),radial-gradient(66.53% 100% at 73.33% 100%, #3D139557 0%, #1318951A 99.69%),linear-gradient(180.03deg, #08080800 50%, #FFD7B326 99.97%),linear-gradient(270deg, #6B0F5733 0%, #08080800 100%),#080808FF)';

/** Фоновый градиент B2E-ассистента на мобиле */
export const backgroundMobileAssistantB2E =
    'var(--background-mobile-assistant-b2-e, linear-gradient(336.84deg, #14744699 0%, #08080800 64.88%),radial-gradient(100% 100% at 75.89% 100%, #0085FF3D 0%, #0047FF08 100%),linear-gradient(180deg, #08080800 50%, #0747214D 100%),linear-gradient(270deg, #061621FF 0%, #08080800 100%),#080808FF)';

/** Фоновый градиент бренда на мобиле */
export const backgroundMobileAssistantBrand =
    'var(--background-mobile-assistant-brand, linear-gradient(336.9deg, #184BABFF 0%, #08080800 64.95%),radial-gradient(66.53% 100% at 73.33% 100%, #1645A470 0%, #0B272D1A 100%),linear-gradient(180.03deg, #08080800 50%, #1645A469 99.97%),linear-gradient(269.47deg, #1645A44D 0.52%, #08080800 99.61%),#080808FF)';

/** Фон ассистента на мобиле */
export const backgroundMobileAssistantMain =
    'var(--background-mobile-assistant-main, linear-gradient(336.84deg, #14744699 0%, #08080800 64.88%),radial-gradient(100% 100% at 75.89% 100%, #0085FF3D 0%, #0047FF08 100%),linear-gradient(180deg, #08080800 50%, #0747214D 100%),linear-gradient(270deg, #061621FF 0%, #08080800 100%),#080808FF)';

/** shadow down soft s */
export const shadowDownSoftS = 'var(--shadow-down-soft-s, 0px 4px 14px -4px #08080814,0px 1px 4px -1px #0000000A)';

/** shadow down soft m */
export const shadowDownSoftM = 'var(--shadow-down-soft-m, 0px 24px 48px -8px #00000014)';

/** shadow down soft l */
export const shadowDownSoftL = 'var(--shadow-down-soft-l, 0px 60px 112px -8px #00000014)';

/** shadow down hard s */
export const shadowDownHardS = 'var(--shadow-down-hard-s, 0px 4px 12px -3px #08080829,0px 1px 4px -2px #00000014)';

/** shadow down hard m */
export const shadowDownHardM = 'var(--shadow-down-hard-m, 0px 16px 32px -8px #0000003D)';

/** shadow down hard l */
export const shadowDownHardL = 'var(--shadow-down-hard-l, 0px 60px 112px -8px #00000066)';

/** shadow up soft s */
export const shadowUpSoftS = 'var(--shadow-up-soft-s, 0px -4px 14px -4px #08080814,0px -1px 4px -1px #00000008)';

/** shadow up soft m */
export const shadowUpSoftM = 'var(--shadow-up-soft-m, 0px -24px 48px -8px #00000014)';

/** shadow up soft l */
export const shadowUpSoftL = 'var(--shadow-up-soft-l, 0px -60px 112px -8px #00000014)';

/** shadow up hard s */
export const shadowUpHardS = 'var(--shadow-up-hard-s, 0px -4px 12px -3px #08080833,0px -1px 4px -1px #00000008)';

/** shadow up hard m */
export const shadowUpHardM = 'var(--shadow-up-hard-m, 0px -16px 32px -8px #0000003D)';

/** shadow up hard l */
export const shadowUpHardL = 'var(--shadow-up-hard-l, 0px -60px 112px -8px #00000066)';

/** borderRadius xxs */
export const borderRadiusXxs = 'var(--border-radius-xxs, 4px)';

/** borderRadius xs */
export const borderRadiusXs = 'var(--border-radius-xs, 8px)';

/** borderRadius s */
export const borderRadiusS = 'var(--border-radius-s, 12px)';

/** borderRadius m */
export const borderRadiusM = 'var(--border-radius-m, 16px)';

/** borderRadius l */
export const borderRadiusL = 'var(--border-radius-l, 20px)';

/** borderRadius xl */
export const borderRadiusXl = 'var(--border-radius-xl, 24px)';

/** borderRadius xxl */
export const borderRadiusXxl = 'var(--border-radius-xxl, 32px)';

/** typography s display-l */
export const dsplL = {
    fontFamily: 'var(--plasma-typo-dspl-l-font-family)',
    fontSize: 'var(--plasma-typo-dspl-l-font-size)',
    fontStyle: 'var(--plasma-typo-dspl-l-font-style)',
    fontWeight: 'var(--plasma-typo-dspl-l-font-weight)',
    letterSpacing: 'var(--plasma-typo-dspl-l-letter-spacing)',
    lineHeight: 'var(--plasma-typo-dspl-l-line-height)',
};

/** typography s display-l-bold */
export const dsplLBold = {
    fontFamily: 'var(--plasma-typo-dspl-l-bold-font-family)',
    fontSize: 'var(--plasma-typo-dspl-l-bold-font-size)',
    fontStyle: 'var(--plasma-typo-dspl-l-bold-font-style)',
    fontWeight: 'var(--plasma-typo-dspl-l-bold-font-weight)',
    letterSpacing: 'var(--plasma-typo-dspl-l-bold-letter-spacing)',
    lineHeight: 'var(--plasma-typo-dspl-l-bold-line-height)',
};

/** typography s display-m */
export const dsplM = {
    fontFamily: 'var(--plasma-typo-dspl-m-font-family)',
    fontSize: 'var(--plasma-typo-dspl-m-font-size)',
    fontStyle: 'var(--plasma-typo-dspl-m-font-style)',
    fontWeight: 'var(--plasma-typo-dspl-m-font-weight)',
    letterSpacing: 'var(--plasma-typo-dspl-m-letter-spacing)',
    lineHeight: 'var(--plasma-typo-dspl-m-line-height)',
};

/** typography s display-m-bold */
export const dsplMBold = {
    fontFamily: 'var(--plasma-typo-dspl-m-bold-font-family)',
    fontSize: 'var(--plasma-typo-dspl-m-bold-font-size)',
    fontStyle: 'var(--plasma-typo-dspl-m-bold-font-style)',
    fontWeight: 'var(--plasma-typo-dspl-m-bold-font-weight)',
    letterSpacing: 'var(--plasma-typo-dspl-m-bold-letter-spacing)',
    lineHeight: 'var(--plasma-typo-dspl-m-bold-line-height)',
};

/** typography s display-s */
export const dsplS = {
    fontFamily: 'var(--plasma-typo-dspl-s-font-family)',
    fontSize: 'var(--plasma-typo-dspl-s-font-size)',
    fontStyle: 'var(--plasma-typo-dspl-s-font-style)',
    fontWeight: 'var(--plasma-typo-dspl-s-font-weight)',
    letterSpacing: 'var(--plasma-typo-dspl-s-letter-spacing)',
    lineHeight: 'var(--plasma-typo-dspl-s-line-height)',
};

/** typography s display-s-bold */
export const dsplSBold = {
    fontFamily: 'var(--plasma-typo-dspl-s-bold-font-family)',
    fontSize: 'var(--plasma-typo-dspl-s-bold-font-size)',
    fontStyle: 'var(--plasma-typo-dspl-s-bold-font-style)',
    fontWeight: 'var(--plasma-typo-dspl-s-bold-font-weight)',
    letterSpacing: 'var(--plasma-typo-dspl-s-bold-letter-spacing)',
    lineHeight: 'var(--plasma-typo-dspl-s-bold-line-height)',
};

/** typography s header-h1 */
export const h1 = {
    fontFamily: 'var(--plasma-typo-h1-font-family)',
    fontSize: 'var(--plasma-typo-h1-font-size)',
    fontStyle: 'var(--plasma-typo-h1-font-style)',
    fontWeight: 'var(--plasma-typo-h1-font-weight)',
    letterSpacing: 'var(--plasma-typo-h1-letter-spacing)',
    lineHeight: 'var(--plasma-typo-h1-line-height)',
};

/** typography s header-h1-bold */
export const h1Bold = {
    fontFamily: 'var(--plasma-typo-h1-bold-font-family)',
    fontSize: 'var(--plasma-typo-h1-bold-font-size)',
    fontStyle: 'var(--plasma-typo-h1-bold-font-style)',
    fontWeight: 'var(--plasma-typo-h1-bold-font-weight)',
    letterSpacing: 'var(--plasma-typo-h1-bold-letter-spacing)',
    lineHeight: 'var(--plasma-typo-h1-bold-line-height)',
};

/** typography s header-h2 */
export const h2 = {
    fontFamily: 'var(--plasma-typo-h2-font-family)',
    fontSize: 'var(--plasma-typo-h2-font-size)',
    fontStyle: 'var(--plasma-typo-h2-font-style)',
    fontWeight: 'var(--plasma-typo-h2-font-weight)',
    letterSpacing: 'var(--plasma-typo-h2-letter-spacing)',
    lineHeight: 'var(--plasma-typo-h2-line-height)',
};

/** typography s header-h2-bold */
export const h2Bold = {
    fontFamily: 'var(--plasma-typo-h2-bold-font-family)',
    fontSize: 'var(--plasma-typo-h2-bold-font-size)',
    fontStyle: 'var(--plasma-typo-h2-bold-font-style)',
    fontWeight: 'var(--plasma-typo-h2-bold-font-weight)',
    letterSpacing: 'var(--plasma-typo-h2-bold-letter-spacing)',
    lineHeight: 'var(--plasma-typo-h2-bold-line-height)',
};

/** typography s header-h3 */
export const h3 = {
    fontFamily: 'var(--plasma-typo-h3-font-family)',
    fontSize: 'var(--plasma-typo-h3-font-size)',
    fontStyle: 'var(--plasma-typo-h3-font-style)',
    fontWeight: 'var(--plasma-typo-h3-font-weight)',
    letterSpacing: 'var(--plasma-typo-h3-letter-spacing)',
    lineHeight: 'var(--plasma-typo-h3-line-height)',
};

/** typography s header-h3-bold */
export const h3Bold = {
    fontFamily: 'var(--plasma-typo-h3-bold-font-family)',
    fontSize: 'var(--plasma-typo-h3-bold-font-size)',
    fontStyle: 'var(--plasma-typo-h3-bold-font-style)',
    fontWeight: 'var(--plasma-typo-h3-bold-font-weight)',
    letterSpacing: 'var(--plasma-typo-h3-bold-letter-spacing)',
    lineHeight: 'var(--plasma-typo-h3-bold-line-height)',
};

/** typography s header-h4 */
export const h4 = {
    fontFamily: 'var(--plasma-typo-h4-font-family)',
    fontSize: 'var(--plasma-typo-h4-font-size)',
    fontStyle: 'var(--plasma-typo-h4-font-style)',
    fontWeight: 'var(--plasma-typo-h4-font-weight)',
    letterSpacing: 'var(--plasma-typo-h4-letter-spacing)',
    lineHeight: 'var(--plasma-typo-h4-line-height)',
};

/** typography s header-h4-bold */
export const h4Bold = {
    fontFamily: 'var(--plasma-typo-h4-bold-font-family)',
    fontSize: 'var(--plasma-typo-h4-bold-font-size)',
    fontStyle: 'var(--plasma-typo-h4-bold-font-style)',
    fontWeight: 'var(--plasma-typo-h4-bold-font-weight)',
    letterSpacing: 'var(--plasma-typo-h4-bold-letter-spacing)',
    lineHeight: 'var(--plasma-typo-h4-bold-line-height)',
};

/** typography s header-h5 */
export const h5 = {
    fontFamily: 'var(--plasma-typo-h5-font-family)',
    fontSize: 'var(--plasma-typo-h5-font-size)',
    fontStyle: 'var(--plasma-typo-h5-font-style)',
    fontWeight: 'var(--plasma-typo-h5-font-weight)',
    letterSpacing: 'var(--plasma-typo-h5-letter-spacing)',
    lineHeight: 'var(--plasma-typo-h5-line-height)',
};

/** typography s header-h5-bold */
export const h5Bold = {
    fontFamily: 'var(--plasma-typo-h5-bold-font-family)',
    fontSize: 'var(--plasma-typo-h5-bold-font-size)',
    fontStyle: 'var(--plasma-typo-h5-bold-font-style)',
    fontWeight: 'var(--plasma-typo-h5-bold-font-weight)',
    letterSpacing: 'var(--plasma-typo-h5-bold-letter-spacing)',
    lineHeight: 'var(--plasma-typo-h5-bold-line-height)',
};

/** typography s body-l */
export const bodyL = {
    fontFamily: 'var(--plasma-typo-body-l-font-family)',
    fontSize: 'var(--plasma-typo-body-l-font-size)',
    fontStyle: 'var(--plasma-typo-body-l-font-style)',
    fontWeight: 'var(--plasma-typo-body-l-font-weight)',
    letterSpacing: 'var(--plasma-typo-body-l-letter-spacing)',
    lineHeight: 'var(--plasma-typo-body-l-line-height)',
};

/** typography s body-l-bold */
export const bodyLBold = {
    fontFamily: 'var(--plasma-typo-body-l-bold-font-family)',
    fontSize: 'var(--plasma-typo-body-l-bold-font-size)',
    fontStyle: 'var(--plasma-typo-body-l-bold-font-style)',
    fontWeight: 'var(--plasma-typo-body-l-bold-font-weight)',
    letterSpacing: 'var(--plasma-typo-body-l-bold-letter-spacing)',
    lineHeight: 'var(--plasma-typo-body-l-bold-line-height)',
};

/** typography s body-m */
export const bodyM = {
    fontFamily: 'var(--plasma-typo-body-m-font-family)',
    fontSize: 'var(--plasma-typo-body-m-font-size)',
    fontStyle: 'var(--plasma-typo-body-m-font-style)',
    fontWeight: 'var(--plasma-typo-body-m-font-weight)',
    letterSpacing: 'var(--plasma-typo-body-m-letter-spacing)',
    lineHeight: 'var(--plasma-typo-body-m-line-height)',
};

/** typography s body-m-bold */
export const bodyMBold = {
    fontFamily: 'var(--plasma-typo-body-m-bold-font-family)',
    fontSize: 'var(--plasma-typo-body-m-bold-font-size)',
    fontStyle: 'var(--plasma-typo-body-m-bold-font-style)',
    fontWeight: 'var(--plasma-typo-body-m-bold-font-weight)',
    letterSpacing: 'var(--plasma-typo-body-m-bold-letter-spacing)',
    lineHeight: 'var(--plasma-typo-body-m-bold-line-height)',
};

/** typography s body-s */
export const bodyS = {
    fontFamily: 'var(--plasma-typo-body-s-font-family)',
    fontSize: 'var(--plasma-typo-body-s-font-size)',
    fontStyle: 'var(--plasma-typo-body-s-font-style)',
    fontWeight: 'var(--plasma-typo-body-s-font-weight)',
    letterSpacing: 'var(--plasma-typo-body-s-letter-spacing)',
    lineHeight: 'var(--plasma-typo-body-s-line-height)',
};

/** typography s body-s-bold */
export const bodySBold = {
    fontFamily: 'var(--plasma-typo-body-s-bold-font-family)',
    fontSize: 'var(--plasma-typo-body-s-bold-font-size)',
    fontStyle: 'var(--plasma-typo-body-s-bold-font-style)',
    fontWeight: 'var(--plasma-typo-body-s-bold-font-weight)',
    letterSpacing: 'var(--plasma-typo-body-s-bold-letter-spacing)',
    lineHeight: 'var(--plasma-typo-body-s-bold-line-height)',
};

/** typography s body-xs */
export const bodyXS = {
    fontFamily: 'var(--plasma-typo-body-xs-font-family)',
    fontSize: 'var(--plasma-typo-body-xs-font-size)',
    fontStyle: 'var(--plasma-typo-body-xs-font-style)',
    fontWeight: 'var(--plasma-typo-body-xs-font-weight)',
    letterSpacing: 'var(--plasma-typo-body-xs-letter-spacing)',
    lineHeight: 'var(--plasma-typo-body-xs-line-height)',
};

/** typography s body-xs-bold */
export const bodyXSBold = {
    fontFamily: 'var(--plasma-typo-body-xs-bold-font-family)',
    fontSize: 'var(--plasma-typo-body-xs-bold-font-size)',
    fontStyle: 'var(--plasma-typo-body-xs-bold-font-style)',
    fontWeight: 'var(--plasma-typo-body-xs-bold-font-weight)',
    letterSpacing: 'var(--plasma-typo-body-xs-bold-letter-spacing)',
    lineHeight: 'var(--plasma-typo-body-xs-bold-line-height)',
};

/** typography s body-xxs */
export const bodyXXS = {
    fontFamily: 'var(--plasma-typo-body-xxs-font-family)',
    fontSize: 'var(--plasma-typo-body-xxs-font-size)',
    fontStyle: 'var(--plasma-typo-body-xxs-font-style)',
    fontWeight: 'var(--plasma-typo-body-xxs-font-weight)',
    letterSpacing: 'var(--plasma-typo-body-xxs-letter-spacing)',
    lineHeight: 'var(--plasma-typo-body-xxs-line-height)',
};

/** typography s body-xxs-bold */
export const bodyXXSBold = {
    fontFamily: 'var(--plasma-typo-body-xxs-bold-font-family)',
    fontSize: 'var(--plasma-typo-body-xxs-bold-font-size)',
    fontStyle: 'var(--plasma-typo-body-xxs-bold-font-style)',
    fontWeight: 'var(--plasma-typo-body-xxs-bold-font-weight)',
    letterSpacing: 'var(--plasma-typo-body-xxs-bold-letter-spacing)',
    lineHeight: 'var(--plasma-typo-body-xxs-bold-line-height)',
};

/** typography s text-l */
export const textL = {
    fontFamily: 'var(--plasma-typo-text-l-font-family)',
    fontSize: 'var(--plasma-typo-text-l-font-size)',
    fontStyle: 'var(--plasma-typo-text-l-font-style)',
    fontWeight: 'var(--plasma-typo-text-l-font-weight)',
    letterSpacing: 'var(--plasma-typo-text-l-letter-spacing)',
    lineHeight: 'var(--plasma-typo-text-l-line-height)',
};

/** typography s text-l-bold */
export const textLBold = {
    fontFamily: 'var(--plasma-typo-text-l-bold-font-family)',
    fontSize: 'var(--plasma-typo-text-l-bold-font-size)',
    fontStyle: 'var(--plasma-typo-text-l-bold-font-style)',
    fontWeight: 'var(--plasma-typo-text-l-bold-font-weight)',
    letterSpacing: 'var(--plasma-typo-text-l-bold-letter-spacing)',
    lineHeight: 'var(--plasma-typo-text-l-bold-line-height)',
};

/** typography s text-m */
export const textM = {
    fontFamily: 'var(--plasma-typo-text-m-font-family)',
    fontSize: 'var(--plasma-typo-text-m-font-size)',
    fontStyle: 'var(--plasma-typo-text-m-font-style)',
    fontWeight: 'var(--plasma-typo-text-m-font-weight)',
    letterSpacing: 'var(--plasma-typo-text-m-letter-spacing)',
    lineHeight: 'var(--plasma-typo-text-m-line-height)',
};

/** typography s text-m-bold */
export const textMBold = {
    fontFamily: 'var(--plasma-typo-text-m-bold-font-family)',
    fontSize: 'var(--plasma-typo-text-m-bold-font-size)',
    fontStyle: 'var(--plasma-typo-text-m-bold-font-style)',
    fontWeight: 'var(--plasma-typo-text-m-bold-font-weight)',
    letterSpacing: 'var(--plasma-typo-text-m-bold-letter-spacing)',
    lineHeight: 'var(--plasma-typo-text-m-bold-line-height)',
};

/** typography s text-s */
export const textS = {
    fontFamily: 'var(--plasma-typo-text-s-font-family)',
    fontSize: 'var(--plasma-typo-text-s-font-size)',
    fontStyle: 'var(--plasma-typo-text-s-font-style)',
    fontWeight: 'var(--plasma-typo-text-s-font-weight)',
    letterSpacing: 'var(--plasma-typo-text-s-letter-spacing)',
    lineHeight: 'var(--plasma-typo-text-s-line-height)',
};

/** typography s text-s-bold */
export const textSBold = {
    fontFamily: 'var(--plasma-typo-text-s-bold-font-family)',
    fontSize: 'var(--plasma-typo-text-s-bold-font-size)',
    fontStyle: 'var(--plasma-typo-text-s-bold-font-style)',
    fontWeight: 'var(--plasma-typo-text-s-bold-font-weight)',
    letterSpacing: 'var(--plasma-typo-text-s-bold-letter-spacing)',
    lineHeight: 'var(--plasma-typo-text-s-bold-line-height)',
};

/** typography s text-xs */
export const textXS = {
    fontFamily: 'var(--plasma-typo-text-xs-font-family)',
    fontSize: 'var(--plasma-typo-text-xs-font-size)',
    fontStyle: 'var(--plasma-typo-text-xs-font-style)',
    fontWeight: 'var(--plasma-typo-text-xs-font-weight)',
    letterSpacing: 'var(--plasma-typo-text-xs-letter-spacing)',
    lineHeight: 'var(--plasma-typo-text-xs-line-height)',
};

/** typography s text-xs-bold */
export const textXSBold = {
    fontFamily: 'var(--plasma-typo-text-xs-bold-font-family)',
    fontSize: 'var(--plasma-typo-text-xs-bold-font-size)',
    fontStyle: 'var(--plasma-typo-text-xs-bold-font-style)',
    fontWeight: 'var(--plasma-typo-text-xs-bold-font-weight)',
    letterSpacing: 'var(--plasma-typo-text-xs-bold-letter-spacing)',
    lineHeight: 'var(--plasma-typo-text-xs-bold-line-height)',
};
