import path from 'path';
import { writeGeneratedToFS, generateThemesCSS, ThemeTokenDataGroups } from '@salutejs/plasma-tokens-utils';

export const createCSSStyles = (srcDir: string, themesTokens: Record<string, ThemeTokenDataGroups>) => {
    const themesDir = path.join(srcDir, 'css');
    const withKebabCase = true;
    const ROBO_COMMENT = '/* Generated by robots, do not change this manually! */\n';

    writeGeneratedToFS(themesDir, generateThemesCSS(themesTokens, undefined, withKebabCase), ROBO_COMMENT);
};
