export const classes = {
    opened: 'plasma-bubble-opened',
    body: 'plasma-bubble-body',
    bodyShape: 'plasma-bubble-body-shape',
    bodyRect: 'plasma-bubble-body-rect',
    bodyJoin: 'plasma-bubble-body-join',
    content: 'plasma-bubble-content',
    trigger: 'plasma-bubble-trigger',
    shapeStar: 'plasma-bubble-shape-star',
    icon: 'plasma-bubble-icon',
    iconStar: 'plasma-bubble-icon-star',
    iconClose: 'plasma-bubble-icon-close',
    decorStar: 'plasma-bubble-decor-star',
};

export const tokens = {
    backgroundColor: '--plasma-bubble-background',
    outlineColor: '--plasma-bubble-outline-color',
    iconColor: '--plasma-bubble-icon-color',
    color: '--plasma-bubble-color',
    triggerSize: '--plasma-bubble-trigger-size',
    iconSize: '--plasma-bubble-icon-size',
    decorStarSize: '--plasma-bubble-decor-star-size',
    borderRadius: '--plasma-bubble-border-radius',
    borderRadiusJoin: '--plasma-bubble-border-radius-join',
    neckOffset: '--plasma-bubble-neck-offset',
    bodyWidth: '--plasma-bubble-body-width',
    contentPadding: '--plasma-bubble-content-padding',
    fontFamily: '--plasma-bubble-font-family',
    fontSize: '--plasma-bubble-font-size',
    fontStyle: '--plasma-bubble-font-style',
    fontWeight: '--plasma-bubble-font-weight',
    letterSpacing: '--plasma-bubble-letter-spacing',
    lineHeight: '--plasma-bubble-line-height',
    duration: '--plasma-bubble-duration',
    delay: '--plasma-bubble-delay',
    easing: '--plasma-bubble-easing',
};
