import { styled } from '@linaria/react';

import { textFieldConfig, textFieldTokens } from '../../../TextField';
import { component, mergeConfig } from '../../../../engines';
import { tokens as autocompleteTokens } from '../../Autocomplete.tokens';

const mergedConfig = mergeConfig(textFieldConfig);
const TextField = component(mergedConfig);

export const StyledTextField = styled(TextField)`
    ${textFieldTokens.color}: var(${autocompleteTokens.textFieldColor});
    ${textFieldTokens.clearColor}: var(${autocompleteTokens.textFieldClearColor});
    ${textFieldTokens.placeholderColor}: var(${autocompleteTokens.textFieldPlaceholderColor});
    ${textFieldTokens.placeholderColorFocus}: var(${autocompleteTokens.textFieldPlaceholderColorFocus});
    ${textFieldTokens.clearPlaceholderColor}: var(${autocompleteTokens.textFieldClearPlaceholderColor});
    ${textFieldTokens.clearPlaceholderColorFocus}: var(${autocompleteTokens.textFieldClearPlaceholderColorFocus});
    ${textFieldTokens.optionalColor}: var(${autocompleteTokens.textFieldOptionalColor});
    ${textFieldTokens.backgroundColor}: var(${autocompleteTokens.textFieldBackgroundColor});
    ${textFieldTokens.backgroundColorHover}: var(${autocompleteTokens.textFieldBackgroundColorHover});
    ${textFieldTokens.backgroundColorFocus}: var(${autocompleteTokens.textFieldBackgroundColorFocus});
    ${textFieldTokens.borderColor}: var(${autocompleteTokens.textFieldBorderColor});
    ${textFieldTokens.borderColorHover}: var(${autocompleteTokens.textFieldBorderColorHover});
    ${textFieldTokens.borderColorFocus}: var(${autocompleteTokens.textFieldBorderColorFocus});
    ${textFieldTokens.dividerColor}: var(${autocompleteTokens.textFieldDividerColor});
    ${textFieldTokens.dividerColorHover}: var(${autocompleteTokens.textFieldDividerColorHover});
    ${textFieldTokens.dividerColorFocus}: var(${autocompleteTokens.textFieldDividerColorFocus});
    ${textFieldTokens.colorReadOnly}: var(${autocompleteTokens.textFieldColorReadOnly});
    ${textFieldTokens.backgroundColorReadOnly}: var(${autocompleteTokens.textFieldBackgroundColorReadOnly});
    ${textFieldTokens.borderColorReadOnly}: var(${autocompleteTokens.textFieldBorderColorReadOnly});
    ${textFieldTokens.placeholderColorReadOnly}: var(${autocompleteTokens.textFieldPlaceholderColorReadOnly});
    ${textFieldTokens.dividerColorReadOnly}: var(${autocompleteTokens.textFieldDividerColorReadOnly});
    ${textFieldTokens.readOnlyOpacity}: var(${autocompleteTokens.textFieldReadOnlyOpacity});
    ${textFieldTokens.caretColor}: var(${autocompleteTokens.textFieldCaretColor});
    ${textFieldTokens.height}: var(${autocompleteTokens.textFieldHeight});
    ${textFieldTokens.borderWidth}: var(${autocompleteTokens.textFieldBorderWidth});
    ${textFieldTokens.borderRadius}: var(${autocompleteTokens.textFieldBorderRadius});
    ${textFieldTokens.padding}: var(${autocompleteTokens.textFieldPadding});
    ${textFieldTokens.leftContentMargin}: var(${autocompleteTokens.textFieldLeftContentMargin});
    ${textFieldTokens.rightContentMargin}: var(${autocompleteTokens.textFieldRightContentMargin});
    ${textFieldTokens.fontFamily}: var(${autocompleteTokens.textFieldFontFamily});
    ${textFieldTokens.fontStyle}: var(${autocompleteTokens.textFieldFontStyle});
    ${textFieldTokens.fontSize}: var(${autocompleteTokens.textFieldFontSize});
    ${textFieldTokens.fontWeight}: var(${autocompleteTokens.textFieldFontWeight});
    ${textFieldTokens.letterSpacing}: var(${autocompleteTokens.textFieldLetterSpacing});
    ${textFieldTokens.lineHeight}: var(${autocompleteTokens.textFieldLineHeight});
    ${textFieldTokens.labelColor}: var(${autocompleteTokens.textFieldLabelColor});
    ${textFieldTokens.labelColorReadOnly}: var(${autocompleteTokens.textFieldLabelColorReadOnly});
    ${textFieldTokens.labelOffset}: var(${autocompleteTokens.textFieldLabelOffset});
    ${textFieldTokens.clearLabelOffset}: var(${autocompleteTokens.textFieldClearLabelOffset});
    ${textFieldTokens.labelFontFamily}: var(${autocompleteTokens.textFieldLabelFontFamily});
    ${textFieldTokens.labelFontStyle}: var(${autocompleteTokens.textFieldLabelFontStyle});
    ${textFieldTokens.labelFontSize}: var(${autocompleteTokens.textFieldLabelFontSize});
    ${textFieldTokens.labelFontWeight}: var(${autocompleteTokens.textFieldLabelFontWeight});
    ${textFieldTokens.labelLetterSpacing}: var(${autocompleteTokens.textFieldLabelLetterSpacing});
    ${textFieldTokens.labelLineHeight}: var(${autocompleteTokens.textFieldLabelLineHeight});
    ${textFieldTokens.labelInnerFontFamily}: var(${autocompleteTokens.textFieldLabelInnerFontFamily});
    ${textFieldTokens.labelInnerFontStyle}: var(${autocompleteTokens.textFieldLabelInnerFontStyle});
    ${textFieldTokens.labelInnerFontSize}: var(${autocompleteTokens.textFieldLabelInnerFontSize});
    ${textFieldTokens.labelInnerFontWeight}: var(${autocompleteTokens.textFieldLabelInnerFontWeight});
    ${textFieldTokens.labelInnerLetterSpacing}: var(${autocompleteTokens.textFieldLabelInnerLetterSpacing});
    ${textFieldTokens.labelInnerLineHeight}: var(${autocompleteTokens.textFieldLabelInnerLineHeight});
    ${textFieldTokens.labelInnerPadding}: var(${autocompleteTokens.textFieldLabelInnerPadding});
    ${textFieldTokens.contentLabelInnerPadding}: var(${autocompleteTokens.textFieldContentLabelInnerPadding});
    ${textFieldTokens.leftHelperColor}: var(${autocompleteTokens.textFieldLeftHelperColor});
    ${textFieldTokens.leftHelperColorFocus}: var(${autocompleteTokens.textFieldLeftHelperColorFocus});
    ${textFieldTokens.leftHelperColorReadOnly}: var(${autocompleteTokens.textFieldLeftHelperColorReadOnly});
    ${textFieldTokens.leftHelperOffset}: var(${autocompleteTokens.textFieldLeftHelperOffset});
    ${textFieldTokens.leftHelperFontFamily}: var(${autocompleteTokens.textFieldLeftHelperFontFamily});
    ${textFieldTokens.leftHelperFontStyle}: var(${autocompleteTokens.textFieldLeftHelperFontStyle});
    ${textFieldTokens.leftHelperFontSize}: var(${autocompleteTokens.textFieldLeftHelperFontSize});
    ${textFieldTokens.leftHelperFontWeight}: var(${autocompleteTokens.textFieldLeftHelperFontWeight});
    ${textFieldTokens.leftHelperLetterSpacing}: var(${autocompleteTokens.textFieldLeftHelperLetterSpacing});
    ${textFieldTokens.leftHelperLineHeight}: var(${autocompleteTokens.textFieldLeftHelperLineHeight});
    ${textFieldTokens.textBeforeColor}: var(${autocompleteTokens.textFieldTextBeforeColor});
    ${textFieldTokens.textAfterColor}: var(${autocompleteTokens.textFieldTextAfterColor});
    ${textFieldTokens.textBeforeMargin}: var(${autocompleteTokens.textFieldTextBeforeMargin});
    ${textFieldTokens.textAfterMargin}: var(${autocompleteTokens.textFieldTextAfterMargin});
    ${textFieldTokens.disabledOpacity}: var(${autocompleteTokens.textFieldDisabledOpacity});
    ${textFieldTokens.focusColor}: var(${autocompleteTokens.textFieldFocusColor});
    ${textFieldTokens.contentSlotColor}: var(${autocompleteTokens.textFieldContentSlotColor});
    ${textFieldTokens.contentSlotColorHover}: var(${autocompleteTokens.textFieldContentSlotColorHover});
    ${textFieldTokens.contentSlotColorActive}: var(${autocompleteTokens.textFieldContentSlotColorActive});
    ${textFieldTokens.contentSlotRightColor}: var(${autocompleteTokens.textFieldContentSlotRightColor});
    ${textFieldTokens.contentSlotRightColorHover}: var(${autocompleteTokens.textFieldContentSlotRightColorHover});
    ${textFieldTokens.contentSlotRightColorActive}: var(${autocompleteTokens.textFieldContentSlotRightColorActive});
    ${textFieldTokens.contentSlotRightOpacityReadOnly}: var(${autocompleteTokens.textFieldContentSlotRightOpacityReadOnly});
    ${textFieldTokens.indicatorColor}: var(${autocompleteTokens.textFieldIndicatorColor});
    ${textFieldTokens.indicatorSizeInner}: var(${autocompleteTokens.textFieldIndicatorSizeInner});
    ${textFieldTokens.indicatorSizeOuter}: var(${autocompleteTokens.textFieldIndicatorSizeOuter});
    ${textFieldTokens.indicatorLabelPlacementInner}: var(${autocompleteTokens.textFieldIndicatorLabelPlacementInner});
    ${textFieldTokens.indicatorLabelPlacementOuter}: var(${autocompleteTokens.textFieldIndicatorLabelPlacementOuter});
    ${textFieldTokens.indicatorLabelPlacementInnerRight}: var(${autocompleteTokens.textFieldIndicatorLabelPlacementInnerRight});
    ${textFieldTokens.indicatorLabelPlacementOuterRight}: var(${autocompleteTokens.textFieldIndicatorLabelPlacementOuterRight});
    ${textFieldTokens.clearIndicatorLabelPlacementInner}: var(${autocompleteTokens.textFieldClearIndicatorLabelPlacementInner});
    ${textFieldTokens.clearIndicatorLabelPlacementInnerRight}: var(${autocompleteTokens.textFieldClearIndicatorLabelPlacementInnerRight});
    ${textFieldTokens.clearIndicatorHintInnerRight}: var(${autocompleteTokens.textFieldClearIndicatorHintInnerRight});
    ${textFieldTokens.boxShadow}: var(${autocompleteTokens.textFieldBoxShadow});
        
    ${textFieldTokens.rightContentWithHintMargin}: var(${autocompleteTokens.textFieldRightContentWithHintMargin});
    ${textFieldTokens.contentRightWrapperGap}: var(${autocompleteTokens.textFieldContentRightWrapperGap});
    ${textFieldTokens.contentRightWrapperMargin}: var(${autocompleteTokens.textFieldContentRightWrapperMargin});
            
    ${textFieldTokens.hintCustomIconTargetSize}: var(${autocompleteTokens.textFieldHintCustomIconTargetSize});
    ${textFieldTokens.hintMargin}: var(${autocompleteTokens.textFieldHintMargin});
    ${textFieldTokens.hintTargetSize}: var(${autocompleteTokens.textFieldHintTargetSize});
    ${textFieldTokens.hintIconColor}: var(${autocompleteTokens.textFieldHintIconColor});
    ${textFieldTokens.hintInnerLabelPlacementOffset}: var(${autocompleteTokens.textFieldHintInnerLabelPlacementOffset});
    ${textFieldTokens.clearHintInnerLabelPlacementOffset}: var(${autocompleteTokens.textFieldClearHintInnerLabelPlacementOffset});
    ${textFieldTokens.tooltipBackgroundColor}: var(${autocompleteTokens.textFieldTooltipBackgroundColor});
    ${textFieldTokens.tooltipBoxShadow}: var(${autocompleteTokens.textFieldTooltipBoxShadow});
    ${textFieldTokens.tooltipColor}: var(${autocompleteTokens.textFieldTooltipColor});
    ${textFieldTokens.tooltipPaddingTop}: var(${autocompleteTokens.textFieldTooltipPaddingTop});
    ${textFieldTokens.tooltipPaddingRight}: var(${autocompleteTokens.textFieldTooltipPaddingRight});
    ${textFieldTokens.tooltipPaddingBottom}: var(${autocompleteTokens.textFieldTooltipPaddingBottom});
    ${textFieldTokens.tooltipPaddingLeft}: var(${autocompleteTokens.textFieldTooltipPaddingLeft});
    ${textFieldTokens.tooltipMinHeight}: var(${autocompleteTokens.textFieldTooltipMinHeight});
    ${textFieldTokens.tooltipBorderRadius}: var(${autocompleteTokens.textFieldTooltipBorderRadius});
    ${textFieldTokens.tooltipTextFontFamily}: var(${autocompleteTokens.textFieldTooltipTextFontFamily});
    ${textFieldTokens.tooltipTextFontSize}: var(${autocompleteTokens.textFieldTooltipTextFontSize});
    ${textFieldTokens.tooltipTextFontStyle}: var(${autocompleteTokens.textFieldTooltipTextFontStyle});
    ${textFieldTokens.tooltipTextFontWeight}: var(${autocompleteTokens.textFieldTooltipTextFontWeight});
    ${textFieldTokens.tooltipTextFontLetterSpacing}: var(${autocompleteTokens.textFieldTooltipTextFontLetterSpacing});
    ${textFieldTokens.tooltipTextFontLineHeight}: var(${autocompleteTokens.textFieldTooltipTextFontLineHeight});
    ${textFieldTokens.tooltipContentLeftMargin}: var(${autocompleteTokens.textFieldTooltipContentLeftMargin});
    ${textFieldTokens.tooltipArrowMaskWidth}: var(${autocompleteTokens.textFieldTooltipArrowMaskWidth});
    ${textFieldTokens.tooltipArrowMaskHeight}: var(${autocompleteTokens.textFieldTooltipArrowMaskHeight});
    ${textFieldTokens.tooltipArrowMaskImage}: var(${autocompleteTokens.textFieldTooltipArrowMaskImage});
    ${textFieldTokens.tooltipArrowHeight}: var(${autocompleteTokens.textFieldTooltipArrowHeight});
    ${textFieldTokens.tooltipArrowEdgeMargin}: var(${autocompleteTokens.textFieldTooltipArrowEdgeMargin});
    ${textFieldTokens.tooltipArrowBackground}: var(${autocompleteTokens.textFieldTooltipArrowBackground});
`;
