export { horizontalTabsRoot, horizontalTabsConfig } from './ui/horizontal/HorizontalTabs/HorizontalTabs';
export { horizontalTabItemRoot, horizontalTabItemConfig } from './ui/horizontal/HorizontalTabItem/HorizontalTabItem';
export { verticalTabsRoot, verticalTabsConfig } from './ui/vertical/VerticalTabs/VerticalTabs';
export { verticalTabItemRoot, verticalTabItemConfig } from './ui/vertical/VerticalTabItem/VerticalTabItem';
export { tokens as tabsTokens } from './tokens';
export { TabItemRefs, TabsContext } from './TabsContext';
export { createTabsController } from './createTabsController';
export type { TabsControllerProps } from './createTabsController';
export type { HorizontalTabsProps, BaseTabsProps } from './Tabs.types';
export type { HorizontalTabItemProps, BaseTabItemProps, RightContent } from './TabItem.types';
