export const classes = {
    selectedTabsItem: 'selected-tabs-item',
    tabsPilled: 'tabs-pilled',
    tabsGroupFilledBackground: 'tabs-group-filled-background',
    tabsStretch: 'tabs-stretched',
    tabsNoDivider: 'tabs-no-divider',
    tabItemDivider: 'tab-item-divider',
    tabItemAnimated: 'tab-item-animated',
    tabContent: 'tab-item-content',
    tabRightContent: 'tab-item-right-content',
    tabLeftContent: 'tab-item-left-content',
    tabsHasLeftArrow: 'tabs-has-left-arrow',
    tabsHasRightArrow: 'tabs-has-right-arrow',
    tabsHasTopArrow: 'tabs-has-top-arrow',
    tabsHasBottomArrow: 'tabs-has-bottom-arrow',
    tabsClipScroll: 'tabs-clip-scroll',
    tabsClipShowAll: 'tabs-clip-show-all',
    tabsTruncate: 'tabs-truncate',
};

export const tokens = {
    disabledOpacity: '--plasma-tabs-disabled-opacity',
    containerWidth: '--plasma-tabs-container-width',
    containerHeight: '--plasma-tabs-container-height',
    cursor: '--plasma-tabs-cursor',
    color: '--plasma-tabs-color',
    colorHover: '--plasma-tabs-color-hover',

    tabsDividerWidth: '--plasma-tabs-divider-width',
    tabsDividerHeight: '--plasma-tabs-divider-height',
    tabsDividerColor: '--plasma-tabs-divider-color',
    tabsDividerBorderRadius: '--plasma-tabs-divider-border-radius',

    itemSelectedDividerWidth: '--plasma-tab-item-selected-divider-width',
    itemSelectedDividerHeight: '--plasma-tab-item-selected-divider-height',
    itemSelectedDividerColor: '--plasma-tab-item-selected-divider-color',
    itemSelectedDividerColorHover: '--plasma-tab-item-selected-hover-divider-color',

    outlineFocusColor: '--plasma-tabs-outline-focus-color',
    arrowColor: '--plasma-tabs-arrow-color',
    arrowColorHover: '--plasma-tabs-arrow-color-hover',
    arrowColorActive: '--plasma-tabs-arrow-color-active',
    tabsFilledBackgroundColor: '--plasma-tabs-filled-background-color',

    tabsBackgroundColor: '--plasma-tabs-background-color',
    tabsBorderRadius: '--plasma-tabs-border-radius',
    tabsWidth: '--plasma-tabs-width',
    tabsHeight: '--plasma-tabs-height',
    tabsPadding: '--plasma-tabs-padding',
    tabsPilledBorderRadius: '--plasma-tabs-pilled-border-radius',

    itemBorderRadius: '--plasma-tab-item-border-radius',
    itemPilledBorderRadius: '--plasma-tab-item-pilled-border-radius',
    itemWidth: '--plasma-tab-item-width',
    itemHeight: '--plasma-tab-item-height',
    itemPadding: '--plasma-tab-item-padding',
    itemPaddingClear: '--plasma-tab-item-padding-clear',
    itemPaddingPilled: '--plasma-tab-item-padding-pilled',
    itemPaddingOrientationVertical: '--plasma-tab-item-padding-orientation-vertical',
    itemMarginLeft: '--plasma-tab-item-margin-left',
    itemMarginLeftFilled: '--plasma-tab-item-margin-left-filled',
    itemContentGap: '--plasma-tab-item-content-gap',

    itemContentPadding: '--plasma-tab-item-content-padding',
    itemContentPaddingClear: '--plasma-tab-item-content-padding-clear',

    arrowInnerPadding: '--plasma-tab-arrow-inner-padding',
    arrowOuterPadding: '--plasma-tab-arrow-outer-padding',
    arrowViewOuterPadding: '--plasma-tab-arrow-view-outer-padding',

    itemColor: '--plasma-tab-item-color',
    itemValueColor: '--plasma-tab-item-value-color',
    itemBackgroundColor: '--plasma-tab-item-background-color',
    itemColorHover: '--plasma-tab-item-color-hover',
    itemValueColorHover: '--plasma-tab-item-value-color-hover',
    itemColorActive: '--plasma-tab-item-color-active',
    itemValueColorActive: '--plasma-tab-item-value-color-active',
    itemBackgroundColorHover: '--plasma-tab-item-background-color-hover',
    itemCursor: '--plasma-tab-item-cursor',
    itemCursorOverNotSelected: '--plasma-tab-item-cursor-over-not-selected',

    itemSelectedColor: '--plasma-tab-item-selected-color',
    itemSelectedValueColor: '--plasma-tab-item-selected-value-color',
    itemSelectedBackgroundColor: '--plasma-tab-item-selected-background-color',
    itemSelectedColorHover: '--plasma-tab-item-selected-color-hover',
    itemSelectedValueColorHover: '--plasma-tab-item-selected-value-color-hover',
    itemSelectedBackgroundColorHover: '--plasma-tab-item-selected-background-color-hover',

    itemBackgroundTransition: '--plasma-tab-item-background-transition',

    fontFamily: '--plasma-tab-item-font-family',
    fontSize: '--plasma-tab-item-font-size',
    fontStyle: '--plasma-tab-item-font-style',
    fontWeight: '--plasma-tab-item-font-weight',
    letterSpacing: '--plasma-tab-item-letter-spacing',
    lineHeight: '--plasma-tab-item-lineheight',

    valueFontFamily: '--plasma-tab-item-value-font-family',
    valueFontSize: '--plasma-tab-item-value-font-size',
    valueFontStyle: '--plasma-tab-item-value-font-style',
    valueFontWeight: '--plasma-tab-item-value-font-weight',
    valueLetterSpacing: '--plasma-tab-item-value-letter-spacing',
    valueLineHeight: '--plasma-tab-item-value-lineheight',
};
