"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.config = void 0;
var _styledComponents = /*#__PURE__*/require("@salutejs/plasma-new-hope/styled-components");
var _templateObject, _templateObject2, _templateObject3, _templateObject4, _templateObject5, _templateObject6, _templateObject7, _templateObject8, _templateObject9, _templateObject10, _templateObject11, _templateObject12;
function _taggedTemplateLiteral(strings, raw) { if (!raw) { raw = strings.slice(0); } return Object.freeze(Object.defineProperties(strings, { raw: { value: Object.freeze(raw) } })); }
var config = exports.config = {
  defaults: {
    view: 'accent',
    size: 'm',
    focused: 'true'
  },
  variations: {
    size: {
      s: /*#__PURE__*/(0, _styledComponents.css)(_templateObject || (_templateObject = /*#__PURE__*/_taggedTemplateLiteral(["\n                --plasma-checkbox-trigger-size: 0.875rem;\n                --plasma-checkbox-trigger-border-radius: 0.25rem;\n                --plasma-checkbox-content-top-offset: 0.063rem;\n                --plasma-checkbox-content-left-offset: 0.5rem;\n                --plasma-checkbox-label-font-family: var(--plasma-typo-body-s-font-family);\n                --plasma-checkbox-label-font-size: var(--plasma-typo-body-s-font-size);\n                --plasma-checkbox-label-font-style: var(--plasma-typo-body-s-font-style);\n                --plasma-checkbox-label-font-weight: var(--plasma-typo-body-s-font-weight);\n                --plasma-checkbox-label-letter-spacing: var(--plasma-typo-body-s-letter-spacing);\n                --plasma-checkbox-label-line-height: var(--plasma-typo-body-s-line-height);\n                --plasma-checkbox-description-font-family: var(--plasma-typo-body-xs-font-family);\n                --plasma-checkbox-description-font-size: var(--plasma-typo-body-xs-font-size);\n                --plasma-checkbox-description-font-style: var(--plasma-typo-body-xs-font-style);\n                --plasma-checkbox-description-font-weight: var(--plasma-typo-body-xs-font-weight);\n                --plasma-checkbox-description-letter-spacing: var(--plasma-typo-body-xs-letter-spacing);\n                --plasma-checkbox-description-line-height: var(--plasma-typo-body-xs-line-height);\n            "]))),
      m: /*#__PURE__*/(0, _styledComponents.css)(_templateObject2 || (_templateObject2 = /*#__PURE__*/_taggedTemplateLiteral(["\n                --plasma-checkbox-trigger-size: 1.25rem;\n                --plasma-checkbox-trigger-border-radius: 0.375rem;\n                --plasma-checkbox-content-top-offset: 0.188rem;\n                --plasma-checkbox-content-left-offset: 0.75rem;\n                --plasma-checkbox-label-font-family: var(--plasma-typo-body-m-font-family);\n                --plasma-checkbox-label-font-size: var(--plasma-typo-body-m-font-size);\n                --plasma-checkbox-label-font-style: var(--plasma-typo-body-m-font-style);\n                --plasma-checkbox-label-font-weight: var(--plasma-typo-body-m-font-weight);\n                --plasma-checkbox-label-letter-spacing: var(--plasma-typo-body-m-letter-spacing);\n                --plasma-checkbox-label-line-height: var(--plasma-typo-body-m-line-height);\n                --plasma-checkbox-description-font-family: var(--plasma-typo-body-s-font-family);\n                --plasma-checkbox-description-font-size: var(--plasma-typo-body-s-font-size);\n                --plasma-checkbox-description-font-style: var(--plasma-typo-body-s-font-style);\n                --plasma-checkbox-description-font-weight: var(--plasma-typo-body-s-font-weight);\n                --plasma-checkbox-description-letter-spacing: var(--plasma-typo-body-s-letter-spacing);\n                --plasma-checkbox-description-line-height: var(--plasma-typo-body-s-line-height);\n            "])))
    },
    view: {
      primary: /*#__PURE__*/(0, _styledComponents.css)(_templateObject3 || (_templateObject3 = /*#__PURE__*/_taggedTemplateLiteral(["\n                --plasma-checkbox-fill-color: var(--text-primary);\n                --plasma-checkbox-icon-color: var(--inverse-text-primary);\n                --plasma-checkbox-description-color: var(--text-secondary);\n                --plasma-checkbox-trigger-border-color: var(--text-secondary);\n            "]))),
      secondary: /*#__PURE__*/(0, _styledComponents.css)(_templateObject4 || (_templateObject4 = /*#__PURE__*/_taggedTemplateLiteral(["\n                --plasma-checkbox-fill-color: var(--text-secondary);\n                --plasma-checkbox-icon-color: var(--inverse-text-primary);\n                --plasma-checkbox-description-color: var(--text-secondary);\n                --plasma-checkbox-trigger-border-color: var(--text-secondary);\n            "]))),
      tertiary: /*#__PURE__*/(0, _styledComponents.css)(_templateObject5 || (_templateObject5 = /*#__PURE__*/_taggedTemplateLiteral(["\n                --plasma-checkbox-fill-color: var(--text-tertiary);\n                --plasma-checkbox-icon-color: var(--inverse-text-primary);\n                --plasma-checkbox-description-color: var(--text-secondary);\n                --plasma-checkbox-trigger-border-color: var(--text-secondary);\n            "]))),
      paragraph: /*#__PURE__*/(0, _styledComponents.css)(_templateObject6 || (_templateObject6 = /*#__PURE__*/_taggedTemplateLiteral(["\n                --plasma-checkbox-fill-color: var(--text-paragraph);\n                --plasma-checkbox-icon-color: var(--inverse-text-primary);\n                --plasma-checkbox-description-color: var(--text-secondary);\n                --plasma-checkbox-trigger-border-color: var(--text-secondary);\n            "]))),
      accent: /*#__PURE__*/(0, _styledComponents.css)(_templateObject7 || (_templateObject7 = /*#__PURE__*/_taggedTemplateLiteral(["\n                --plasma-checkbox-fill-color: var(--text-accent);\n                --plasma-checkbox-icon-color: var(--on-dark-text-primary);\n                --plasma-checkbox-description-color: var(--text-secondary);\n                --plasma-checkbox-trigger-border-color: var(--text-secondary);\n            "]))),
      positive: /*#__PURE__*/(0, _styledComponents.css)(_templateObject8 || (_templateObject8 = /*#__PURE__*/_taggedTemplateLiteral(["\n                --plasma-checkbox-fill-color: var(--text-positive);\n                --plasma-checkbox-icon-color: var(--on-dark-text-primary);\n                --plasma-checkbox-description-color: var(--text-secondary);\n                --plasma-checkbox-trigger-border-color: var(--text-secondary);\n            "]))),
      warning: /*#__PURE__*/(0, _styledComponents.css)(_templateObject9 || (_templateObject9 = /*#__PURE__*/_taggedTemplateLiteral(["\n                --plasma-checkbox-fill-color: var(--text-warning);\n                --plasma-checkbox-icon-color: var(--on-dark-text-primary);\n                --plasma-checkbox-description-color: var(--text-secondary);\n                --plasma-checkbox-trigger-border-color: var(--text-secondary);\n            "]))),
      negative: /*#__PURE__*/(0, _styledComponents.css)(_templateObject10 || (_templateObject10 = /*#__PURE__*/_taggedTemplateLiteral(["\n                --plasma-checkbox-fill-color: var(--text-negative);\n                --plasma-checkbox-icon-color: var(--on-dark-text-primary);\n                --plasma-checkbox-description-color: var(--text-secondary);\n                --plasma-checkbox-trigger-border-color: var(--text-secondary);\n            "])))
    },
    disabled: {
      "true": /*#__PURE__*/(0, _styledComponents.css)(_templateObject11 || (_templateObject11 = /*#__PURE__*/_taggedTemplateLiteral(["\n                --plasma-checkbox-disabled-opacity: 0.4;\n            "])))
    },
    focused: {
      "true": /*#__PURE__*/(0, _styledComponents.css)(_templateObject12 || (_templateObject12 = /*#__PURE__*/_taggedTemplateLiteral(["\n                --plasma-checkbox-focus-color: var(--text-accent);\n            "])))
    }
  }
};