import { styled } from '@linaria/react';
import { informationWrapperConfig, informationWrapperTokens } from 'src/components/InformationWrapper';
import { component, mergeConfig } from 'src/engines';

import { tokens } from '../../Range.tokens';

const mergedConfig = mergeConfig(informationWrapperConfig);
const InformationWrapper = component(mergedConfig);

export const InformationWrapperUI = styled(InformationWrapper)`
    ${informationWrapperTokens.indicatorWrapperGap}: var(${tokens.indicatorWrapperGap});
    ${informationWrapperTokens.labelWrapperOffset}: var(${tokens.labelWrapperOffset});
    ${informationWrapperTokens.labelWrapperTitleCaptionOffset}: var(${tokens.labelWrapperTitleCaptionOffset});
    ${informationWrapperTokens.labelFontFamily}: var(${tokens.labelFontFamily});
    ${informationWrapperTokens.labelFontStyle}: var(${tokens.labelFontStyle});
    ${informationWrapperTokens.labelFontSize}: var(${tokens.labelFontSize});
    ${informationWrapperTokens.labelFontWeight}: var(${tokens.labelFontWeight});
    ${informationWrapperTokens.labelLetterSpacing}: var(${tokens.labelLetterSpacing});
    ${informationWrapperTokens.labelLineHeight}: var(${tokens.labelLineHeight});
    ${informationWrapperTokens.labelColor}: var(${tokens.labelColor});
    ${informationWrapperTokens.contentGap}: var(${tokens.contentGap});
    ${informationWrapperTokens.titleCaptionOffset}: var(${tokens.titleCaptionOffset});
    ${informationWrapperTokens.titleCaptionColor}: var(${tokens.titleCaptionColor});
    ${informationWrapperTokens.titleCaptionFontFamily}: var(${tokens.titleCaptionFontFamily});
    ${informationWrapperTokens.titleCaptionFontStyle}: var(${tokens.titleCaptionFontStyle});
    ${informationWrapperTokens.titleCaptionFontSize}: var(${tokens.titleCaptionFontSize});
    ${informationWrapperTokens.titleCaptionFontWeight}: var(${tokens.titleCaptionFontWeight});
    ${informationWrapperTokens.titleCaptionLetterSpacing}: var(${tokens.titleCaptionLetterSpacing});
    ${informationWrapperTokens.titleCaptionLineHeight}: var(${tokens.titleCaptionLineHeight});
    ${informationWrapperTokens.hintMargin}: var(${tokens.hintMargin});
    ${informationWrapperTokens.hintTargetSize}: var(${tokens.hintTargetSize});
    ${informationWrapperTokens.hintCustomIconTargetSize}: var(${tokens.hintCustomIconTargetSize});
    ${informationWrapperTokens.hintIconColor}: var(${tokens.hintIconColor});
    ${informationWrapperTokens.hintWithoutLabelPlacementOffset}: var(${tokens.hintWithoutLabelPlacementOffset});
    ${informationWrapperTokens.tooltipBackgroundColor}: var(${tokens.tooltipBackgroundColor});
    ${informationWrapperTokens.tooltipBoxShadow}: var(${tokens.tooltipBoxShadow});
    ${informationWrapperTokens.tooltipColor}: var(${tokens.tooltipColor});
    ${informationWrapperTokens.tooltipPaddingTop}: var(${tokens.tooltipPaddingTop});
    ${informationWrapperTokens.tooltipPaddingRight}: var(${tokens.tooltipPaddingRight});
    ${informationWrapperTokens.tooltipPaddingBottom}: var(${tokens.tooltipPaddingBottom});
    ${informationWrapperTokens.tooltipPaddingLeft}: var(${tokens.tooltipPaddingLeft});
    ${informationWrapperTokens.tooltipMinHeight}: var(${tokens.tooltipMinHeight});
    ${informationWrapperTokens.tooltipBorderRadius}: var(${tokens.tooltipBorderRadius});
    ${informationWrapperTokens.tooltipTextFontFamily}: var(${tokens.tooltipTextFontFamily});
    ${informationWrapperTokens.tooltipTextFontSize}: var(${tokens.tooltipTextFontSize});
    ${informationWrapperTokens.tooltipTextFontStyle}: var(${tokens.tooltipTextFontStyle});
    ${informationWrapperTokens.tooltipTextFontWeight}: var(${tokens.tooltipTextFontWeight});
    ${informationWrapperTokens.tooltipTextFontLetterSpacing}: var(${tokens.tooltipTextFontLetterSpacing});
    ${informationWrapperTokens.tooltipTextFontLineHeight}: var(${tokens.tooltipTextFontLineHeight});
    ${informationWrapperTokens.tooltipContentLeftMargin}: var(${tokens.tooltipContentLeftMargin});
    ${informationWrapperTokens.tooltipArrowMaskWidth}: var(${tokens.tooltipArrowMaskWidth});
    ${informationWrapperTokens.tooltipArrowMaskHeight}: var(${tokens.tooltipArrowMaskHeight});
    ${informationWrapperTokens.tooltipArrowMaskImage}: var(${tokens.tooltipArrowMaskImage});
    ${informationWrapperTokens.tooltipArrowHeight}: var(${tokens.tooltipArrowHeight});
    ${informationWrapperTokens.tooltipArrowEdgeMargin}: var(${tokens.tooltipArrowEdgeMargin});
    ${informationWrapperTokens.tooltipArrowBackground}: var(${tokens.tooltipArrowBackground});
    ${informationWrapperTokens.indicatorColor}: var(${tokens.indicatorColor});
    ${informationWrapperTokens.indicatorSizeInner}: var(${tokens.indicatorSizeInner});
    ${informationWrapperTokens.indicatorSizeOuter}: var(${tokens.indicatorSizeOuter});
    ${informationWrapperTokens.indicatorMarginTop}: var(${tokens.indicatorMarginTop});
    ${informationWrapperTokens.indicatorOuterLeft}: var(${tokens.indicatorOuterLeft});
    ${informationWrapperTokens.indicatorWithoutLabelInner}: var(${tokens.indicatorWithoutLabelInner});
    ${informationWrapperTokens.indicatorWithoutLabelInnerLeft}: var(${tokens.indicatorWithoutLabelInnerLeft});
    ${informationWrapperTokens.leftHelperColor}: var(${tokens.leftHelperColor});
    ${informationWrapperTokens.helpersPadding}: var(${tokens.helpersPadding});
    ${informationWrapperTokens.helpersGap}: var(${tokens.helpersGap});
    ${informationWrapperTokens.leftHelperFontFamily}: var(${tokens.leftHelperFontFamily});
    ${informationWrapperTokens.leftHelperFontStyle}: var(${tokens.leftHelperFontStyle});
    ${informationWrapperTokens.leftHelperFontSize}: var(${tokens.leftHelperFontSize});
    ${informationWrapperTokens.leftHelperFontWeight}: var(${tokens.leftHelperFontWeight});
    ${informationWrapperTokens.leftHelperLetterSpacing}: var(${tokens.leftHelperLetterSpacing});
    ${informationWrapperTokens.leftHelperLineHeight}: var(${tokens.leftHelperLineHeight});
    ${informationWrapperTokens.labelColorReadOnly}: var(${tokens.labelColorReadOnly});
    ${informationWrapperTokens.titleCaptionColorReadOnly}: var(${tokens.titleCaptionColorReadOnly});
    ${informationWrapperTokens.leftHelperColorReadOnly}: var(${tokens.leftHelperColorReadOnly});
    ${informationWrapperTokens.rightHelperColorReadOnly}: var(${tokens.rightHelperColorReadOnly});
`;
