export const classes = {
    dropdownItemIsFocused: 'dropdown-item-is-focused',
    dropdownItemIsDisabled: 'dropdown-item-is-disabled',
    dropdownItemIsActive: 'dropdown-item-is-active',
    selectTargetArrow: 'select-target-arrow',
    arrowInverse: 'arrow-inverse',
    textfieldTarget: 'select-textfield-target',
    selectChipIsFocused: 'select-chip-is-focused',
    selectWithoutBoxShadow: 'select-without-box-shadow',
    selectItemCheckbox: 'select-item-checkbox',
    selectSpinner: 'select-spinner',
};

export const tokens = {
    borderRadius: '--plasma-select-border-radius',
    padding: '--plasma-select-padding',
    focusOffset: '--plasma-select-focus-offset',

    fontFamily: '--plasma-select-font-family',
    fontSize: '--plasma-select-font-size',
    fontStyle: '--plasma-select-font-style',
    fontWeight: '--plasma-select-font-weight',
    fontLetterSpacing: '--plasma-select-font-letter-spacing',
    fontLineHeight: '--plasma-select-font-line-height',

    itemHeight: '--plasma-select-item-height',
    itemBorderRadius: '--plasma-select-item-border-radius',
    itemPadding: '--plasma-select-item-padding',
    itemPaddingTight: '--plasma-select-item-padding-tight',
    itemIconSize: '--plasma-select-item-icon-size',
    itemIconSizeTight: '--plasma-select-item-icon-size-tight',
    itemIconMargin: '--plasma-select-item-icon-margin',

    checkboxTriggerSize: '--plasma-select-checkbox-trigger-size',
    checkboxTriggerSizeTight: '--plasma-select-checkbox-trigger-size-tight',
    checkboxTriggerBorderRadius: '--plasma-select-checkbox-trigger-border-radius',
    checkboxTriggerBorderRadiusTight: '--plasma-select-checkbox-trigger-border-radius-tight',
    checkboxFillColor: '--plasma-select-checkbox-fill-color',
    checkboxIconColor: '--plasma-select-checkbox-icon-color',
    checkboxTriggerBorderColor: '--plasma-select-checkbox-trigger-border-color',

    indicatorSize: '--plasma-select-indicator-size',

    targetButtonColor: '--plasma-select-target-button-color',
    targetButtonColorHover: '--plasma-select-target-button-color-hover',
    targetButtonColorActive: '--plasma-select-target-button-color-active',
    targetButtonArrowColor: '--plasma-select-target-button-arrow-color',
    targetButtonArrowColorHover: '--plasma-select-target-button-arrow-color-hover',
    targetButtonArrowColorActive: '--plasma-select-target-button-arrow-color-active',
    targetTextfieldArrowColor: '--plasma-select-target-textfield-arrow-color',
    targetTextfieldArrowColorHover: '--plasma-select-target-textfield-arrow-color-hover',
    targetTextfieldArrowColorActive: '--plasma-select-target-textfield-arrow-color-active',
    targetButtonArrowMargin: '--plasma-select-target-button-arrow-margin',
    targetTextfieldArrowMargin: '--plasma-select-target-textfield-arrow-margin',
    targetButtonBackgroundColor: '--plasma-select-target-button-background-color',
    targetButtonBackgroundColorHover: '--plasma-select-target-button-background-color-hover',
    targetButtonBackgroundColorActive: '--plasma-select-target-button-background-color-active',
    targetTextfieldBackgroundColor: '--plasma-select-target-textfield-background-color',
    targetTextfieldBackgroundColorOpened: '--plasma-select-target-textfield-background-color-opened',
    targetTextfieldBorderColor: '--plasma-select-target-textfield-border-color',
    targetTextfieldBorderColorHover: '--plasma-select-target-textfield-border-color-hover',
    targetTextfieldBorderOpenedColor: '--plasma-select-target-textfield-border-opened-color',
    targetTextfieldBorderSize: '--plasma-select-target-textfield-border-size',
    targetButtonPadding: '--plasma-select-target-button-padding',
    targetTextfieldPadding: '--plasma-select-target-textfield-padding',
    targetTextfieldChipPadding: '--plasma-select-target-textfield-chip-padding',
    targetHeight: '--plasma-select-target-height',

    chipColor: '--plasma-select-chip-color',
    chipBackground: '--plasma-select-chip-background',
    chipBackgroundHover: '--plasma-select-chip-background-hover',
    chipBackgroundActive: '--plasma-select-chip-background-active',
    chipGap: '--plasma-select-chip-gap',
    chipBorderRadius: '--plasma-select-chip-border-radius',
    chipHeight: '--plasma-select-chip-height',
    chipPaddingRight: '--plasma-select-chip-padding-right',
    chipPaddingLeft: '--plasma-select-chip-padding-left',
    chipCloseIconSize: '--plasma-select-chip-close-icon-size',
    chipClearContentMarginLeft: '--plasma-select-chip-clear-content-margin-left',
    chipClearContentMarginRight: '--plasma-select-chip-clear-content-margin-right',

    popoverBorderColor: '--plasma-select-popover-border-color',
    popoverBorderWidth: '--plasma-select-popover-border-width',

    labelOffset: '--plasma-select-label-offset',

    innerLabelGap: '--plasma-select-inner-label-gap',

    helperTextColor: '--plasma-select-helper-text-color',
    helperTextOffset: '--plasma-select-helper-text-offset',

    spinnerSize: '--plasma-select-spinner-size',
    spinnerSizeTight: '--plasma-select-spinner-size-tight',
};

export const constants = {
    focusColor: '--surface-accent',
    focusSize: '0.0625rem',
    background: '--surface-solid-card',
    boxShadow: '0px 4px 14px -4px rgba(8, 8, 8, 0.08), 0px 1px 4px -1px rgba(0, 0, 0, 0.04)',
    disclosureIconColor: '--text-secondary',
    disclosureIconColorHover: '--text-secondary-hover',
    itemBackground: '--plasma-colors-transparent',
    itemBackgroundHover: '--surface-transparent-secondary',
    textfieldTargetColor: '--text-primary',
    textfieldOuterLabelColor: '--text-primary',
    textfieldInnerLabelColor: '--text-secondary',
    textfieldPlaceholderColor: '--text-secondary',
    opacity: '0.4',
    fontFamily: '--plasma-typo-body-xs-font-family',
    fontSize: '--plasma-typo-body-xs-font-size',
    fontStyle: '--plasma-typo-body-xs-font-style',
    fontWeight: '--plasma-typo-body-xs-font-weight',
    fontLetterSpacing: '--plasma-typo-body-xs-letter-spacing',
    fontLineHeight: '--plasma-typo-body-xs-line-height',
};
