// generated by theme-builder { version } { plasma-hope-version??? }
import React from 'react';

import { ComponentStory, ComponentMeta } from '@storybook/react';

import { Button } from './Button';

export default {
    title: 'plasma_b2c/Button',
    component: Button,
    argTypes: {
        view: {
            control: {
                type: 'select',
            },
            options: [
                'primary',
                'secondary',
            ],
            defaultValue: 'primary',
        },
        size: {
            control: {
                type: 'select',
            },
            options: [
                's',
                'm',
                'l',
            ],
        },
        disabled: {
            control: {
                type: 'boolean',
            },
        },
        focused: {
            control: {
                type: 'boolean',
            },
            defaultValue: true,
        },
    },
} as ComponentMeta<typeof Button>;

export const Default: ComponentStory<typeof Button> = (props) => {
    return (
        <div style={{ padding: '1rem' }}>
            <Button {...props}>Hello</Button>
        </div>
    )
};