"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.config = void 0;
var _styledComponents = /*#__PURE__*/require("@salutejs/plasma-new-hope/styled-components");
var _templateObject, _templateObject2, _templateObject3, _templateObject4, _templateObject5;
function _taggedTemplateLiteral(strings, raw) { if (!raw) { raw = strings.slice(0); } return Object.freeze(Object.defineProperties(strings, { raw: { value: Object.freeze(raw) } })); }
var dropdownSizeCommon = /*#__PURE__*/"\n    ".concat(_styledComponents.dropdownTokens.width, ": 12.5rem;\n    ").concat(_styledComponents.dropdownTokens.height, ": auto;\n    ").concat(_styledComponents.dropdownTokens.borderRadius, ": 0.5rem;\n    ").concat(_styledComponents.dropdownTokens.paddingTop, ": 0.125rem;\n    ").concat(_styledComponents.dropdownTokens.paddingRight, ": 0.0625rem;\n    ").concat(_styledComponents.dropdownTokens.paddingBottom, ": 0.125rem;\n    ").concat(_styledComponents.dropdownTokens.paddingLeft, ": 0.125rem;\n");
var dropdownItemSizeCommon = /*#__PURE__*/"\n    ".concat(_styledComponents.dropdownTokens.itemWidth, ": auto;\n    ").concat(_styledComponents.dropdownTokens.itemHeight, ": auto;\n    ").concat(_styledComponents.dropdownTokens.itemMarginTop, ": 0;\n    ").concat(_styledComponents.dropdownTokens.itemMarginRight, ": 0;\n    ").concat(_styledComponents.dropdownTokens.itemMarginBottom, ": 0;\n    ").concat(_styledComponents.dropdownTokens.itemMarginLeft, ": 0;\n");
var config = exports.config = {
  defaults: {
    view: 'primary',
    size: 'm'
  },
  variations: {
    size: {
      xs: /*#__PURE__*/(0, _styledComponents.css)(_templateObject || (_templateObject = /*#__PURE__*/_taggedTemplateLiteral(["\n                ", ";\n\n                ", ";\n                ", ": 0.5625rem;\n                ", ": 0.5rem;\n                ", ": 0.5625rem;\n                ", ": 0.5rem;\n                ", ": 0.375rem;\n\n                ", ": var(--plasma-typo-body-xs-font-family);\n                ", ": var(--plasma-typo-body-xs-font-size);\n                ", ": var(--plasma-typo-body-xs-font-style);\n                ", ": var(--plasma-typo-body-xs-font-weight);\n                ", ": var(--plasma-typo-body-xs-letter-spacing);\n                ", ": var(--plasma-typo-body-xs-line-height);\n            "])), dropdownSizeCommon, dropdownItemSizeCommon, _styledComponents.dropdownTokens.itemPaddingTop, _styledComponents.dropdownTokens.itemPaddingRight, _styledComponents.dropdownTokens.itemPaddingBottom, _styledComponents.dropdownTokens.itemPaddingLeft, _styledComponents.dropdownTokens.itemBorderRadius, _styledComponents.dropdownTokens.itemFontFamily, _styledComponents.dropdownTokens.itemFontSize, _styledComponents.dropdownTokens.itemFontStyle, _styledComponents.dropdownTokens.itemFontWeightBold, _styledComponents.dropdownTokens.itemFontLetterSpacing, _styledComponents.dropdownTokens.itemFontLineHeight),
      s: /*#__PURE__*/(0, _styledComponents.css)(_templateObject2 || (_templateObject2 = /*#__PURE__*/_taggedTemplateLiteral(["\n                ", ";\n\n                ", ";\n                ", ": 0.6875rem;\n                ", ": 0.75rem;\n                ", ": 0.6875rem;\n                ", ": 0.75rem;\n                ", ": 0.5rem;\n\n                ", ": var(--plasma-typo-body-s-font-family);\n                ", ": var(--plasma-typo-body-s-font-size);\n                ", ": var(--plasma-typo-body-s-font-style);\n                ", ": var(--plasma-typo-body-s-font-weight);\n                ", ": var(--plasma-typo-body-s-letter-spacing);\n                ", ": var(--plasma-typo-body-s-line-height);\n            "])), dropdownSizeCommon, dropdownItemSizeCommon, _styledComponents.dropdownTokens.itemPaddingTop, _styledComponents.dropdownTokens.itemPaddingRight, _styledComponents.dropdownTokens.itemPaddingBottom, _styledComponents.dropdownTokens.itemPaddingLeft, _styledComponents.dropdownTokens.itemBorderRadius, _styledComponents.dropdownTokens.itemFontFamily, _styledComponents.dropdownTokens.itemFontSize, _styledComponents.dropdownTokens.itemFontStyle, _styledComponents.dropdownTokens.itemFontWeightBold, _styledComponents.dropdownTokens.itemFontLetterSpacing, _styledComponents.dropdownTokens.itemFontLineHeight),
      m: /*#__PURE__*/(0, _styledComponents.css)(_templateObject3 || (_templateObject3 = /*#__PURE__*/_taggedTemplateLiteral(["\n                ", ";\n\n                ", ";\n                ", ": 0.875rem;\n                ", ": 0.875rem;\n                ", ": 0.875rem;\n                ", ": 0.875rem;\n                ", ": 0.625rem;\n\n                ", ": var(--plasma-typo-body-m-font-family);\n                ", ": var(--plasma-typo-body-m-font-size);\n                ", ": var(--plasma-typo-body-m-font-style);\n                ", ": var(--plasma-typo-body-m-font-weight);\n                ", ": var(--plasma-typo-body-m-letter-spacing);\n                ", ": var(--plasma-typo-body-m-line-height);\n            "])), dropdownSizeCommon, dropdownItemSizeCommon, _styledComponents.dropdownTokens.itemPaddingTop, _styledComponents.dropdownTokens.itemPaddingRight, _styledComponents.dropdownTokens.itemPaddingBottom, _styledComponents.dropdownTokens.itemPaddingLeft, _styledComponents.dropdownTokens.itemBorderRadius, _styledComponents.dropdownTokens.itemFontFamily, _styledComponents.dropdownTokens.itemFontSize, _styledComponents.dropdownTokens.itemFontStyle, _styledComponents.dropdownTokens.itemFontWeightBold, _styledComponents.dropdownTokens.itemFontLetterSpacing, _styledComponents.dropdownTokens.itemFontLineHeight),
      l: /*#__PURE__*/(0, _styledComponents.css)(_templateObject4 || (_templateObject4 = /*#__PURE__*/_taggedTemplateLiteral(["\n                ", ";\n\n                ", ";\n                ", ": 1.0625rem;\n                ", ": 1rem;\n                ", ": 1.0625rem;\n                ", ": 1rem;\n                ", ": 0.75rem;\n\n                ", ": var(--plasma-typo-body-l-font-family);\n                ", ": var(--plasma-typo-body-l-font-size);\n                ", ": var(--plasma-typo-body-l-font-style);\n                ", ": var(--plasma-typo-body-l-font-weight);\n                ", ": var(--plasma-typo-body-l-letter-spacing);\n                ", ": var(--plasma-typo-body-l-line-height);\n            "])), dropdownSizeCommon, dropdownItemSizeCommon, _styledComponents.dropdownTokens.itemPaddingTop, _styledComponents.dropdownTokens.itemPaddingRight, _styledComponents.dropdownTokens.itemPaddingBottom, _styledComponents.dropdownTokens.itemPaddingLeft, _styledComponents.dropdownTokens.itemBorderRadius, _styledComponents.dropdownTokens.itemFontFamily, _styledComponents.dropdownTokens.itemFontSize, _styledComponents.dropdownTokens.itemFontStyle, _styledComponents.dropdownTokens.itemFontWeightBold, _styledComponents.dropdownTokens.itemFontLetterSpacing, _styledComponents.dropdownTokens.itemFontLineHeight)
    },
    view: {
      primary: /*#__PURE__*/(0, _styledComponents.css)(_templateObject5 || (_templateObject5 = /*#__PURE__*/_taggedTemplateLiteral(["\n                ", ": 0.4;\n                ", ": var(--surface-solid-card);\n                ", ": var(--shadow-down-soft-s);\n\n                ", ": var(--plasma-colors-transparent);\n                ", ": var(--surface-transparent-secondary);\n                ", ": inherit;\n                ", ": inherit;\n                ", ": inherit;\n                ", ": inherit;\n                ", ": var(--text-primary);\n            "])), _styledComponents.dropdownTokens.disabledOpacity, _styledComponents.dropdownTokens.background, _styledComponents.dropdownTokens.boxShadow, _styledComponents.dropdownTokens.itemBackground, _styledComponents.dropdownTokens.itemBackgroundHover, _styledComponents.dropdownTokens.itemBackgroundSelected, _styledComponents.dropdownTokens.itemColorSelected, _styledComponents.dropdownTokens.itemBackgroundSelectedHover, _styledComponents.dropdownTokens.itemColorSelectedHover, _styledComponents.dropdownTokens.itemColor)
    }
  }
};