export const classes = {
    filledStretching: 'accordion-stretching-filled',
    fixedStretching: 'accordion-stretching-fixed',
    accordionRoot: 'accordion-root',
    accordionItem: 'accordion-item',
    clearAccordionItem: 'clear-accordion-item',
    accordionItemShowBody: 'accordion-item-show-body',
    accordionPlusAnimationElement: 'accordion-plus-animation-element',
    accordionDisabled: 'accordion-disabled',
    accordionItemBody: 'accordion-item-body',
};

export const tokens = {
    accordionGap: '--plasma-accordion-gap',
    accordionWidth: '--plasma-accordion-width',
    accordionBackground: '--plasma-accordion-background',

    accordionItemBackground: '--plasma-accordion-item-background',
    accordionItemBorderRadius: '--plasma-accordion-item-border-radius',
    accordionItemPadding: '--plasma-accordion-item-padding',
    accordionItemPaddingVertical: '--plasma-accordion-item-padding-vertical',
    accordionItemPaddingHorizontal: '--plasma-accordion-item-padding-horizontal',
    accordionItemPaddingHorizontalLeft: '--plasma-accordion-item-padding-horizontal-left',
    accordionItemGap: '--plasma-accordion-item-gap',
    accordionItemFocus: '--plasma-accordion-item-focus',
    accordionItemBorder: '--plasma-accordion-item-border',
    accordionItemBorderBottom: '--plasma-accordion-item-border-bottom',
    accordionItemIconColor: '--plasma-accordion-item-color-icon',

    accordionItemTitleColor: '--plasma-accordion-item-title-color',
    accordionItemTitleFontFamily: '--plasma-accordion-item-title-font-family',
    accordionItemTitleFontSize: '--plasma-accordion-item-title-font-size',
    accordionItemTitleFontStyle: '--plasma-accordion-item-title-font-style',
    accordionItemTitleFontWeight: '--plasma-accordion-item-title-font-weight',
    accordionItemTitleLetterSpacing: '--plasma-accordion-item-title-letter-spacing',
    accordionItemTitleLineHeight: '--plasma-accordion-item-title-line-height',

    accordionItemTextColor: '--plasma-accordion-item-text-color',
    accordionItemTextFontFamily: '--plasma-accordion-item-text-font-family',
    accordionItemTextFontSize: '--plasma-accordion-item-text-font-size',
    accordionItemTextFontStyle: '--plasma-accordion-item-text-font-style',
    accordionItemTextFontWeight: '--plasma-accordion-item-text-font-weight',
    accordionItemTextLetterSpacing: '--plasma-accordion-item-text-letter-spacing',
    accordionItemTextLineHeight: '--plasma-accordion-item-text-line-height',
};
