export const classes = {
    datePickerError: 'date-picker-error',
    datePickerSuccess: 'date-picker-success',
    datePickerRoot: 'date-picker-root',
    datePickerstretched: 'date-picker-stretched',
    datePickerCalendarstretched: 'date-picker-calendar-stretched',
    clear: 'date-picker-clear',
    clearDivider: 'date-picker-clear-divider',
};

export const pivateTokens = {
    calendarDoubleWidth: '--plasma_private-calendar-double-width',
};

export const tokens = {
    width: '--plasma-date-picker-width',

    /** Токены полей ввода в рендже */
    background: '--plasma-date-picker_range-background',
    backgroundError: '--plasma-date-picker_range-background-error',
    backgroundSuccess: '--plasma-date-picker_range-background-success',
    backgroundReadOnly: '--plasma-date-picker_range-background-readonly',
    borderRadius: '--plasma-date-picker_range-border-radius',
    borderWidth: '--plasma-date-picker_range-border-width',
    borderColor: '--plasma-date-picker_range-border-color',
    borderColorHover: '--plasma-date-picker_range-border-color-hover',
    borderColorFocus: '--plasma-date-picker_range-border-color-focus',
    borderColorError: '--plasma-date-picker_range-border-color-error',
    borderColorSuccess: '--plasma-date-picker_range-border-color-success',
    borderColorReadOnly: '--plasma-date-picker_range-border-color-readonly',

    /** Токены разделителя */
    clearDividerColor: '--plasma-date-picker-clear__divider-color',
    dividerColor: '--plasma-date-picker_range__divider-color',
    dividerColorReadOnly: '--plasma-date-picker_range__divider-color-readonly',
    dividerPadding: '--plasma-date-picker_range__divider-padding',
    dividerFontFamily: '--plasma-date-picker_range__divider-font-family',
    dividerFontStyle: '--plasma-date-picker_range__divider-font-style',
    dividerFontSize: '--plasma-date-picker_range__divider-font-size',
    dividerFontWeight: '--plasma-date-picker_range__divider-font-weight',
    dividerLetterSpacing: '--plasma-date-picker_range__divider-letter-spacing',
    dividerLineHeight: '--plasma-date-picker_range__divider-line-height',
    dividerOpacityReadOnly: '--plasma-date-picker_range__divider-opacity-readonly',

    /** Токены слотов для контента в range */
    leftContentMargin: '--plasma-date-picker_range__left-content-margin',
    rightContentMargin: '--plasma-date-picker_range__right-content-margin',
    rightContentOpacityReadOnly: '--plasma-date-picker_range__right-content-opacity-readonly',

    contentSlotColor: '--plasma-date-picker-content-slot-color',
    contentSlotColorHover: '--plasma-date-picker-content-slot-color-hover',
    contentSlotColorActive: '--plasma-date-picker-content-slot-color-active',

    contentSlotColorSuccess: '--plasma-date-picker-content-slot-color-success',
    contentSlotColorSuccessHover: '--plasma-date-picker-content-slot-color-success-hover',
    contentSlotColorSuccessActive: '--plasma-date-picker-content-slot-color-success-active',

    contentSlotColorError: '--plasma-date-picker-content-slot-color-error',
    contentSlotColorErrorHover: '--plasma-date-picker-content-slot-color-error-hover',
    contentSlotColorErrorActive: '--plasma-date-picker-content-slot-color-error-active',

    contentSlotRightColor: '--plasma-date-picker-content-right-slot-color',
    contentSlotRightColorHover: '--plasma-date-picker-content-right-slot-color-hover',
    contentSlotRightColorActive: '--plasma-date-picker-content-right-slot-color-active',

    /** Токены лейбла */
    labelWrapperOffset: '--plasma-date-picker-label-wrapper-offset',
    labelColor: '--plasma-date-picker__label-color',
    labelColorReadOnly: '--plasma-date-picker__label-color-readonly',
    labelOffset: '--plasma-date-picker__label-offset',

    labelFontFamily: '--plasma-date-picker__label-font-family',
    labelFontStyle: '--plasma-date-picker__label-font-style',
    labelFontSize: '--plasma-date-picker__label-font-size',
    labelFontWeight: '--plasma-date-picker__label-font-weight',
    labelLetterSpacing: '--plasma-date-picker__label-letter-spacing',
    labelLineHeight: '--plasma-date-picker__label-line-height',

    /** Токены индикатора */
    indicatorWrapperGap: '--plasma-date-picker-indicator-wrapper-gap',
    indicatorColor: '--plasma-date-picker__indicator-color',
    indicatorSizeInner: '--plasma-date-picker__indicator-size',
    indicatorSizeOuter: '--plasma-date-picker__indicator-size-outer',

    indicatorPlacement: '--plasma-date-picker__indicator-placement',
    indicatorPlacementRight: '--plasma-date-picker__indicator-placement-right',
    indicatorOuterPlacement: '--plasma-date-picker__indicator-placement-outer',
    indicatorOuterPlacementRight: '--plasma-date-picker__indicator-placement-outer-right',

    indicatorMarginTop: '--plasma-date-picker-indicator-margin-top',
    indicatorOuterLeft: '--plasma-date-picker-indicator-outer-left',
    indicatorWithoutLabelInner: '--plasma-date-picker-indicator-without-label-inner',
    indicatorWithoutLabelInnerLeft: '--plasma-date-picker-indicator-without-label-inner-left',
    indicatorWithoutLabelOuterHint: '--plasma-date-picker-indicator-without-label-outer-hint',

    /** Токены индикатора (удалить после перехода на InformationWrapper в Textfield) */
    clearIndicatorHintInnerRight: '--plasma-date-picker__clear-indicator-hint-placement-inner-right',

    /* label-placement-inner */
    labelInnerFontFamily: '--plasma-date-picker-placement_inner__label-font-family',
    labelInnerFontStyle: '--plasma-date-picker-placement_inner__label-font-style',
    labelInnerFontSize: '--plasma-date-picker-placement_inner__label-font-size',
    labelInnerFontWeight: '--plasma-date-picker-placement_inner__label-font-weight',
    labelInnerLetterSpacing: '--plasma-date-picker-placement_inner__label-letter-spacing',
    labelInnerLineHeight: '--plasma-date-picker-placement_inner__label-line-height',

    labelInnerPadding: '--plasma-date-picker-placement_inner__label-padding',
    contentLabelInnerPadding: '--plasma-date-picker-placement_inner__content-padding',

    /** Токены вспомогательного текста */
    leftHelperColor: '--plasma-date-picker__left-helper-color',
    leftHelperColorError: '--plasma-date-picker__left-helper-color-error',
    leftHelperColorSuccess: '--plasma-date-picker__left-helper-color-success',
    leftHelperColorReadOnly: '--plasma-date-picker__left-helper-color-readonly',
    leftHelperOffset: '--plasma-date-picker__left-helper-offset',

    leftHelperFontFamily: '--plasma-date-picker__left-helper-font-family',
    leftHelperFontStyle: '--plasma-date-picker__left-helper-font-style',
    leftHelperFontSize: '--plasma-date-picker__left-helper-font-size',
    leftHelperFontWeight: '--plasma-date-picker__left-helper-font-weight',
    leftHelperLetterSpacing: '--plasma-date-picker__left-helper-letter-spacing',
    leftHelperLineHeight: '--plasma-date-picker__left-helper-line-height',

    titleCaptionOffset: '--plasma-date-picker-title-caption-offset',
    titleCaptionColor: '--plasma-date-picker-title-caption-color',
    titleCaptionFontFamily: '--plasma-date-picker-title-caption-font-family',
    titleCaptionFontStyle: '--plasma-date-picker-title-caption-font-style',
    titleCaptionFontSize: '--plasma-date-picker-title-caption-font-size',
    titleCaptionFontWeight: '--plasma-date-picker-title-caption-font-weight',
    titleCaptionLetterSpacing: '--plasma-date-picker-title-caption-letter-spacing',
    titleCaptionLineHeight: '--plasma-date-picker-title-caption-line-height',

    /** Прозрачность для всего компонента в состоянии disabled */
    disabledOpacity: '--plasma-date-picker-disabled-opacity',

    rangeReadOnlyOpacity: '--plasma-date-picker-readonly-opacity',

    /** Цвет обводки поля ввода при фокусе */
    focusColor: '--plasma-date-picker-focus-color',

    /** Токены полей ввода */
    textFieldColor: '--plasma-date-picker-textfield-color',
    textFieldColorError: '--plasma-date-picker-textfield-color-error',
    textFieldColorSuccess: '--plasma-date-picker-textfield-color-success',
    textFieldPlaceholderColorFocus: '--plasma-datepicker-textfield__placeholder-color-focus',
    textFieldFocusColor: '--plasma-date-picker-textfield-focus-color',
    textFieldPlaceholderColor: '--plasma-date-picker-textfield-placeholder-color',
    textFieldClearPlaceholderColorFocus: '--plasma-date-picker-textfield-clear-placeholder-color-focus',
    textFieldCaretColor: '--plasma-date-picker-textfield-caret-color',

    textFieldBackgroundColor: '--plasma-date-picker-textfield-background-color',
    textFieldBackgroundColorHover: '--plasma-date-picker-textfield-background-color-hover',
    textFieldBackgroundColorFocus: '--plasma-date-picker-textfield-background-color-focus',
    textFieldBackgroundErrorColor: '--plasma-date-picker-textfield-background-color-error',
    textFieldBackgroundErrorColorHover: '--plasma-date-picker-textfield-background-color-error-hover',
    textFieldBackgroundErrorColorFocus: '--plasma-date-picker-textfield-background-color-error-focus',
    textFieldBackgroundSuccessColor: '--plasma-date-picker-textfield-background-color-success',
    textFieldBackgroundSuccessColorHover: '--plasma-date-picker-textfield-background-color-success-hover',
    textFieldBackgroundSuccessColorFocus: '--plasma-date-picker-textfield-background-color-success-focus',

    textFieldBorderColor: '--plasma-date-picker-textfield-border-color',
    textFieldBorderColorHover: '--plasma-date-picker-textfield-border-color-hover',
    textFieldBorderColorFocus: '--plasma-date-picker-textfield-border-color-focus',
    textFieldBorderColorError: '--plasma-date-picker-textfield-border-color-error',
    textFieldBorderColorErrorHover: '--plasma-date-picker-textfield-border-color-error-hover',
    textFieldBorderColorErrorFocus: '--plasma-date-picker-textfield-border-color-error-focus',
    textFieldBorderColorSuccess: '--plasma-date-picker-textfield-border-color-success',
    textFieldBorderColorSuccessHover: '--plasma-date-picker-textfield-border-color-success-hover',
    textFieldBorderColorSuccessFocus: '--plasma-date-picker-textfield-border-color-success-focus',

    textFieldColorReadOnly: '--plasma-date-picker-textfield-color-readonly',
    textFieldBackgroundColorReadOnly: '--plasma-date-picker-textfield-background-color-readonly',
    textFieldBorderColorReadOnly: '--plasma-date-picker-textfield-border-color-readonly',
    textFieldPlaceholderColorReadOnly: '--plasma-date-picker-textfield-placeholder-color-readonly',
    textFieldReadOnlyOpacity: '--plasma-date-picker-textfield-readonly-opacity',

    textFieldHeight: '--plasma-date-picker-textfield-height',
    textFieldBorderWidth: '--plasma-date-picker-textfield-border-width',
    textFieldBorderRadius: '--plasma-date-picker-textfield-border-radius',
    textFieldPadding: '--plasma-date-picker-textfield-padding',
    textFieldLeftContentMargin: '--plasma-date-picker-textfield__left-content-margin',
    textFieldRightContentMargin: '--plasma-date-picker-textfield__right-content-margin',
    textFieldFontFamily: '--plasma-date-picker-textfield-font-family',
    textFieldFontStyle: '--plasma-date-picker-textfield-font-style',
    textFieldFontSize: '--plasma-date-picker-textfield-font-size',
    textFieldFontWeight: '--plasma-date-picker-textfield-font-weight',
    textFieldLetterSpacing: '--plasma-date-picker-textfield-letter-spacing',
    textFieldLineHeight: '--plasma-date-picker-textfield-line-height',

    textFieldTextBeforeColor: '--plasma-date-picker-textfield__before-text-color',
    textFieldTextAfterColor: '--plasma-date-picker-textfield__after-text-color',
    textFieldTextBeforeMargin: '--plasma-date-picker-textfield__before-text-margin',
    textFieldTextAfterMargin: '--plasma-date-picker-textfield__after-text-margin',

    textFieldContentSlotRightColor: '--plasma-date-picker-textfield__content-right-color',
    textFieldContentSlotRightColorHover: '--plasma-date-picker-textfield__content-right-color-hover',
    textFieldContentSlotRightColorActive: '--plasma-date-picker-textfield__content-right-color-active',

    textFieldContentSlotColor: '--plasma-date-picker-textfield__content-color',
    textFieldContentSlotColorHover: '--plasma-date-picker-textfield__content-color-hover',
    textFieldContentSlotColorActive: '--plasma-date-picker-textfield__content-color-active',

    textFieldContentRightSlotColor: '--plasma-date-picker-textfield__content-right-color',
    textFieldContentRightSlotColorHover: '--plasma-date-picker-textfield__content-right-color-hover',
    textFieldContentRightSlotColorActive: '--plasma-date-picker-textfield__content-right-color-active',
    textFieldContentSlotRightOpacityReadOnly: '--plasma-date-picker-textfield__content-right-readonly-opacity',

    textFieldContentSlotColorSuccess: '--plasma-textfield-content-slot-color-success',
    textFieldContentSlotColorSuccessHover: '--plasma-textfield-content-slot-color-success-hover',
    textFieldContentSlotColorSuccessActive: '--plasma-textfield-content-slot-color-success-active',

    textFieldContentSlotColorError: '--plasma-textfield-content-slot-color-error',
    textFieldContentSlotColorErrorHover: '--plasma-textfield-content-slot-color-error-hover',
    textFieldContentSlotColorErrorActive: '--plasma-textfield-content-slot-color-error-active',

    textFieldDividerColorSuccess: '--plasma-date-picker-textfield__divider-color-success',
    textFieldDividerColorError: '--plasma-date-picker-textfield__divider-color-error',
    textFieldDividerColorHover: '--plasma-date-picker-textfield__divider-color-hover',
    textFieldDividerColorFocus: '--plasma-date-picker-textfield__divider-color-focus',

    /** Токены календаря */
    calendarMarginTop: '--plasma-date-picker-calendar-margin-top',
    calendarPaddingTop: '--plasma-date-picker-calendar-padding-top',
    calendarShadow: '--plasma-date-picker-calendar-shadow',
    calendarBorderRadius: '--plasma-date-picker-calendar-border-radius',
    calendarContainerWidth: '--plasma-date-picker-calendar-container-width',
    calendarContainerHeight: '--plasma-date-picker-calendar-container-height',
    calendarBorderWidth: '--plasma-date-picker-calendar-border-width',
    calendarBorderColor: '--plasma-date-picker-calendar-border-color',

    calendarYearsPadding: '--plasma-date-picker-calendar__years-padding',
    calendarYearItemBorderRadius: '--plasma-date-picker-calendar__year-item-border-radius',
    calendarYearFontFamily: '--plasma-date-picker-calendar__year-font-family',
    calendarYearFontSize: '--plasma-date-picker-calendar__year-font-size',
    calendarYearFontStyle: '--plasma-date-picker-calendar__year-font-style',
    calendarYearFontLetterSpacing: '--plasma-date-picker-calendar__year-letter-spacing',
    calendarYearFontLineHeight: '--plasma-date-picker-calendar__year-line-height',
    calendarYearFontWeight: '--plasma-date-picker-calendar__year-font-weight',
    calendarYearSelectedFontWeight: '--plasma-date-picker-calendar__year-selected-font-weight',

    calendarMonthsPadding: '--plasma-date-picker-calendar__months-padding',
    calendarMonthItemBorderRadius: '--plasma-date-picker-calendar__month-item-border-radius',
    calendarMonthFontFamily: '--plasma-date-picker-calendar__month-font-family',
    calendarMonthFontSize: '--plasma-date-picker-calendar__month-font-size',
    calendarMonthFontStyle: '--plasma-date-picker-calendar__month-font-style',
    calendarMonthFontLetterSpacing: '--plasma-date-picker-calendar__month-letter-spacing',
    calendarMonthFontLineHeight: '--plasma-date-picker-calendar__month-line-height',
    calendarMonthFontWeight: '--plasma-date-picker-calendar__month-font-weight',
    calendarMonthSelectedFontWeight: '--plasma-date-picker-calendar__month-selected-font-weight',

    calendarQuartersPadding: '--plasma-date-picker-calendar__quarters-padding',
    calendarQuarterItemBorderRadius: '--plasma-date-picker-calendar__quarter-item-border-radius',
    calendarQuarterFontFamily: '--plasma-date-picker-calendar__quarter-font-family',
    calendarQuarterFontSize: '--plasma-date-picker-calendar__quarter-font-size',
    calendarQuarterFontStyle: '--plasma-date-picker-calendar__quarter-font-style',
    calendarQuarterFontLetterSpacing: '--plasma-date-picker-calendar__quarter-letter-spacing',
    calendarQuarterFontLineHeight: '--plasma-date-picker-calendar__quarter-line-height',
    calendarQuarterFontWeight: '--plasma-date-picker-calendar__quarter-font-weight',
    calendarQuarterSelectedFontWeight: '--plasma-date-picker-calendar__quarter-selected-font-weight',

    calendarDaysPadding: '--plasma-date-picker-calendar__days-padding',
    calendarDayItemBorderRadius: '--plasma-date-picker-calendar__day-item-border-radius',
    calendarDayFontFamily: '--plasma-date-picker-calendar__day-font-family',
    calendarDayFontSize: '--plasma-date-picker-calendar__day-font-size',
    calendarDayFontStyle: '--plasma-date-picker-calendar__day-font-style',
    calendarDayFontLetterSpacing: '--plasma-date-picker-calendar__day-letter-spacing',
    calendarDayFontLineHeight: '--plasma-date-picker-calendar__day-line-height',
    calendarDayFontWeight: '--plasma-date-picker-calendar__day-font-weight',
    calendarDaySelectedFontWeight: '--plasma-date-picker-calendar__day-selected-font-weight',
    calendarDayOfWeekColor: '--plasma-date-picker-calendar__day-of-week-color',

    calendarEventItemBottom: '--plasma-date-picker-calendar__event-item-bottom',

    calendarHeaderWrapperPadding: '--plasma-date-picker-calendar__header-wrapper-padding',
    calendarHeaderArrowGap: '--plasma-date-picker-calendar__header-arrow-gap',
    calendarHeaderArrowPadding: '--plasma-date-picker-calendar__header-arrow-padding',
    calendarHeaderPadding: '--plasma-date-picker-calendar__header-padding',
    calendarHeaderDateGap: '--plasma-date-picker-calendar__header-date-gap',
    calendarHeaderFontFamily: '--plasma-date-picker-calendar__header-font-family',
    calendarHeaderFontSize: '--plasma-date-picker-calendar__header-font-size',
    calendarHeaderFontStyle: '--plasma-date-picker-calendar__header-font-style',
    calendarHeaderFontLetterSpacing: '--plasma-date-picker-calendar__header-letter-spacing',
    calendarHeaderFontLineHeight: '--plasma-date-picker-calendar__header-line-height',
    calendarHeaderFontWeight: '--plasma-date-picker-calendar__header-font-weight',
    calendarHeaderFontWeightBold: '--plasma-date-picker-calendar__header-font-weight-bold',
    calendarHeaderArrowColor: '--plasma-date-picker-calendar__header-arrow-color',
    calendarHeaderArrowCustomSize: '--plasma-date-picker-calendar__header-arrow-custom-size',

    iconButtonColor: '--plasma-date-picker-icon-button__color',
    iconButtonBackgroundColor: '--plasma-date-picker-icon-button__background-color',
    iconButtonColorHover: '--plasma-date-picker-icon-button__color-hover',
    iconButtonBackgroundColorHover: '--plasma-date-picker-icon-button__background-color-hover',
    iconButtonColorActive: '--plasma-date-picker-icon-button__color-active',
    iconButtonBackgroundColorActive: '--plasma-date-picker-icon-button__background-color-active',
    iconButtonHeight: '--plasma-date-picker-icon-button__height',
    iconButtonWidth: '--plasma-date-picker-icon-button__width',
    iconButtonPadding: '--plasma-date-picker-icon-button__padding',
    iconButtonRadius: '--plasma-date-picker-icon-button__radius',
    iconButtonFocusColor: '--plasma-date-picker-icon-button__focus-color',
    calendarBackgroundColor: '--plasma-date-picker-calendar__background-color',

    calendarSelectedItemBackground: '--plasma-date-picker-calendar__selected-item-background',
    calendarSelectedItemColor: '--plasma-date-picker-calendar__selected-item-color',
    calendarSelectableItemBackgroundHover: '--plasma-date-picker-calendar__selectable-item-background-hover',
    calendarCurrentItemBorderColor: '--plasma-date-picker-calendar__current-item-border-color',
    calendarCurrentItemBorderWidth: '--plasma-date-picker-calendar__current-item-border-width',
    calendarCurrentItemBackgroundHover: '--plasma-date-picker-calendar__current-item-background-hover',
    calendarCurrentItemColorHover: '--plasma-date-picker-calendar__current-item-color-hover',
    calendarCurrentItemChildBackgroundHover: '--plasma-date-picker-calendar__current-item-child-background-hover',
    calendarActiveItemBackground: '--plasma-date-picker-calendar__active-item-background',
    calendarActiveItemColor: '--plasma-date-picker-calendar__active-item-color',
    calendarHoveredItemBackground: '--plasma-date-picker-calendar__hovered-item-background',
    calendarHoveredItemColor: '--plasma-date-picker-calendar__hovered-item-color',
    calendarSeparatorBackground: '--plasma-date-picker-calendar__separator-background',
    calendarRangeBackground: '--plasma-date-picker-calendar__range-background',
    calendarOutlineFocusColor: '--plasma-date-picker-calendar__outline-focus-color',
    calendarContentPrimaryColor: '--plasma-date-picker-calendar__content-primary-color',
    calendarContentSecondaryColor: '--plasma-date-picker-calendar__content-secondary-color',
    calendarContentPrimaryDisabledColor: '--plasma-date-picker-calendar__content-primary-disabled-color',
    calendarContentSecondaryDisabledColor: '--plasma-date-picker-calendar__content-secondary-disabled-color',
    calendarDisabledOpacity: '--plasma-date-picker-calendar__disabled-opacity',

    /* Токены тултипа для событий */
    tooltipPaddingTop: '--plasma-datepicker-calendar-tooltip-padding-top',
    tooltipPaddingRight: '--plasma-datepicker-calendar-tooltip-padding-right',
    tooltipPaddingBottom: '--plasma-datepicker-calendar-tooltip-padding-bottom',
    tooltipPaddingLeft: '--plasma-datepicker-calendar-tooltip-padding-left',
    tooltipMinHeight: '--plasma-datepicker-calendar-tooltip-min-height',
    tooltipBackgroundColor: '--plasma-datepicker-calendar-tooltip-background-color',
    tooltipBoxShadow: '--plasma-datepicker-calendar-tooltip-box-shadow',
    tooltipBorderRadius: '--plasma-datepicker-calendar-tooltip-border-radius',
    tooltipColor: '--plasma-datepicker-calendar-tooltip-color',
    tooltipTextFontFamily: '--plasma-datepicker-calendar-tooltip-text-font-family',
    tooltipTextFontSize: '--plasma-datepicker-calendar-tooltip-text-font-size',
    tooltipTextFontStyle: '--plasma-datepicker-calendar-tooltip-text-font-style',
    tooltipTextFontWeight: '--plasma-datepicker-calendar-tooltip-text-font-weight',
    tooltipTextFontLetterSpacing: '--plasma-datepicker-calendar-tooltip-text-font-letter-spacing',
    tooltipTextFontLineHeight: '--plasma-datepicker-calendar-tooltip-text-font-line-height',
    tooltipContentLeftMargin: '--plasma-datepicker-calendar-tooltip-content-left-margin',
    tooltipArrowMaskWidth: '--plasma-datepicker-calendar-tooltip-arrow-mask-width',
    tooltipArrowMaskHeight: '--plasma-datepicker-calendar-tooltip-arrow-mask-height',
    tooltipArrowMaskImage: '--plasma-datepicker-calendar-tooltip-arrow-mask-image',
    tooltipArrowBackground: '--plasma-datepicker-calendar-tooltip-arrow-background',
    tooltipArrowHeight: '--plasma-datepicker-calendar-tooltip-arrow-height',
    tooltipArrowEdgeMargin: '--plasma-datepicker-calendar-tooltip-arrow-edge-margin',

    /* токены для hint */
    hintMargin: '--plasma-date-picker-info-wrapper-hint-margin',
    hintTargetSize: '--plasma-date-picker-info-wrapper-hint-target-size',
    hintCustomIconTargetSize: '--plasma-date-picker-info-wrapper-hint-custom-icon-target-size',
    hintIconColor: '--plasma-date-picker-info-wrapper-hint-icon-color',
    hintWithoutLabelPlacementOffset: '--plasma-date-picker-info-wrapper-hint-without-label-placement-offset',
    hintPlacementInnerMargin: '--plasma-date-picker-info-wrapper-hint-placement-inner-offset',
    hintInnerLabelPlacementOffset: '--plasma-date-picker_old_hint-inner-label-placement-offset',
    clearHintInnerLabelPlacementOffset: '--plasma-date-picker_old_clear-hint-inner-label-placement-offset',

    hintTooltipPaddingTop: '--plasma-datepicker-calendar-hint-tooltip-padding-top',
    hintTooltipPaddingRight: '--plasma-datepicker-calendar-hint-tooltip-padding-right',
    hintTooltipPaddingBottom: '--plasma-datepicker-calendar-hint-tooltip-padding-bottom',
    hintTooltipPaddingLeft: '--plasma-datepicker-calendar-hint-tooltip-padding-left',
    hintTooltipMinHeight: '--plasma-datepicker-calendar-hint-tooltip-min-height',
    hintTooltipBackgroundColor: '--plasma-datepicker-calendar-hint-tooltip-background-color',
    hintTooltipBoxShadow: '--plasma-datepicker-calendar-hint-tooltip-box-shadow',
    hintTooltipBorderRadius: '--plasma-datepicker-calendar-hint-tooltip-border-radius',
    hintTooltipColor: '--plasma-datepicker-calendar-hint-tooltip-color',
    hintTooltipTextFontFamily: '--plasma-datepicker-calendar-hint-tooltip-text-font-family',
    hintTooltipTextFontSize: '--plasma-datepicker-calendar-hint-tooltip-text-font-size',
    hintTooltipTextFontStyle: '--plasma-datepicker-calendar-hint-tooltip-text-font-style',
    hintTooltipTextFontWeight: '--plasma-datepicker-calendar-hint-tooltip-text-font-weight',
    hintTooltipTextFontLetterSpacing: '--plasma-datepicker-calendar-hint-tooltip-text-font-letter-spacing',
    hintTooltipTextFontLineHeight: '--plasma-datepicker-calendar-hint-tooltip-text-font-line-height',
    hintTooltipContentLeftMargin: '--plasma-datepicker-calendar-hint-tooltip-content-left-margin',
    hintTooltipArrowMaskWidth: '--plasma-datepicker-calendar-hint-tooltip-arrow-mask-width',
    hintTooltipArrowMaskHeight: '--plasma-datepicker-calendar-hint-tooltip-arrow-mask-height',
    hintTooltipArrowMaskImage: '--plasma-datepicker-calendar-hint-tooltip-arrow-mask-image',
    hintTooltipArrowBackground: '--plasma-datepicker-calendar-hint-tooltip-arrow-background',
    hintTooltipArrowHeight: '--plasma-datepicker-calendar-hint-tooltip-arrow-height',
    hintTooltipArrowEdgeMargin: '--plasma-datepicker-calendar-hint-tooltip-arrow-edge-margin',
};
