export const classes = {
    datePickerError: 'date-picker-error',
    datePickerSuccess: 'date-picker-success',
    datePickerRoot: 'date-picker-root',
};

export const tokens = {
    width: '--plasma-date-picker-width',

    /** Токены полей ввода в рендже */
    background: '--plasma-date-picker_range-background',
    backgroundError: '--plasma-date-picker_range-background-error',
    backgroundSuccess: '--plasma-date-picker_range-background-success',
    backgroundReadOnly: '--plasma-date-picker_range-background-readonly',
    borderRadius: '--plasma-date-picker_range-border-radius',
    borderWidth: '--plasma-date-picker_range-border-width',
    borderColor: '--plasma-date-picker_range-border-color',
    borderColorHover: '--plasma-date-picker_range-border-color-hover',
    borderColorFocus: '--plasma-date-picker_range-border-color-focus',
    borderColorError: '--plasma-date-picker_range-border-color-error',
    borderColorSuccess: '--plasma-date-picker_range-border-color-success',
    borderColorReadOnly: '--plasma-date-picker_range-border-color-readonly',

    /** Токены разделителя */
    dividerColor: '--plasma-date-picker_range__divider-color',
    dividerColorReadOnly: '--plasma-date-picker_range__divider-color-readonly',
    dividerPadding: '--plasma-date-picker_range__divider-padding',
    dividerFontFamily: '--plasma-date-picker_range__divider-font-family',
    dividerFontStyle: '--plasma-date-picker_range__divider-font-style',
    dividerFontSize: '--plasma-date-picker_range__divider-font-size',
    dividerFontWeight: '--plasma-date-picker_range__divider-font-weight',
    dividerLetterSpacing: '--plasma-date-picker_range__divider-letter-spacing',
    dividerLineHeight: '--plasma-date-picker_range__divider-line-height',

    /** Токены слотов для контента в рендже */
    leftContentMargin: '--plasma-date-picker_range__left-content-margin',
    rightContentMargin: '--plasma-date-picker_range__right-content-margin',

    /** Токены лейбла */
    labelColor: '--plasma-date-picker__label-color',
    labelColorReadOnly: '--plasma-date-picker__label-color-readonly',
    labelOffset: '--plasma-date-picker__label-offset',

    labelFontFamily: '--plasma-date-picker__label-font-family',
    labelFontStyle: '--plasma-date-picker__label-font-style',
    labelFontSize: '--plasma-date-picker__label-font-size',
    labelFontWeight: '--plasma-date-picker__label-font-weight',
    labelLetterSpacing: '--plasma-date-picker__label-letter-spacing',
    labelLineHeight: '--plasma-date-picker__label-line-height',

    /* label-placement-inner */
    labelInnerFontFamily: '--plasma-date-picker-placement_inner__label-font-family',
    labelInnerFontStyle: '--plasma-date-picker-placement_inner__label-font-style',
    labelInnerFontSize: '--plasma-date-picker-placement_inner__label-font-size',
    labelInnerFontWeight: '--plasma-date-picker-placement_inner__label-font-weight',
    labelInnerLetterSpacing: '--plasma-date-picker-placement_inner__label-letter-spacing',
    labelInnerLineHeight: '--plasma-date-picker-placement_inner__label-line-height',

    labelInnerPadding: '--plasma-date-picker-placement_inner__label-padding',
    contentLabelInnerPadding: '--plasma-date-picker-placement_inner__content-padding',

    /** Токены вспомогательного текста */
    leftHelperColor: '--plasma-date-picker__left-helper-color',
    leftHelperColorReadOnly: '--plasma-date-picker__left-helper-color-readonly',
    leftHelperOffset: '--plasma-date-picker__left-helper-offset',

    leftHelperFontFamily: '--plasma-date-picker__left-helper-font-family',
    leftHelperFontStyle: '--plasma-date-picker__left-helper-font-style',
    leftHelperFontSize: '--plasma-date-picker__left-helper-font-size',
    leftHelperFontWeight: '--plasma-date-picker__left-helper-font-weight',
    leftHelperLetterSpacing: '--plasma-date-picker__left-helper-letter-spacing',
    leftHelperLineHeight: '--plasma-date-picker__left-helper-line-height',

    /** Прозрачность для всего компонента в состоянии disabled */
    disabledOpacity: '--plasma-date-picker-disabled-opacity',

    /** Цвет обводки поля ввода при фокусе */
    focusColor: '--plasma-date-picker-focus-color',

    /** Токены полей ввода */
    textFieldColor: '--plasma-date-picker-textfield-color',
    textFieldFocusColor: '--plasma-date-picker-textfield-focus-color',
    textFieldPlaceholderColor: '--plasma-date-picker-textfield-placeholder-color',
    textFieldCaretColor: '--plasma-date-picker-textfield-caret-color',

    textFieldBackgroundColor: '--plasma-date-picker-textfield-background-color',
    textFieldBackgroundColorHover: '--plasma-date-picker-textfield-background-color-hover',
    textFieldBackgroundColorFocus: '--plasma-date-picker-textfield-background-color-focus',
    textFieldBackgroundErrorColor: '--plasma-date-picker-textfield-background-color-error',
    textFieldBackgroundErrorColorHover: '--plasma-date-picker-textfield-background-color-error-hover',
    textFieldBackgroundErrorColorFocus: '--plasma-date-picker-textfield-background-color-error-focus',
    textFieldBackgroundSuccessColor: '--plasma-date-picker-textfield-background-color-success',
    textFieldBackgroundSuccessColorHover: '--plasma-date-picker-textfield-background-color-success-hover',
    textFieldBackgroundSuccessColorFocus: '--plasma-date-picker-textfield-background-color-success-focus',

    textFieldBorderColor: '--plasma-date-picker-textfield-border-color',
    textFieldBorderColorHover: '--plasma-date-picker-textfield-border-color-hover',
    textFieldBorderColorFocus: '--plasma-date-picker-textfield-border-color-focus',
    textFieldBorderColorError: '--plasma-date-picker-textfield-border-color-error',
    textFieldBorderColorErrorHover: '--plasma-date-picker-textfield-border-color-error-hover',
    textFieldBorderColorErrorFocus: '--plasma-date-picker-textfield-border-color-error-focus',
    textFieldBorderColorSuccess: '--plasma-date-picker-textfield-border-color-success',
    textFieldBorderColorSuccessHover: '--plasma-date-picker-textfield-border-color-success-hover',
    textFieldBorderColorSuccessFocus: '--plasma-date-picker-textfield-border-color-success-focus',

    textFieldColorReadOnly: '--plasma-date-picker-textfield-color-readonly',
    textFieldBackgroundColorReadOnly: '--plasma-date-picker-textfield-background-color-readonly',
    textFieldBorderColorReadOnly: '--plasma-date-picker-textfield-border-color-readonly',
    textFieldPlaceholderColorReadOnly: '--plasma-date-picker-textfield-placeholder-color-readonly',

    textFieldHeight: '--plasma-date-picker-textfield-height',
    textFieldBorderWidth: '--plasma-date-picker-textfield-border-width',
    textFieldBorderRadius: '--plasma-date-picker-textfield-border-radius',
    textFieldPadding: '--plasma-date-picker-textfield-padding',
    textFieldLeftContentMargin: '--plasma-date-picker-textfield__left-content-margin',
    textFieldRightContentMargin: '--plasma-date-picker-textfield__right-content-margin',
    textFieldFontFamily: '--plasma-date-picker-textfield-font-family',
    textFieldFontStyle: '--plasma-date-picker-textfield-font-style',
    textFieldFontSize: '--plasma-date-picker-textfield-font-size',
    textFieldFontWeight: '--plasma-date-picker-textfield-font-weight',
    textFieldLetterSpacing: '--plasma-date-picker-textfield-letter-spacing',
    textFieldLineHeight: '--plasma-date-picker-textfield-line-height',

    textFieldTextBeforeColor: '--plasma-date-picker-textfield__before-text-color',
    textFieldTextAfterColor: '--plasma-date-picker-textfield__after-text-color',
    textFieldTextBeforeMargin: '--plasma-date-picker-textfield__before-text-margin',
    textFieldTextAfterMargin: '--plasma-date-picker-textfield__after-text-margin',
    textFieldContentSlotColor: '--plasma-date-picker-textfield__content-color',

    /** Токены календаря */
    calendarPaddingTop: '--plasma-date-picker-calendar-padding-top',
    calendarShadow: '--plasma-date-picker-calendar-shadow',
    calendarBorderRadius: '--plasma-date-picker-calendar-border-radius',
    calendarWidth: '--plasma-date-picker-calendar-width',
    calendarHeight: '--plasma-date-picker-calendar-height',

    calendarYearsPadding: '--plasma-date-picker-calendar__years-padding',
    calendarYearItemBorderRadius: '--plasma-date-picker-calendar__year-item-border-radius',
    calendarYearItemWidth: '--plasma-date-picker-calendar__year-item-width',
    calendarYearItemHeight: '--plasma-date-picker-calendar__year-item-height',
    calendarYearFontFamily: '--plasma-date-picker-calendar__year-font-family',
    calendarYearFontSize: '--plasma-date-picker-calendar__year-font-size',
    calendarYearFontStyle: '--plasma-date-picker-calendar__year-font-style',
    calendarYearFontLetterSpacing: '--plasma-date-picker-calendar__year-letter-spacing',
    calendarYearFontLineHeight: '--plasma-date-picker-calendar__year-line-height',
    calendarYearFontWeight: '--plasma-date-picker-calendar__year-font-weight',
    calendarYearSelectedFontWeight: '--plasma-date-picker-calendar__year-selected-font-weight',

    calendarMonthsPadding: '--plasma-date-picker-calendar__months-padding',
    calendarMonthItemBorderRadius: '--plasma-date-picker-calendar__month-item-border-radius',
    calendarMonthItemWidth: '--plasma-date-picker-calendar__month-item-width',
    calendarMonthItemHeight: '--plasma-date-picker-calendar__month-item-height',
    calendarMonthFontFamily: '--plasma-date-picker-calendar__month-font-family',
    calendarMonthFontSize: '--plasma-date-picker-calendar__month-font-size',
    calendarMonthFontStyle: '--plasma-date-picker-calendar__month-font-style',
    calendarMonthFontLetterSpacing: '--plasma-date-picker-calendar__month-letter-spacing',
    calendarMonthFontLineHeight: '--plasma-date-picker-calendar__month-line-height',
    calendarMonthFontWeight: '--plasma-date-picker-calendar__month-font-weight',
    calendarMonthSelectedFontWeight: '--plasma-date-picker-calendar__month-selected-font-weight',

    calendarQuartersPadding: '--plasma-date-picker-calendar__quarters-padding',
    calendarQuarterItemBorderRadius: '--plasma-date-picker-calendar__quarter-item-border-radius',
    calendarQuarterItemWidth: '--plasma-date-picker-calendar__quarter-item-width',
    calendarQuarterItemHeight: '--plasma-date-picker-calendar__quarter-item-height',
    calendarQuarterFontFamily: '--plasma-date-picker-calendar__quarter-font-family',
    calendarQuarterFontSize: '--plasma-date-picker-calendar__quarter-font-size',
    calendarQuarterFontStyle: '--plasma-date-picker-calendar__quarter-font-style',
    calendarQuarterFontLetterSpacing: '--plasma-date-picker-calendar__quarter-letter-spacing',
    calendarQuarterFontLineHeight: '--plasma-date-picker-calendar__quarter-line-height',
    calendarQuarterFontWeight: '--plasma-date-picker-calendar__quarter-font-weight',
    calendarQuarterSelectedFontWeight: '--plasma-date-picker-calendar__quarter-selected-font-weight',

    calendarDaysPadding: '--plasma-date-picker-calendar__days-padding',
    calendarDayItemBorderRadius: '--plasma-date-picker-calendar__day-item-border-radius',
    calendarDayItemWidth: '--plasma-date-picker-calendar__day-item-width',
    calendarDayItemHeight: '--plasma-date-picker-calendar__day-item-height',
    calendarDayFontFamily: '--plasma-date-picker-calendar__day-font-family',
    calendarDayFontSize: '--plasma-date-picker-calendar__day-font-size',
    calendarDayFontStyle: '--plasma-date-picker-calendar__day-font-style',
    calendarDayFontLetterSpacing: '--plasma-date-picker-calendar__day-letter-spacing',
    calendarDayFontLineHeight: '--plasma-date-picker-calendar__day-line-height',
    calendarDayFontWeight: '--plasma-date-picker-calendar__day-font-weight',
    calendarDaySelectedFontWeight: '--plasma-date-picker-calendar__day-selected-font-weight',
    calendarDayOfWeekColor: '--plasma-date-picker-calendar__day-of-week-color',

    calendarHeaderWrapperPadding: '--plasma-date-picker-calendar__header-wrapper-padding',
    calendarHeaderArrowGap: '--plasma-date-picker-calendar__header-arrow-gap',
    calendarHeaderArrowPadding: '--plasma-date-picker-calendar__header-arrow-padding',
    calendarHeaderPadding: '--plasma-date-picker-calendar__header-padding',
    calendarHeaderDateGap: '--plasma-date-picker-calendar__header-date-gap',
    calendarHeaderFontFamily: '--plasma-date-picker-calendar__header-font-family',
    calendarHeaderFontSize: '--plasma-date-picker-calendar__header-font-size',
    calendarHeaderFontStyle: '--plasma-date-picker-calendar__header-font-style',
    calendarHeaderFontLetterSpacing: '--plasma-date-picker-calendar__header-letter-spacing',
    calendarHeaderFontLineHeight: '--plasma-date-picker-calendar__header-line-height',
    calendarHeaderFontWeight: '--plasma-date-picker-calendar__header-font-weight',
    calendarHeaderFontWeightBold: '--plasma-date-picker-calendar__header-font-weight-bold',

    iconButtonColor: '--plasma-date-picker-icon-button__color',
    iconButtonBackgroundColor: '--plasma-date-picker-icon-button__background-color',
    iconButtonColorHover: '--plasma-date-picker-icon-button__color-hover',
    iconButtonBackgroundColorHover: '--plasma-date-picker-icon-button__background-color-hover',
    iconButtonColorActive: '--plasma-date-picker-icon-button__color-active',
    iconButtonBackgroundColorActive: '--plasma-date-picker-icon-button__background-color-active',
    iconButtonHeight: '--plasma-date-picker-icon-button__height',
    iconButtonWidth: '--plasma-date-picker-icon-button__width',
    iconButtonPadding: '--plasma-date-picker-icon-button__padding',
    iconButtonRadius: '--plasma-date-picker-icon-button__radius',
    iconButtonFocusColor: '--plasma-date-picker-icon-button__focus-color',
    calendarBackgroundColor: '--plasma-date-picker-calendar__background-color',

    calendarSelectedItemBackground: '--plasma-date-picker-calendar__selected-item-background',
    calendarSelectedItemColor: '--plasma-date-picker-calendar__selected-item-color',
    calendarSelectableItemBackgroundHover: '--plasma-date-picker-calendar__selectable-item-background-hover',
    calendarCurrentItemBorderColor: '--plasma-date-picker-calendar__current-item-border-color',
    calendarCurrentItemBackgroundHover: '--plasma-date-picker-calendar__current-item-background-hover',
    calendarCurrentItemColorHover: '--plasma-date-picker-calendar__current-item-color-hover',
    calendarCurrentItemChildBackgroundHover: '--plasma-date-picker-calendar__current-item-child-background-hover',
    calendarActiveItemBackground: '--plasma-date-picker-calendar__active-item-background',
    calendarActiveItemColor: '--plasma-date-picker-calendar__active-item-color',
    calendarHoveredItemBackground: '--plasma-date-picker-calendar__hovered-item-background',
    calendarHoveredItemColor: '--plasma-date-picker-calendar__hovered-item-color',
    calendarSeparatorBackground: '--plasma-date-picker-calendar__separator-background',
    calendarRangeBackground: '--plasma-date-picker-calendar__range-background',
    calendarOutlineFocusColor: '--plasma-date-picker-calendar__outline-focus-color',
    calendarContentPrimaryColor: '--plasma-date-picker-calendar__content-primary-color',
    calendarContentSecondaryColor: '--plasma-date-picker-calendar__content-secondary-color',
};
