name: Run performance test
description: Install Plasma and run performance test in plasma
inputs:
  branch:
    description: Branch to install from
    required: true
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ inputs.branch }}
  
    - name: Prepare repository
      shell: bash
      run: git fetch --unshallow --tags

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'

    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: node_modules
        key: npm-deps-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          npm-deps-${{ hashFiles('package-lock.json') }}

    - name: Setup packages
      shell: bash
      run: |
        npm ci
        npx lerna bootstrap

    - name: Use Node.js 16.15.x
      uses: actions/setup-node@v1
      with:
        node-version: 16.15.x
    
    - name: Prepare directory
      shell: bash
      run: |
        mkdir perftest-reports

    - name: Run performance test
      shell: bash
      run: |
        (cd ./packages/plasma-ui && node --experimental-specifier-resolution=node ./node_modules/.bin/perftool)

    - name: Save report result
      uses: actions/upload-artifact@v2
      with:
        name: ${{ inputs.branch == 'master' && 'master' || 'PR' }} report result
        path: /home/runner/work/plasma/plasma/packages/plasma-ui/perftest/result.json
