import { bodyConfig, dsplConfig, headingConfig, textConfig, component, mergeConfig } from '@salutejs/plasma-new-hope/styled-components';
import { configL as bodyConfigLCustom, configM as bodyConfigMCustom, configS as bodyConfigSCustom, configXS as bodyConfigXSCustom, configXXS as bodyConfigXXSCustom } from './Body.config';
import { configL as dsplConfigLCustom, configM as dsplConfigMCustom, configS as dsplConfigSCustom } from './Dspl.config';
import { configH1 as headingConfigH1Custom, configH2 as headingConfigH2Custom, configH3 as headingConfigH3Custom, configH4 as headingConfigH4Custom, configH5 as headingConfigH5Custom } from './Heading.config';
import { configL as textConfigLCustom, configM as textConfigMCustom, configS as textConfigSCustom, configXS as textConfigXSCustom } from './Text.config';
var bodyMConfig = /*#__PURE__*/mergeConfig(bodyConfig, bodyConfigMCustom);
var BodyMComponent = /*#__PURE__*/component(bodyMConfig);
var bodyLConfig = /*#__PURE__*/mergeConfig(bodyConfig, bodyConfigLCustom);
var BodyLComponent = /*#__PURE__*/component(bodyLConfig);
var bodySConfig = /*#__PURE__*/mergeConfig(bodyConfig, bodyConfigSCustom);
var BodySComponent = /*#__PURE__*/component(bodySConfig);
var bodyXSConfig = /*#__PURE__*/mergeConfig(bodyConfig, bodyConfigXSCustom);
var BodyXSComponent = /*#__PURE__*/component(bodyXSConfig);
var bodyXXSConfig = /*#__PURE__*/mergeConfig(bodyConfig, bodyConfigXXSCustom);
var BodyXXSComponent = /*#__PURE__*/component(bodyXXSConfig);
var dsplMConfig = /*#__PURE__*/mergeConfig(dsplConfig, dsplConfigMCustom);
var DsplMComponent = /*#__PURE__*/component(dsplMConfig);
var dsplLConfig = /*#__PURE__*/mergeConfig(dsplConfig, dsplConfigLCustom);
var DsplLComponent = /*#__PURE__*/component(dsplLConfig);
var dsplSConfig = /*#__PURE__*/mergeConfig(dsplConfig, dsplConfigSCustom);
var DsplSComponent = /*#__PURE__*/component(dsplSConfig);
var heading1Config = /*#__PURE__*/mergeConfig(headingConfig, headingConfigH1Custom);
var Heading1Component = /*#__PURE__*/component(heading1Config);
var heading2Config = /*#__PURE__*/mergeConfig(headingConfig, headingConfigH2Custom);
var Heading2Component = /*#__PURE__*/component(heading2Config);
var heading3Config = /*#__PURE__*/mergeConfig(headingConfig, headingConfigH3Custom);
var Heading3Component = /*#__PURE__*/component(heading3Config);
var heading4Config = /*#__PURE__*/mergeConfig(headingConfig, headingConfigH4Custom);
var Heading4Component = /*#__PURE__*/component(heading4Config);
var heading5Config = /*#__PURE__*/mergeConfig(headingConfig, headingConfigH5Custom);
var Heading5Component = /*#__PURE__*/component(heading5Config);
var textMConfig = /*#__PURE__*/mergeConfig(textConfig, textConfigMCustom);
var TextMComponent = /*#__PURE__*/component(textMConfig);
var textLConfig = /*#__PURE__*/mergeConfig(textConfig, textConfigLCustom);
var TextLComponent = /*#__PURE__*/component(textLConfig);
var textSConfig = /*#__PURE__*/mergeConfig(textConfig, textConfigSCustom);
var TextSComponent = /*#__PURE__*/component(textSConfig);
var textXSConfig = /*#__PURE__*/mergeConfig(textConfig, textConfigXSCustom);
var TextXSComponent = /*#__PURE__*/component(textXSConfig);
export var BodyM = BodyMComponent;
export var BodyL = BodyLComponent;
export var BodyS = BodySComponent;
export var BodyXS = BodyXSComponent;
export var BodyXXS = BodyXXSComponent;
export var DsplM = DsplMComponent;
export var DsplL = DsplLComponent;
export var DsplS = DsplSComponent;
export var H1 = Heading1Component;
export var H2 = Heading2Component;
export var H3 = Heading3Component;
export var H4 = Heading4Component;
export var H5 = Heading5Component;
export var TextM = TextMComponent;
export var TextL = TextLComponent;
export var TextS = TextSComponent;
export var TextXS = TextXSComponent;