// generated by theme-builder { version } { plasma-hope-version??? }
import { css } from '@linaria/core';

import { tabsTokens } from '../../../../components/Tabs';

export const config = {
    defaults: {
        view: 'default',
    },
    variations: {
        view: {
            default: css`
                ${tabsTokens.underlineColor}: var(--surface-solid-tertiary);
                ${tabsTokens.underlineHeight}: 0.125rem;
                ${tabsTokens.fontWeight}: 500;
                ${tabsTokens.color}: var(--text-accent);
                ${tabsTokens.cursor}: pointer;
                ${tabsTokens.colorHover}: var(--text-primary);
            `,
        },
        disabled: {
            true: css`
                ${tabsTokens.cursor}: not-allowed;
                ${tabsTokens.colorHover}: var(--text-accent);
            `,
        },
        active: {
            true: css`
                ${tabsTokens.underlineColor}: var(--text-primary);
                ${tabsTokens.color}: var(--text-primary);
                ${tabsTokens.colorHover}: var(--text-primary);
            `,
        },
    },
};
