// generated by theme-builder { version } { plasma-hope-version??? }

import { css } from '@linaria/core';

export const config = {
    defaults: {
        view: 'default',
    },
    variations: {
        view: {
            default: css`
                --plasma-tabs-underline-color: var(--surface-solid-tertiary);
                --plasma-tabs-underline-height: 2px;
                --plasma-tabs-font-weight: 500;
                --plasma-tabs-color: var(--text-accent);
                --plasma-tabs-cursor: pointer;
                --plasma-tabs-color-hover: var(--text-primary);
            `,
        },
        disabled: {
            true: css`
                --plasma-tabs-cursor: not-allowed;
                --plasma-tabs-color-hover: var(--text-accent);
            `,
        },
        active: {
            true: css`
                --plasma-tabs-underline-color: var(--text-primary);
                --plasma-tabs-color: var(--text-primary);
                --plasma-tabs-color-hover: var(--text-primary);
            `,
        },
    },
};
