// generated by theme-builder { version } { plasma-hope-version??? }

import { tabItemConfig } from '../../../../components/Tabs/TabItem';
import { component, mergeConfig } from '../../../../engines';

import { config } from './TabItem.config';

const mergedConfig = mergeConfig(tabItemConfig, config);

export const TabItem = component(mergedConfig);
