import { TokenType } from '../../../types';

export const gradientTokens: Array<TokenType> = [
    {
        type: 'gradient',
        name: 'dark.text.default.accent-gradient',
        tags: ['dark', 'text', 'default', 'accent-gradient'],
        displayName: 'textAccentGradient',
        description: 'Акцентный цвет с градиентом',
        enabled: false,
    },
    {
        type: 'gradient',
        name: 'dark.text.default.accent-minor-gradient',
        tags: ['dark', 'text', 'default', 'accent-minor-gradient'],
        displayName: 'textAccentMinorGradient',
        description: 'Акцентный минорный цвет с градиентом',
        enabled: false,
    },
    {
        type: 'gradient',
        name: 'dark.text.default.promo-gradient',
        tags: ['dark', 'text', 'default', 'promo-gradient'],
        displayName: 'textPromoGradient',
        description: 'Промо цвет с градиентом',
        enabled: false,
    },
    {
        type: 'gradient',
        name: 'dark.text.default.promo-minor-gradient',
        tags: ['dark', 'text', 'default', 'promo-minor-gradient'],
        displayName: 'textPromoMinorGradient',
        description: 'Минорный промо цвет с градиентом',
        enabled: false,
    },
    {
        type: 'gradient',
        name: 'dark.text.on-dark.accent-gradient',
        tags: ['dark', 'text', 'on-dark', 'accent-gradient'],
        displayName: 'onDarkTextAccentGradient',
        description: 'Акцентный цвет с градиентом на темном фоне',
        enabled: false,
    },
    {
        type: 'gradient',
        name: 'dark.text.on-dark.accent-minor-gradient',
        tags: ['dark', 'text', 'on-dark', 'accent-minor-gradient'],
        displayName: 'onDarkTextAccentMinorGradient',
        description: 'Акцентный минорный цвет с градиентом на темном фоне',
        enabled: false,
    },
    {
        type: 'gradient',
        name: 'dark.text.on-dark.promo-gradient',
        tags: ['dark', 'text', 'on-dark', 'promo-gradient'],
        displayName: 'onDarkTextPromoGradient',
        description: 'Промо цвет на темном фоне с градиентом',
        enabled: false,
    },
    {
        type: 'gradient',
        name: 'dark.text.on-dark.promo-minor-gradient',
        tags: ['dark', 'text', 'on-dark', 'promo-minor-gradient'],
        displayName: 'onDarkTextPromoMinorGradient',
        description: 'Минорный промо цвет на темном фоне с градиентом',
        enabled: false,
    },
    {
        type: 'gradient',
        name: 'dark.text.on-light.accent-gradient',
        tags: ['dark', 'text', 'on-light', 'accent-gradient'],
        displayName: 'onLightTextAccentGradient',
        description: 'Акцентный цвет с градиентом на светлом фоне',
        enabled: false,
    },
    {
        type: 'gradient',
        name: 'dark.text.on-light.accent-minor-gradient',
        tags: ['dark', 'text', 'on-light', 'accent-minor-gradient'],
        displayName: 'onLightTextAccentMinorGradient',
        description: 'Акцентный минорный цвет с градиентом на светлом фоне',
        enabled: false,
    },
    {
        type: 'gradient',
        name: 'dark.text.on-light.promo-gradient',
        tags: ['dark', 'text', 'on-light', 'promo-gradient'],
        displayName: 'onLightTextPromoGradient',
        description: 'Промо цвет на светлом фоне с градиентом',
        enabled: false,
    },
    {
        type: 'gradient',
        name: 'dark.text.on-light.promo-minor-gradient',
        tags: ['dark', 'text', 'on-light', 'promo-minor-gradient'],
        displayName: 'onLightTextPromoMinorGradient',
        description: 'Минорный промо цвет на светлом фоне с градиентом',
        enabled: false,
    },
    {
        type: 'gradient',
        name: 'dark.text.inverse.accent-gradient',
        tags: ['dark', 'text', 'inverse', 'accent-gradient'],
        displayName: 'inverseTextAccentGradient',
        description: 'Инвертированный акцентный цвет с градиентом',
        enabled: false,
    },
    {
        type: 'gradient',
        name: 'dark.text.inverse.accent-minor-gradient',
        tags: ['dark', 'text', 'inverse', 'accent-minor-gradient'],
        displayName: 'inverseTextAccentMinorGradient',
        description: 'Инвертированный акцентный минорный цвет с градиентом',
        enabled: false,
    },
    {
        type: 'gradient',
        name: 'dark.text.inverse.promo-gradient',
        tags: ['dark', 'text', 'inverse', 'promo-gradient'],
        displayName: 'inverseTextPromoGradient',
        description: 'Инвертированный промо цвет с градиентом',
        enabled: false,
    },
    {
        type: 'gradient',
        name: 'dark.text.inverse.promo-minor-gradient',
        tags: ['dark', 'text', 'inverse', 'promo-minor-gradient'],
        displayName: 'inverseTextPromoMinorGradient',
        description: 'Инвертированный минорный промо цвет с градиентом',
        enabled: false,
    },
    {
        type: 'gradient',
        name: 'dark.surface.default.accent-gradient',
        tags: ['dark', 'surface', 'default', 'accent-gradient'],
        displayName: 'surfaceAccentGradient',
        description: 'Акцентный фон поверхности/контрола с градиентом',
        enabled: false,
    },
    {
        type: 'gradient',
        name: 'dark.surface.default.accent-minor-gradient',
        tags: ['dark', 'surface', 'default', 'accent-minor-gradient'],
        displayName: 'surfaceAccentMinorGradient',
        description: 'Акцентный минорный фон поверхности/контрола с градиентом',
        enabled: false,
    },
    {
        type: 'gradient',
        name: 'dark.surface.default.transparent-accent-gradient',
        tags: ['dark', 'surface', 'default', 'transparent-accent-gradient'],
        displayName: 'surfaceTransparentAccentGradient',
        description: 'Прозрачный акцентный фон поверхности/контрола с градиентом',
        enabled: false,
    },
    {
        type: 'gradient',
        name: 'dark.surface.default.promo-gradient',
        tags: ['dark', 'surface', 'default', 'promo-gradient'],
        displayName: 'surfacePromoGradient',
        description: 'Промо фон поверхности/контрола с градиентом',
        enabled: false,
    },
    {
        type: 'gradient',
        name: 'dark.surface.default.promo-minor-gradient',
        tags: ['dark', 'surface', 'default', 'promo-minor-gradient'],
        displayName: 'surfacePromoMinorGradient',
        description: 'Минорный промо фон поверхности/контрола с градиентом',
        enabled: false,
    },
    {
        type: 'gradient',
        name: 'dark.surface.default.transparent-promo-gradient',
        tags: ['dark', 'surface', 'default', 'transparent-promo-gradient'],
        displayName: 'surfaceTransparentPromoGradient',
        description: 'Прозрачный промо фон поверхности/контрола с градиентом',
        enabled: false,
    },
    {
        type: 'gradient',
        name: 'dark.surface.on-dark.accent-gradient',
        tags: ['dark', 'surface', 'on-dark', 'accent-gradient'],
        displayName: 'onDarkSurfaceAccentGradient',
        description: 'Акцентный фон поверхности/контрола с градиентом на темном фоне',
        enabled: false,
    },
    {
        type: 'gradient',
        name: 'dark.surface.on-dark.accent-minor-gradient',
        tags: ['dark', 'surface', 'on-dark', 'accent-minor-gradient'],
        displayName: 'onDarkSurfaceAccentMinorGradient',
        description: 'Акцентный минорный фон поверхности/контрола с градиентом на темном фоне',
        enabled: false,
    },
    {
        type: 'gradient',
        name: 'dark.surface.on-dark.transparent-accent-gradient',
        tags: ['dark', 'surface', 'on-dark', 'transparent-accent-gradient'],
        displayName: 'onDarkSurfaceTransparentAccentGradient',
        description: 'Прозрачный акцентный фон поверхности/контрола с градиентом на темном фоне',
        enabled: false,
    },
    {
        type: 'gradient',
        name: 'dark.surface.on-dark.promo-gradient',
        tags: ['dark', 'surface', 'on-dark', 'promo-gradient'],
        displayName: 'onDarkSurfacePromoGradient',
        description: 'Промо фон поверхности/контрола с градиентом на темном фоне',
        enabled: false,
    },
    {
        type: 'gradient',
        name: 'dark.surface.on-dark.promo-minor-gradient',
        tags: ['dark', 'surface', 'on-dark', 'promo-minor-gradient'],
        displayName: 'onDarkSurfacePromoMinorGradient',
        description: 'Минорный промо фон поверхности/контрола с градиентом на темном фоне',
        enabled: false,
    },
    {
        type: 'gradient',
        name: 'dark.surface.on-dark.transparent-promo-gradient',
        tags: ['dark', 'surface', 'on-dark', 'transparent-promo-gradient'],
        displayName: 'onDarkSurfaceTransparentPromoGradient',
        description: 'Прозрачный промо фон поверхности/контрола с градиентом на темном фоне',
        enabled: false,
    },
    {
        type: 'gradient',
        name: 'dark.surface.on-light.accent-gradient',
        tags: ['dark', 'surface', 'on-light', 'accent-gradient'],
        displayName: 'onLightSurfaceAccentGradient',
        description: 'Акцентный фон поверхности/контрола с градиентом на светлом фоне',
        enabled: false,
    },
    {
        type: 'gradient',
        name: 'dark.surface.on-light.accent-minor-gradient',
        tags: ['dark', 'surface', 'on-light', 'accent-minor-gradient'],
        displayName: 'onLightSurfaceAccentMinorGradient',
        description: 'Акцентный минорный фон поверхности/контрола с градиентом на светлом фоне',
        enabled: false,
    },
    {
        type: 'gradient',
        name: 'dark.surface.on-light.transparent-accent-gradient',
        tags: ['dark', 'surface', 'on-light', 'transparent-accent-gradient'],
        displayName: 'onLightSurfaceTransparentAccentGradient',
        description: 'Прозрачный акцентный фон поверхности/контрола с градиентом на светлом фоне',
        enabled: false,
    },
    {
        type: 'gradient',
        name: 'dark.surface.on-light.promo-gradient',
        tags: ['dark', 'surface', 'on-light', 'promo-gradient'],
        displayName: 'onLightSurfacePromoGradient',
        description: 'Промо фон поверхности/контрола с градиентом на светлом фоне',
        enabled: false,
    },
    {
        type: 'gradient',
        name: 'dark.surface.on-light.promo-minor-gradient',
        tags: ['dark', 'surface', 'on-light', 'promo-minor-gradient'],
        displayName: 'onLightSurfacePromoMinorGradient',
        description: 'Минорный промо фон поверхности/контрола с градиентом на светлом фоне',
        enabled: false,
    },
    {
        type: 'gradient',
        name: 'dark.surface.on-light.transparent-promo-gradient',
        tags: ['dark', 'surface', 'on-light', 'transparent-promo-gradient'],
        displayName: 'onLightSurfaceTransparentPromoGradient',
        description: 'Прозрачный промо фон поверхности/контрола с градиентом на светлом фоне',
        enabled: false,
    },
    {
        type: 'gradient',
        name: 'dark.surface.inverse.accent-gradient',
        tags: ['dark', 'surface', 'inverse', 'accent-gradient'],
        displayName: 'inverseSurfaceAccentGradient',
        description: 'Инвертированный акцентный фон поверхности/контрола с градиентом',
        enabled: false,
    },
    {
        type: 'gradient',
        name: 'dark.surface.inverse.accent-minor-gradient',
        tags: ['dark', 'surface', 'inverse', 'accent-minor-gradient'],
        displayName: 'inverseSurfaceAccentMinorGradient',
        description: 'Инвертированный акцентный минорный фон поверхности/контрола с градиентом',
        enabled: false,
    },
    {
        type: 'gradient',
        name: 'dark.surface.inverse.transparent-accent-gradient',
        tags: ['dark', 'surface', 'inverse', 'transparent-accent-gradient'],
        displayName: 'inverseSurfaceTransparentAccentGradient',
        description: 'Прозрачный инвертированный акцентный фон поверхности/контрола с градиентом',
        enabled: false,
    },
    {
        type: 'gradient',
        name: 'dark.surface.inverse.promo-gradient',
        tags: ['dark', 'surface', 'inverse', 'promo-gradient'],
        displayName: 'inverseSurfacePromoGradient',
        description: 'Инвертированный промо фон поверхности/контрола с градиентом',
        enabled: false,
    },
    {
        type: 'gradient',
        name: 'dark.surface.inverse.promo-minor-gradient',
        tags: ['dark', 'surface', 'inverse', 'promo-minor-gradient'],
        displayName: 'inverseSurfacePromoMinorGradient',
        description: 'Инвертированный минорный промо фон поверхности/контрола с градиентом',
        enabled: false,
    },
    {
        type: 'gradient',
        name: 'dark.surface.inverse.transparent-promo-gradient',
        tags: ['dark', 'surface', 'inverse', 'transparent-promo-gradient'],
        displayName: 'inverseSurfaceTransparentPromoGradient',
        description: 'Инвертированный прозрачный промо фон поверхности/контрола с градиентом',
        enabled: false,
    },
    {
        type: 'gradient',
        name: 'dark.outline.default.accent-gradient',
        tags: ['dark', 'outline', 'default', 'accent-gradient'],
        displayName: 'outlineAccentGradient',
        description: 'Акцентный цвет обводки с градиентом',
        enabled: false,
    },
    {
        type: 'gradient',
        name: 'dark.outline.default.accent-minor-gradient',
        tags: ['dark', 'outline', 'default', 'accent-minor-gradient'],
        displayName: 'outlineAccentMinorGradient',
        description: 'Акцентный минорный цвет обводки с градиентом',
        enabled: false,
    },
    {
        type: 'gradient',
        name: 'dark.outline.default.transparent-accent-gradient',
        tags: ['dark', 'outline', 'default', 'transparent-accent-gradient'],
        displayName: 'outlineTransparentAccentGradient',
        description: 'Прозрачный акцентный цвет обводки с градиентом',
        enabled: false,
    },
    {
        type: 'gradient',
        name: 'dark.outline.default.promo-gradient',
        tags: ['dark', 'outline', 'default', 'promo-gradient'],
        displayName: 'outlinePromoGradient',
        description: 'Промо цвет обводки с градиентом',
        enabled: false,
    },
    {
        type: 'gradient',
        name: 'dark.outline.default.promo-minor-gradient',
        tags: ['dark', 'outline', 'default', 'promo-minor-gradient'],
        displayName: 'outlinePromoMinorGradient',
        description: 'Минорный промо цвет обводки с градиентом',
        enabled: false,
    },
    {
        type: 'gradient',
        name: 'dark.outline.on-dark.accent-gradient',
        tags: ['dark', 'outline', 'on-dark', 'accent-gradient'],
        displayName: 'onDarkOutlineAccentGradient',
        description: 'Акцентный цвет обводки с градиентом на темном фоне',
        enabled: false,
    },
    {
        type: 'gradient',
        name: 'dark.outline.on-dark.accent-minor-gradient',
        tags: ['dark', 'outline', 'on-dark', 'accent-minor-gradient'],
        displayName: 'onDarkOutlineAccentMinorGradient',
        description: 'Акцентный минорный цвет обводки с градиентом на темном фоне',
        enabled: false,
    },
    {
        type: 'gradient',
        name: 'dark.outline.on-dark.transparent-accent-gradient',
        tags: ['dark', 'outline', 'on-dark', 'transparent-accent-gradient'],
        displayName: 'onDarkOutlineTransparentAccentGradient',
        description: 'Прозрачный акцентный цвет обводки с градиентом на темном фоне',
        enabled: false,
    },
    {
        type: 'gradient',
        name: 'dark.outline.on-dark.promo-gradient',
        tags: ['dark', 'outline', 'on-dark', 'promo-gradient'],
        displayName: 'onDarkOutlinePromoGradient',
        description: 'Промо цвет обводки с градиентом на темном фоне',
        enabled: false,
    },
    {
        type: 'gradient',
        name: 'dark.outline.on-dark.promo-minor-gradient',
        tags: ['dark', 'outline', 'on-dark', 'promo-minor-gradient'],
        displayName: 'onDarkOutlinePromoMinorGradient',
        description: 'Минорный промо цвет обводки с градиентом на темном фоне',
        enabled: false,
    },
    {
        type: 'gradient',
        name: 'dark.outline.on-light.accent-gradient',
        tags: ['dark', 'outline', 'on-light', 'accent-gradient'],
        displayName: 'onLightOutlineAccentGradient',
        description: 'Акцентный цвет обводки с градиентом на светлом фоне',
        enabled: false,
    },
    {
        type: 'gradient',
        name: 'dark.outline.on-light.accent-minor-gradient',
        tags: ['dark', 'outline', 'on-light', 'accent-minor-gradient'],
        displayName: 'onLightOutlineAccentMinorGradient',
        description: 'Акцентный минорный цвет обводки с градиентом на светлом фоне',
        enabled: false,
    },
    {
        type: 'gradient',
        name: 'dark.outline.on-light.transparent-accent-gradient',
        tags: ['dark', 'outline', 'on-light', 'transparent-accent-gradient'],
        displayName: 'onLightOutlineTransparentAccentGradient',
        description: 'Прозрачный акцентный цвет обводки с градиентом на светлом фоне',
        enabled: false,
    },
    {
        type: 'gradient',
        name: 'dark.outline.on-light.promo-gradient',
        tags: ['dark', 'outline', 'on-light', 'promo-gradient'],
        displayName: 'onLightOutlinePromoGradient',
        description: 'Промо цвет обводки с градиентом на светлом фоне',
        enabled: false,
    },
    {
        type: 'gradient',
        name: 'dark.outline.on-light.promo-minor-gradient',
        tags: ['dark', 'outline', 'on-light', 'promo-minor-gradient'],
        displayName: 'onLightOutlinePromoMinorGradient',
        description: 'Минорный промо цвет обводки с градиентом на светлом фоне',
        enabled: false,
    },
    {
        type: 'gradient',
        name: 'dark.outline.inverse.accent-gradient',
        tags: ['dark', 'outline', 'inverse', 'accent-gradient'],
        displayName: 'inverseOutlineAccentGradient',
        description: 'Инвертированный акцентный цвет обводки с градиентом',
        enabled: false,
    },
    {
        type: 'gradient',
        name: 'dark.outline.inverse.accent-minor-gradient',
        tags: ['dark', 'outline', 'inverse', 'accent-minor-gradient'],
        displayName: 'inverseOutlineAccentMinorGradient',
        description: 'Инвертированный акцентный минорный цвет обводки с градиентом',
        enabled: false,
    },
    {
        type: 'gradient',
        name: 'dark.outline.inverse.transparent-accent-gradient',
        tags: ['dark', 'outline', 'inverse', 'transparent-accent-gradient'],
        displayName: 'inverseOutlineTransparentAccentGradient',
        description: 'Прозрачный инвертированный акцентный цвет обводки с градиентом',
        enabled: false,
    },
    {
        type: 'gradient',
        name: 'dark.outline.inverse.promo-gradient',
        tags: ['dark', 'outline', 'inverse', 'promo-gradient'],
        displayName: 'inverseOutlinePromoGradient',
        description: 'Инвертированный промо цвет обводки с градиентом',
        enabled: false,
    },
    {
        type: 'gradient',
        name: 'dark.outline.inverse.promo-minor-gradient',
        tags: ['dark', 'outline', 'inverse', 'promo-minor-gradient'],
        displayName: 'inverseOutlinePromoMinorGradient',
        description: 'Инвертированный минорный промо цвет обводки с градиентом',
        enabled: false,
    },
    {
        type: 'gradient',
        name: 'light.text.default.accent-gradient',
        tags: ['light', 'text', 'default', 'accent-gradient'],
        displayName: 'textAccentGradient',
        description: 'Акцентный цвет с градиентом',
        enabled: false,
    },
    {
        type: 'gradient',
        name: 'light.text.default.accent-minor-gradient',
        tags: ['light', 'text', 'default', 'accent-minor-gradient'],
        displayName: 'textAccentMinorGradient',
        description: 'Акцентный минорный цвет с градиентом',
        enabled: false,
    },
    {
        type: 'gradient',
        name: 'light.text.default.promo-gradient',
        tags: ['light', 'text', 'default', 'promo-gradient'],
        displayName: 'textPromoGradient',
        description: 'Промо цвет с градиентом',
        enabled: false,
    },
    {
        type: 'gradient',
        name: 'light.text.default.promo-minor-gradient',
        tags: ['light', 'text', 'default', 'promo-minor-gradient'],
        displayName: 'textPromoMinorGradient',
        description: 'Минорный промо цвет с градиентом',
        enabled: false,
    },
    {
        type: 'gradient',
        name: 'light.text.on-dark.accent-gradient',
        tags: ['light', 'text', 'on-dark', 'accent-gradient'],
        displayName: 'onDarkTextAccentGradient',
        description: 'Акцентный цвет с градиентом на темном фоне',
        enabled: false,
    },
    {
        type: 'gradient',
        name: 'light.text.on-dark.accent-minor-gradient',
        tags: ['light', 'text', 'on-dark', 'accent-minor-gradient'],
        displayName: 'onDarkTextAccentMinorGradient',
        description: 'Акцентный минорный цвет с градиентом на темном фоне',
        enabled: false,
    },
    {
        type: 'gradient',
        name: 'light.text.on-dark.promo-gradient',
        tags: ['light', 'text', 'on-dark', 'promo-gradient'],
        displayName: 'onDarkTextPromoGradient',
        description: 'Промо цвет на темном фоне с градиентом',
        enabled: false,
    },
    {
        type: 'gradient',
        name: 'light.text.on-dark.promo-minor-gradient',
        tags: ['light', 'text', 'on-dark', 'promo-minor-gradient'],
        displayName: 'onDarkTextPromoMinorGradient',
        description: 'Минорный промо цвет на темном фоне с градиентом',
        enabled: false,
    },
    {
        type: 'gradient',
        name: 'light.text.on-light.accent-gradient',
        tags: ['light', 'text', 'on-light', 'accent-gradient'],
        displayName: 'onLightTextAccentGradient',
        description: 'Акцентный цвет с градиентом на светлом фоне',
        enabled: false,
    },
    {
        type: 'gradient',
        name: 'light.text.on-light.accent-minor-gradient',
        tags: ['light', 'text', 'on-light', 'accent-minor-gradient'],
        displayName: 'onLightTextAccentMinorGradient',
        description: 'Акцентный минорный цвет с градиентом на светлом фоне',
        enabled: false,
    },
    {
        type: 'gradient',
        name: 'light.text.on-light.promo-gradient',
        tags: ['light', 'text', 'on-light', 'promo-gradient'],
        displayName: 'onLightTextPromoGradient',
        description: 'Промо цвет на светлом фоне с градиентом',
        enabled: false,
    },
    {
        type: 'gradient',
        name: 'light.text.on-light.promo-minor-gradient',
        tags: ['light', 'text', 'on-light', 'promo-minor-gradient'],
        displayName: 'onLightTextPromoMinorGradient',
        description: 'Минорный промо цвет на светлом фоне с градиентом',
        enabled: false,
    },
    {
        type: 'gradient',
        name: 'light.text.inverse.accent-gradient',
        tags: ['light', 'text', 'inverse', 'accent-gradient'],
        displayName: 'inverseTextAccentGradient',
        description: 'Инвертированный акцентный цвет с градиентом',
        enabled: false,
    },
    {
        type: 'gradient',
        name: 'light.text.inverse.accent-minor-gradient',
        tags: ['light', 'text', 'inverse', 'accent-minor-gradient'],
        displayName: 'inverseTextAccentMinorGradient',
        description: 'Инвертированный акцентный минорный цвет с градиентом',
        enabled: false,
    },
    {
        type: 'gradient',
        name: 'light.text.inverse.promo-gradient',
        tags: ['light', 'text', 'inverse', 'promo-gradient'],
        displayName: 'inverseTextPromoGradient',
        description: 'Инвертированный промо цвет с градиентом',
        enabled: false,
    },
    {
        type: 'gradient',
        name: 'light.text.inverse.promo-minor-gradient',
        tags: ['light', 'text', 'inverse', 'promo-minor-gradient'],
        displayName: 'inverseTextPromoMinorGradient',
        description: 'Инвертированный минорный промо цвет с градиентом',
        enabled: false,
    },
    {
        type: 'gradient',
        name: 'light.surface.default.accent-gradient',
        tags: ['light', 'surface', 'default', 'accent-gradient'],
        displayName: 'surfaceAccentGradient',
        description: 'Акцентный фон поверхности/контрола с градиентом',
        enabled: false,
    },
    {
        type: 'gradient',
        name: 'light.surface.default.accent-minor-gradient',
        tags: ['light', 'surface', 'default', 'accent-minor-gradient'],
        displayName: 'surfaceAccentMinorGradient',
        description: 'Акцентный минорный фон поверхности/контрола с градиентом',
        enabled: false,
    },
    {
        type: 'gradient',
        name: 'light.surface.default.transparent-accent-gradient',
        tags: ['light', 'surface', 'default', 'transparent-accent-gradient'],
        displayName: 'surfaceTransparentAccentGradient',
        description: 'Прозрачный акцентный фон поверхности/контрола с градиентом',
        enabled: false,
    },
    {
        type: 'gradient',
        name: 'light.surface.default.promo-gradient',
        tags: ['light', 'surface', 'default', 'promo-gradient'],
        displayName: 'surfacePromoGradient',
        description: 'Промо фон поверхности/контрола с градиентом',
        enabled: false,
    },
    {
        type: 'gradient',
        name: 'light.surface.default.promo-minor-gradient',
        tags: ['light', 'surface', 'default', 'promo-minor-gradient'],
        displayName: 'surfacePromoMinorGradient',
        description: 'Минорный промо фон поверхности/контрола с градиентом',
        enabled: false,
    },
    {
        type: 'gradient',
        name: 'light.surface.default.transparent-promo-gradient',
        tags: ['light', 'surface', 'default', 'transparent-promo-gradient'],
        displayName: 'surfaceTransparentPromoGradient',
        description: 'Прозрачный промо фон поверхности/контрола с градиентом',
        enabled: false,
    },
    {
        type: 'gradient',
        name: 'light.surface.on-dark.accent-gradient',
        tags: ['light', 'surface', 'on-dark', 'accent-gradient'],
        displayName: 'onDarkSurfaceAccentGradient',
        description: 'Акцентный фон поверхности/контрола с градиентом на темном фоне',
        enabled: false,
    },
    {
        type: 'gradient',
        name: 'light.surface.on-dark.accent-minor-gradient',
        tags: ['light', 'surface', 'on-dark', 'accent-minor-gradient'],
        displayName: 'onDarkSurfaceAccentMinorGradient',
        description: 'Акцентный минорный фон поверхности/контрола с градиентом на темном фоне',
        enabled: false,
    },
    {
        type: 'gradient',
        name: 'light.surface.on-dark.transparent-accent-gradient',
        tags: ['light', 'surface', 'on-dark', 'transparent-accent-gradient'],
        displayName: 'onDarkSurfaceTransparentAccentGradient',
        description: 'Прозрачный акцентный фон поверхности/контрола с градиентом на темном фоне',
        enabled: false,
    },
    {
        type: 'gradient',
        name: 'light.surface.on-dark.promo-gradient',
        tags: ['light', 'surface', 'on-dark', 'promo-gradient'],
        displayName: 'onDarkSurfacePromoGradient',
        description: 'Промо фон поверхности/контрола с градиентом на темном фоне',
        enabled: false,
    },
    {
        type: 'gradient',
        name: 'light.surface.on-dark.promo-minor-gradient',
        tags: ['light', 'surface', 'on-dark', 'promo-minor-gradient'],
        displayName: 'onDarkSurfacePromoMinorGradient',
        description: 'Минорный промо фон поверхности/контрола с градиентом на темном фоне',
        enabled: false,
    },
    {
        type: 'gradient',
        name: 'light.surface.on-dark.transparent-promo-gradient',
        tags: ['light', 'surface', 'on-dark', 'transparent-promo-gradient'],
        displayName: 'onDarkSurfaceTransparentPromoGradient',
        description: 'Прозрачный промо фон поверхности/контрола с градиентом на темном фоне',
        enabled: false,
    },
    {
        type: 'gradient',
        name: 'light.surface.on-light.accent-gradient',
        tags: ['light', 'surface', 'on-light', 'accent-gradient'],
        displayName: 'onLightSurfaceAccentGradient',
        description: 'Акцентный фон поверхности/контрола с градиентом на светлом фоне',
        enabled: false,
    },
    {
        type: 'gradient',
        name: 'light.surface.on-light.accent-minor-gradient',
        tags: ['light', 'surface', 'on-light', 'accent-minor-gradient'],
        displayName: 'onLightSurfaceAccentMinorGradient',
        description: 'Акцентный минорный фон поверхности/контрола с градиентом на светлом фоне',
        enabled: false,
    },
    {
        type: 'gradient',
        name: 'light.surface.on-light.transparent-accent-gradient',
        tags: ['light', 'surface', 'on-light', 'transparent-accent-gradient'],
        displayName: 'onLightSurfaceTransparentAccentGradient',
        description: 'Прозрачный акцентный фон поверхности/контрола с градиентом на светлом фоне',
        enabled: false,
    },
    {
        type: 'gradient',
        name: 'light.surface.on-light.promo-gradient',
        tags: ['light', 'surface', 'on-light', 'promo-gradient'],
        displayName: 'onLightSurfacePromoGradient',
        description: 'Промо фон поверхности/контрола с градиентом на светлом фоне',
        enabled: false,
    },
    {
        type: 'gradient',
        name: 'light.surface.on-light.promo-minor-gradient',
        tags: ['light', 'surface', 'on-light', 'promo-minor-gradient'],
        displayName: 'onLightSurfacePromoMinorGradient',
        description: 'Минорный промо фон поверхности/контрола с градиентом на светлом фоне',
        enabled: false,
    },
    {
        type: 'gradient',
        name: 'light.surface.on-light.transparent-promo-gradient',
        tags: ['light', 'surface', 'on-light', 'transparent-promo-gradient'],
        displayName: 'onLightSurfaceTransparentPromoGradient',
        description: 'Прозрачный промо фон поверхности/контрола с градиентом на светлом фоне',
        enabled: false,
    },
    {
        type: 'gradient',
        name: 'light.surface.inverse.accent-gradient',
        tags: ['light', 'surface', 'inverse', 'accent-gradient'],
        displayName: 'inverseSurfaceAccentGradient',
        description: 'Инвертированный акцентный фон поверхности/контрола с градиентом',
        enabled: false,
    },
    {
        type: 'gradient',
        name: 'light.surface.inverse.accent-minor-gradient',
        tags: ['light', 'surface', 'inverse', 'accent-minor-gradient'],
        displayName: 'inverseSurfaceAccentMinorGradient',
        description: 'Инвертированный акцентный минорный фон поверхности/контрола с градиентом',
        enabled: false,
    },
    {
        type: 'gradient',
        name: 'light.surface.inverse.transparent-accent-gradient',
        tags: ['light', 'surface', 'inverse', 'transparent-accent-gradient'],
        displayName: 'inverseSurfaceTransparentAccentGradient',
        description: 'Прозрачный инвертированный акцентный фон поверхности/контрола с градиентом',
        enabled: false,
    },
    {
        type: 'gradient',
        name: 'light.surface.inverse.promo-gradient',
        tags: ['light', 'surface', 'inverse', 'promo-gradient'],
        displayName: 'inverseSurfacePromoGradient',
        description: 'Инвертированный промо фон поверхности/контрола с градиентом',
        enabled: false,
    },
    {
        type: 'gradient',
        name: 'light.surface.inverse.promo-minor-gradient',
        tags: ['light', 'surface', 'inverse', 'promo-minor-gradient'],
        displayName: 'inverseSurfacePromoMinorGradient',
        description: 'Инвертированный минорный промо фон поверхности/контрола с градиентом',
        enabled: false,
    },
    {
        type: 'gradient',
        name: 'light.surface.inverse.transparent-promo-gradient',
        tags: ['light', 'surface', 'inverse', 'transparent-promo-gradient'],
        displayName: 'inverseSurfaceTransparentPromoGradient',
        description: 'Инвертированный прозрачный промо фон поверхности/контрола с градиентом',
        enabled: false,
    },
    {
        type: 'gradient',
        name: 'light.outline.default.accent-gradient',
        tags: ['light', 'outline', 'default', 'accent-gradient'],
        displayName: 'outlineAccentGradient',
        description: 'Акцентный цвет обводки с градиентом',
        enabled: false,
    },
    {
        type: 'gradient',
        name: 'light.outline.default.accent-minor-gradient',
        tags: ['light', 'outline', 'default', 'accent-minor-gradient'],
        displayName: 'outlineAccentMinorGradient',
        description: 'Акцентный минорный цвет обводки с градиентом',
        enabled: false,
    },
    {
        type: 'gradient',
        name: 'light.outline.default.transparent-accent-gradient',
        tags: ['light', 'outline', 'default', 'transparent-accent-gradient'],
        displayName: 'outlineTransparentAccentGradient',
        description: 'Прозрачный акцентный цвет обводки с градиентом',
        enabled: false,
    },
    {
        type: 'gradient',
        name: 'light.outline.default.promo-gradient',
        tags: ['light', 'outline', 'default', 'promo-gradient'],
        displayName: 'outlinePromoGradient',
        description: 'Промо цвет обводки с градиентом',
        enabled: false,
    },
    {
        type: 'gradient',
        name: 'light.outline.default.promo-minor-gradient',
        tags: ['light', 'outline', 'default', 'promo-minor-gradient'],
        displayName: 'outlinePromoMinorGradient',
        description: 'Минорный промо цвет обводки с градиентом',
        enabled: false,
    },
    {
        type: 'gradient',
        name: 'light.outline.on-dark.accent-gradient',
        tags: ['light', 'outline', 'on-dark', 'accent-gradient'],
        displayName: 'onDarkOutlineAccentGradient',
        description: 'Акцентный цвет обводки с градиентом на темном фоне',
        enabled: false,
    },
    {
        type: 'gradient',
        name: 'light.outline.on-dark.accent-minor-gradient',
        tags: ['light', 'outline', 'on-dark', 'accent-minor-gradient'],
        displayName: 'onDarkOutlineAccentMinorGradient',
        description: 'Акцентный минорный цвет обводки с градиентом на темном фоне',
        enabled: false,
    },
    {
        type: 'gradient',
        name: 'light.outline.on-dark.transparent-accent-gradient',
        tags: ['light', 'outline', 'on-dark', 'transparent-accent-gradient'],
        displayName: 'onDarkOutlineTransparentAccentGradient',
        description: 'Прозрачный акцентный цвет обводки с градиентом на темном фоне',
        enabled: false,
    },
    {
        type: 'gradient',
        name: 'light.outline.on-dark.promo-gradient',
        tags: ['light', 'outline', 'on-dark', 'promo-gradient'],
        displayName: 'onDarkOutlinePromoGradient',
        description: 'Промо цвет обводки с градиентом на темном фоне',
        enabled: false,
    },
    {
        type: 'gradient',
        name: 'light.outline.on-dark.promo-minor-gradient',
        tags: ['light', 'outline', 'on-dark', 'promo-minor-gradient'],
        displayName: 'onDarkOutlinePromoMinorGradient',
        description: 'Минорный промо цвет обводки с градиентом на темном фоне',
        enabled: false,
    },
    {
        type: 'gradient',
        name: 'light.outline.on-light.accent-gradient',
        tags: ['light', 'outline', 'on-light', 'accent-gradient'],
        displayName: 'onLightOutlineAccentGradient',
        description: 'Акцентный цвет обводки с градиентом на светлом фоне',
        enabled: false,
    },
    {
        type: 'gradient',
        name: 'light.outline.on-light.accent-minor-gradient',
        tags: ['light', 'outline', 'on-light', 'accent-minor-gradient'],
        displayName: 'onLightOutlineAccentMinorGradient',
        description: 'Акцентный минорный цвет обводки с градиентом на светлом фоне',
        enabled: false,
    },
    {
        type: 'gradient',
        name: 'light.outline.on-light.transparent-accent-gradient',
        tags: ['light', 'outline', 'on-light', 'transparent-accent-gradient'],
        displayName: 'onLightOutlineTransparentAccentGradient',
        description: 'Прозрачный акцентный цвет обводки с градиентом на светлом фоне',
        enabled: false,
    },
    {
        type: 'gradient',
        name: 'light.outline.on-light.promo-gradient',
        tags: ['light', 'outline', 'on-light', 'promo-gradient'],
        displayName: 'onLightOutlinePromoGradient',
        description: 'Промо цвет обводки с градиентом на светлом фоне',
        enabled: false,
    },
    {
        type: 'gradient',
        name: 'light.outline.on-light.promo-minor-gradient',
        tags: ['light', 'outline', 'on-light', 'promo-minor-gradient'],
        displayName: 'onLightOutlinePromoMinorGradient',
        description: 'Минорный промо цвет обводки с градиентом на светлом фоне',
        enabled: false,
    },
    {
        type: 'gradient',
        name: 'light.outline.inverse.accent-gradient',
        tags: ['light', 'outline', 'inverse', 'accent-gradient'],
        displayName: 'inverseOutlineAccentGradient',
        description: 'Инвертированный акцентный цвет обводки с градиентом',
        enabled: false,
    },
    {
        type: 'gradient',
        name: 'light.outline.inverse.accent-minor-gradient',
        tags: ['light', 'outline', 'inverse', 'accent-minor-gradient'],
        displayName: 'inverseOutlineAccentMinorGradient',
        description: 'Инвертированный акцентный минорный цвет обводки с градиентом',
        enabled: false,
    },
    {
        type: 'gradient',
        name: 'light.outline.inverse.transparent-accent-gradient',
        tags: ['light', 'outline', 'inverse', 'transparent-accent-gradient'],
        displayName: 'inverseOutlineTransparentAccentGradient',
        description: 'Прозрачный инвертированный акцентный цвет обводки с градиентом',
        enabled: false,
    },
    {
        type: 'gradient',
        name: 'light.outline.inverse.promo-gradient',
        tags: ['light', 'outline', 'inverse', 'promo-gradient'],
        displayName: 'inverseOutlinePromoGradient',
        description: 'Инвертированный промо цвет обводки с градиентом',
        enabled: false,
    },
    {
        type: 'gradient',
        name: 'light.outline.inverse.promo-minor-gradient',
        tags: ['light', 'outline', 'inverse', 'promo-minor-gradient'],
        displayName: 'inverseOutlinePromoMinorGradient',
        description: 'Инвертированный минорный промо цвет обводки с градиентом',
        enabled: false,
    },
];
