export const classes = {
    treeInverted: 'tree-inverted',
    treeItemFilled: 'tree-item-filled',
    treeItemPrimaryBackground: 'tree-item-primary-background',
    treeItemHasSelectedChildren: 'tree-item-has-selected-children',
    treeRadioMode: 'tree-radio-mode',
    treeLeafNode: 'tree-leaf-node',
    treeTightVariant: 'tree-tight-variant',
};

export const treeTokens = {
    arrowColor: '--plasma-tree-arrow-color',
    arrowColorHover: '--plasma-tree-arrow-color-hover',
    arrowColorActive: '--plasma-tree-arrow-color-active',
    color: '--plasma-tree-color',
    colorSelected: '--plasma-tree-color-selected',
    fontFamily: '--plasma-tree-font-family',
    fontSize: '--plasma-tree-font-size',
    fontStyle: '--plasma-tree-font-style',
    fontWeight: '--plasma-tree-font-weight',
    letterSpacing: '--plasma-tree-letter-spacing',
    lineHeight: '--plasma-tree-line-height',
    itemHeight: '--plasma-tree-item-height',
    itemTop: '--plasma-tree-item-top',
    itemBottom: '--plasma-tree-item-bottom',
    itemPadding: '--plasma-tree-item-padding',
    itemPaddingTight: '--plasma-tree-item-padding-tight',
    itemIndent: '--plasma-tree-item-indent',
    itemBorderRadius: '--plasma-tree-item-border-radius',
    iconFolderMargin: '--plasma-tree-icon-folder-margin',
    iconFolderColor: '--plasma-tree-icon-folder-color',
    switcherMargin: '--plasma-tree-switcher-margin',
    switcherMarginInverted: '--plasma-tree-switcher-margin-inverted',
    switcherSize: '--plasma-tree-switcher-size',
    checkboxSize: '--plasma-tree-checkbox-size',
    checkboxInnerSize: '--plasma-tree-checkbox-inner-size',
    checkboxBorderRadius: '--plasma-tree-checkbox-border-radius',
    checkboxMargin: '--plasma-tree-checkbox-margin',
    checkboxBorderColor: '--plasma-tree-checkbox-border-color',
    checkboxBackgroundColor: '--plasma-tree-checkbox-background-color',
    itemBackgroundExtraOffset: '--plasma-tree-item-background-extra-offset',
    itemBackgroundColorSelected: '--plasma-tree-item-background-color-selected',
    itemBackgroundColorPrimary: '--plasma-tree-item-background-color-primary',
    itemBackgroundColorHover: '--plasma-tree-item-background-color-hover',
    itemBackgroundColorActive: '--plasma-tree-item-background-color-active',
    itemDisabledOpacity: '--plasma-tree-item-disabled-opacity',
    itemDisabledColor: '--plasma-tree-item-disabled-color',
    itemDisabledBorderColor: '--plasma-tree-item-disabled-border-color',
    itemDraggableBorderColor: '--plasma-tree-item-draggable-border-color',
    itemDraggableLineColor: '--plasma-tree-item-draggable-line-color',
};
