export const classes = {
    dropdownItemIsFocused: 'dropdown-item-is-focused',
    dropdownItemIsDisabled: 'dropdown-item-is-disabled',
    dropdownItemIsActive: 'dropdown-item-is-active',
    comboboxTargetArrow: 'combobox-target-arrow',
    arrowInverse: 'arrow-inverse',
    textfieldTarget: 'combobox-textfield-target',
    selectChipIsFocused: 'combobox-chip-is-focused',
    selectWithoutBoxShadow: 'combobox-without-box-shadow',
    selectItemCheckbox: 'combobox-item-checkbox',
    selectSpinner: 'combobox-spinner',
    emptyStateWrapper: 'combobox-empty-state-wrapper',
};

export const tokens = {
    borderRadius: '--plasma-combobox-border-radius',
    padding: '--plasma-combobox-padding',
    margin: '--plasma-combobox-margin',
    focusOffset: '--plasma-combobox-focus-offset',

    fontFamily: '--plasma-combobox-font-family',
    fontSize: '--plasma-combobox-font-size',
    fontStyle: '--plasma-combobox-font-style',
    fontWeight: '--plasma-combobox-font-weight',
    fontLetterSpacing: '--plasma-combobox-font-letter-spacing',
    fontLineHeight: '--plasma-combobox-font-line-height',

    dropdownBorderColor: '--plasma-select-dropdown-border-color',
    dropdownBorderWidth: '--plasma-select-dropdown-border-width',

    itemHeight: '--plasma-combobox-item-height',
    itemBorderRadius: '--plasma-combobox-item-border-radius',
    itemPadding: '--plasma-combobox-item-padding',
    itemPaddingTight: '--plasma-combobox-item-padding-tight',
    itemIconSize: '--plasma-combobox-item-icon-size',
    itemIconSizeTight: '--plasma-combobox-item-icon-size-tight',
    itemIconMargin: '--plasma-combobox-item-icon-margin',
    itemBackgroundHover: '--plasma-combobox-item-background-hover',
    itemIconColor: '--plasma-combobox-item-icon-color',

    cellPadding: '--plasma-combobox-cell-padding',
    cellPaddingLeftContent: '--plasma-combobox-cell-padding-left-content',
    cellPaddingContent: '--plasma-combobox-cell-padding-content',
    cellPaddingRightContent: '--plasma-combobox-cell-padding-right-content',
    cellTextboxGap: '--plasma-combobox-cell-textbox-gap',
    cellGap: '--plasma-combobox-cell-gap',
    cellTitleFontFamily: '--plasma-combobox-cell-title-font-family',
    cellTitleFontSize: '--plasma-combobox-cell-title-font-size',
    cellTitleFontStyle: '--plasma-combobox-cell-title-font-style',
    cellTitleFontWeight: '--plasma-combobox-cell-title-font-weight',
    cellTitleLetterSpacing: '--plasma-combobox-cell-title-letter-spacing',
    cellTitleLineHeight: '--plasma-combobox-cell-title-line-height',

    checkboxTriggerSize: '--plasma-combobox-checkbox-trigger-size',
    checkboxTriggerSizeTight: '--plasma-combobox-checkbox-trigger-size-tight',
    checkboxTriggerBorderRadius: '--plasma-combobox-checkbox-trigger-border-radius',
    checkboxTriggerBorderRadiusTight: '--plasma-combobox-checkbox-trigger-border-radius-tight',
    checkboxFillColor: '--plasma-combobox-checkbox-fill-color',
    checkboxIconColor: '--plasma-combobox-checkbox-icon-color',
    checkboxTriggerBorderColor: '--plasma-combobox-checkbox-trigger-border-color',
    checkboxTriggerBorderCheckedColor: '--plasma-combobox-checkbox-trigger-border-checked-color',
    checkboxTriggerBorderWidth: '--plasma-combobox-checkbox-trigger-border-width',

    indicatorSize: '--plasma-combobox-indicator-size',

    // Токены для TextField
    textFieldColor: '--plasma-combobox-new-textfield-color',
    textFieldClearColor: '--plasma-combobox-new-textfield-clear-color',

    textFieldBackgroundColor: '--plasma-combobox-new-textfield-background-color',
    textFieldBackgroundColorHover: '--plasma-combobox-new-textfield-background-color-hover',
    textFieldBackgroundColorFocus: '--plasma-combobox-new-textfield-background-color-focus',

    textFieldBorderColor: '--plasma-combobox-new-textfield-border-color',
    textFieldBorderColorHover: '--plasma-combobox-new-textfield-border-color-hover',
    textFieldBorderColorFocus: '--plasma-combobox-new-textfield-border-color-focus',

    textFieldColorReadOnly: '--plasma-combobox-new-textfield-color-readonly',
    textFieldBackgroundColorReadOnly: '--plasma-combobox-new-textfield-bg-color-readonly',
    textFieldBorderColorReadOnly: '--plasma-combobox-new-textfield-border-color-readonly',
    textFieldPlaceholderColorReadOnly: '--plasma-combobox-new-textfield-placeholder-color-readonly',

    textFieldCaretColor: '--plasma-combobox-new-textfield-caret-color',
    textFieldPlaceholderColor: '--plasma-combobox-new-textfield-placeholder-color',
    textFieldPlaceholderColorFocus: '--plasma-combobox-new-textfield-placeholder-color-focus',
    textFieldClearPlaceholderColor: '--plasma-combobox-new-textfield-clear-placeholder-color',
    textFieldClearPlaceholderColorFocus: '--plasma-combobox-new-textfield-clear-placeholder-color-focus',
    textFieldOptionalColor: '--plasma-combobox-new-textfield-optional-color',

    textFieldHeight: '--plasma-combobox-new-textfield-height',
    textFieldBorderWidth: '--plasma-combobox-new-textfield-border-width',
    textFieldBorderRadius: '--plasma-combobox-new-textfield-border-radius',

    textFieldPadding: '--plasma-combobox-new-textfield-padding',
    textFieldPaddingWithChips: '--plasma-combobox-new-textfield-padding-with-chips',

    textFieldLeftContentMargin: '--plasma-combobox-new-textfield-left-content-margin',
    textFieldRightContentMargin: '--plasma-combobox-new-textfield-right-content-margin',
    textFieldRightContentWithHintMargin: '--plasma-combobox-textfield-right-content-with-hint-margin',

    textFieldContentRightWrapperGap: '--plasma-combobox-textfield-content-right-wrapper-gap',
    textFieldContentRightWrapperMargin: '--plasma-combobox-textfield-content-right-wrapper-margin',

    textFieldFontFamily: '--plasma-combobox-new-textfield-font-family',
    textFieldFontStyle: '--plasma-combobox-new-textfield-font-style',
    textFieldFontSize: '--plasma-combobox-new-textfield-font-size',
    textFieldFontWeight: '--plasma-combobox-new-textfield-font-weight',
    textFieldLetterSpacing: '--plasma-combobox-new-textfield-letter-spacing',
    textFieldLineHeight: '--plasma-combobox-new-textfield-line-height',

    textFieldContentSlotColor: '--plasma-combobox-new-textfield-content-slot-color',
    textFieldContentSlotColorHover: '--plasma-combobox-new-textfield-content-slot-color-hover',
    textFieldContentSlotColorActive: '--plasma-combobox-new-textfield-content-slot-color-active',

    textFieldContentSlotRightColor: '--plasma-combobox-new-textfield-content-right-slot-color',
    textFieldContentSlotRightColorHover: '--plasma-combobox-new-textfield-content-right-slot-color-hover',
    textFieldContentSlotRightColorActive: '--plasma-combobox-new-textfield-content-right-slot-color-active',
    textFieldContentSlotRightOpacityReadOnly: '--plasma-combobox-new-textfield-content-right-slot-opacity-readonly',

    textFieldLabelColor: '--plasma-combobox-new-textfield-label-color',
    textFieldLabelColorReadOnly: '--plasma-combobox-new-textfield-label-color-readonly',
    textFieldLabelOffset: '--plasma-combobox-new-textfield-label-offset',
    textFieldClearLabelOffset: '--plasma-combobox-new-textfield-clear-label-offset',

    textFieldLabelFontFamily: '--plasma-combobox-new-textfield-label-font-family',
    textFieldLabelFontStyle: '--plasma-combobox-new-textfield-label-font-style',
    textFieldLabelFontSize: '--plasma-combobox-new-textfield-label-font-size',
    textFieldLabelFontWeight: '--plasma-combobox-new-textfield-label-font-weight',
    textFieldLabelLetterSpacing: '--plasma-combobox-new-textfield-label-letter-spacing',
    textFieldLabelLineHeight: '--plasma-combobox-new-textfield-label-line-height',

    textFieldLabelInnerFontFamily: '--plasma-combobox-new-textfield-placement_inner-label-font-family',
    textFieldLabelInnerFontStyle: '--plasma-combobox-new-textfield-placement_inner-label-font-style',
    textFieldLabelInnerFontSize: '--plasma-combobox-new-textfield-placement_inner-label-font-size',
    textFieldLabelInnerFontWeight: '--plasma-combobox-new-textfield-placement_inner-label-font-weight',
    textFieldLabelInnerLetterSpacing: '--plasma-combobox-new-textfield-placement_inner-label-letter-spacing',
    textFieldLabelInnerLineHeight: '--plasma-combobox-new-textfield-placement_inner-label-line-height',

    textFieldLabelInnerPadding: '--plasma-combobox-new-textfield-placement_inner-label-padding',
    textFieldContentLabelInnerPadding: '--plasma-combobox-new-textfield-placement_inner-content-padding',

    textFieldTitleCaptionColor: '--plasma-combobox-new-textfield-title-caption-color',
    textFieldTitleCaptionColorReadOnly: '--plasma-combobox-new-textfield-title-caption-color-readonly',
    textFieldTitleCaptionInnerLabelOffset: '--plasma-combobox-new-textfield-title-caption-label-inner-offset',

    textFieldTitleCaptionFontFamily: '--plasma-combobox-new-textfield-title-caption-font-family',
    textFieldTitleCaptionFontStyle: '--plasma-combobox-new-textfield-title-caption-font-style',
    textFieldTitleCaptionFontSize: '--plasma-combobox-new-textfield-title-caption-font-size',
    textFieldTitleCaptionFontWeight: '--plasma-combobox-new-textfield-title-caption-font-weight',
    textFieldTitleCaptionLetterSpacing: '--plasma-combobox-new-textfield-title-caption-letter-spacing',
    textFieldTitleCaptionLineHeight: '--plasma-combobox-new-textfield-title-caption-line-height',

    textFieldLeftHelperColor: '--plasma-combobox-new-textfield-left-helper-color',
    textFieldLeftHelperColorReadOnly: '--plasma-combobox-new-textfield-left-helper-color-readonly',
    textFieldLeftHelperOffset: '--plasma-combobox-new-textfield-left-helper-offset',

    textFieldLeftHelperFontFamily: '--plasma-combobox-new-textfield-left-helper-font-family',
    textFieldLeftHelperFontStyle: '--plasma-combobox-new-textfield-left-helper-font-style',
    textFieldLeftHelperFontSize: '--plasma-combobox-new-textfield-left-helper-font-size',
    textFieldLeftHelperFontWeight: '--plasma-combobox-new-textfield-left-helper-font-weight',
    textFieldLeftHelperLetterSpacing: '--plasma-combobox-new-textfield-left-helper-letter-spacing',
    textFieldLeftHelperLineHeight: '--plasma-combobox-new-textfield-left-helper-line-height',

    textFieldTextBeforeColor: '--plasma-combobox-new-textfield-before-text-color',
    textFieldTextAfterColor: '--plasma-combobox-new-textfield-after-text-color',
    textFieldTextBeforeMargin: '--plasma-combobox-new-textfield-before-text-margin',
    textFieldTextAfterMargin: '--plasma-combobox-new-textfield-after-text-margin',

    textFieldDisabledOpacity: '--plasma-combobox-new-textfield-disabled-opacity',
    textFieldReadOnlyOpacity: '--plasma-combobox-new-textfield-readonly-opacity',

    /** Токены для tooltip */
    textFieldHintCustomIconTargetSize: '--plasma-combobox-textfield__hint-custom-icon-target-size',
    textFieldHintMargin: '--plasma-combobox-textfield__hint-margin',
    textFieldHintTargetSize: '--plasma-combobox-textfield__hint-target-size',
    textFieldHintIconColor: '--plasma-combobox-textfield__hint-icon-color',
    textFieldHintInnerLabelPlacementOffset: '--plasma-combobox-textfield__hint-inner-label-placement-offset',
    textFieldClearHintInnerLabelPlacementOffset: '--plasma-combobox-textfield__clear-hint-inner-label-placement-offset',

    textFieldTooltipBackgroundColor: '--plasma-combobox-textfield__tooltip-background-color',
    textFieldTooltipBoxShadow: '--plasma-combobox-textfield__tooltip-box-shadow',
    textFieldTooltipColor: '--plasma-combobox-textfield__tooltip-color',

    textFieldTooltipPaddingTop: '--plasma-combobox-textfield__tooltip-padding-top',
    textFieldTooltipPaddingRight: '--plasma-combobox-textfield__tooltip-padding-right',
    textFieldTooltipPaddingBottom: '--plasma-combobox-textfield__tooltip-padding-bottom',
    textFieldTooltipPaddingLeft: '--plasma-combobox-textfield__tooltip-padding-left',
    textFieldTooltipMinHeight: '--plasma-combobox-textfield__tooltip-min-height',
    textFieldTooltipBorderRadius: '--plasma-combobox-textfield__tooltip-border-radius',
    textFieldTooltipTextFontFamily: '--plasma-combobox-textfield__tooltip-text-font-family',
    textFieldTooltipTextFontSize: '--plasma-combobox-textfield__tooltip-text-font-size',
    textFieldTooltipTextFontStyle: '--plasma-combobox-textfield__tooltip-text-font-style',
    textFieldTooltipTextFontWeight: '--plasma-combobox-textfield__tooltip-text-font-weight',
    textFieldTooltipTextFontLetterSpacing: '--plasma-combobox-textfield__tooltip-text-font-letter-spacing',
    textFieldTooltipTextFontLineHeight: '--plasma-combobox-textfield__tooltip-text-font-line-height',
    textFieldTooltipContentLeftMargin: '--plasma-combobox-textfield__tooltip-content-left-margin',
    textFieldTooltipArrowMaskWidth: '--plasma-combobox-textfield__tooltip-arrow-mask-width',
    textFieldTooltipArrowMaskHeight: '--plasma-combobox-textfield__tooltip-arrow-mask-height',
    textFieldTooltipArrowMaskImage: '--plasma-combobox-textfield__tooltip-arrow-mask-image',
    textFieldTooltipArrowHeight: '--plasma-combobox-textfield__tooltip-arrow-height',
    textFieldTooltipArrowEdgeMargin: '--plasma-combobox-textfield__tooltip-arrow-edge-margin',
    textFieldTooltipArrowBackground: '--plasma-combobox-textfield__tooltip-arrow-background',

    textFieldChipHeight: '--plasma-combobox-new-textfield-chip-height',
    textFieldChipBorderRadius: '--plasma-combobox-new-textfield-chip-border-radius',
    textFieldChipGap: '--plasma-combobox-new-textfield-chip-gap',
    textFieldChipBackground: '--plasma-combobox-new-textfield--chip-background',
    textFieldChipColor: '--plasma-combobox-new-textfield-chip-color',
    textFieldChipBackgroundHover: '--plasma-combobox-new-textfield-chip-background-hover',
    textFieldChipColorHover: '--plasma-combobox-new-textfield-chip-color-hover',
    textFieldChipBackgroundReadOnly: '--plasma-combobox-new-textfield-chip-background-read-only',
    textFieldChipColorReadOnly: '--plasma-combobox-new-textfield-chip-color-read-only',
    textFieldChipBackgroundReadOnlyHover: '--plasma-combobox-new-textfield-chip-background-read-only-hover',
    textFieldChipColorReadOnlyHover: '--plasma-combobox-new-textfield-chip-color-read-only-hover',
    textFieldChipBackgroundActive: '--plasma-combobox-new-textfield-chip-background-active',
    textFieldChipColorActive: '--plasma-combobox-new-textfield-chip-color-active',
    textFieldChipCloseIconColor: '--plasma-combobox-new-textfield-chip-close-icons-color',
    textFieldChipOutlineSize: '--plasma-combobox-new-textfield-chip-outline-size',
    textFieldChipWidth: '--plasma-combobox-new-textfield-chip-width',
    textFieldChipPadding: '--plasma-combobox-new-textfield-chip-padding',
    textFieldChipCloseIconSize: '--plasma-combobox-new-textfield-chip-close-icon-size',
    textFieldChipFontFamily: '--plasma-combobox-new-textfield-chip-font-family',
    textFieldChipFontSize: '--plasma-combobox-new-textfield-chip-font-size',
    textFieldChipFontStyle: '--plasma-combobox-new-textfield-chip-font-style',
    textFieldChipFontWeight: '--plasma-combobox-new-textfield-chip-font-weight',
    textFieldChipLetterSpacing: '--plasma-combobox-new-textfield-chip-letter-spacing',
    textFieldChipLineHeight: '--plasma-combobox-new-textfield-chip-line-height',
    textFieldChipClearContentMarginLeft: '--plasma-combobox-new-textfield-chip-clear-content-margin-left',
    textFieldChipClearContentMarginRight: '--plasma-combobox-new-textfield-chip-clear-content-margin-right',
    textFieldChipOpacityReadonly: '--plasma-combobox-new-textfield-chip-opacity-readonly',

    textFieldFocusColor: '--plasma-combobox-new-textfield-focus-color',

    textFieldBoxShadow: '--plasma-select-textfield-box-shadow',

    textFieldIndicatorColor: '--plasma-combobox-new-textfield-indicator-color',
    textFieldIndicatorSizeInner: '--plasma-combobox-new-textfield-indicator-size-inner',
    textFieldIndicatorSizeOuter: '--plasma-combobox-new-textfield-indicator-size-outer',
    textFieldIndicatorLabelPlacementInner: '--plasma-combobox-new-textfield-indicator-placement-inner',
    textFieldIndicatorLabelPlacementOuter: '--plasma-combobox-new-textfield-indicator-placement-outer',
    textFieldIndicatorLabelPlacementInnerRight: '--plasma-combobox-new-textfield-indicator-placement-inner-right',
    textFieldIndicatorLabelPlacementOuterRight: '--plasma-combobox-new-textfield-indicator-placement-outer-right',
    textFieldClearIndicatorLabelPlacementInner: '--plasma-combobox-new-textfield-clear-indicator-placement-inner',
    textFieldClearIndicatorLabelPlacementInnerRight:
        '--plasma-combobox-new-textfield-clear-indicator-placement-inner-right',
    textFieldClearIndicatorHintInnerRight: '--plasma-combobox-new-textfield-clear-indicator-hint-placement-inner-right',

    // Токены для EmptyState
    emptyStatePadding: '--plasma-combobox-new-empty-state-padding',

    labelOffset: '--plasma-combobox-label-offset',

    innerLabelGap: '--plasma-combobox-inner-label-gap',

    helperTextColor: '--plasma-combobox-helper-text-color',
    helperTextOffset: '--plasma-combobox-helper-text-offset',

    spinnerSize: '--plasma-combobox-spinner-size',
    spinnerSizeTight: '--plasma-combobox-spinner-size-tight',

    disclosureIconColor: '--plasma-combobox-disclosure-icon-color',
    disclosureIconColorHover: '--plasma-combobox-disclosure-icon-color-hover',
    disclosureIconSize: '--plasma-select-disclosure-icon-size',
    disclosureIconMargin: '--plasma-select-disclosure-icon-margin',

    dividerMarginTop: '--plasma-combobox-divider-margin-top',
    dividerMarginTopTight: '--plasma-combobox-divider-margin-top-tight',
    dividerMarginRight: '--plasma-combobox-divider-margin-right',
    dividerMarginBottom: '--plasma-combobox-divider-margin-bottom',
    dividerMarginBottomTight: '--plasma-combobox-divider-margin-bottom-tight',
    dividerMarginLeft: '--plasma-combobox-divider-margin-left',
    dividerColor: '--plasma-combobox-divider-color',
};

export const constants = {
    focusColor: '--surface-accent',
    focusSize: '0.0625rem',
    background: '--surface-solid-card',
    boxShadow: '0px 4px 14px -4px rgba(8, 8, 8, 0.08), 0px 1px 4px -1px rgba(0, 0, 0, 0.04)',
    itemBackground: '--surface-clear',
    textfieldTargetColor: '--text-primary',
    textfieldOuterLabelColor: '--text-primary',
    textfieldInnerLabelColor: '--text-secondary',
    textfieldPlaceholderColor: '--text-secondary',
    textfieldBorderSize: '0.0625rem',
    opacity: '0.4',
    fontFamily: '--plasma-typo-body-xs-font-family',
    fontSize: '--plasma-typo-body-xs-font-size',
    fontStyle: '--plasma-typo-body-xs-font-style',
    fontWeight: '--plasma-typo-body-xs-font-weight',
    fontLetterSpacing: '--plasma-typo-body-xs-letter-spacing',
    fontLineHeight: '--plasma-typo-body-xs-line-height',
    cellTitleColor: '--text-primary',
    cellBackgroundColor: '--surface-clear',
};
