export const classes = {
    dropdownItemIsFocused: 'dropdown-item-is-focused',
    dropdownItemIsDisabled: 'dropdown-item-is-disabled',
    dropdownItemIsActive: 'dropdown-item-is-active',
    selectTargetArrow: 'combobox-target-arrow',
    arrowInverse: 'arrow-inverse',
    textfieldTarget: 'combobox-textfield-target',
    selectChipIsFocused: 'combobox-chip-is-focused',
    selectWithoutBoxShadow: 'combobox-without-box-shadow',
    selectItemCheckbox: 'combobox-item-checkbox',
    selectSpinner: 'combobox-spinner',
    emptyStateWrapper: 'combobox-empty-state-wrapper',
};

export const tokens = {
    borderRadius: '--plasma-combobox-border-radius',
    padding: '--plasma-combobox-padding',
    focusOffset: '--plasma-combobox-focus-offset',

    fontFamily: '--plasma-combobox-font-family',
    fontSize: '--plasma-combobox-font-size',
    fontStyle: '--plasma-combobox-font-style',
    fontWeight: '--plasma-combobox-font-weight',
    fontLetterSpacing: '--plasma-combobox-font-letter-spacing',
    fontLineHeight: '--plasma-combobox-font-line-height',

    dropdownBorderColor: '--plasma-select-dropdown-border-color',
    dropdownBorderWidth: '--plasma-select-dropdown-border-width',

    itemHeight: '--plasma-combobox-item-height',
    itemBorderRadius: '--plasma-combobox-item-border-radius',
    itemPadding: '--plasma-combobox-item-padding',
    itemPaddingTight: '--plasma-combobox-item-padding-tight',
    itemIconSize: '--plasma-combobox-item-icon-size',
    itemIconSizeTight: '--plasma-combobox-item-icon-size-tight',
    itemIconMargin: '--plasma-combobox-item-icon-margin',

    cellPadding: '--plasma-combobox-cell-padding',
    cellPaddingLeftContent: '--plasma-combobox-cell-padding-left-content',
    cellPaddingContent: '--plasma-combobox-cell-padding-content',
    cellPaddingRightContent: '--plasma-combobox-cell-padding-right-content',
    cellTextboxGap: '--plasma-combobox-cell-textbox-gap',
    cellGap: '--plasma-combobox-cell-gap',
    cellTitleFontFamily: '--plasma-combobox-cell-title-font-family',
    cellTitleFontSize: '--plasma-combobox-cell-title-font-size',
    cellTitleFontStyle: '--plasma-combobox-cell-title-font-style',
    cellTitleFontWeight: '--plasma-combobox-cell-title-font-weight',
    cellTitleLetterSpacing: '--plasma-combobox-cell-title-letter-spacing',
    cellTitleLineHeight: '--plasma-combobox-cell-title-line-height',

    checkboxTriggerSize: '--plasma-combobox-checkbox-trigger-size',
    checkboxTriggerSizeTight: '--plasma-combobox-checkbox-trigger-size-tight',
    checkboxTriggerBorderRadius: '--plasma-combobox-checkbox-trigger-border-radius',
    checkboxTriggerBorderRadiusTight: '--plasma-combobox-checkbox-trigger-border-radius-tight',
    checkboxFillColor: '--plasma-combobox-checkbox-fill-color',
    checkboxIconColor: '--plasma-combobox-checkbox-icon-color',
    checkboxTriggerBorderColor: '--plasma-combobox-checkbox-trigger-border-color',

    indicatorSize: '--plasma-combobox-indicator-size',

    targetHeight: '--plasma-combobox-target-height',

    // Токены для TextField
    textFieldColor: '--plasma-combobox-new-textfield-color',
    textFieldBackgroundColor: '--plasma-combobox-new-textfield-background-color',
    textFieldBackgroundColorHover: '--plasma-combobox-new-textfield-background-color-hover',
    textFieldBackgroundColorFocus: '--plasma-combobox-new-textfield-background-color-focus',
    textFieldBorderColor: '--plasma-combobox-new-textfield-border-color',
    textFieldBorderColorHover: '--plasma-combobox-new-textfield-border-color-hover',
    textFieldBorderColorFocus: '--plasma-combobox-new-textfield-border-color-focus',
    textFieldColorReadOnly: '--plasma-combobox-new-textfield-color-readonly',
    textFieldBackgroundColorReadOnly: '--plasma-combobox-new-textfield-bg-color-readonly',
    textFieldBorderColorReadOnly: '--plasma-combobox-new-textfield-border-color-readonly',
    textFieldPlaceholderColorReadOnly: '--plasma-combobox-new-textfield__placeholder-color-readonly',
    textFieldCaretColor: '--plasma-combobox-new-textfield-caret-color',
    textFieldPlaceholderColor: '--plasma-combobox-new-textfield-placeholder-color',
    textFieldHeight: '--plasma-combobox-new-textfield-height',
    textFieldBorderWidth: '--plasma-combobox-new-textfield-border-width',
    textFieldBorderRadius: '--plasma-combobox-new-textfield-border-radius',
    textFieldPadding: '--plasma-combobox-new-textfield-padding',
    textFieldPaddingWithChips: '--plasma-combobox-new-textfield-padding-with-chips',
    textFieldLeftContentMargin: '--plasma-combobox-new-textfield__left-content-margin',
    textFieldRightContentMargin: '--plasma-combobox-new-textfield__right-content-margin',
    textFieldFontFamily: '--plasma-combobox-new-textfield-font-family',
    textFieldFontStyle: '--plasma-combobox-new-textfield-font-style',
    textFieldFontSize: '--plasma-combobox-new-textfield-font-size',
    textFieldFontWeight: '--plasma-combobox-new-textfield-font-weight',
    textFieldLetterSpacing: '--plasma-combobox-new-textfield-letter-spacing',
    textFieldLineHeight: '--plasma-combobox-new-textfield-line-height',
    textFieldLabelColor: '--plasma-combobox-new-textfield-label-color',
    textFieldLabelColorReadOnly: '--plasma-combobox-new-textfield__label-color-readonly',
    textFieldLabelOffset: '--plasma-combobox-new-textfield__label-offset',
    textFieldLabelFontFamily: '--plasma-combobox-new-textfield__label-font-family',
    textFieldLabelFontStyle: '--plasma-combobox-new-textfield__label-font-style',
    textFieldLabelFontSize: '--plasma-combobox-new-textfield__label-font-size',
    textFieldLabelFontWeight: '--plasma-combobox-new-textfield__label-font-weight',
    textFieldLabelLetterSpacing: '--plasma-combobox-new-textfield__label-letter-spacing',
    textFieldLabelLineHeight: '--plasma-combobox-new-textfield__label-line-height',
    textFieldLabelInnerFontFamily: '--plasma-combobox-new-textfield-placement_inner__label-font-family',
    textFieldLabelInnerFontStyle: '--plasma-combobox-new-textfield-placement_inner__label-font-style',
    textFieldLabelInnerFontSize: '--plasma-combobox-new-textfield-placement_inner__label-font-size',
    textFieldLabelInnerFontWeight: '--plasma-combobox-new-textfield-placement_inner__label-font-weight',
    textFieldLabelInnerLetterSpacing: '--plasma-combobox-new-textfield-placement_inner__label-letter-spacing',
    textFieldLabelInnerLineHeight: '--plasma-combobox-new-textfield-placement_inner__label-line-height',
    textFieldLabelInnerPadding: '--plasma-combobox-new-textfield-placement_inner__label-padding',
    textFieldContentLabelInnerPadding: '--plasma-combobox-new-textfield-placement_inner__content-padding',
    textFieldLeftHelperColor: '--plasma-combobox-new-textfield__left-helper-color',
    textFieldLeftHelperColorReadOnly: '--plasma-combobox-new-textfield__left-helper-color-readonly',
    textFieldLeftHelperOffset: '--plasma-combobox-new-textfield__left-helper-offset',
    textFieldLeftHelperFontFamily: '--plasma-combobox-new-textfield__left-helper-font-family',
    textFieldLeftHelperFontStyle: '--plasma-combobox-new-textfield__left-helper-font-style',
    textFieldLeftHelperFontSize: '--plasma-combobox-new-textfield__left-helper-font-size',
    textFieldLeftHelperFontWeight: '--plasma-combobox-new-textfield__left-helper-font-weight',
    textFieldLeftHelperLetterSpacing: '--plasma-combobox-new-textfield__left-helper-letter-spacing',
    textFieldLeftHelperLineHeight: '--plasma-combobox-new-textfield__left-helper-line-height',
    textFieldTextBeforeColor: '--plasma-combobox-new-textfield__before-text-color',
    textFieldTextAfterColor: '--plasma-combobox-new-textfield__after-text-color',
    textFieldTextBeforeMargin: '--plasma-combobox-new-textfield__before-text-margin',
    textFieldTextAfterMargin: '--plasma-combobox-new-textfield__after-text-margin',
    textFieldDisabledOpacity: '--plasma-combobox-new-textfield-disabled-opacity',
    textFieldFocusColor: '--plasma-combobox-new-textfield-focus-color',
    textFieldChipCloseIconColor: '--plasma-combobox-new-textfield-chip-close-icons-color',
    textFieldChipColor: '--plasma-combobox-new-textfield-chip-color',
    textFieldChipBackground: '--plasma-combobox-new-textfield--chip-background',
    textFieldChipColorHover: '--plasma-combobox-new-textfield-chip-color-hover',
    textFieldChipBackgroundHover: '--plasma-combobox-new-textfield-chip-background-hover',
    textFieldChipColorActive: '--plasma-combobox-new-textfield-chip-color-active',
    textFieldChipBackgroundActive: '--plasma-combobox-new-textfield-chip-background-active',
    textFieldChipBackgroundReadOnly: '--plasma-combobox-new-textfield-chip-background-read-only',
    textFieldChipColorReadOnly: '--plasma-combobox-new-textfield-chip-color-read-only',
    textFieldChipBackgroundReadOnlyHover: '--plasma-combobox-new-textfield-chip-background-read-only-hover',
    textFieldChipColorReadOnlyHover: '--plasma-combobox-new-textfield-chip-color-read-only-hover',
    textFieldChipOpacityReadonly: '--plasma-combobox-new-textfield-chip-opacity-read-only',
    textFieldChipGap: '--plasma-combobox-new-textfield-chip-gap',
    textFieldChipBorderRadius: '--plasma-combobox-new-textfield-chip-border-radius',
    textFieldChipWidth: '--plasma-combobox-new-textfield-chip-width',
    textFieldChipHeight: '--plasma-combobox-new-textfield-chip-height',
    textFieldChipPaddingRight: '--plasma-combobox-new-textfield-chip-padding-right',
    textFieldChipPaddingLeft: '--plasma-combobox-new-textfield-chip-padding-left',
    textFieldChipClearContentMarginLeft: '--plasma-combobox-new-textfield-chip-clear-content-margin-left',
    textFieldChipClearContentMarginRight: '--plasma-combobox-new-textfield-chip-clear-content-margin-right',
    textFieldChipCloseIconSize: '--plasma-combobox-new-textfield-chip-close-icon-size',
    textFieldChipFontFamily: '--plasma-combobox-new-textfield-chip-font-family',
    textFieldChipFontSize: '--plasma-combobox-new-textfield-chip-font-size',
    textFieldChipFontStyle: '--plasma-combobox-new-textfield-chip-font-style',
    textFieldChipFontWeight: '--plasma-combobox-new-textfield-chip-font-weight',
    textFieldChipLetterSpacing: '--plasma-combobox-new-textfield-chip-letter-spacing',
    textFieldChipLineHeight: '--plasma-combobox-new-textfield-chip-line-height',

    // Токены для EmptyState
    emptyStatePadding: '--plasma-combobox-new-empty-state-padding',

    labelOffset: '--plasma-combobox-label-offset',

    innerLabelGap: '--plasma-combobox-inner-label-gap',

    helperTextColor: '--plasma-combobox-helper-text-color',
    helperTextOffset: '--plasma-combobox-helper-text-offset',

    spinnerSize: '--plasma-combobox-spinner-size',
    spinnerSizeTight: '--plasma-combobox-spinner-size-tight',
};

export const constants = {
    focusColor: '--surface-accent',
    focusSize: '0.0625rem',
    background: '--surface-solid-card',
    boxShadow: '0px 4px 14px -4px rgba(8, 8, 8, 0.08), 0px 1px 4px -1px rgba(0, 0, 0, 0.04)',
    disclosureIconColor: '--text-secondary',
    disclosureIconColorHover: '--text-secondary-hover',
    itemBackground: '--plasma-colors-transparent',
    itemBackgroundHover: '--surface-transparent-secondary',
    textfieldTargetColor: '--text-primary',
    textfieldOuterLabelColor: '--text-primary',
    textfieldInnerLabelColor: '--text-secondary',
    textfieldPlaceholderColor: '--text-secondary',
    textfieldBorderSize: '0.0625rem',
    opacity: '0.4',
    fontFamily: '--plasma-typo-body-xs-font-family',
    fontSize: '--plasma-typo-body-xs-font-size',
    fontStyle: '--plasma-typo-body-xs-font-style',
    fontWeight: '--plasma-typo-body-xs-font-weight',
    fontLetterSpacing: '--plasma-typo-body-xs-letter-spacing',
    fontLineHeight: '--plasma-typo-body-xs-line-height',
    cellTitleColor: '--text-primary',
    cellBackgroundColor: '--plasma-colors-transparent',
};
