var _templateObject, _templateObject2, _templateObject3, _templateObject4, _templateObject5, _templateObject6, _templateObject7, _templateObject8, _templateObject9, _templateObject10, _templateObject11, _templateObject12;
function _taggedTemplateLiteral(strings, raw) { if (!raw) { raw = strings.slice(0); } return Object.freeze(Object.defineProperties(strings, { raw: { value: Object.freeze(raw) } })); }
import { css } from '@salutejs/plasma-new-hope/styled-components';
export var config = {
  defaults: {
    view: 'accent',
    size: 'm',
    focused: 'true'
  },
  variations: {
    size: {
      s: /*#__PURE__*/css(_templateObject || (_templateObject = /*#__PURE__*/_taggedTemplateLiteral(["\n                --plasma-radiobox-trigger-size: 1rem;\n                --plasma-radiobox-trigger-border-radius 1.125rem;\n                --plasma-radiobox-ellipse-size 0.5rem;\n                --plasma-radiobox-content-top-offset: 0.1rem;\n                --plasma-radiobox-content-left-offset 0.5rem;\n                --plasma-radiobox-label-font-family: var(--plasma-typo-body-s-font-family);\n                --plasma-radiobox-label-font-size: var(--plasma-typo-body-s-font-size);\n                --plasma-radiobox-label-font-style: var(--plasma-typo-body-s-font-style);\n                --plasma-radiobox-label-font-weight: var(--plasma-typo-body-s-font-weight);\n                --plasma-radiobox-label-letter-spacing: var(--plasma-typo-body-s-letter-spacing);\n                --plasma-radiobox-label-line-height: var(--plasma-typo-body-s-line-height);\n                --plasma-radiobox-description-font-family: var(--plasma-typo-body-xs-font-family);\n                --plasma-radiobox-description-font-size: var(--plasma-typo-body-xs-font-size);\n                --plasma-radiobox-description-font-style: var(--plasma-typo-body-xs-font-style);\n                --plasma-radiobox-description-font-weight: var(--plasma-typo-body-xs-font-weight);\n                --plasma-radiobox-description-letter-spacing: var(--plasma-typo-body-xs-letter-spacing);\n                --plasma-radiobox-description-line-height: var(--plasma-typo-body-xs-line-height);\n            "]))),
      m: /*#__PURE__*/css(_templateObject2 || (_templateObject2 = /*#__PURE__*/_taggedTemplateLiteral(["\n                --plasma-radiobox-trigger-size: 1.375rem;\n                --plasma-radiobox-trigger-border-radius 1.125rem;\n                --plasma-radiobox-ellipse-size 0.625rem;\n                --plasma-radiobox-content-top-offset: 0.25rem;\n                --plasma-radiobox-content-left-offset 0.625rem;\n                --plasma-radiobox-label-font-family: var(--plasma-typo-body-m-font-family);\n                --plasma-radiobox-label-font-size: var(--plasma-typo-body-m-font-size);\n                --plasma-radiobox-label-font-style: var(--plasma-typo-body-m-font-style);\n                --plasma-radiobox-label-font-weight: var(--plasma-typo-body-m-font-weight);\n                --plasma-radiobox-label-letter-spacing: var(--plasma-typo-body-m-letter-spacing);\n                --plasma-radiobox-label-line-height: var(--plasma-typo-body-m-line-height);\n                --plasma-radiobox-description-font-family: var(--plasma-typo-body-s-font-family);\n                --plasma-radiobox-description-font-size: var(--plasma-typo-body-s-font-size);\n                --plasma-radiobox-description-font-style: var(--plasma-typo-body-s-font-style);\n                --plasma-radiobox-description-font-weight: var(--plasma-typo-body-s-font-weight);\n                --plasma-radiobox-description-letter-spacing: var(--plasma-typo-body-s-letter-spacing);\n                --plasma-radiobox-description-line-height: var(--plasma-typo-body-s-line-height);\n            "])))
    },
    view: {
      primary: /*#__PURE__*/css(_templateObject3 || (_templateObject3 = /*#__PURE__*/_taggedTemplateLiteral(["\n                --plasma-radiobox-fill-color: var(--text-primary);\n                --plasma-radiobox-ellipse-color: var(--inverse-text-primary);\n                --plasma-radiobox-description-color: var(--text-secondary);\n                --plasma-radiobox-trigger-border-color: var(--text-secondary);\n            "]))),
      secondary: /*#__PURE__*/css(_templateObject4 || (_templateObject4 = /*#__PURE__*/_taggedTemplateLiteral(["\n                --plasma-radiobox-fill-color: var(--text-secondary);\n                --plasma-radiobox-ellipse-color: var(--inverse-text-primary);\n                --plasma-radiobox-description-color: var(--text-secondary);\n                --plasma-radiobox-trigger-border-color: var(--text-secondary);\n            "]))),
      tertiary: /*#__PURE__*/css(_templateObject5 || (_templateObject5 = /*#__PURE__*/_taggedTemplateLiteral(["\n                --plasma-radiobox-fill-color: var(--text-tertiary);\n                --plasma-radiobox-ellipse-color: var(--inverse-text-primary);\n                --plasma-radiobox-description-color: var(--text-secondary);\n                --plasma-radiobox-trigger-border-color: var(--text-secondary);\n            "]))),
      paragraph: /*#__PURE__*/css(_templateObject6 || (_templateObject6 = /*#__PURE__*/_taggedTemplateLiteral(["\n                --plasma-radiobox-fill-color: var(--text-paragraph);\n                --plasma-radiobox-ellipse-color: var(--inverse-text-primary);\n                --plasma-radiobox-description-color: var(--text-secondary);\n                --plasma-radiobox-trigger-border-color: var(--text-secondary);\n            "]))),
      accent: /*#__PURE__*/css(_templateObject7 || (_templateObject7 = /*#__PURE__*/_taggedTemplateLiteral(["\n                --plasma-radiobox-fill-color: var(--text-accent);\n                --plasma-radiobox-ellipse-color: var(--on-dark-text-primary);\n                --plasma-radiobox-description-color: var(--text-secondary);\n                --plasma-radiobox-trigger-border-color: var(--text-secondary);\n            "]))),
      positive: /*#__PURE__*/css(_templateObject8 || (_templateObject8 = /*#__PURE__*/_taggedTemplateLiteral(["\n                --plasma-radiobox-fill-color: var(--text-positive);\n                --plasma-radiobox-ellipse-color: var(--on-dark-text-primary);\n                --plasma-radiobox-description-color: var(--text-secondary);\n                --plasma-radiobox-trigger-border-color: var(--text-secondary);\n            "]))),
      warning: /*#__PURE__*/css(_templateObject9 || (_templateObject9 = /*#__PURE__*/_taggedTemplateLiteral(["\n                --plasma-radiobox-fill-color: var(--text-warning);\n                --plasma-radiobox-ellipse-color: var(--on-dark-text-primary);\n                --plasma-radiobox-description-color: var(--text-secondary);\n                --plasma-radiobox-trigger-border-color: var(--text-secondary);\n            "]))),
      negative: /*#__PURE__*/css(_templateObject10 || (_templateObject10 = /*#__PURE__*/_taggedTemplateLiteral(["\n                --plasma-radiobox-fill-color: var(--text-negative);\n                --plasma-radiobox-ellipse-color: var(--on-dark-text-primary);\n                --plasma-radiobox-description-color: var(--text-secondary);\n                --plasma-radiobox-trigger-border-color: var(--text-secondary);\n            "])))
    },
    disabled: {
      "true": /*#__PURE__*/css(_templateObject11 || (_templateObject11 = /*#__PURE__*/_taggedTemplateLiteral(["\n                --plasma-radiobox-disabled-opacity: 0.4;\n            "])))
    },
    focused: {
      "true": /*#__PURE__*/css(_templateObject12 || (_templateObject12 = /*#__PURE__*/_taggedTemplateLiteral(["\n                --plasma-radiobox-focus-color: var(--text-accent);\n            "])))
    }
  }
};