// Generated by robots, do not change this manually!

/** Основной цвет текста */
export const textPrimary = 'var(--text-primary, rgba(255, 255, 255, 0.96))';

/** Вторичный цвет текста */
export const textSecondary = 'var(--text-secondary, rgba(255, 255, 255, 0.56))';

/** Акцентный цвет */
export const textAccent = 'var(--text-accent, #0C9C0C)';

/** Цвет успеха */
export const textPositive = 'var(--text-positive, #1A9E32)';

/** Цвет ошибки */
export const textNegative = 'var(--text-negative, #FF293E)';

/** Основной цвет текста на темном фоне */
export const onDarkTextPrimary = 'var(--on-dark-text-primary, rgba(255, 255, 255, 0.96))';

/** Вторичный цвет текста на темном фоне */
export const onDarkTextSecondary = 'var(--on-dark-text-secondary, rgba(255, 255, 255, 0.56))';

/** Акцентный цвет на темном фоне */
export const onDarkTextAccent = 'var(--on-dark-text-accent, #0C9C0C)';

/** Акцентный минорный цвет на темном фоне */
export const onDarkTextAccentMinor = 'var(--on-dark-text-accent-minor, #94FF94)';

/** Цвет успеха на темном фоне */
export const onDarkTextPositive = 'var(--on-dark-text-positive, #1A9E32)';

/** Цвет ошибки на темном фоне */
export const onDarkTextNegative = 'var(--on-dark-text-negative, #FF293E)';

/** Инвертированный основной цвет текста */
export const inverseTextPrimary = 'var(--inverse-text-primary, #060A0CF5)';

/** Инвертированный вторичный цвет текста */
export const inverseTextSecondary = 'var(--inverse-text-secondary, #060A0C8F)';

/** Инвертированный акцентный цвет */
export const inverseTextAccent = 'var(--inverse-text-accent, #108210)';

/** Инвертированный минорный акцентный цвет */
export const inverseTextAccentMinor = 'var(--inverse-text-accent-minor, #082B08)';

/** Инвертированный цвет успеха */
export const inverseTextPositive = 'var(--inverse-text-positive, #108E26)';

/** Инвертированный цвет ошибки */
export const inverseTextNegative = 'var(--inverse-text-negative, #F31B31)';

/** Основной непрозрачный фон поверхности/контрола */
export const surfaceSolidPrimary = 'var(--surface-solid-primary, #13181B)';

/** Основной фон для карточек */
export const surfaceSolidCard = 'var(--surface-solid-card, #13181B)';

/** Непрозрачный фон поверхности/контрола по умолчанию */
export const surfaceSolidDefault = 'var(--surface-solid-default, #F7F9FB)';

/** Акцентный фон поверхности/контрола */
export const surfaceAccent = 'var(--surface-accent, #0C9C0C)';

/** Цвет фона поверхности/контрола успех */
export const surfacePositive = 'var(--surface-positive, #1A9E32)';

/** Цвет фона поверхности/контрола ошибка */
export const surfaceNegative = 'var(--surface-negative, #FF293E)';

/** Цвет фона поверхности/контрола информация */
export const surfaceInfo = 'var(--surface-info, #118CDF)';

/** Основной непрозрачный фон поверхности/контрола на темном фоне */
export const onDarkSurfaceSolidPrimary = 'var(--on-dark-surface-solid-primary, #13181B)';

/** Основной фон для карточек на темном фоне */
export const onDarkSurfaceSolidCard = 'var(--on-dark-surface-solid-card, #13181B)';

/** Непрозрачный фон поверхности/контрола по умолчанию на темном фоне */
export const onDarkSurfaceSolidDefault = 'var(--on-dark-surface-solid-default, #F7F9FB)';

/** Акцентный фон поверхности/контрола на темном фоне */
export const onDarkSurfaceAccent = 'var(--on-dark-surface-accent, #0C9C0C)';

/** Цвет фона поверхности/контрола успех на темном фоне */
export const onDarkSurfacePositive = 'var(--on-dark-surface-positive, #1A9E32)';

/** Цвет фона поверхности/контрола ошибка на темном фоне */
export const onDarkSurfaceNegative = 'var(--on-dark-surface-negative, #FF293E)';

/** Цвет фона поверхности/контрола информация на темном фоне */
export const onDarkSurfaceInfo = 'var(--on-dark-surface-info, #118CDF)';

/** Основной непрозрачный фон поверхности/контрола на светлом фоне */
export const onLightSurfaceSolidPrimary = 'var(--on-light-surface-solid-primary, #F2F5F8)';

/** Основной фон для карточек на светлом фоне */
export const onLightSurfaceSolidCard = 'var(--on-light-surface-solid-card, #FFFFFF)';

/** Непрозрачный фон поверхности/контрола по умолчанию на светлом фоне */
export const onLightSurfaceSolidDefault = 'var(--on-light-surface-solid-default, #060A0C)';

/** Акцентный фон поверхности/контрола на светлом фоне */
export const onLightSurfaceAccent = 'var(--on-light-surface-accent, #108210)';

/** Цвет фона поверхности/контрола успех на светлом фоне */
export const onLightSurfacePositive = 'var(--on-light-surface-positive, #1A9E32)';

/** Цвет фона поверхности/контрола ошибка на светлом фоне */
export const onLightSurfaceNegative = 'var(--on-light-surface-negative, #FF293E)';

/** Цвет фона поверхности/контрола информация на светлом фоне */
export const onLightSurfaceInfo = 'var(--on-light-surface-info, #118CDF)';

/** Инвертированный основной непрозрачный фон поверхности/контрола */
export const inverseSurfaceSolidPrimary = 'var(--inverse-surface-solid-primary, #F2F5F8)';

/** Инвертированный основной фон для карточек */
export const inverseSurfaceSolidCard = 'var(--inverse-surface-solid-card, #FFFFFF)';

/** Инвертированный непрозрачный фон поверхности/контрола по умолчанию */
export const inverseSurfaceSolidDefault = 'var(--inverse-surface-solid-default, #060A0C)';

/** Инвертированный акцентный фон поверхности/контрола */
export const inverseSurfaceAccent = 'var(--inverse-surface-accent, #108210)';

/** Инвертированный цвет фона поверхности/контрола успех */
export const inverseSurfacePositive = 'var(--inverse-surface-positive, #1A9E32)';

/** Инвертированный цвет фона поверхности/контрола ошибка */
export const inverseSurfaceNegative = 'var(--inverse-surface-negative, #FF293E)';

/** Инвертированный цвет фона поверхности/контрола информация */
export const inverseSurfaceInfo = 'var(--inverse-surface-info, #118CDF)';

/** Основной фон */
export const backgroundPrimary = 'var(--background-primary, #060A0C)';

/** Основной фон на темном фоне */
export const darkBackgroundPrimary = 'var(--dark-background-primary, #060A0C)';

/** Основной фон на светлом фоне */
export const lightBackgroundPrimary = 'var(--light-background-primary, #F7F9FB)';

/** Инвертированный основной фон */
export const inverseBackgroundPrimary = 'var(--inverse-background-primary, #F7F9FB)';

/** Основной непрозрачный цвет обводки */
export const outlineDefaultOutlineSolidPrimary = 'var(--outline-default-outline-solid-primary, #23292D)';

/** Вторичный непрозрачный цвет обводки */
export const outlineDefaultOutlineSolidSecondary = 'var(--outline-default-outline-solid-secondary, #30373C)';

/** Акцентный цвет обводки */
export const outlineDefaultOutlineAccent = 'var(--outline-default-outline-accent, #0C9C0C)';

/** Цвет обводки успех */
export const outlineDefaultOutlinePositive = 'var(--outline-default-outline-positive, #1A9E32)';

/** Цвет обводки ошибка */
export const outlineDefaultOutlineNegative = 'var(--outline-default-outline-negative, #FF293E)';

/** Цвет обводки информация */
export const outlineDefaultOutlineInfo = 'var(--outline-default-outline-info, #118CDF)';

/** Основной непрозрачный цвет обводки на темном фоне */
export const outlineOnDarkOutlineSolidPrimary = 'var(--outline-on-dark-outline-solid-primary, #23292D)';

/** Вторичный непрозрачный цвет обводки на темном фоне */
export const outlineOnDarkOutlineSolidSecondary = 'var(--outline-on-dark-outline-solid-secondary, #30373C)';

/** Акцентный цвет обводки на темном фоне */
export const outlineOnDarkOutlineAccent = 'var(--outline-on-dark-outline-accent, #0C9C0C)';

/** Цвет обводки успех на темном фоне */
export const outlineOnDarkOutlinePositive = 'var(--outline-on-dark-outline-positive, #1A9E32)';

/** Цвет обводки ошибка на темном фоне */
export const outlineOnDarkOutlineNegative = 'var(--outline-on-dark-outline-negative, #FF293E)';

/** Цвет обводки информация на темном фоне */
export const outlineOnDarkOutlineInfo = 'var(--outline-on-dark-outline-info, #118CDF)';

/** Основной непрозрачный цвет обводки на светлом фоне */
export const outlineOnLightOutlineSolidPrimary = 'var(--outline-on-light-outline-solid-primary, #D5DFE6)';

/** Вторичный непрозрачный цвет обводки на светлом фоне */
export const outlineOnLightOutlineSolidSecondary = 'var(--outline-on-light-outline-solid-secondary, #ADB9C2)';

/** Акцентный цвет обводки на светлом фоне */
export const outlineOnLightOutlineAccent = 'var(--outline-on-light-outline-accent, #108210)';

/** Цвет обводки успех на светлом фоне */
export const outlineOnLightOutlinePositive = 'var(--outline-on-light-outline-positive, #108E26)';

/** Цвет обводки ошибка на светлом фоне */
export const outlineOnLightOutlineNegative = 'var(--outline-on-light-outline-negative, #F31B31)';

/** Цвет обводки информация на светлом фоне */
export const outlineOnLightOutlineInfo = 'var(--outline-on-light-outline-info, #0B7ECB)';

/** Инвертированный основной непрозрачный цвет обводки */
export const outlineInverseOutlineSolidPrimary = 'var(--outline-inverse-outline-solid-primary, #D5DFE6)';

/** Инвертированный вторичный непрозрачный цвет обводки */
export const outlineInverseOutlineSolidSecondary = 'var(--outline-inverse-outline-solid-secondary, #ADB9C2)';

/** Инвертированный акцентный цвет обводки */
export const outlineInverseOutlineAccent = 'var(--outline-inverse-outline-accent, #108210)';

/** Инвертированный цвет обводки успех */
export const outlineInverseOutlinePositive = 'var(--outline-inverse-outline-positive, #108E26)';

/** Инвертированный цвет обводки ошибка */
export const outlineInverseOutlineNegative = 'var(--outline-inverse-outline-negative, #F31B31)';

/** Инвертированный цвет обводки информация */
export const outlineInverseOutlineInfo = 'var(--outline-inverse-outline-info, #0B7ECB)';

export const skeletonGradient =
    'var(--skeleton-gradient, linear-gradient( 90deg, rgba(255, 255, 255, 0.09) 0%, rgba(255, 255, 255, 0.08) 6.25%, rgba(255, 255, 255, 0.05) 12.5%, rgba(255, 255, 255, 0.01) 25%, rgba(255, 255, 255, 0.05) 37.5%, rgba(255, 255, 255, 0.08) 43.75%, rgba(255, 255, 255, 0.09) 50%, rgba(255, 255, 255, 0.08) 56.25%, rgba(255, 255, 255, 0.05) 62.5%, rgba(255, 255, 255, 0.01) 75%, rgba(255, 255, 255, 0.05) 87.5%, rgba(255, 255, 255, 0.08) 93.75%, rgba(255, 255, 255, 0.09) 100% ))';

export const skeletonGradientLighter =
    'var(--skeleton-gradient-lighter, linear-gradient( 90deg, rgba(255, 255, 255, 0.36) 0%, rgba(255, 255, 255, 0.32) 6.25%, rgba(255, 255, 255, 0.20) 12.5%, rgba(255, 255, 255, 0.04) 25%, rgba(255, 255, 255, 0.20) 37.5%, rgba(255, 255, 255, 0.32) 43.75%, rgba(255, 255, 255, 0.36) 50%, rgba(255, 255, 255, 0.08) 56.25%, rgba(255, 255, 255, 0.20) 62.5%, rgba(255, 255, 255, 0.04) 75%, rgba(255, 255, 255, 0.20) 87.5%, rgba(255, 255, 255, 0.32) 93.75%, rgba(255, 255, 255, 0.36) 100% ))';

/** @deprecated instead use onDarkTextPrimary */
export const whitePrimary = 'var(--plasma-colors-white-primary, var(--on-dark-text-primary))';

/** @deprecated instead use onDarkTextSecondary */
export const whiteSecondary = 'var(--plasma-colors-white-secondary, var(--on-dark-text-secondary))';

/** @deprecated instead use onLightSurfaceSolidDefault */
export const buttonBlack = 'var(--plasma-colors-button-black, var(--on-light-surface-solid-default))';

/** @deprecated instead use onDarkSurfaceSolidDefault */
export const buttonWhite = 'var(--plasma-colors-button-white, var(--on-dark-surface-solid-default))';

/** @deprecated instead use textPrimary */
export const text = 'var(--plasma-colors-text, var(--text-primary))';

/** @deprecated instead use textPrimary */
export const primary = 'var(--plasma-colors-primary, var(--text-primary))';

/** @deprecated instead use textSecondary */
export const secondary = 'var(--plasma-colors-secondary, var(--text-secondary))';

/** @deprecated instead use backgroundPrimary */
export const background = 'var(--plasma-colors-background, var(--background-primary))';

/** @deprecated instead use textAccent */
export const accent = 'var(--plasma-colors-accent, var(--text-accent))';

/** @deprecated instead use textPositive */
export const success = 'var(--plasma-colors-success, var(--text-positive))';

/** @deprecated instead use textNegative */
export const critical = 'var(--plasma-colors-critical, var(--text-negative))';

/** @deprecated instead use surfaceSolidPrimary */
export const surfaceSolid01 = 'var(--plasma-colors-surface-solid01, var(--surface-solid-primary))';

/** @deprecated instead use textAccent */
export const buttonAccent = 'var(--plasma-colors-button-accent, var(--text-accent))';

/** @deprecated instead use surfacePositive */
export const buttonSuccess = 'var(--plasma-colors-button-success, var(--surface-positive))';

/** @deprecated instead use surfaceNegative */
export const buttonCritical = 'var(--plasma-colors-button-critical, var(--surface-negative))';
