// Generated by robots, do not change this manually!

/** Основной цвет текста */
export const textPrimary = 'var(--text-primary, #F2F5F7)';

/** Вторичный цвет текста */
export const textSecondary = 'var(--text-secondary, #A8B4BD)';

/** Третичный цвет текста */
export const textTertiary = 'var(--text-tertiary, #7D868C)';

/** Сплошной наборный текст */
export const textParagraph = 'var(--text-paragraph, #BEC9D1)';

/** Акцентный цвет */
export const textAccent = 'var(--text-accent, #24B23E)';

/** Цвет ошибки */
export const textNegative = 'var(--text-negative, #FF2E43)';

/** Дополнительный акцент */
export const textAccentDiscount = 'var(--text-accent-discount, #FF1F78)';

/** Дополнительный акцент */
export const textAccentGold = 'var(--text-accent-gold, #FFD83D)';

/** Акцентный цвет бренда */
export const textAccentB2B = 'var(--text-accent-b2-b, #04C6C9)';

/** Основной цвет текста на темном фоне */
export const onDarkTextPrimary = 'var(--on-dark-text-primary, rgba(242, 245, 247, 0.96))';

/** Вторичный цвет текста на темном фоне */
export const onDarkTextSecondary = 'var(--on-dark-text-secondary, rgba(242, 245, 247, 0.64))';

/** Третичный цвет текста на темном фоне */
export const onDarkTextTertiary = 'var(--on-dark-text-tertiary, rgba(242, 245, 247, 0.4))';

/** Сплошной наборный текст на темном фоне */
export const onDarkTextParagraph = 'var(--on-dark-text-paragraph, rgba(242, 245, 247, 0.8))';

/** Акцентный цвет на темном фоне */
export const onDarkTextAccent = 'var(--on-dark-text-accent, #24B23E)';

/** Цвет ошибки на темном фоне */
export const onDarkTextNegative = 'var(--on-dark-text-negative, #FF2E43)';

/** Дополнительный акцент */
export const onDarkTextAccentDiscount = 'var(--on-dark-text-accent-discount, #FF1F78)';

/** Дополнительный акцент */
export const onDarkTextAccentGold = 'var(--on-dark-text-accent-gold, #FFD83D)';

/** Акцентный цвет бренда */
export const onDarkTextAccentB2B = 'var(--on-dark-text-accent-b2-b, #04C6C9)';

/** Основной цвет текста на светлом фоне */
export const onLightTextPrimary = 'var(--on-light-text-primary, #24282B)';

/** Вторичный цвет текста на светлом фоне */
export const onLightTextSecondary = 'var(--on-light-text-secondary, #8C959C)';

/** Третичный цвет текста на светлом фоне */
export const onLightTextTertiary = 'var(--on-light-text-tertiary, #BEC9D1)';

/** Сплошной наборный текст на светлом фоне */
export const onLightTextParagraph = 'var(--on-light-text-paragraph, #24282B)';

/** Акцентный цвет на светлом фоне */
export const onLightTextAccent = 'var(--on-light-text-accent, #108E26)';

/** Цвет ошибки на светлом фоне */
export const onLightTextNegative = 'var(--on-light-text-negative, #F31B31)';

/** Дополнительный акцент */
export const onLightTextAccentDiscount = 'var(--on-light-text-accent-discount, #FF1F78)';

/** Дополнительный акцент */
export const onLightTextAccentGold = 'var(--on-light-text-accent-gold, #FFD83D)';

/** Акцентный цвет бренда */
export const onLightTextAccentB2B = 'var(--on-light-text-accent-b2-b, #0C8688)';

/** Инвертированный основной цвет текста */
export const inverseTextPrimary = 'var(--inverse-text-primary, #24282B)';

/** Вторичный непрозрачный фон поверхности/контрола */
export const surfaceSolidSecondary = 'var(--surface-solid-secondary, #24282B)';

/** Третичный непрозрачный фон поверхности/контрола */
export const surfaceSolidTertiary = 'var(--surface-solid-tertiary, #31373B)';

/** Основной фон для карточек */
export const surfaceSolidCard = 'var(--surface-solid-card, #15181A)';

/** Акцентный фон поверхности/контрола */
export const surfaceAccent = 'var(--surface-accent, #24B23E)';

/** Акцентный фон поверхности/контрола с градиентом */
export const surfaceAccentGradient =
    'var(--surface-accent-gradient, linear-gradient(122.62deg, #4817C1 0%, #C505D6 100%))';

/** Цвет фона поверхности/контрола ошибка */
export const surfaceNegative = 'var(--surface-negative, #FF2E43)';

/** Акцентный фон поверхности/контрола */
export const surfaceAccentB2B = 'var(--surface-accent-b2-b, #0DA8AB)';

/** Дополнительный акцент для обозначения акций */
export const surfaceAccentDiscount = 'var(--surface-accent-discount, #FF1F78)';

/** Дополнительный акцент */
export const surfaceAccentGold = 'var(--surface-accent-gold, #FFD83D)';

/** Дополнительный акцент */
export const surfaceAccentBlue = 'var(--surface-accent-blue, #5993FF)';

/** Пунктирные дивайдеры и неактивные контролы */
export const surfaceAdditional = 'var(--surface-additional, #494F54)';

/** Вторичный непрозрачный фон поверхности/контрола на темном фоне */
export const onDarkSurfaceSolidSecondary = 'var(--on-dark-surface-solid-secondary, #24282B)';

/** Третичный непрозрачный фон поверхности/контрола на темном фоне */
export const onDarkSurfaceSolidTertiary = 'var(--on-dark-surface-solid-tertiary, #31373B)';

/** Основной фон для карточек на темном фоне */
export const onDarkSurfaceSolidCard = 'var(--on-dark-surface-solid-card, #15181A)';

/** Акцентный фон поверхности/контрола на темном фоне */
export const onDarkSurfaceAccent = 'var(--on-dark-surface-accent, #24B23E)';

/** Акцентный фон поверхности/контрола с градиентом на темном фоне */
export const onDarkSurfaceAccentGradient =
    'var(--on-dark-surface-accent-gradient, linear-gradient(122.62deg, #4817C1 0%, #C505D6 100%))';

/** Цвет фона поверхности/контрола ошибка на темном фоне */
export const onDarkSurfaceNegative = 'var(--on-dark-surface-negative, #FF2E43)';

/** Акцентный фон поверхности/контрола */
export const onDarkSurfaceAccentB2B = 'var(--on-dark-surface-accent-b2-b, #0DA8AB)';

/** Дополнительный акцент для обозначения акций */
export const onDarkSurfaceAccentDiscount = 'var(--on-dark-surface-accent-discount, #FF1F78)';

/** Дополнительный акцент */
export const onDarkSurfaceAccentGold = 'var(--on-dark-surface-accent-gold, #FFD83D)';

/** Дополнительный акцент */
export const onDarkSurfaceAccentBlue = 'var(--on-dark-surface-accent-blue, #5993FF)';

/** Пунктирные дивайдеры и неактивные контролы */
export const onDarkSurfaceAdditional = 'var(--on-dark-surface-additional, #494F54)';

/** Вторичный непрозрачный фон поверхности/контрола на светлом фоне */
export const onLightSurfaceSolidSecondary = 'var(--on-light-surface-solid-secondary, #F2F5F7)';

/** Третичный непрозрачный фон поверхности/контрола на светлом фоне */
export const onLightSurfaceSolidTertiary = 'var(--on-light-surface-solid-tertiary, #E4EBF0)';

/** Основной фон для карточек на светлом фоне */
export const onLightSurfaceSolidCard = 'var(--on-light-surface-solid-card, #FFFFFF)';

/** Акцентный фон поверхности/контрола на светлом фоне */
export const onLightSurfaceAccent = 'var(--on-light-surface-accent, #24B23E)';

/** Акцентный фон поверхности/контрола с градиентом на светлом фоне */
export const onLightSurfaceAccentGradient =
    'var(--on-light-surface-accent-gradient, linear-gradient(122.62deg, #4817C1 0%, #C505D6 100%))';

/** Цвет фона поверхности/контрола ошибка на светлом фоне */
export const onLightSurfaceNegative = 'var(--on-light-surface-negative, #F31B31)';

/** Акцентный фон поверхности/контрола */
export const onLightSurfaceAccentB2B = 'var(--on-light-surface-accent-b2-b, #0DA8AB)';

/** Дополнительный акцент для обозначения акций */
export const onLightSurfaceAccentDiscount = 'var(--on-light-surface-accent-discount, #FF1F78)';

/** Дополнительный акцент */
export const onLightSurfaceAccentGold = 'var(--on-light-surface-accent-gold, #FFD83D)';

/** Дополнительный акцент */
export const onLightSurfaceAccentBlue = 'var(--on-light-surface-accent-blue, #3F81FD)';

/** Пунктирные дивайдеры и неактивные контролы */
export const onLightSurfaceAdditional = 'var(--on-light-surface-additional, #D1DDE5)';

/** Бэкграунд для баннеров и всплывающих нотификаций */
export const bannersDefaultBannerRed = 'var(--banners-default-banner-red, #2E090D)';

/** Бэкграунд для баннеров и всплывающих нотификаций */
export const bannersDefaultBannerGold = 'var(--banners-default-banner-gold, #1F1903)';

/** Бэкграунд для баннеров и всплывающих нотификаций */
export const bannersDefaultBannerGreen = 'var(--banners-default-banner-green, #071F0C)';

/** Бэкграунд для баннеров и всплывающих нотификаций */
export const bannersDefaultBannerMalachite = 'var(--banners-default-banner-malachite, #0A1C1C)';

/** Бэкграунд для баннеров и всплывающих нотификаций */
export const bannersDefaultBannerBlue = 'var(--banners-default-banner-blue, #0A162B)';

/** Основной фон */
export const backgroundPrimary = 'var(--background-primary, #08090A)';

/** Вторичный фон */
export const backgroundOverlay = 'var(--background-overlay, rgba(21, 24, 26, 0.56))';

export const skeletonGradient =
    'var(--skeleton-gradient, linear-gradient( 90deg, rgba(255, 255, 255, 0.09) 0%, rgba(255, 255, 255, 0.08) 6.25%, rgba(255, 255, 255, 0.05) 12.5%, rgba(255, 255, 255, 0.01) 25%, rgba(255, 255, 255, 0.05) 37.5%, rgba(255, 255, 255, 0.08) 43.75%, rgba(255, 255, 255, 0.09) 50%, rgba(255, 255, 255, 0.08) 56.25%, rgba(255, 255, 255, 0.05) 62.5%, rgba(255, 255, 255, 0.01) 75%, rgba(255, 255, 255, 0.05) 87.5%, rgba(255, 255, 255, 0.08) 93.75%, rgba(255, 255, 255, 0.09) 100% ))';

export const skeletonGradientLighter =
    'var(--skeleton-gradient-lighter, linear-gradient( 90deg, rgba(255, 255, 255, 0.36) 0%, rgba(255, 255, 255, 0.32) 6.25%, rgba(255, 255, 255, 0.20) 12.5%, rgba(255, 255, 255, 0.04) 25%, rgba(255, 255, 255, 0.20) 37.5%, rgba(255, 255, 255, 0.32) 43.75%, rgba(255, 255, 255, 0.36) 50%, rgba(255, 255, 255, 0.08) 56.25%, rgba(255, 255, 255, 0.20) 62.5%, rgba(255, 255, 255, 0.04) 75%, rgba(255, 255, 255, 0.20) 87.5%, rgba(255, 255, 255, 0.32) 93.75%, rgba(255, 255, 255, 0.36) 100% ))';

/** @deprecated instead use onDarkTextPrimary */
export const whitePrimary = 'var(--white-primary, rgba(242, 245, 247, 0.96))';

/** @deprecated instead use onDarkTextSecondary */
export const whiteSecondary = 'var(--white-secondary, rgba(242, 245, 247, 0.64))';

/** @deprecated instead use onDarkTextTertiary */
export const whiteTertiary = 'var(--white-tertiary, rgba(242, 245, 247, 0.4))';

/** @deprecated instead use onLightTextPrimary */
export const blackPrimary = 'var(--black-primary, #24282B)';

/** @deprecated instead use onLightTextSecondary */
export const blackSecondary = 'var(--black-secondary, #8C959C)';

/** @deprecated instead use onLightTextTertiary */
export const blackTertiary = 'var(--black-tertiary, #BEC9D1)';

/** @deprecated instead use textPrimary */
export const text = 'var(--text, #F2F5F7)';

/** @deprecated instead use textPrimary */
export const primary = 'var(--primary, #F2F5F7)';

/** @deprecated instead use textSecondary */
export const secondary = 'var(--secondary, #A8B4BD)';

/** @deprecated instead use textTertiary */
export const tertiary = 'var(--tertiary, #7D868C)';

/** @deprecated instead use textParagraph */
export const paragraph = 'var(--paragraph, #BEC9D1)';

/** @deprecated instead use backgroundPrimary */
export const background = 'var(--background, #08090A)';

/** @deprecated instead use textAccent */
export const accent = 'var(--accent, #24B23E)';

/** @deprecated instead use textNegative */
export const critical = 'var(--critical, #FF2E43)';

/** @deprecated instead use surfaceSolidSecondary */
export const surfaceSolid02 = 'var(--surface-solid02, #24282B)';

/** @deprecated instead use surfaceSolidTertiary */
export const surfaceSolid03 = 'var(--surface-solid03, #31373B)';

/** @deprecated instead use textAccent */
export const buttonAccent = 'var(--button-accent, #24B23E)';

/** @deprecated instead use surfaceNegative */
export const buttonCritical = 'var(--button-critical, #FF2E43)';
