// Generated by robots, do not change this manually!

/** Основной цвет текста */
export const textPrimaryHover = 'var(--text-primary-hover, #F5F5F593)';

/** Основной цвет текста */
export const textPrimaryActive = 'var(--text-primary-active, #F5F5F5C4)';

/** Основной цвет текста */
export const textPrimary = 'var(--text-primary, #F5F5F5F5)';

/** Вторичный цвет текста */
export const textSecondaryHover = 'var(--text-secondary-hover, #F5F5F5FF)';

/** Вторичный цвет текста */
export const textSecondaryActive = 'var(--text-secondary-active, #F5F5F5AB)';

/** Вторичный цвет текста */
export const textSecondary = 'var(--text-secondary, #F5F5F58F)';

/** Третичный цвет текста */
export const textTertiaryHover = 'var(--text-tertiary-hover, #F5F5F5FF)';

/** Третичный цвет текста */
export const textTertiaryActive = 'var(--text-tertiary-active, #F5F5F556)';

/** Третичный цвет текста */
export const textTertiary = 'var(--text-tertiary, #F5F5F548)';

/** Сплошной наборный текст */
export const textParagraphHover = 'var(--text-paragraph-hover, #F5F5F57A)';

/** Сплошной наборный текст */
export const textParagraphActive = 'var(--text-paragraph-active, #F5F5F5A3)';

/** Сплошной наборный текст */
export const textParagraph = 'var(--text-paragraph, #F5F5F5CC)';

/** Акцентный цвет */
export const textAccentHover = 'var(--text-accent-hover, #2ACB47FF)';

/** Акцентный цвет */
export const textAccentActive = 'var(--text-accent-active, #1F9835FF)';

/** Акцентный цвет */
export const textAccent = 'var(--text-accent, #24B23E)';

/** Цвет успеха */
export const textPositiveHover = 'var(--text-positive-hover, #2ACB47FF)';

/** Цвет успеха */
export const textPositiveActive = 'var(--text-positive-active, #1F9835FF)';

/** Цвет успеха */
export const textPositive = 'var(--text-positive, #24B23E)';

/** Цвет предупреждения */
export const textWarningHover = 'var(--text-warning-hover, #FF8442FF)';

/** Цвет предупреждения */
export const textWarningActive = 'var(--text-warning-active, #FF5D05FF)';

/** Цвет предупреждения */
export const textWarning = 'var(--text-warning, #FF7024)';

/** Цвет ошибки */
export const textNegativeHover = 'var(--text-negative-hover, #FF5C6CFF)';

/** Цвет ошибки */
export const textNegativeActive = 'var(--text-negative-active, #FF1F35FF)';

/** Цвет ошибки */
export const textNegative = 'var(--text-negative, #FF3D51)';

/** Основной цвет текста на темном фоне */
export const onDarkTextPrimaryHover = 'var(--on-dark-text-primary-hover, #F5F5F593)';

/** Основной цвет текста на темном фоне */
export const onDarkTextPrimaryActive = 'var(--on-dark-text-primary-active, #F5F5F5C4)';

/** Основной цвет текста на темном фоне */
export const onDarkTextPrimary = 'var(--on-dark-text-primary, #F5F5F5F5)';

/** Вторичный цвет текста на темном фоне */
export const onDarkTextSecondaryHover = 'var(--on-dark-text-secondary-hover, #F5F5F5FF)';

/** Вторичный цвет текста на темном фоне */
export const onDarkTextSecondaryActive = 'var(--on-dark-text-secondary-active, #F5F5F5AB)';

/** Вторичный цвет текста на темном фоне */
export const onDarkTextSecondary = 'var(--on-dark-text-secondary, #F5F5F58F)';

/** Третичный цвет текста на темном фоне */
export const onDarkTextTertiaryHover = 'var(--on-dark-text-tertiary-hover, #F5F5F5FF)';

/** Третичный цвет текста на темном фоне */
export const onDarkTextTertiaryActive = 'var(--on-dark-text-tertiary-active, #F5F5F556)';

/** Третичный цвет текста на темном фоне */
export const onDarkTextTertiary = 'var(--on-dark-text-tertiary, #F5F5F548)';

/** Сплошной наборный текст на темном фоне */
export const onDarkTextParagraphHover = 'var(--on-dark-text-paragraph-hover, #F5F5F57A)';

/** Сплошной наборный текст на темном фоне */
export const onDarkTextParagraphActive = 'var(--on-dark-text-paragraph-active, #F5F5F5A3)';

/** Сплошной наборный текст на темном фоне */
export const onDarkTextParagraph = 'var(--on-dark-text-paragraph, #F5F5F5CC)';

/** Акцентный цвет на темном фоне */
export const onDarkTextAccentHover = 'var(--on-dark-text-accent-hover, #2ACB47FF)';

/** Акцентный цвет на темном фоне */
export const onDarkTextAccentActive = 'var(--on-dark-text-accent-active, #1F9835FF)';

/** Акцентный цвет на темном фоне */
export const onDarkTextAccent = 'var(--on-dark-text-accent, #24B23E)';

/** Цвет успеха на темном фоне */
export const onDarkTextPositiveHover = 'var(--on-dark-text-positive-hover, #2ACB47FF)';

/** Цвет успеха на темном фоне */
export const onDarkTextPositiveActive = 'var(--on-dark-text-positive-active, #1F9835FF)';

/** Цвет успеха на темном фоне */
export const onDarkTextPositive = 'var(--on-dark-text-positive, #24B23E)';

/** Цвет предупреждения на темном фоне */
export const onDarkTextWarningHover = 'var(--on-dark-text-warning-hover, #FF8442FF)';

/** Цвет предупреждения на темном фоне */
export const onDarkTextWarningActive = 'var(--on-dark-text-warning-active, #FF5D05FF)';

/** Цвет предупреждения на темном фоне */
export const onDarkTextWarning = 'var(--on-dark-text-warning, #FF7024)';

/** Цвет ошибки на темном фоне */
export const onDarkTextNegativeHover = 'var(--on-dark-text-negative-hover, #FF5C6CFF)';

/** Цвет ошибки на темном фоне */
export const onDarkTextNegativeActive = 'var(--on-dark-text-negative-active, #FF1F35FF)';

/** Цвет ошибки на темном фоне */
export const onDarkTextNegative = 'var(--on-dark-text-negative, #FF3D51)';

/** Основной цвет текста на светлом фоне */
export const onLightTextPrimaryHover = 'var(--on-light-text-primary-hover, #17171793)';

/** Основной цвет текста на светлом фоне */
export const onLightTextPrimaryActive = 'var(--on-light-text-primary-active, #171717C4)';

/** Основной цвет текста на светлом фоне */
export const onLightTextPrimary = 'var(--on-light-text-primary, #171717F5)';

/** Вторичный цвет текста на светлом фоне */
export const onLightTextSecondaryHover = 'var(--on-light-text-secondary-hover, #171717FF)';

/** Вторичный цвет текста на светлом фоне */
export const onLightTextSecondaryActive = 'var(--on-light-text-secondary-active, #171717AB)';

/** Вторичный цвет текста на светлом фоне */
export const onLightTextSecondary = 'var(--on-light-text-secondary, #1717178F)';

/** Третичный цвет текста на светлом фоне */
export const onLightTextTertiaryHover = 'var(--on-light-text-tertiary-hover, #171717FF)';

/** Третичный цвет текста на светлом фоне */
export const onLightTextTertiaryActive = 'var(--on-light-text-tertiary-active, #17171756)';

/** Третичный цвет текста на светлом фоне */
export const onLightTextTertiary = 'var(--on-light-text-tertiary, #17171748)';

/** Сплошной наборный текст на светлом фоне */
export const onLightTextParagraphHover = 'var(--on-light-text-paragraph-hover, #1717177A)';

/** Сплошной наборный текст на светлом фоне */
export const onLightTextParagraphActive = 'var(--on-light-text-paragraph-active, #171717A3)';

/** Сплошной наборный текст на светлом фоне */
export const onLightTextParagraph = 'var(--on-light-text-paragraph, #171717CC)';

/** Акцентный цвет на светлом фоне */
export const onLightTextAccentHover = 'var(--on-light-text-accent-hover, #13AA2CFF)';

/** Акцентный цвет на светлом фоне */
export const onLightTextAccentActive = 'var(--on-light-text-accent-active, #0D731EFF)';

/** Акцентный цвет на светлом фоне */
export const onLightTextAccent = 'var(--on-light-text-accent, #108E26)';

/** Цвет успеха на светлом фоне */
export const onLightTextPositiveHover = 'var(--on-light-text-positive-hover, #13AA2CFF)';

/** Цвет успеха на светлом фоне */
export const onLightTextPositiveActive = 'var(--on-light-text-positive-active, #0D731EFF)';

/** Цвет успеха на светлом фоне */
export const onLightTextPositive = 'var(--on-light-text-positive, #108E26)';

/** Цвет предупреждения на светлом фоне */
export const onLightTextWarningHover = 'var(--on-light-text-warning-hover, #FD650DFF)';

/** Цвет предупреждения на светлом фоне */
export const onLightTextWarningActive = 'var(--on-light-text-warning-active, #CA4B02FF)';

/** Цвет предупреждения на светлом фоне */
export const onLightTextWarning = 'var(--on-light-text-warning, #E85702)';

/** Цвет ошибки на светлом фоне */
export const onLightTextNegativeHover = 'var(--on-light-text-negative-hover, #F5384BFF)';

/** Цвет ошибки на светлом фоне */
export const onLightTextNegativeActive = 'var(--on-light-text-negative-active, #E40C22FF)';

/** Цвет ошибки на светлом фоне */
export const onLightTextNegative = 'var(--on-light-text-negative, #F31B31)';

/** Инвертированный основной цвет текста */
export const inverseTextPrimaryHover = 'var(--inverse-text-primary-hover, #17171793)';

/** Инвертированный основной цвет текста */
export const inverseTextPrimaryActive = 'var(--inverse-text-primary-active, #171717C4)';

/** Инвертированный основной цвет текста */
export const inverseTextPrimary = 'var(--inverse-text-primary, #171717F5)';

/** Инвертированный вторичный цвет текста */
export const inverseTextSecondaryHover = 'var(--inverse-text-secondary-hover, #171717FF)';

/** Инвертированный вторичный цвет текста */
export const inverseTextSecondaryActive = 'var(--inverse-text-secondary-active, #171717AB)';

/** Инвертированный вторичный цвет текста */
export const inverseTextSecondary = 'var(--inverse-text-secondary, #1717178F)';

/** Инвертированный третичный цвет текста */
export const inverseTextTertiaryHover = 'var(--inverse-text-tertiary-hover, #171717FF)';

/** Инвертированный третичный цвет текста */
export const inverseTextTertiaryActive = 'var(--inverse-text-tertiary-active, #17171756)';

/** Инвертированный третичный цвет текста */
export const inverseTextTertiary = 'var(--inverse-text-tertiary, #17171748)';

/** Инвертированный cплошной наборный текст */
export const inverseTextParagraphHover = 'var(--inverse-text-paragraph-hover, #1717177A)';

/** Инвертированный cплошной наборный текст */
export const inverseTextParagraphActive = 'var(--inverse-text-paragraph-active, #171717A3)';

/** Инвертированный cплошной наборный текст */
export const inverseTextParagraph = 'var(--inverse-text-paragraph, #171717CC)';

/** Инвертированный акцентный цвет */
export const inverseTextAccentHover = 'var(--inverse-text-accent-hover, #13AA2CFF)';

/** Инвертированный акцентный цвет */
export const inverseTextAccentActive = 'var(--inverse-text-accent-active, #0D731EFF)';

/** Инвертированный акцентный цвет */
export const inverseTextAccent = 'var(--inverse-text-accent, #108E26)';

/** Инвертированный цвет успеха */
export const inverseTextPositiveHover = 'var(--inverse-text-positive-hover, #13AA2CFF)';

/** Инвертированный цвет успеха */
export const inverseTextPositiveActive = 'var(--inverse-text-positive-active, #0D731EFF)';

/** Инвертированный цвет успеха */
export const inverseTextPositive = 'var(--inverse-text-positive, #108E26)';

/** Инвертированный цвет предупреждения */
export const inverseTextWarningHover = 'var(--inverse-text-warning-hover, #FD650DFF)';

/** Инвертированный цвет предупреждения */
export const inverseTextWarningActive = 'var(--inverse-text-warning-active, #CA4B02FF)';

/** Инвертированный цвет предупреждения */
export const inverseTextWarning = 'var(--inverse-text-warning, #E85702)';

/** Инвертированный цвет ошибки */
export const inverseTextNegativeHover = 'var(--inverse-text-negative-hover, #F5384BFF)';

/** Инвертированный цвет ошибки */
export const inverseTextNegativeActive = 'var(--inverse-text-negative-active, #E40C22FF)';

/** Инвертированный цвет ошибки */
export const inverseTextNegative = 'var(--inverse-text-negative, #F31B31)';

/** Основной непрозрачный фон поверхности/контрола */
export const surfaceSolidPrimaryHover = 'var(--surface-solid-primary-hover, #1C1C1CFF)';

/** Основной непрозрачный фон поверхности/контрола */
export const surfaceSolidPrimaryActive = 'var(--surface-solid-primary-active, #121212FF)';

/** Основной непрозрачный фон поверхности/контрола */
export const surfaceSolidPrimary = 'var(--surface-solid-primary, #171717)';

/** Вторичный непрозрачный фон поверхности/контрола */
export const surfaceSolidSecondaryHover = 'var(--surface-solid-secondary-hover, #303030FF)';

/** Вторичный непрозрачный фон поверхности/контрола */
export const surfaceSolidSecondaryActive = 'var(--surface-solid-secondary-active, #212121FF)';

/** Вторичный непрозрачный фон поверхности/контрола */
export const surfaceSolidSecondary = 'var(--surface-solid-secondary, #262626)';

/** Третичный непрозрачный фон поверхности/контрола */
export const surfaceSolidTertiaryHover = 'var(--surface-solid-tertiary-hover, #404040FF)';

/** Третичный непрозрачный фон поверхности/контрола */
export const surfaceSolidTertiaryActive = 'var(--surface-solid-tertiary-active, #303030FF)';

/** Третичный непрозрачный фон поверхности/контрола */
export const surfaceSolidTertiary = 'var(--surface-solid-tertiary, #363636)';

/** Основной фон для карточек */
export const surfaceSolidCardHover = 'var(--surface-solid-card-hover, #1C1C1CFF)';

/** Основной фон для карточек */
export const surfaceSolidCardActive = 'var(--surface-solid-card-active, #121212FF)';

/** Основной фон для карточек */
export const surfaceSolidCard = 'var(--surface-solid-card, #171717)';

/** Непрозрачный фон поверхности/контрола по умолчанию */
export const surfaceSolidDefaultHover = 'var(--surface-solid-default-hover, #FFFFFFFF)';

/** Непрозрачный фон поверхности/контрола по умолчанию */
export const surfaceSolidDefaultActive = 'var(--surface-solid-default-active, #F5F5F5FF)';

/** Непрозрачный фон поверхности/контрола по умолчанию */
export const surfaceSolidDefault = 'var(--surface-solid-default, #F9F9F9)';

/** Основной прозрачный фон поверхности/контрола */
export const surfaceTransparentPrimaryHover = 'var(--surface-transparent-primary-hover, #FFFFFF1F)';

/** Основной прозрачный фон поверхности/контрола */
export const surfaceTransparentPrimaryActive = 'var(--surface-transparent-primary-active, #FFFFFF0A)';

/** Основной прозрачный фон поверхности/контрола */
export const surfaceTransparentPrimary = 'var(--surface-transparent-primary, #FFFFFF0F)';

/** Вторичный прозрачный фон поверхности/контрола */
export const surfaceTransparentSecondaryHover = 'var(--surface-transparent-secondary-hover, #FFFFFF3D)';

/** Вторичный прозрачный фон поверхности/контрола */
export const surfaceTransparentSecondaryActive = 'var(--surface-transparent-secondary-active, #FFFFFF0F)';

/** Вторичный прозрачный фон поверхности/контрола */
export const surfaceTransparentSecondary = 'var(--surface-transparent-secondary, #FFFFFF1F)';

/** Третичный прозрачный фон поверхности/контрола */
export const surfaceTransparentTertiaryHover = 'var(--surface-transparent-tertiary-hover, #FFFFFF52)';

/** Третичный прозрачный фон поверхности/контрола */
export const surfaceTransparentTertiaryActive = 'var(--surface-transparent-tertiary-active, #FFFFFF24)';

/** Третичный прозрачный фон поверхности/контрола */
export const surfaceTransparentTertiary = 'var(--surface-transparent-tertiary, #FFFFFF33)';

/** Прозрачный фон поверхности/контрола по умолчанию */
export const surfaceTransparentDeepHover = 'var(--surface-transparent-deep-hover, #FFFFFFC2)';

/** Прозрачный фон поверхности/контрола по умолчанию */
export const surfaceTransparentDeepActive = 'var(--surface-transparent-deep-active, #FFFFFF94)';

/** Прозрачный фон поверхности/контрола по умолчанию */
export const surfaceTransparentDeep = 'var(--surface-transparent-deep, #FFFFFFA3)';

/** Прозрачный фон для карточек */
export const surfaceTransparentCardHover = 'var(--surface-transparent-card-hover, #FFFFFF1F)';

/** Прозрачный фон для карточек */
export const surfaceTransparentCardActive = 'var(--surface-transparent-card-active, #FFFFFF0A)';

/** Прозрачный фон для карточек */
export const surfaceTransparentCard = 'var(--surface-transparent-card, #FFFFFF0F)';

/** Фон поверхности/контрола без заливки */
export const surfaceClearHover = 'var(--surface-clear-hover, #00000000)';

/** Фон поверхности/контрола без заливки */
export const surfaceClearActive = 'var(--surface-clear-active, #00000000)';

/** Фон поверхности/контрола без заливки */
export const surfaceClear = 'var(--surface-clear, #00000000)';

/** Акцентный фон поверхности/контрола */
export const surfaceAccentHover = 'var(--surface-accent-hover, #1DAF37FF)';

/** Акцентный фон поверхности/контрола */
export const surfaceAccentActive = 'var(--surface-accent-active, #18952FFF)';

/** Акцентный фон поверхности/контрола */
export const surfaceAccent = 'var(--surface-accent, #1A9E32)';

/** Цвет фона поверхности/контрола успех */
export const surfacePositiveHover = 'var(--surface-positive-hover, #1DAF37FF)';

/** Цвет фона поверхности/контрола успех */
export const surfacePositiveActive = 'var(--surface-positive-active, #18952FFF)';

/** Цвет фона поверхности/контрола успех */
export const surfacePositive = 'var(--surface-positive, #1A9E32)';

/** Цвет фона поверхности предупреждение */
export const surfaceWarningHover = 'var(--surface-warning-hover, #FB7223FF)';

/** Цвет фона поверхности предупреждение */
export const surfaceWarningActive = 'var(--surface-warning-active, #F05B05FF)';

/** Цвет фона поверхности предупреждение */
export const surfaceWarning = 'var(--surface-warning, #FA5F05)';

/** Цвет фона поверхности/контрола ошибка */
export const surfaceNegativeHover = 'var(--surface-negative-hover, #FF475AFF)';

/** Цвет фона поверхности/контрола ошибка */
export const surfaceNegativeActive = 'var(--surface-negative-active, #FF1F35FF)';

/** Цвет фона поверхности/контрола ошибка */
export const surfaceNegative = 'var(--surface-negative, #FF293E)';

/** Прозрачный цвет фона поверхности/контрола успех */
export const surfaceTransparentPositiveHover = 'var(--surface-transparent-positive-hover, #1A9E323D)';

/** Прозрачный цвет фона поверхности/контрола успех */
export const surfaceTransparentPositiveActive = 'var(--surface-transparent-positive-active, #1A9E320F)';

/** Прозрачный цвет фона поверхности/контрола успех */
export const surfaceTransparentPositive = 'var(--surface-transparent-positive, #1A9E321F)';

/** Прозрачный цвет фона поверхности/контрола предупреждение */
export const surfaceTransparentWarningHover = 'var(--surface-transparent-warning-hover, #FA5F053D)';

/** Прозрачный цвет фона поверхности/контрола предупреждение */
export const surfaceTransparentWarningActive = 'var(--surface-transparent-warning-active, #FA5F050F)';

/** Прозрачный цвет фона поверхности/контрола предупреждение */
export const surfaceTransparentWarning = 'var(--surface-transparent-warning, #FA5F051F)';

/** Прозрачный цвет фона поверхности/контрола предупреждение */
export const surfaceTransparentNegativeHover = 'var(--surface-transparent-negative-hover, #FF293E3D)';

/** Прозрачный цвет фона поверхности/контрола предупреждение */
export const surfaceTransparentNegativeActive = 'var(--surface-transparent-negative-active, #FF293E0F)';

/** Прозрачный цвет фона поверхности/контрола предупреждение */
export const surfaceTransparentNegative = 'var(--surface-transparent-negative, #FF293E1F)';

/** Основной непрозрачный фон поверхности/контрола на темном фоне */
export const onDarkSurfaceSolidPrimaryHover = 'var(--on-dark-surface-solid-primary-hover, #1C1C1CFF)';

/** Основной непрозрачный фон поверхности/контрола на темном фоне */
export const onDarkSurfaceSolidPrimaryActive = 'var(--on-dark-surface-solid-primary-active, #121212FF)';

/** Основной непрозрачный фон поверхности/контрола на темном фоне */
export const onDarkSurfaceSolidPrimary = 'var(--on-dark-surface-solid-primary, #171717)';

/** Вторичный непрозрачный фон поверхности на темном фоне */
export const onDarkSurfaceSolidSecondaryHover = 'var(--on-dark-surface-solid-secondary-hover, #303030FF)';

/** Вторичный непрозрачный фон поверхности на темном фоне */
export const onDarkSurfaceSolidSecondaryActive = 'var(--on-dark-surface-solid-secondary-active, #212121FF)';

/** Вторичный непрозрачный фон поверхности на темном фоне */
export const onDarkSurfaceSolidSecondary = 'var(--on-dark-surface-solid-secondary, #262626)';

/** Третичный непрозрачный фон поверхности/контрола на темном фоне */
export const onDarkSurfaceSolidTertiaryHover = 'var(--on-dark-surface-solid-tertiary-hover, #404040FF)';

/** Третичный непрозрачный фон поверхности/контрола на темном фоне */
export const onDarkSurfaceSolidTertiaryActive = 'var(--on-dark-surface-solid-tertiary-active, #303030FF)';

/** Третичный непрозрачный фон поверхности/контрола на темном фоне */
export const onDarkSurfaceSolidTertiary = 'var(--on-dark-surface-solid-tertiary, #363636)';

/** Основной фон для карточек на темном фоне */
export const onDarkSurfaceSolidCardHover = 'var(--on-dark-surface-solid-card-hover, #1C1C1CFF)';

/** Основной фон для карточек на темном фоне */
export const onDarkSurfaceSolidCardActive = 'var(--on-dark-surface-solid-card-active, #121212FF)';

/** Основной фон для карточек на темном фоне */
export const onDarkSurfaceSolidCard = 'var(--on-dark-surface-solid-card, #171717)';

/** Непрозрачный фон поверхности/контрола по умолчанию на темном фоне */
export const onDarkSurfaceSolidDefaultHover = 'var(--on-dark-surface-solid-default-hover, #FFFFFFFF)';

/** Непрозрачный фон поверхности/контрола по умолчанию на темном фоне */
export const onDarkSurfaceSolidDefaultActive = 'var(--on-dark-surface-solid-default-active, #F5F5F5FF)';

/** Непрозрачный фон поверхности/контрола по умолчанию на темном фоне */
export const onDarkSurfaceSolidDefault = 'var(--on-dark-surface-solid-default, #F9F9F9)';

/** Основной прозрачный фон поверхности/контрола на темном фоне */
export const onDarkSurfaceTransparentPrimaryHover = 'var(--on-dark-surface-transparent-primary-hover, #FFFFFF1F)';

/** Основной прозрачный фон поверхности/контрола на темном фоне */
export const onDarkSurfaceTransparentPrimaryActive = 'var(--on-dark-surface-transparent-primary-active, #FFFFFF0A)';

/** Основной прозрачный фон поверхности/контрола на темном фоне */
export const onDarkSurfaceTransparentPrimary = 'var(--on-dark-surface-transparent-primary, #FFFFFF0F)';

/** Вторичный прозрачный фон поверхности/контрола на темном фоне */
export const onDarkSurfaceTransparentSecondaryHover = 'var(--on-dark-surface-transparent-secondary-hover, #FFFFFF3D)';

/** Вторичный прозрачный фон поверхности/контрола на темном фоне */
export const onDarkSurfaceTransparentSecondaryActive = 'var(--on-dark-surface-transparent-secondary-active, #FFFFFF0F)';

/** Вторичный прозрачный фон поверхности/контрола на темном фоне */
export const onDarkSurfaceTransparentSecondary = 'var(--on-dark-surface-transparent-secondary, #FFFFFF1F)';

/** Третичный прозрачный фон поверхности/контрола на темном фоне */
export const onDarkSurfaceTransparentTertiaryHover = 'var(--on-dark-surface-transparent-tertiary-hover, #FFFFFF52)';

/** Третичный прозрачный фон поверхности/контрола на темном фоне */
export const onDarkSurfaceTransparentTertiaryActive = 'var(--on-dark-surface-transparent-tertiary-active, #FFFFFF24)';

/** Третичный прозрачный фон поверхности/контрола на темном фоне */
export const onDarkSurfaceTransparentTertiary = 'var(--on-dark-surface-transparent-tertiary, #FFFFFF33)';

/** Прозрачный фон поверхности по умолчанию на темном фоне */
export const onDarkSurfaceTransparentDeepHover = 'var(--on-dark-surface-transparent-deep-hover, #FFFFFFC2)';

/** Прозрачный фон поверхности по умолчанию на темном фоне */
export const onDarkSurfaceTransparentDeepActive = 'var(--on-dark-surface-transparent-deep-active, #FFFFFF94)';

/** Прозрачный фон поверхности по умолчанию на темном фоне */
export const onDarkSurfaceTransparentDeep = 'var(--on-dark-surface-transparent-deep, #FFFFFFA3)';

/** Прозрачный фон для карточек на темном фоне */
export const onDarkSurfaceTransparentCardHover = 'var(--on-dark-surface-transparent-card-hover, #FFFFFF1F)';

/** Прозрачный фон для карточек на темном фоне */
export const onDarkSurfaceTransparentCardActive = 'var(--on-dark-surface-transparent-card-active, #FFFFFF0A)';

/** Прозрачный фон для карточек на темном фоне */
export const onDarkSurfaceTransparentCard = 'var(--on-dark-surface-transparent-card, #FFFFFF0F)';

/** Фон поверхности/контрола без заливки на темном фоне */
export const onDarkSurfaceClearHover = 'var(--on-dark-surface-clear-hover, #00000000)';

/** Фон поверхности/контрола без заливки на темном фоне */
export const onDarkSurfaceClearActive = 'var(--on-dark-surface-clear-active, #00000000)';

/** Фон поверхности/контрола без заливки на темном фоне */
export const onDarkSurfaceClear = 'var(--on-dark-surface-clear, #00000000)';

/** Акцентный фон поверхности/контрола на темном фоне */
export const onDarkSurfaceAccentHover = 'var(--on-dark-surface-accent-hover, #1DAF37FF)';

/** Акцентный фон поверхности/контрола на темном фоне */
export const onDarkSurfaceAccentActive = 'var(--on-dark-surface-accent-active, #18952FFF)';

/** Акцентный фон поверхности/контрола на темном фоне */
export const onDarkSurfaceAccent = 'var(--on-dark-surface-accent, #1A9E32)';

/** Цвет фона поверхности/контрола успех на темном фоне */
export const onDarkSurfacePositiveHover = 'var(--on-dark-surface-positive-hover, #1DAF37FF)';

/** Цвет фона поверхности/контрола успех на темном фоне */
export const onDarkSurfacePositiveActive = 'var(--on-dark-surface-positive-active, #18952FFF)';

/** Цвет фона поверхности/контрола успех на темном фоне */
export const onDarkSurfacePositive = 'var(--on-dark-surface-positive, #1A9E32)';

/** Цвет фона поверхности предупреждение на темном фоне */
export const onDarkSurfaceWarningHover = 'var(--on-dark-surface-warning-hover, #FB7223FF)';

/** Цвет фона поверхности предупреждение на темном фоне */
export const onDarkSurfaceWarningActive = 'var(--on-dark-surface-warning-active, #F05B05FF)';

/** Цвет фона поверхности предупреждение на темном фоне */
export const onDarkSurfaceWarning = 'var(--on-dark-surface-warning, #FA5F05)';

/** Цвет фона поверхности/контрола ошибка на темном фоне */
export const onDarkSurfaceNegativeHover = 'var(--on-dark-surface-negative-hover, #FF475AFF)';

/** Цвет фона поверхности/контрола ошибка на темном фоне */
export const onDarkSurfaceNegativeActive = 'var(--on-dark-surface-negative-active, #FF1F35FF)';

/** Цвет фона поверхности/контрола ошибка на темном фоне */
export const onDarkSurfaceNegative = 'var(--on-dark-surface-negative, #FF293E)';

/** Основной непрозрачный фон поверхности на светлом фоне */
export const onLightSurfaceSolidPrimaryHover = 'var(--on-light-surface-solid-primary-hover, #FAFAFAFF)';

/** Основной непрозрачный фон поверхности на светлом фоне */
export const onLightSurfaceSolidPrimaryActive = 'var(--on-light-surface-solid-primary-active, #F0F0F0FF)';

/** Основной непрозрачный фон поверхности на светлом фоне */
export const onLightSurfaceSolidPrimary = 'var(--on-light-surface-solid-primary, #F5F5F5)';

/** Вторичный непрозрачный фон поверхности на светлом фоне */
export const onLightSurfaceSolidSecondaryHover = 'var(--on-light-surface-solid-secondary-hover, #F7F7F7FF)';

/** Вторичный непрозрачный фон поверхности на светлом фоне */
export const onLightSurfaceSolidSecondaryActive = 'var(--on-light-surface-solid-secondary-active, #E8E8E8FF)';

/** Вторичный непрозрачный фон поверхности на светлом фоне */
export const onLightSurfaceSolidSecondary = 'var(--on-light-surface-solid-secondary, #ECECEC)';

/** Третичный непрозрачный фон поверхности на светлом фоне */
export const onLightSurfaceSolidTertiaryHover = 'var(--on-light-surface-solid-tertiary-hover, #E8E8E8FF)';

/** Третичный непрозрачный фон поверхности на светлом фоне */
export const onLightSurfaceSolidTertiaryActive = 'var(--on-light-surface-solid-tertiary-active, #D9D9D9FF)';

/** Третичный непрозрачный фон поверхности на светлом фоне */
export const onLightSurfaceSolidTertiary = 'var(--on-light-surface-solid-tertiary, #DDDDDD)';

/** Основной фон для карточек на светлом фоне */
export const onLightSurfaceSolidCardHover = 'var(--on-light-surface-solid-card-hover, #FFFFFFFF)';

/** Основной фон для карточек на светлом фоне */
export const onLightSurfaceSolidCardActive = 'var(--on-light-surface-solid-card-active, #FFFFFFFF)';

/** Основной фон для карточек на светлом фоне */
export const onLightSurfaceSolidCard = 'var(--on-light-surface-solid-card, #FFFFFFFF)';

/** Непрозрачный фон поверхности/контрола по умолчанию на светлом фоне */
export const onLightSurfaceSolidDefaultHover = 'var(--on-light-surface-solid-default-hover, #0D0D0DFF)';

/** Непрозрачный фон поверхности/контрола по умолчанию на светлом фоне */
export const onLightSurfaceSolidDefaultActive = 'var(--on-light-surface-solid-default-active, #030303FF)';

/** Непрозрачный фон поверхности/контрола по умолчанию на светлом фоне */
export const onLightSurfaceSolidDefault = 'var(--on-light-surface-solid-default, #080808)';

/** Основной прозрачный фон поверхности/контрола на светлом фоне */
export const onLightSurfaceTransparentPrimaryHover = 'var(--on-light-surface-transparent-primary-hover, #0808080F)';

/** Основной прозрачный фон поверхности/контрола на светлом фоне */
export const onLightSurfaceTransparentPrimaryActive = 'var(--on-light-surface-transparent-primary-active, #08080800)';

/** Основной прозрачный фон поверхности/контрола на светлом фоне */
export const onLightSurfaceTransparentPrimary = 'var(--on-light-surface-transparent-primary, #08080805)';

/** Вторичный прозрачный фон поверхности/контрола на светлом фоне */
export const onLightSurfaceTransparentSecondaryHover = 'var(--on-light-surface-transparent-secondary-hover, #0808081F)';

/** Вторичный прозрачный фон поверхности/контрола на светлом фоне */
export const onLightSurfaceTransparentSecondaryActive =
    'var(--on-light-surface-transparent-secondary-active, #0808080A)';

/** Вторичный прозрачный фон поверхности/контрола на светлом фоне */
export const onLightSurfaceTransparentSecondary = 'var(--on-light-surface-transparent-secondary, #0808080F)';

/** Третичный прозрачный фон поверхности/контрола на светлом фоне */
export const onLightSurfaceTransparentTertiaryHover = 'var(--on-light-surface-transparent-tertiary-hover, #0808083D)';

/** Третичный прозрачный фон поверхности/контрола на светлом фоне */
export const onLightSurfaceTransparentTertiaryActive = 'var(--on-light-surface-transparent-tertiary-active, #0808080F)';

/** Третичный прозрачный фон поверхности/контрола на светлом фоне */
export const onLightSurfaceTransparentTertiary = 'var(--on-light-surface-transparent-tertiary, #0808081F)';

/** Прозрачный фон поверхности по умолчанию на светлом фоне */
export const onLightSurfaceTransparentDeepHover = 'var(--on-light-surface-transparent-deep-hover, #080808C2)';

/** Прозрачный фон поверхности по умолчанию на светлом фоне */
export const onLightSurfaceTransparentDeepActive = 'var(--on-light-surface-transparent-deep-active, #08080894)';

/** Прозрачный фон поверхности по умолчанию на светлом фоне */
export const onLightSurfaceTransparentDeep = 'var(--on-light-surface-transparent-deep, #080808A3)';

/** Прозрачный фон для карточек на светлом фоне */
export const onLightSurfaceTransparentCardHover = 'var(--on-light-surface-transparent-card-hover, #0808081F)';

/** Прозрачный фон для карточек на светлом фоне */
export const onLightSurfaceTransparentCardActive = 'var(--on-light-surface-transparent-card-active, #0808080A)';

/** Прозрачный фон для карточек на светлом фоне */
export const onLightSurfaceTransparentCard = 'var(--on-light-surface-transparent-card, #0808080F)';

/** Фон поверхности/контрола без заливки на светлом фоне */
export const onLightSurfaceClearHover = 'var(--on-light-surface-clear-hover, #00000000)';

/** Фон поверхности/контрола без заливки на светлом фоне */
export const onLightSurfaceClearActive = 'var(--on-light-surface-clear-active, #00000000)';

/** Фон поверхности/контрола без заливки на светлом фоне */
export const onLightSurfaceClear = 'var(--on-light-surface-clear, #00000000)';

/** Акцентный фон поверхности/контрола на светлом фоне */
export const onLightSurfaceAccentHover = 'var(--on-light-surface-accent-hover, #1DAF37FF)';

/** Акцентный фон поверхности/контрола на светлом фоне */
export const onLightSurfaceAccentActive = 'var(--on-light-surface-accent-active, #18952FFF)';

/** Акцентный фон поверхности/контрола на светлом фоне */
export const onLightSurfaceAccent = 'var(--on-light-surface-accent, #1A9E32)';

/** Цвет фона поверхности/контрола успех на светлом фоне */
export const onLightSurfacePositiveHover = 'var(--on-light-surface-positive-hover, #1DAF37FF)';

/** Цвет фона поверхности/контрола успех на светлом фоне */
export const onLightSurfacePositiveActive = 'var(--on-light-surface-positive-active, #18952FFF)';

/** Цвет фона поверхности/контрола успех на светлом фоне */
export const onLightSurfacePositive = 'var(--on-light-surface-positive, #1A9E32)';

/** Цвет фона поверхности / предупреждение на светлом фоне */
export const onLightSurfaceWarningHover = 'var(--on-light-surface-warning-hover, #FB7223FF)';

/** Цвет фона поверхности / предупреждение на светлом фоне */
export const onLightSurfaceWarningActive = 'var(--on-light-surface-warning-active, #F05B05FF)';

/** Цвет фона поверхности / предупреждение на светлом фоне */
export const onLightSurfaceWarning = 'var(--on-light-surface-warning, #FA5F05)';

/** Цвет фона поверхности/контрола ошибка на светлом фоне */
export const onLightSurfaceNegativeHover = 'var(--on-light-surface-negative-hover, #FF475AFF)';

/** Цвет фона поверхности/контрола ошибка на светлом фоне */
export const onLightSurfaceNegativeActive = 'var(--on-light-surface-negative-active, #FF1F35FF)';

/** Цвет фона поверхности/контрола ошибка на светлом фоне */
export const onLightSurfaceNegative = 'var(--on-light-surface-negative, #FF293E)';

/** Инвертированный основной непрозрачный фон поверхности */
export const inverseSurfaceSolidPrimaryHover = 'var(--inverse-surface-solid-primary-hover, #FAFAFAFF)';

/** Инвертированный основной непрозрачный фон поверхности */
export const inverseSurfaceSolidPrimaryActive = 'var(--inverse-surface-solid-primary-active, #F0F0F0FF)';

/** Инвертированный основной непрозрачный фон поверхности */
export const inverseSurfaceSolidPrimary = 'var(--inverse-surface-solid-primary, #F5F5F5)';

/** Инвертированный вторичный непрозрачный фон поверхности */
export const inverseSurfaceSolidSecondaryHover = 'var(--inverse-surface-solid-secondary-hover, #F7F7F7FF)';

/** Инвертированный вторичный непрозрачный фон поверхности */
export const inverseSurfaceSolidSecondaryActive = 'var(--inverse-surface-solid-secondary-active, #E8E8E8FF)';

/** Инвертированный вторичный непрозрачный фон поверхности */
export const inverseSurfaceSolidSecondary = 'var(--inverse-surface-solid-secondary, #ECECEC)';

/** Инвертированный третичный непрозрачный фон поверхности */
export const inverseSurfaceSolidTertiaryHover = 'var(--inverse-surface-solid-tertiary-hover, #E8E8E8FF)';

/** Инвертированный третичный непрозрачный фон поверхности */
export const inverseSurfaceSolidTertiaryActive = 'var(--inverse-surface-solid-tertiary-active, #D9D9D9FF)';

/** Инвертированный третичный непрозрачный фон поверхности */
export const inverseSurfaceSolidTertiary = 'var(--inverse-surface-solid-tertiary, #DDDDDD)';

/** Инвертированный основной фон для карточек */
export const inverseSurfaceSolidCardHover = 'var(--inverse-surface-solid-card-hover, #FFFFFFFF)';

/** Инвертированный основной фон для карточек */
export const inverseSurfaceSolidCardActive = 'var(--inverse-surface-solid-card-active, #FFFFFFFF)';

/** Инвертированный основной фон для карточек */
export const inverseSurfaceSolidCard = 'var(--inverse-surface-solid-card, #FFFFFFFF)';

/** Инвертированный непрозрачный фон поверхности/контрола по умолчанию */
export const inverseSurfaceSolidDefaultHover = 'var(--inverse-surface-solid-default-hover, #0D0D0DFF)';

/** Инвертированный непрозрачный фон поверхности/контрола по умолчанию */
export const inverseSurfaceSolidDefaultActive = 'var(--inverse-surface-solid-default-active, #030303FF)';

/** Инвертированный непрозрачный фон поверхности/контрола по умолчанию */
export const inverseSurfaceSolidDefault = 'var(--inverse-surface-solid-default, #080808)';

/** Инвертированный основной прозрачный фон поверхности/контрола */
export const inverseSurfaceTransparentPrimaryHover = 'var(--inverse-surface-transparent-primary-hover, #0808080F)';

/** Инвертированный основной прозрачный фон поверхности/контрола */
export const inverseSurfaceTransparentPrimaryActive = 'var(--inverse-surface-transparent-primary-active, #08080800)';

/** Инвертированный основной прозрачный фон поверхности/контрола */
export const inverseSurfaceTransparentPrimary = 'var(--inverse-surface-transparent-primary, #08080805)';

/** Инвертированный вторичный прозрачный фон поверхности/контрола */
export const inverseSurfaceTransparentSecondaryHover = 'var(--inverse-surface-transparent-secondary-hover, #0808081F)';

/** Инвертированный вторичный прозрачный фон поверхности/контрола */
export const inverseSurfaceTransparentSecondaryActive =
    'var(--inverse-surface-transparent-secondary-active, #0808080A)';

/** Инвертированный вторичный прозрачный фон поверхности/контрола */
export const inverseSurfaceTransparentSecondary = 'var(--inverse-surface-transparent-secondary, #0808080F)';

/** Инвертированный третичный прозрачный фон поверхности/контрола */
export const inverseSurfaceTransparentTertiaryHover = 'var(--inverse-surface-transparent-tertiary-hover, #0808083D)';

/** Инвертированный третичный прозрачный фон поверхности/контрола */
export const inverseSurfaceTransparentTertiaryActive = 'var(--inverse-surface-transparent-tertiary-active, #0808080F)';

/** Инвертированный третичный прозрачный фон поверхности/контрола */
export const inverseSurfaceTransparentTertiary = 'var(--inverse-surface-transparent-tertiary, #0808081F)';

/** Инвертированный прозрачный фон поверхности по умолчанию */
export const inverseSurfaceTransparentDeepHover = 'var(--inverse-surface-transparent-deep-hover, #080808C2)';

/** Инвертированный прозрачный фон поверхности по умолчанию */
export const inverseSurfaceTransparentDeepActive = 'var(--inverse-surface-transparent-deep-active, #08080894)';

/** Инвертированный прозрачный фон поверхности по умолчанию */
export const inverseSurfaceTransparentDeep = 'var(--inverse-surface-transparent-deep, #080808A3)';

/** Инвертированный прозрачный фон для карточек */
export const inverseSurfaceTransparentCardHover = 'var(--inverse-surface-transparent-card-hover, #FFFFFFFF)';

/** Инвертированный прозрачный фон для карточек */
export const inverseSurfaceTransparentCardActive = 'var(--inverse-surface-transparent-card-active, #FFFFFFFF)';

/** Инвертированный прозрачный фон для карточек */
export const inverseSurfaceTransparentCard = 'var(--inverse-surface-transparent-card, #FFFFFFFF)';

/** Инвертированный фон поверхности/контрола без заливки */
export const inverseSurfaceClearHover = 'var(--inverse-surface-clear-hover, #00000000)';

/** Инвертированный фон поверхности/контрола без заливки */
export const inverseSurfaceClearActive = 'var(--inverse-surface-clear-active, #00000000)';

/** Инвертированный фон поверхности/контрола без заливки */
export const inverseSurfaceClear = 'var(--inverse-surface-clear, #00000000)';

/** Инвертированный акцентный фон поверхности/контрола */
export const inverseSurfaceAccentHover = 'var(--inverse-surface-accent-hover, #1DAF37FF)';

/** Инвертированный акцентный фон поверхности/контрола */
export const inverseSurfaceAccentActive = 'var(--inverse-surface-accent-active, #18952FFF)';

/** Инвертированный акцентный фон поверхности/контрола */
export const inverseSurfaceAccent = 'var(--inverse-surface-accent, #1A9E32)';

/** Инвертированный цвет фона поверхности/контрола успех */
export const inverseSurfacePositiveHover = 'var(--inverse-surface-positive-hover, #1DAF37FF)';

/** Инвертированный цвет фона поверхности/контрола успех */
export const inverseSurfacePositiveActive = 'var(--inverse-surface-positive-active, #18952FFF)';

/** Инвертированный цвет фона поверхности/контрола успех */
export const inverseSurfacePositive = 'var(--inverse-surface-positive, #1A9E32)';

/** Инвертированный цвет фона поверхности / предупреждение */
export const inverseSurfaceWarningHover = 'var(--inverse-surface-warning-hover, #FB7223FF)';

/** Инвертированный цвет фона поверхности / предупреждение */
export const inverseSurfaceWarningActive = 'var(--inverse-surface-warning-active, #F05B05FF)';

/** Инвертированный цвет фона поверхности / предупреждение */
export const inverseSurfaceWarning = 'var(--inverse-surface-warning, #FA5F05)';

/** Инвертированный цвет фона поверхности/контрола ошибка */
export const inverseSurfaceNegativeHover = 'var(--inverse-surface-negative-hover, #FF475AFF)';

/** Инвертированный цвет фона поверхности/контрола ошибка */
export const inverseSurfaceNegativeActive = 'var(--inverse-surface-negative-active, #FF1F35FF)';

/** Инвертированный цвет фона поверхности/контрола ошибка */
export const inverseSurfaceNegative = 'var(--inverse-surface-negative, #FF293E)';

/** Основной фон */
export const backgroundPrimary = 'var(--background-primary, #080808)';

/** Основной фон на темном фоне */
export const darkBackgroundPrimary = 'var(--dark-background-primary, #080808)';

/** Основной фон на светлом фоне */
export const lightBackgroundPrimary = 'var(--light-background-primary, #F9F9F9)';

/** Инвертированный основной фон */
export const inverseBackgroundPrimary = 'var(--inverse-background-primary, #F9F9F9)';

/** Цвет фона паранжи светлый */
export const overlaySoft = 'var(--overlay-soft, #0808088F)';

/** Цвет фона паранжи темный */
export const overlayHard = 'var(--overlay-hard, #080808F5)';

/** dark overlay default overlayBlur */
export const overlayBlur = 'var(--overlay-blur, #08080847)';

/** Цвет фона паранжи светлый на темном фоне */
export const onDarkOverlaySoft = 'var(--on-dark-overlay-soft, #0808088F)';

/** Цвет фона паранжи темный на темном фоне */
export const onDarkOverlayHard = 'var(--on-dark-overlay-hard, #080808F5)';

/** dark overlay onDark overlayBlur */
export const onDarkOverlayBlur = 'var(--on-dark-overlay-blur, #08080847)';

/** Цвет фона паранжи светлый на светлом фоне */
export const onLightOverlaySoft = 'var(--on-light-overlay-soft, #F9F9F98F)';

/** Цвет фона паранжи темный на светлом фоне */
export const onLightOverlayHard = 'var(--on-light-overlay-hard, #F9F9F9F5)';

/** dark overlay onLight overlayBlur */
export const onLightOverlayBlur = 'var(--on-light-overlay-blur, #F9F9F947)';

/** Инвертированный цвет фона паранжи светлый */
export const inverseOverlaySoft = 'var(--inverse-overlay-soft, #F9F9F98F)';

/** Инвертированный цвет фона паранжи темный */
export const inverseOverlayHard = 'var(--inverse-overlay-hard, #F9F9F9F5)';

/** dark overlay inverse overlayBlur */
export const inverseOverlayBlur = 'var(--inverse-overlay-blur, #F9F9F947)';

/** Акцентный цвет с градиентом */
export const textAccentGradientHover = 'var(--text-accent-gradient-hover, #CCCCCCFF)';

/** Акцентный цвет с градиентом */
export const textAccentGradientActive = 'var(--text-accent-gradient-active, #E6E6E6FF)';

/** Акцентный цвет с градиентом */
export const textAccentGradient = 'var(--text-accent-gradient, linear-gradient(45deg, #1A9E32FF 0%, #04C6C9FF 100%))';

/** Акцентный цвет с градиентом на темном фоне */
export const onDarkTextAccentGradientHover = 'var(--on-dark-text-accent-gradient-hover, #CCCCCCFF)';

/** Акцентный цвет с градиентом на темном фоне */
export const onDarkTextAccentGradientActive = 'var(--on-dark-text-accent-gradient-active, #E6E6E6FF)';

/** Акцентный цвет с градиентом на темном фоне */
export const onDarkTextAccentGradient =
    'var(--on-dark-text-accent-gradient, linear-gradient(45deg, #1A9E32FF 0%, #04C6C9FF 100%))';

/** Акцентный цвет с градиентом на светлом фоне */
export const onLightTextAccentGradientHover = 'var(--on-light-text-accent-gradient-hover, #CCCCCCFF)';

/** Акцентный цвет с градиентом на светлом фоне */
export const onLightTextAccentGradientActive = 'var(--on-light-text-accent-gradient-active, #E6E6E6FF)';

/** Акцентный цвет с градиентом на светлом фоне */
export const onLightTextAccentGradient =
    'var(--on-light-text-accent-gradient, linear-gradient(45deg, #0D8523FF 0%, #0DA8ABFF 100%))';

/** Инвертированный акцентный цвет с градиентом */
export const inverseTextAccentGradientHover = 'var(--inverse-text-accent-gradient-hover, #CCCCCCFF)';

/** Инвертированный акцентный цвет с градиентом */
export const inverseTextAccentGradientActive = 'var(--inverse-text-accent-gradient-active, #E6E6E6FF)';

/** Инвертированный акцентный цвет с градиентом */
export const inverseTextAccentGradient =
    'var(--inverse-text-accent-gradient, linear-gradient(45deg, #0D8523FF 0%, #0DA8ABFF 100%))';

/** Акцентный фон поверхности/контрола с градиентом */
export const surfaceAccentGradientHover = 'var(--surface-accent-gradient-hover, #FFFFFFFF)';

/** Акцентный фон поверхности/контрола с градиентом */
export const surfaceAccentGradientActive = 'var(--surface-accent-gradient-active, #FFFFFFFF)';

/** Акцентный фон поверхности/контрола с градиентом */
export const surfaceAccentGradient =
    'var(--surface-accent-gradient, linear-gradient(45deg, #1A9E32FF 0%, #04C6C9FF 100%))';

/** Фон для скелетона */
export const surfaceSkeletonGradient =
    'var(--surface-skeleton-gradient, linear-gradient(90deg, #FFFFFF17 0%, #FFFFFF14 6.25%, #FFFFFF0D 12.5%, #FFFFFF03 25%, #FFFFFF0D 37.5%, #FFFFFF14 43.75%, #FFFFFF17 50%, #FFFFFF14 56.25%, #FFFFFF0D 62.5%, #FFFFFF03 75%, #FFFFFF0D 87.5%, #FFFFFF14 93.75%, #FFFFFF17 100%))';

/** Фон для скелетона */
export const surfaceSkeletonGradientHover = 'var(--surface-skeleton-gradient-hover, #FFFFFFFF)';

/** Фон для скелетона */
export const surfaceSkeletonGradientActive = 'var(--surface-skeleton-gradient-active, #FFFFFFFF)';

/** Яркий фон для скелетона */
export const surfaceSkeletonDeepGradient =
    'var(--surface-skeleton-deep-gradient, linear-gradient(90deg, #FFFFFF5C 0%, #FFFFFF52 6.25%, #FFFFFF33 12.5%, #FFFFFF0A 25%, #FFFFFF33 37.5%, #FFFFFF52 43.75%, #FFFFFF5C 50%, #FFFFFF14 56.25%, #FFFFFF33 62.5%, #FFFFFF0A 75%, #FFFFFF33 87.5%, #FFFFFF52 93.75%, #FFFFFF5C 100%))';

/** Яркий фон для скелетона */
export const surfaceSkeletonDeepGradientHover = 'var(--surface-skeleton-deep-gradient-hover, #FFFFFFFF)';

/** Яркий фон для скелетона */
export const surfaceSkeletonDeepGradientActive = 'var(--surface-skeleton-deep-gradient-active, #FFFFFFFF)';

/** Акцентный фон поверхности/контрола с градиентом на темном фоне */
export const onDarkSurfaceAccentGradientHover = 'var(--on-dark-surface-accent-gradient-hover, #FFFFFFFF)';

/** Акцентный фон поверхности/контрола с градиентом на темном фоне */
export const onDarkSurfaceAccentGradientActive = 'var(--on-dark-surface-accent-gradient-active, #FFFFFFFF)';

/** Акцентный фон поверхности/контрола с градиентом на темном фоне */
export const onDarkSurfaceAccentGradient =
    'var(--on-dark-surface-accent-gradient, linear-gradient(45deg, #1A9E32FF 0%, #04C6C9FF 100%))';

/** Фон для скелетона */
export const onDarkSurfaceSkeletonGradient =
    'var(--on-dark-surface-skeleton-gradient, linear-gradient(90deg, #FFFFFF17 0%, #FFFFFF14 6.25%, #FFFFFF0D 12.5%, #FFFFFF03 25%, #FFFFFF0D 37.5%, #FFFFFF14 43.75%, #FFFFFF17 50%, #FFFFFF14 56.25%, #FFFFFF0D 62.5%, #FFFFFF03 75%, #FFFFFF0D 87.5%, #FFFFFF14 93.75%, #FFFFFF17 100%))';

/** Фон для скелетона */
export const onDarkSurfaceSkeletonGradientHover = 'var(--on-dark-surface-skeleton-gradient-hover, #FFFFFFFF)';

/** Фон для скелетона */
export const onDarkSurfaceSkeletonGradientActive = 'var(--on-dark-surface-skeleton-gradient-active, #FFFFFFFF)';

/** Яркий фон для скелетона */
export const onDarkSurfaceSkeletonDeepGradient =
    'var(--on-dark-surface-skeleton-deep-gradient, linear-gradient(90deg, #FFFFFF5C 0%, #FFFFFF52 6.25%, #FFFFFF33 12.5%, #FFFFFF0A 25%, #FFFFFF33 37.5%, #FFFFFF52 43.75%, #FFFFFF5C 50%, #FFFFFF14 56.25%, #FFFFFF33 62.5%, #FFFFFF0A 75%, #FFFFFF33 87.5%, #FFFFFF52 93.75%, #FFFFFF5C 100%))';

/** Яркий фон для скелетона */
export const onDarkSurfaceSkeletonDeepGradientHover = 'var(--on-dark-surface-skeleton-deep-gradient-hover, #FFFFFFFF)';

/** Яркий фон для скелетона */
export const onDarkSurfaceSkeletonDeepGradientActive =
    'var(--on-dark-surface-skeleton-deep-gradient-active, #FFFFFFFF)';

/** Акцентный фон поверхности/контрола с градиентом на светлом фоне */
export const onLightSurfaceAccentGradientHover = 'var(--on-light-surface-accent-gradient-hover, #FFFFFFFF)';

/** Акцентный фон поверхности/контрола с градиентом на светлом фоне */
export const onLightSurfaceAccentGradientActive = 'var(--on-light-surface-accent-gradient-active, #FFFFFFFF)';

/** Акцентный фон поверхности/контрола с градиентом на светлом фоне */
export const onLightSurfaceAccentGradient =
    'var(--on-light-surface-accent-gradient, linear-gradient(45deg, #1A9E32FF 0%, #04C6C9FF 100%))';

/** Фон для скелетона */
export const onLightSurfaceSkeletonGradient =
    'var(--on-light-surface-skeleton-gradient, linear-gradient(90deg, #08080817 0%, #08080814 6.25%, #0808080D 12.5%, #08080803 25%, #0808080D 37.5%, #08080814 43.75%, #08080817 50%, #08080814 56.25%, #0808080D 62.5%, #08080803 75%, #0808080D 87.5%, #08080814 93.75%, #08080817 100%))';

/** Фон для скелетона */
export const onLightSurfaceSkeletonGradientHover = 'var(--on-light-surface-skeleton-gradient-hover, #FFFFFFFF)';

/** Фон для скелетона */
export const onLightSurfaceSkeletonGradientActive = 'var(--on-light-surface-skeleton-gradient-active, #FFFFFFFF)';

/** Яркий фон для скелетона */
export const onLightSurfaceSkeletonDeepGradient =
    'var(--on-light-surface-skeleton-deep-gradient, linear-gradient(90deg, #0808085C 0%, #08080852 6.25%, #08080833 12.5%, #0808080A 25%, #08080833 37.5%, #08080852 43.75%, #0808085C 50%, #08080814 56.25%, #08080833 62.5%, #0808080A 75%, #08080833 87.5%, #08080852 93.75%, #0808085C 100%))';

/** Яркий фон для скелетона */
export const onLightSurfaceSkeletonDeepGradientHover =
    'var(--on-light-surface-skeleton-deep-gradient-hover, #FFFFFFFF)';

/** Яркий фон для скелетона */
export const onLightSurfaceSkeletonDeepGradientActive =
    'var(--on-light-surface-skeleton-deep-gradient-active, #FFFFFFFF)';

/** Инвертированный акцентный фон поверхности/контрола с градиентом */
export const inverseSurfaceAccentGradientHover = 'var(--inverse-surface-accent-gradient-hover, #FFFFFFFF)';

/** Инвертированный акцентный фон поверхности/контрола с градиентом */
export const inverseSurfaceAccentGradientActive = 'var(--inverse-surface-accent-gradient-active, #FFFFFFFF)';

/** Инвертированный акцентный фон поверхности/контрола с градиентом */
export const inverseSurfaceAccentGradient =
    'var(--inverse-surface-accent-gradient, linear-gradient(45deg, #1A9E32FF 0%, #04C6C9FF 100%))';

/** Фон для скелетона */
export const inverseSurfaceSkeletonGradient =
    'var(--inverse-surface-skeleton-gradient, linear-gradient(90deg, #08080817 0%, #08080814 6.25%, #0808080D 12.5%, #08080803 25%, #0808080D 37.5%, #08080814 43.75%, #08080817 50%, #08080814 56.25%, #0808080D 62.5%, #08080803 75%, #0808080D 87.5%, #08080814 93.75%, #08080817 100%))';

/** Фон для скелетона */
export const inverseSurfaceSkeletonGradientHover = 'var(--inverse-surface-skeleton-gradient-hover, #FFFFFFFF)';

/** Фон для скелетона */
export const inverseSurfaceSkeletonGradientActive = 'var(--inverse-surface-skeleton-gradient-active, #FFFFFFFF)';

/** Яркий фон для скелетона */
export const inverseSurfaceSkeletonDeepGradient =
    'var(--inverse-surface-skeleton-deep-gradient, linear-gradient(90deg, #0808085C 0%, #08080852 6.25%, #08080833 12.5%, #0808080A 25%, #08080833 37.5%, #08080852 43.75%, #0808085C 50%, #08080814 56.25%, #08080833 62.5%, #0808080A 75%, #08080833 87.5%, #08080852 93.75%, #0808085C 100%))';

/** Яркий фон для скелетона */
export const inverseSurfaceSkeletonDeepGradientHover = 'var(--inverse-surface-skeleton-deep-gradient-hover, #FFFFFFFF)';

/** Яркий фон для скелетона */
export const inverseSurfaceSkeletonDeepGradientActive =
    'var(--inverse-surface-skeleton-deep-gradient-active, #FFFFFFFF)';

/** shadow down soft s */
export const shadowDownSoftS = 'var(--shadow-down-soft-s, 0px 4px 14px -4px #08080814,0px 1px 4px -1px #0000000A)';

/** shadow down soft m */
export const shadowDownSoftM = 'var(--shadow-down-soft-m, 0px 24px 48px -8px #00000014)';

/** shadow down soft l */
export const shadowDownSoftL = 'var(--shadow-down-soft-l, 0px 60px 112px -8px #00000014)';

/** shadow down hard s */
export const shadowDownHardS = 'var(--shadow-down-hard-s, 0px 4px 12px -3px #08080829,0px 1px 4px -2px #00000014)';

/** shadow down hard m */
export const shadowDownHardM = 'var(--shadow-down-hard-m, 0px 16px 32px -8px #0000003D)';

/** shadow down hard l */
export const shadowDownHardL = 'var(--shadow-down-hard-l, 0px 60px 112px -8px #00000066)';

/** shadow up soft s */
export const shadowUpSoftS = 'var(--shadow-up-soft-s, 0px -4px 14px -4px #08080814,0px -1px 4px -1px #00000008)';

/** shadow up soft m */
export const shadowUpSoftM = 'var(--shadow-up-soft-m, 0px -24px 48px -8px #00000014)';

/** shadow up soft l */
export const shadowUpSoftL = 'var(--shadow-up-soft-l, 0px -60px 112px -8px #00000014)';

/** shadow up hard s */
export const shadowUpHardS = 'var(--shadow-up-hard-s, 0px -4px 12px -3px #08080833,0px -1px 4px -1px #00000008)';

/** shadow up hard m */
export const shadowUpHardM = 'var(--shadow-up-hard-m, 0px -16px 32px -8px #0000003D)';

/** shadow up hard l */
export const shadowUpHardL = 'var(--shadow-up-hard-l, 0px -60px 112px -8px #00000066)';

/** borderRadius xxs */
export const borderRadiusXxs = 'var(--border-radius-xxs, 4px)';

/** borderRadius xs */
export const borderRadiusXs = 'var(--border-radius-xs, 8px)';

/** borderRadius s */
export const borderRadiusS = 'var(--border-radius-s, 12px)';

/** borderRadius m */
export const borderRadiusM = 'var(--border-radius-m, 16px)';

/** borderRadius l */
export const borderRadiusL = 'var(--border-radius-l, 20px)';

/** borderRadius xl */
export const borderRadiusXl = 'var(--border-radius-xl, 24px)';

/** borderRadius xxl */
export const borderRadiusXxl = 'var(--border-radius-xxl, 32px)';

/** typography s display-l */
export const dsplL = {
    fontFamily: 'var(--plasma-typo-dspl-l-font-family)',
    fontSize: 'var(--plasma-typo-dspl-l-font-size)',
    fontStyle: 'var(--plasma-typo-dspl-l-font-style)',
    fontWeight: 'var(--plasma-typo-dspl-l-font-weight)',
    letterSpacing: 'var(--plasma-typo-dspl-l-letter-spacing)',
    lineHeight: 'var(--plasma-typo-dspl-l-line-height)',
};

/** typography s display-l-bold */
export const dsplLBold = {
    fontFamily: 'var(--plasma-typo-dspl-l-bold-font-family)',
    fontSize: 'var(--plasma-typo-dspl-l-bold-font-size)',
    fontStyle: 'var(--plasma-typo-dspl-l-bold-font-style)',
    fontWeight: 'var(--plasma-typo-dspl-l-bold-font-weight)',
    letterSpacing: 'var(--plasma-typo-dspl-l-bold-letter-spacing)',
    lineHeight: 'var(--plasma-typo-dspl-l-bold-line-height)',
};

/** typography s display-m */
export const dsplM = {
    fontFamily: 'var(--plasma-typo-dspl-m-font-family)',
    fontSize: 'var(--plasma-typo-dspl-m-font-size)',
    fontStyle: 'var(--plasma-typo-dspl-m-font-style)',
    fontWeight: 'var(--plasma-typo-dspl-m-font-weight)',
    letterSpacing: 'var(--plasma-typo-dspl-m-letter-spacing)',
    lineHeight: 'var(--plasma-typo-dspl-m-line-height)',
};

/** typography s display-m-bold */
export const dsplMBold = {
    fontFamily: 'var(--plasma-typo-dspl-m-bold-font-family)',
    fontSize: 'var(--plasma-typo-dspl-m-bold-font-size)',
    fontStyle: 'var(--plasma-typo-dspl-m-bold-font-style)',
    fontWeight: 'var(--plasma-typo-dspl-m-bold-font-weight)',
    letterSpacing: 'var(--plasma-typo-dspl-m-bold-letter-spacing)',
    lineHeight: 'var(--plasma-typo-dspl-m-bold-line-height)',
};

/** typography s display-s */
export const dsplS = {
    fontFamily: 'var(--plasma-typo-dspl-s-font-family)',
    fontSize: 'var(--plasma-typo-dspl-s-font-size)',
    fontStyle: 'var(--plasma-typo-dspl-s-font-style)',
    fontWeight: 'var(--plasma-typo-dspl-s-font-weight)',
    letterSpacing: 'var(--plasma-typo-dspl-s-letter-spacing)',
    lineHeight: 'var(--plasma-typo-dspl-s-line-height)',
};

/** typography s display-s-bold */
export const dsplSBold = {
    fontFamily: 'var(--plasma-typo-dspl-s-bold-font-family)',
    fontSize: 'var(--plasma-typo-dspl-s-bold-font-size)',
    fontStyle: 'var(--plasma-typo-dspl-s-bold-font-style)',
    fontWeight: 'var(--plasma-typo-dspl-s-bold-font-weight)',
    letterSpacing: 'var(--plasma-typo-dspl-s-bold-letter-spacing)',
    lineHeight: 'var(--plasma-typo-dspl-s-bold-line-height)',
};

/** typography s header-h1 */
export const h1 = {
    fontFamily: 'var(--plasma-typo-h1-font-family)',
    fontSize: 'var(--plasma-typo-h1-font-size)',
    fontStyle: 'var(--plasma-typo-h1-font-style)',
    fontWeight: 'var(--plasma-typo-h1-font-weight)',
    letterSpacing: 'var(--plasma-typo-h1-letter-spacing)',
    lineHeight: 'var(--plasma-typo-h1-line-height)',
};

/** typography s header-h1-bold */
export const h1Bold = {
    fontFamily: 'var(--plasma-typo-h1-bold-font-family)',
    fontSize: 'var(--plasma-typo-h1-bold-font-size)',
    fontStyle: 'var(--plasma-typo-h1-bold-font-style)',
    fontWeight: 'var(--plasma-typo-h1-bold-font-weight)',
    letterSpacing: 'var(--plasma-typo-h1-bold-letter-spacing)',
    lineHeight: 'var(--plasma-typo-h1-bold-line-height)',
};

/** typography s header-h2 */
export const h2 = {
    fontFamily: 'var(--plasma-typo-h2-font-family)',
    fontSize: 'var(--plasma-typo-h2-font-size)',
    fontStyle: 'var(--plasma-typo-h2-font-style)',
    fontWeight: 'var(--plasma-typo-h2-font-weight)',
    letterSpacing: 'var(--plasma-typo-h2-letter-spacing)',
    lineHeight: 'var(--plasma-typo-h2-line-height)',
};

/** typography s header-h2-bold */
export const h2Bold = {
    fontFamily: 'var(--plasma-typo-h2-bold-font-family)',
    fontSize: 'var(--plasma-typo-h2-bold-font-size)',
    fontStyle: 'var(--plasma-typo-h2-bold-font-style)',
    fontWeight: 'var(--plasma-typo-h2-bold-font-weight)',
    letterSpacing: 'var(--plasma-typo-h2-bold-letter-spacing)',
    lineHeight: 'var(--plasma-typo-h2-bold-line-height)',
};

/** typography s header-h3 */
export const h3 = {
    fontFamily: 'var(--plasma-typo-h3-font-family)',
    fontSize: 'var(--plasma-typo-h3-font-size)',
    fontStyle: 'var(--plasma-typo-h3-font-style)',
    fontWeight: 'var(--plasma-typo-h3-font-weight)',
    letterSpacing: 'var(--plasma-typo-h3-letter-spacing)',
    lineHeight: 'var(--plasma-typo-h3-line-height)',
};

/** typography s header-h3-bold */
export const h3Bold = {
    fontFamily: 'var(--plasma-typo-h3-bold-font-family)',
    fontSize: 'var(--plasma-typo-h3-bold-font-size)',
    fontStyle: 'var(--plasma-typo-h3-bold-font-style)',
    fontWeight: 'var(--plasma-typo-h3-bold-font-weight)',
    letterSpacing: 'var(--plasma-typo-h3-bold-letter-spacing)',
    lineHeight: 'var(--plasma-typo-h3-bold-line-height)',
};

/** typography s header-h4 */
export const h4 = {
    fontFamily: 'var(--plasma-typo-h4-font-family)',
    fontSize: 'var(--plasma-typo-h4-font-size)',
    fontStyle: 'var(--plasma-typo-h4-font-style)',
    fontWeight: 'var(--plasma-typo-h4-font-weight)',
    letterSpacing: 'var(--plasma-typo-h4-letter-spacing)',
    lineHeight: 'var(--plasma-typo-h4-line-height)',
};

/** typography s header-h4-bold */
export const h4Bold = {
    fontFamily: 'var(--plasma-typo-h4-bold-font-family)',
    fontSize: 'var(--plasma-typo-h4-bold-font-size)',
    fontStyle: 'var(--plasma-typo-h4-bold-font-style)',
    fontWeight: 'var(--plasma-typo-h4-bold-font-weight)',
    letterSpacing: 'var(--plasma-typo-h4-bold-letter-spacing)',
    lineHeight: 'var(--plasma-typo-h4-bold-line-height)',
};

/** typography s header-h5 */
export const h5 = {
    fontFamily: 'var(--plasma-typo-h5-font-family)',
    fontSize: 'var(--plasma-typo-h5-font-size)',
    fontStyle: 'var(--plasma-typo-h5-font-style)',
    fontWeight: 'var(--plasma-typo-h5-font-weight)',
    letterSpacing: 'var(--plasma-typo-h5-letter-spacing)',
    lineHeight: 'var(--plasma-typo-h5-line-height)',
};

/** typography s header-h5-bold */
export const h5Bold = {
    fontFamily: 'var(--plasma-typo-h5-bold-font-family)',
    fontSize: 'var(--plasma-typo-h5-bold-font-size)',
    fontStyle: 'var(--plasma-typo-h5-bold-font-style)',
    fontWeight: 'var(--plasma-typo-h5-bold-font-weight)',
    letterSpacing: 'var(--plasma-typo-h5-bold-letter-spacing)',
    lineHeight: 'var(--plasma-typo-h5-bold-line-height)',
};

/** typography s body-l */
export const bodyL = {
    fontFamily: 'var(--plasma-typo-body-l-font-family)',
    fontSize: 'var(--plasma-typo-body-l-font-size)',
    fontStyle: 'var(--plasma-typo-body-l-font-style)',
    fontWeight: 'var(--plasma-typo-body-l-font-weight)',
    letterSpacing: 'var(--plasma-typo-body-l-letter-spacing)',
    lineHeight: 'var(--plasma-typo-body-l-line-height)',
};

/** typography s body-l-bold */
export const bodyLBold = {
    fontFamily: 'var(--plasma-typo-body-l-bold-font-family)',
    fontSize: 'var(--plasma-typo-body-l-bold-font-size)',
    fontStyle: 'var(--plasma-typo-body-l-bold-font-style)',
    fontWeight: 'var(--plasma-typo-body-l-bold-font-weight)',
    letterSpacing: 'var(--plasma-typo-body-l-bold-letter-spacing)',
    lineHeight: 'var(--plasma-typo-body-l-bold-line-height)',
};

/** typography s body-m */
export const bodyM = {
    fontFamily: 'var(--plasma-typo-body-m-font-family)',
    fontSize: 'var(--plasma-typo-body-m-font-size)',
    fontStyle: 'var(--plasma-typo-body-m-font-style)',
    fontWeight: 'var(--plasma-typo-body-m-font-weight)',
    letterSpacing: 'var(--plasma-typo-body-m-letter-spacing)',
    lineHeight: 'var(--plasma-typo-body-m-line-height)',
};

/** typography s body-m-bold */
export const bodyMBold = {
    fontFamily: 'var(--plasma-typo-body-m-bold-font-family)',
    fontSize: 'var(--plasma-typo-body-m-bold-font-size)',
    fontStyle: 'var(--plasma-typo-body-m-bold-font-style)',
    fontWeight: 'var(--plasma-typo-body-m-bold-font-weight)',
    letterSpacing: 'var(--plasma-typo-body-m-bold-letter-spacing)',
    lineHeight: 'var(--plasma-typo-body-m-bold-line-height)',
};

/** typography s body-s */
export const bodyS = {
    fontFamily: 'var(--plasma-typo-body-s-font-family)',
    fontSize: 'var(--plasma-typo-body-s-font-size)',
    fontStyle: 'var(--plasma-typo-body-s-font-style)',
    fontWeight: 'var(--plasma-typo-body-s-font-weight)',
    letterSpacing: 'var(--plasma-typo-body-s-letter-spacing)',
    lineHeight: 'var(--plasma-typo-body-s-line-height)',
};

/** typography s body-s-bold */
export const bodySBold = {
    fontFamily: 'var(--plasma-typo-body-s-bold-font-family)',
    fontSize: 'var(--plasma-typo-body-s-bold-font-size)',
    fontStyle: 'var(--plasma-typo-body-s-bold-font-style)',
    fontWeight: 'var(--plasma-typo-body-s-bold-font-weight)',
    letterSpacing: 'var(--plasma-typo-body-s-bold-letter-spacing)',
    lineHeight: 'var(--plasma-typo-body-s-bold-line-height)',
};

/** typography s body-xs */
export const bodyXS = {
    fontFamily: 'var(--plasma-typo-body-xs-font-family)',
    fontSize: 'var(--plasma-typo-body-xs-font-size)',
    fontStyle: 'var(--plasma-typo-body-xs-font-style)',
    fontWeight: 'var(--plasma-typo-body-xs-font-weight)',
    letterSpacing: 'var(--plasma-typo-body-xs-letter-spacing)',
    lineHeight: 'var(--plasma-typo-body-xs-line-height)',
};

/** typography s body-xs-bold */
export const bodyXSBold = {
    fontFamily: 'var(--plasma-typo-body-xs-bold-font-family)',
    fontSize: 'var(--plasma-typo-body-xs-bold-font-size)',
    fontStyle: 'var(--plasma-typo-body-xs-bold-font-style)',
    fontWeight: 'var(--plasma-typo-body-xs-bold-font-weight)',
    letterSpacing: 'var(--plasma-typo-body-xs-bold-letter-spacing)',
    lineHeight: 'var(--plasma-typo-body-xs-bold-line-height)',
};

/** typography s body-xxs */
export const bodyXXS = {
    fontFamily: 'var(--plasma-typo-body-xxs-font-family)',
    fontSize: 'var(--plasma-typo-body-xxs-font-size)',
    fontStyle: 'var(--plasma-typo-body-xxs-font-style)',
    fontWeight: 'var(--plasma-typo-body-xxs-font-weight)',
    letterSpacing: 'var(--plasma-typo-body-xxs-letter-spacing)',
    lineHeight: 'var(--plasma-typo-body-xxs-line-height)',
};

/** typography s body-xxs-bold */
export const bodyXXSBold = {
    fontFamily: 'var(--plasma-typo-body-xxs-bold-font-family)',
    fontSize: 'var(--plasma-typo-body-xxs-bold-font-size)',
    fontStyle: 'var(--plasma-typo-body-xxs-bold-font-style)',
    fontWeight: 'var(--plasma-typo-body-xxs-bold-font-weight)',
    letterSpacing: 'var(--plasma-typo-body-xxs-bold-letter-spacing)',
    lineHeight: 'var(--plasma-typo-body-xxs-bold-line-height)',
};

/** typography s text-l */
export const textL = {
    fontFamily: 'var(--plasma-typo-text-l-font-family)',
    fontSize: 'var(--plasma-typo-text-l-font-size)',
    fontStyle: 'var(--plasma-typo-text-l-font-style)',
    fontWeight: 'var(--plasma-typo-text-l-font-weight)',
    letterSpacing: 'var(--plasma-typo-text-l-letter-spacing)',
    lineHeight: 'var(--plasma-typo-text-l-line-height)',
};

/** typography s text-l-bold */
export const textLBold = {
    fontFamily: 'var(--plasma-typo-text-l-bold-font-family)',
    fontSize: 'var(--plasma-typo-text-l-bold-font-size)',
    fontStyle: 'var(--plasma-typo-text-l-bold-font-style)',
    fontWeight: 'var(--plasma-typo-text-l-bold-font-weight)',
    letterSpacing: 'var(--plasma-typo-text-l-bold-letter-spacing)',
    lineHeight: 'var(--plasma-typo-text-l-bold-line-height)',
};

/** typography s text-m */
export const textM = {
    fontFamily: 'var(--plasma-typo-text-m-font-family)',
    fontSize: 'var(--plasma-typo-text-m-font-size)',
    fontStyle: 'var(--plasma-typo-text-m-font-style)',
    fontWeight: 'var(--plasma-typo-text-m-font-weight)',
    letterSpacing: 'var(--plasma-typo-text-m-letter-spacing)',
    lineHeight: 'var(--plasma-typo-text-m-line-height)',
};

/** typography s text-m-bold */
export const textMBold = {
    fontFamily: 'var(--plasma-typo-text-m-bold-font-family)',
    fontSize: 'var(--plasma-typo-text-m-bold-font-size)',
    fontStyle: 'var(--plasma-typo-text-m-bold-font-style)',
    fontWeight: 'var(--plasma-typo-text-m-bold-font-weight)',
    letterSpacing: 'var(--plasma-typo-text-m-bold-letter-spacing)',
    lineHeight: 'var(--plasma-typo-text-m-bold-line-height)',
};

/** typography s text-s */
export const textS = {
    fontFamily: 'var(--plasma-typo-text-s-font-family)',
    fontSize: 'var(--plasma-typo-text-s-font-size)',
    fontStyle: 'var(--plasma-typo-text-s-font-style)',
    fontWeight: 'var(--plasma-typo-text-s-font-weight)',
    letterSpacing: 'var(--plasma-typo-text-s-letter-spacing)',
    lineHeight: 'var(--plasma-typo-text-s-line-height)',
};

/** typography s text-s-bold */
export const textSBold = {
    fontFamily: 'var(--plasma-typo-text-s-bold-font-family)',
    fontSize: 'var(--plasma-typo-text-s-bold-font-size)',
    fontStyle: 'var(--plasma-typo-text-s-bold-font-style)',
    fontWeight: 'var(--plasma-typo-text-s-bold-font-weight)',
    letterSpacing: 'var(--plasma-typo-text-s-bold-letter-spacing)',
    lineHeight: 'var(--plasma-typo-text-s-bold-line-height)',
};

/** typography s text-xs */
export const textXS = {
    fontFamily: 'var(--plasma-typo-text-xs-font-family)',
    fontSize: 'var(--plasma-typo-text-xs-font-size)',
    fontStyle: 'var(--plasma-typo-text-xs-font-style)',
    fontWeight: 'var(--plasma-typo-text-xs-font-weight)',
    letterSpacing: 'var(--plasma-typo-text-xs-letter-spacing)',
    lineHeight: 'var(--plasma-typo-text-xs-line-height)',
};

/** typography s text-xs-bold */
export const textXSBold = {
    fontFamily: 'var(--plasma-typo-text-xs-bold-font-family)',
    fontSize: 'var(--plasma-typo-text-xs-bold-font-size)',
    fontStyle: 'var(--plasma-typo-text-xs-bold-font-style)',
    fontWeight: 'var(--plasma-typo-text-xs-bold-font-weight)',
    letterSpacing: 'var(--plasma-typo-text-xs-bold-letter-spacing)',
    lineHeight: 'var(--plasma-typo-text-xs-bold-line-height)',
};
