export const classes = {
    attachedOverlay: 'attached-overlay',
};

export const tokens = {
    background: '--plasma-input-background',
    paddingTop: '--plasma-input-padding-top',
    paddingRight: '--plasma-input-padding-right',
    paddingBottom: '--plasma-input-padding-bottom',
    paddingLeft: '--plasma-input-padding-left',
    borderRadius: '--plasma-input-border-radius',
    focusColor: '--plasma-input-focus-color',

    attachmentsListMargin: '--plasma-input-attachments-list-margin',
    attachmentsGap: '--plasma-input-attachments-gap',
    fileBackground: '--plasma-input-file-background',
    filePaddingTop: '--plasma-input-file-padding-top',
    filePaddingRight: '--plasma-input-file-padding-right',
    filePaddingBottom: '--plasma-input-file-padding-bottom',
    filePaddingLeft: '--plasma-input-file-padding-left',
    fileBorderRadius: '--plasma-input-file-border-radius',
    fileEmbedIconButtonColor: '--plasma-input-file-embed-icon-button-color',
    fileEmbedIconButtonColorHover: '--plasma-input-file-embed-icon-button-color-hover',
    fileEmbedIconButtonColorActive: '--plasma-input-file-embed-icon-button-color-active',
    fileCellTitleColor: '--plasma-input-file-embed-cell-title-color',
    fileCellSubtitleColor: '--plasma-input-file-embed-cell-subtitle-color',
    fileEmbedIconButtonHeight: '--plasma-input-file-embed-icon-button-height',
    fileEmbedIconButtonWidth: '--plasma-input-file-embed-icon-button-width',
    fileEmbedIconButtonPadding: '--plasma-input-file-embed-icon-button-padding',
    fileEmbedIconButtonRadius: '--plasma-input-file-embed-icon-button-radius',
    fileCellHeight: '--plasma-input-file-cell-height',
    fileCellTextboxGap: '--plasma-input-file-cell-textbox-gap',
    fileCellGap: '--plasma-input-file-cell-gap',
    fileCellTitleFontFamily: '--plasma-input-file-cell-title-font-family',
    fileCellTitleFontSize: '--plasma-input-file-cell-title-font-size',
    fileCellTitleFontStyle: '--plasma-input-file-cell-title-font-style',
    fileCellTitleFontWeight: '--plasma-input-file-cell-title-font-weight',
    fileCellTitleLetterSpacing: '--plasma-input-file-cell-title-letter-spacing',
    fileCellTitleLineHeight: '--plasma-input-file-cell-title-line-height',
    fileCellSubtitleFontFamily: '--plasma-input-file-cell-subtitle-font-family',
    fileCellSubtitleFontSize: '--plasma-input-file-cell-subtitle-font-size',
    fileCellSubtitleFontStyle: '--plasma-input-file-cell-subtitle-font-style',
    fileCellSubtitleFontWeight: '--plasma-input-file-cell-subtitle-font-weight',
    fileCellSubtitleLetterSpacing: '--plasma-input-file-cell-subtitle-letter-spacing',
    fileCellSubtitleLineHeight: '--plasma-input-file-cell-subtitle-line-height',
    fileThumbSize: '--plasma-input-file-thumb-size',
    fileThumbRadius: '--plasma-input-file-thumb-radius',

    textareaPaddingTop: '--plasma-input-textarea-padding-top',
    textareaPaddingRight: '--plasma-input-textarea-padding-right',
    textareaPaddingBottom: '--plasma-input-textarea-padding-bottom',
    textareaPaddingLeft: '--plasma-input-textarea-padding-left',
    textareaColor: '--plasma-input-textarea-color',
    textareaPlaceholderColor: '--plasma-input-textarea-placeholder-color',
    textareaPlaceholderColorFocus: '--plasma-input-textarea-placeholder-color-focus',
    textareaCaretColor: '--plasma-input-textarea-caret-color',
    textareaFontFamily: '--plasma-input-textarea-font-family',
    textareaFontSize: '--plasma-input-textarea-font-size',
    textareaFontStyle: '--plasma-input-textarea-font-style',
    textareaFontWeight: '--plasma-input-textarea-font-weight',
    textareaLetterSpacing: '--plasma-input-textarea-letter-spacing',
    textareaLineHeight: '--plasma-input-textarea-line-height',
    textareaScrollWidth: '--plasma-input-textarea-scroll-width',
    textareaScrollTrackColor: '--plasma-input-textarea-scroll-track-color',
    textareaScrollThumbColor: '--plasma-input-textarea-scroll-thumb-color',

    inputFieldPadding: '--plasma-input-input-field-padding',

    submitButtonColor: '--plasma-input-submit-button-color',
    submitButtonBackgroundColor: '--plasma-input-submit-button-background-color',
    submitButtonBackgroundColorHover: '--plasma-input-submit-button-background-color-hover',
    submitButtonBackgroundColorActive: '--plasma-input-submit-button-background-color-active',
    submitButtonLoadingBackgroundColor: '--plasma-input-submit-button-loading-background-color',
    submitButtonWidth: '--plasma-input-submit-button-width',
    submitButtonHeight: '--plasma-input-submit-button-height',
    submitButtonPadding: '--plasma-input-submit-button-padding',
    submitButtonRadius: '--plasma-input-submit-button-radius',
    submitButtonSpinnerSize: '--plasma-input-submit-button-spinner-size',
    submitButtonSpinnerColor: '--plasma-input-submit-button-spinner-color',
};
