export const classes = {
    rangeInformationWrapper: 'range-information-wrapper',
    rangeError: 'range-error',
    rangeValueError: 'range-value-error',
    rangeSuccess: 'range-success',
    rangeValueSuccess: 'range-value-success',
    requiredAlignRight: 'required-align-right',
    requiredOuterPlacement: 'required-placement-outer',
    noCaptionAndLabel: 'range-no-caption-label',
    clear: 'range-clear',
    clearDivider: 'range-clear-divider',
    clearHasOuterHint: 'range-clear-has-outer-hint',
};

export const tokens = {
    background: '--plasma-range-background',
    backgroundError: '--plasma-range-background-error',
    backgroundSuccess: '--plasma-range-background-success',
    backgroundReadOnly: '--plasma-range-background-readonly',
    borderRadius: '--plasma-range-border-radius',
    borderWidth: '--plasma-range-border-width',
    borderColor: '--plasma-range-border-color',
    borderColorError: '--plasma-range-border-color-error',
    borderColorSuccess: '--plasma-range-border-color-success',
    borderColorReadOnly: '--plasma-range-border-color-readonly',
    shadow: '--plasma-range-shadow',

    /** Токены разделителя */
    clearDividerColor: '--plasma-range-clear__divider-color',

    dividerColor: '--plasma-range__divider-color',
    dividerColorReadOnly: '--plasma-range__divider-color-readonly',
    dividerOpacityReadOnly: '--plasma-range__divider-opacity-readonly',
    dividerPadding: '--plasma-range__divider-padding',
    dividerFontFamily: '--plasma-range__divider-font-family',
    dividerFontStyle: '--plasma-range__divider-font-style',
    dividerFontSize: '--plasma-range__divider-font-size',
    dividerFontWeight: '--plasma-range__divider-font-weight',
    dividerLetterSpacing: '--plasma-range__divider-letter-spacing',
    dividerLineHeight: '--plasma-range__divider-line-height',

    /** Токены слотов для контента */
    leftContentMargin: '--plasma-range__left-content-margin',
    rightContentMargin: '--plasma-range__right-content-margin',
    rightContentOpacityReadOnly: '--plasma-range__right-content-opacity-readonly',

    contentSlotColor: '--plasma-range-content-slot-color',
    contentSlotColorHover: '--plasma-range-content-slot-color-hover',
    contentSlotColorActive: '--plasma-range-content-slot-color-active',

    contentSlotColorSuccess: '--plasma-range-content-slot-color-success',
    contentSlotColorSuccessHover: '--plasma-range-content-slot-color-success-hover',
    contentSlotColorSuccessActive: '--plasma-range-content-slot-color-success-active',

    contentSlotColorError: '--plasma-range-content-slot-color-error',
    contentSlotColorErrorHover: '--plasma-range-content-slot-color-error-hover',
    contentSlotColorErrorActive: '--plasma-range-content-slot-color-error-active',

    textFieldContentSlotColor: '--plasma-textfield-content-slot-color',
    textFieldContentSlotColorHover: '--plasma-textfield-content-slot-color-hover',
    textFieldContentSlotColorActive: '--plasma-textfield-content-slot-color-active',

    textFieldContentSlotColorSuccess: '--plasma-textfield-content-slot-color-success',
    textFieldContentSlotColorSuccessHover: '--plasma-textfield-content-slot-color-success-hover',
    textFieldContentSlotColorSuccessActive: '--plasma-textfield-content-slot-color-success-active',

    textFieldContentSlotColorError: '--plasma-textfield-content-slot-color-error',
    textFieldContentSlotColorErrorHover: '--plasma-textfield-content-slot-color-error-hover',
    textFieldContentSlotColorErrorActive: '--plasma-textfield-content-slot-color-error-active',

    contentSlotRightColor: '--plasma-range-content-right-slot-color',
    contentSlotRightColorHover: '--plasma-range-content-right-slot-color-hover',
    contentSlotRightColorActive: '--plasma-range-content-right-slot-color-active',

    embedIconButtonHeight: '--plasma-range-embed-icon-button-height',
    embedIconButtonWidth: '--plasma-range-embed-icon-button-width',
    embedIconButtonPadding: '--plasma-range-embed-icon-button-padding',
    embedIconButtonRadius: '--plasma-range-embed-icon-button-radius',
    embedIconButtonFocusColor: '--plasma-range-embed-icon-button-focus-color',

    textFieldContentSlotRightColor: '--plasma-textfield-content-right-slot-color',
    textFieldContentSlotRightColorHover: '--plasma-textfield-content-right-slot-color-hover',
    textFieldContentSlotRightColorActive: '--plasma-textfield-content-right-slot-color-active',

    indicatorWrapperGap: '--plasma-range-info-wrapper-indicator-wrapper-gap',
    labelWrapperOffset: '--plasma-range-info-wrapper-label-wrapper-offset',
    labelWrapperTitleCaptionOffset: '--plasma-range-info-wrapper-label-wrapper-title-caption-offset',
    labelFontFamily: '--plasma-range-info-wrapper-label-font-family',
    labelFontStyle: '--plasma-range-info-wrapper-label-font-style',
    labelFontSize: '--plasma-range-info-wrapper-label-font-size',
    labelFontWeight: '--plasma-range-info-wrapper-label-font-weight',
    labelLetterSpacing: '--plasma-range-info-wrapper-label-letter-spacing',
    labelLineHeight: '--plasma-range-info-wrapper-label-line-height',
    labelColor: '--plasma-range-info-wrapper-label-color',

    contentGap: '--plasma-range-info-wrapper-content-gap',

    titleCaptionOffset: '--plasma-range-info-wrapper-title-caption-offset',
    titleCaptionColor: '--plasma-range-info-wrapper-title-caption-color',
    titleCaptionFontFamily: '--plasma-range-info-wrapper-title-caption-font-family',
    titleCaptionFontStyle: '--plasma-range-info-wrapper-title-caption-font-style',
    titleCaptionFontSize: '--plasma-range-info-wrapper-title-caption-font-size',
    titleCaptionFontWeight: '--plasma-range-info-wrapper-title-caption-font-weight',
    titleCaptionLetterSpacing: '--plasma-range-info-wrapper-title-caption-letter-spacing',
    titleCaptionLineHeight: '--plasma-range-info-wrapper-title-caption-line-height',

    /** Токены для tooltip */
    hintMargin: '--plasma-range-info-wrapper-hint-margin',
    hintTargetSize: '--plasma-range-info-wrapper-hint-target-size',
    hintCustomIconTargetSize: '--plasma-range-info-wrapper-hint-custom-icon-target-size',
    hintIconColor: '--plasma-range-info-wrapper-hint-icon-color',
    hintWithoutLabelPlacementOffset: '--plasma-range-info-wrapper-hint-without-label-placement-offset',
    hintPlacementInnerMargin: '--plasma-range-info-wrapper-hint-placement-inner-offset',

    tooltipBackgroundColor: '--plasma-range-info-wrapper-tooltip-background-color',
    tooltipBoxShadow: '--plasma-range-info-wrapper-tooltip-box-shadow',
    tooltipColor: '--plasma-range-info-wrapper-tooltip-color',

    tooltipPaddingTop: '--plasma-range-info-wrapper-tooltip-padding-top',
    tooltipPaddingRight: '--plasma-range-info-wrapper-tooltip-padding-right',
    tooltipPaddingBottom: '--plasma-range-info-wrapper-tooltip-padding-bottom',
    tooltipPaddingLeft: '--plasma-range-info-wrapper-tooltip-padding-left',
    tooltipMinHeight: '--plasma-range-info-wrapper-tooltip-min-height',
    tooltipBorderRadius: '--plasma-range-info-wrapper-tooltip-border-radius',
    tooltipTextFontFamily: '--plasma-range-info-wrapper-tooltip-text-font-family',
    tooltipTextFontSize: '--plasma-range-info-wrapper-tooltip-text-font-size',
    tooltipTextFontStyle: '--plasma-range-info-wrapper-tooltip-text-font-style',
    tooltipTextFontWeight: '--plasma-range-info-wrapper-tooltip-text-font-weight',
    tooltipTextFontLetterSpacing: '--plasma-range-info-wrapper-tooltip-text-font-letter-spacing',
    tooltipTextFontLineHeight: '--plasma-range-info-wrapper-tooltip-text-font-line-height',
    tooltipContentLeftMargin: '--plasma-range-info-wrapper-tooltip-content-left-margin',
    tooltipArrowMaskWidth: '--plasma-range-info-wrapper-tooltip-arrow-mask-width',
    tooltipArrowMaskHeight: '--plasma-range-info-wrapper-tooltip-arrow-mask-height',
    tooltipArrowMaskImage: '--plasma-range-info-wrapper-tooltip-arrow-mask-image',
    tooltipArrowHeight: '--plasma-range-info-wrapper-tooltip-arrow-height',
    tooltipArrowEdgeMargin: '--plasma-range-info-wrapper-tooltip-arrow-edge-margin',
    tooltipArrowBackground: '--plasma-range-info-wrapper-tooltip-arrow-background',

    /** Токены для required indicator */
    indicatorColor: '--plasma-range-info-wrapper-indicator-color',
    indicatorSizeInner: '--plasma-range-info-wrapper-indicator-size-inner',
    indicatorSizeOuter: '--plasma-range-info-wrapper-indicator-size-outer',
    indicatorMarginTop: '--plasma-range-info-wrapper-indicator-margin-top',
    indicatorOuterLeft: '--plasma-range-info-wrapper-indicator-outer-left',
    indicatorWithoutLabelInner: '--plasma-range-info-wrapper-indicator-without-label-inner',
    indicatorWithoutLabelInnerLeft: '--plasma-range-info-wrapper-indicator-without-label-inner-left',
    indicatorWithoutLabelOuterHint: '--plasma-range-info-wrapper-indicator-without-label-outer-hint',

    /** Токены для подписей снизу */
    leftHelperColor: '--plasma-range-info-wrapper-left-helper-color',
    leftHelperColorError: '--plasma-range-info-wrapper-left-helper--error',
    leftHelperColorSuccess: '--plasma-range-info-wrapper-left-helper--success',

    helpersPadding: '--plasma-range-info-wrapper-helpers-padding-top',
    helpersGap: '--plasma-range-info-wrapper-helpers-gap',

    leftHelperFontFamily: '--plasma-range-info-wrapper-left-helper-font-family',
    leftHelperFontStyle: '--plasma-range-info-wrapper-left-helper-font-style',
    leftHelperFontSize: '--plasma-range-info-wrapper-left-helper-font-size',
    leftHelperFontWeight: '--plasma-range-info-wrapper-left-helper-font-weight',
    leftHelperLetterSpacing: '--plasma-range-info-wrapper-left-helper-letter-spacing',
    leftHelperLineHeight: '--plasma-range-info-wrapper-left-helper-line-height',

    /** Прозрачность для всего компонента в состоянии disabled */
    disabledOpacity: '--plasma-range-disabled-opacity',
    readOnlyOpacity: '--plasma-range-readonly-opacity',
    labelColorReadOnly: '--plasma-range-info-wrapper-label-color-readonly',
    titleCaptionColorReadOnly: '--plasma-range-info-wrapper-title-caption-color-readonly',
    leftHelperColorReadOnly: '--plasma-range-info-wrapper-left-helper-color-readonly',
    rightHelperColorReadOnly: '--plasma-range-info-wrapper-right-helper-color-readonly',

    /** Цвет обводки поля ввода при фокусе */
    focusColor: '--plasma-range-focus-color',

    /** Токены полей ввода */
    textFieldColor: '--plasma-range-textfield-color',
    textFieldColorError: '--plasma-range-textfield-color-error',
    textFieldColorSuccess: '--plasma-range-textfield-color-success',
    textFieldFocusColor: '--plasma-range-textfield-focus-color',
    textFieldPlaceholderColor: '--plasma-range-textfield-placeholder-color',
    textFieldClearPlaceholderColorFocus: '--plasma-range-textfield-clear-placeholder-color-focus',
    textFieldCaretColor: '--plasma-range-textfield-caret-color',

    textFieldBackgroundColor: '--plasma-range-textfield-background-color',
    textFieldBackgroundColorHover: '--plasma-range-textfield-background-color-hover',
    textFieldBackgroundColorFocus: '--plasma-range-textfield-background-color-focus',
    textFieldBackgroundErrorColor: '--plasma-range-textfield-background-color-error',
    textFieldBackgroundErrorColorHover: '--plasma-range-textfield-background-color-error-hover',
    textFieldBackgroundErrorColorFocus: '--plasma-range-textfield-background-color-error-focus',
    textFieldBackgroundSuccessColor: '--plasma-range-textfield-background-color-success',
    textFieldBackgroundSuccessColorHover: '--plasma-range-textfield-background-color-success-hover',
    textFieldBackgroundSuccessColorFocus: '--plasma-range-textfield-background-color-success-focus',

    textFieldBorderColor: '--plasma-range-textfield-border-color',
    textFieldPlaceholderColorFocus: '--plasma-range-textfield__placeholder-color-focus',
    textFieldBorderColorHover: '--plasma-range-textfield-border-color-hover',
    textFieldBorderColorFocus: '--plasma-range-textfield-border-color-focus',
    textFieldBorderColorError: '--plasma-range-textfield-border-color-error',
    textFieldBorderColorErrorHover: '--plasma-range-textfield-border-color-error-hover',
    textFieldBorderColorErrorFocus: '--plasma-range-textfield-border-color-error-focus',
    textFieldBorderColorSuccess: '--plasma-range-textfield-border-color-success',
    textFieldBorderColorSuccessHover: '--plasma-range-textfield-border-color-success-hover',
    textFieldBorderColorSuccessFocus: '--plasma-range-textfield-border-color-success-focus',

    textFieldColorReadOnly: '--plasma-range-textfield-color-readonly',
    textFieldBackgroundColorReadOnly: '--plasma-range-textfield-background-color-readonly',
    textFieldBorderColorReadOnly: '--plasma-range-textfield-border-color-readonly',
    textFieldPlaceholderColorReadOnly: '--plasma-range-textfield-placeholder-color-readonly',

    textFieldHeight: '--plasma-range-textfield-height',
    textFieldBorderWidth: '--plasma-range-textfield-border-width',
    textFieldBorderRadius: '--plasma-range-textfield-border-radius',
    textFieldPadding: '--plasma-range-textfield-padding',
    textFieldLeftContentMargin: '--plasma-range-textfield__left-content-margin',
    textFieldRightContentMargin: '--plasma-range-textfield__right-content-margin',
    textFieldFontFamily: '--plasma-range-textfield-font-family',
    textFieldFontStyle: '--plasma-range-textfield-font-style',
    textFieldFontSize: '--plasma-range-textfield-font-size',
    textFieldFontWeight: '--plasma-range-textfield-font-weight',
    textFieldLetterSpacing: '--plasma-range-textfield-letter-spacing',
    textFieldLineHeight: '--plasma-range-textfield-line-height',

    textFieldTextBeforeColor: '--plasma-range-textfield__before-text-color',
    textFieldTextAfterColor: '--plasma-range-textfield__after-text-color',
    textFieldTextBeforeMargin: '--plasma-range-textfield__before-text-margin',
    textFieldTextAfterMargin: '--plasma-range-textfield__after-text-margin',

    textFieldDividerColorSuccess: '--plasma-range-textfield__divider-color-success',
    textFieldDividerColorError: '--plasma-range-textfield__divider-color-error',
    textFieldDividerColorHover: '--plasma-range-textfield__divider-color-hover',
    textFieldDividerColorFocus: '--plasma-range-textfield__divider-color-focus',
};
