export const classes = {
    editIcon: 'edit-icon',
    sortingDefaultIcon: 'sorting-default-icon',
    sortingAscIcon: 'sorting-asc-icon',
    sortingDescIcon: 'sorting-desc-icon',
    filterIcon: 'filter-icon',
    resizeDivider: 'resize-divider',
};

export const tableTokens = {
    fontFamily: '--plasma-table-font-family',
    fontSize: '--plasma-table-font-size',
    fontStyle: '--plasma-table-font-style',
    fontWeight: '--plasma-table-font-weight',
    letterSpacing: '--plasma-table-letter-spacing',
    lineHeight: '--plasma-table-line-height',

    borderColor: '--plasma-table-border-color',
    headerRowHeight: '--plasma-table-header-row-height',
    rowHeight: '--plasma-table-row-height',
    cellPadding: '--plasma-cell-padding',
    checkboxCellPadding: '--plasma-checkbox-cell-padding',

    checkboxTriggerSize: '--plasma-table-checkbox-trigger-size',
    checkboxTriggerBorderCheckedColor: '--plasma-table-checkbox-trigger-border-checked-color',
    checkboxTriggerBorderRadius: '--plasma-table-checkbox-trigger-border-radius',
    checkboxTriggerBorderWidth: '--plasma-table-checkbox-trigger-border-width',

    editableCellIconGap: '--plasma-table-editable-cell-icon-gap',
    editableCellIconButtonWidth: '--plasma-table-editable-cell-icon-button-width',
    editableCellIconButtonHeight: '--plasma-table-editable-cell-icon-button-height',
    editableCellPadding: '--plasma-table-editable-cell-padding',
    editableCellInputBorderRadius: '--plasma-table-editable-cell-input-border-radius',
    editableCellInputPadding: '--plasma-table-editable-cell-input-padding',
    editableCellInputBackground: '--plasma-table-editable-cell-input-background',
    editableCellInputBorderColor: '--plasma-table-editable-cell-input-border-color',

    filterCheckboxPadding: '--plasma-table-filter-checkbox-padding',
    filterDividerMargin: '--plasma-table-filter-divider-margin',

    buttonHeight: '--plasma-table-button-height',
    buttonFontFamily: '--plasma-table-button-font-family',
    buttonFontSize: '--plasma-table-button-font-size',
    buttonFontStyle: '--plasma-table-button-font-style',
    buttonFontWeight: '--plasma-table-button-font-weight',
    buttonLetterSpacing: '--plasma-table-button-letter-spacing',
    buttonLineHeight: '--plasma-table-button-line-height',

    selectPadding: '--plasma-table-select-padding',
    selectBorderRadius: '--plasma-table-select-border-radius',
    selectItemHeight: '--plasma-table-select-item-height',
    selectItemPadding: '--plasma-table-select-item-padding',
    selectItemBorderRadius: '--plasma-table-select-item-border-radius',
    selectItemIconMargin: '--plasma-table-select-item-icon-margin',
    selectItemIconSize: '--plasma-table-select-item-icon-size',
    selectCellPadding: '--plasma-table-select-cell-padding',
    selectCellTitleFontFamily: '--plasma-table-select-cell-title-font-family',
    selectCellTitleFontSize: '--plasma-table-select-cell-title-font-size',
    selectCellTitleFontStyle: '--plasma-table-select-cell-title-font-style',
    selectCellTitleFontWeight: '--plasma-table-select-cell-title-font-weight',
    selectCellTitleLetterSpacing: '--plasma-table-select-cell-title-letter-spacing',
    selectCellTitleLineHeight: '--plasma-table-select-cell-title-line-height',
    selectCheckboxTriggerSize: '--plasma-table-select-checkbox-trigger-size',
    selectCheckboxTriggerBorderRadius: '--plasma-table-select-checkbox-trigger-border-radius',
    selectCheckboxTriggerBorderWidth: '--plasma-table-select-checkbox-trigger-border-width',
    selectCheckboxTriggerBorderCheckedColor: '--plasma-table-select-checkbox-trigger-border-color-checked',
    selectControlPanelPadding: '--plasma-table-select-control-panel-padding',
    selectControlPanelGap: '--plasma-table-select-control-panel-gap',

    linkButtonFontFamily: '--plasma-table-link-button-font-family',
    linkButtonFontSize: '--plasma-table-link-button-font-size',
    linkButtonFontStyle: '--plasma-table-link-button-font-style',
    linkButtonFontWeight: '--plasma-table-link-button-font-weight',
    linkButtonLetterSpacing: '--plasma-table-link-button-letter-spacing',
    linkButtonLineHeight: '--plasma-table-link-button-line-height',
};
