export const classes = {
    root: 'plasma_date-time-picker-root',
    error: 'plasma_date-time-picker-error',
    success: 'plasma_date-time-picker-success',
    stretched: 'plasma_date-time-picker-stretched',
    popoverStretched: 'plasma_date-time-picker-popover-stretched',
    shortcutItemDisabled: 'plasma_date-time-picker-shortcut-item-disabled',
};

export const privateTokens = {
    calendarDoubleWidth: '--plasma_private-calendar-double-width',
};

export const tokens = {
    /** Токены полей ввода */
    textFieldColor: '--plasma-date-time-picker-textfield-color',
    textFieldPlaceholderColorFocus: '--plasma-date-time-picker-textfield__placeholder-color-focus',
    textFieldFocusColor: '--plasma-date-time-picker-textfield-focus-color',
    textFieldPlaceholderColor: '--plasma-date-time-picker-textfield-placeholder-color',
    textFieldCaretColor: '--plasma-date-time-picker-textfield-caret-color',

    textFieldBackgroundColor: '--plasma-date-time-picker-textfield-background-color',
    textFieldBackgroundColorHover: '--plasma-date-time-picker-textfield-background-color-hover',
    textFieldBackgroundColorFocus: '--plasma-date-time-picker-textfield-background-color-focus',
    textFieldBackgroundErrorColor: '--plasma-date-time-picker-textfield-background-color-error',
    textFieldBackgroundErrorColorHover: '--plasma-date-time-picker-textfield-background-color-error-hover',
    textFieldBackgroundErrorColorFocus: '--plasma-date-time-picker-textfield-background-color-error-focus',
    textFieldBackgroundSuccessColor: '--plasma-date-time-picker-textfield-background-color-success',
    textFieldBackgroundSuccessColorHover: '--plasma-date-time-picker-textfield-background-color-success-hover',
    textFieldBackgroundSuccessColorFocus: '--plasma-date-time-picker-textfield-background-color-success-focus',

    textFieldBorderColor: '--plasma-date-time-picker-textfield-border-color',
    textFieldBorderColorHover: '--plasma-date-time-picker-textfield-border-color-hover',
    textFieldBorderColorFocus: '--plasma-date-time-picker-textfield-border-color-focus',
    textFieldBorderColorError: '--plasma-date-time-picker-textfield-border-color-error',
    textFieldBorderColorErrorHover: '--plasma-date-time-picker-textfield-border-color-error-hover',
    textFieldBorderColorErrorFocus: '--plasma-date-time-picker-textfield-border-color-error-focus',
    textFieldBorderColorSuccess: '--plasma-date-time-picker-textfield-border-color-success',
    textFieldBorderColorSuccessHover: '--plasma-date-time-picker-textfield-border-color-success-hover',
    textFieldBorderColorSuccessFocus: '--plasma-date-time-picker-textfield-border-color-success-focus',

    textFieldColorReadOnly: '--plasma-date-time-picker-textfield-color-readonly',
    textFieldBackgroundColorReadOnly: '--plasma-date-time-picker-textfield-background-color-readonly',
    textFieldBorderColorReadOnly: '--plasma-date-time-picker-textfield-border-color-readonly',
    textFieldPlaceholderColorReadOnly: '--plasma-date-time-picker-textfield-placeholder-color-readonly',
    textFieldReadOnlyOpacity: '--plasma-date-time-picker-textfield-readonly-opacity',

    textFieldHeight: '--plasma-date-time-picker-textfield-height',
    textFieldBorderWidth: '--plasma-date-time-picker-textfield-border-width',
    textFieldBorderRadius: '--plasma-date-time-picker-textfield-border-radius',
    textFieldPadding: '--plasma-date-time-picker-textfield-padding',
    textFieldLeftContentMargin: '--plasma-date-time-picker-textfield__left-content-margin',
    textFieldRightContentMargin: '--plasma-date-time-picker-textfield__right-content-margin',
    textFieldFontFamily: '--plasma-date-time-picker-textfield-font-family',
    textFieldFontStyle: '--plasma-date-time-picker-textfield-font-style',
    textFieldFontSize: '--plasma-date-time-picker-textfield-font-size',
    textFieldFontWeight: '--plasma-date-time-picker-textfield-font-weight',
    textFieldLetterSpacing: '--plasma-date-time-picker-textfield-letter-spacing',
    textFieldLineHeight: '--plasma-date-time-picker-textfield-line-height',

    textFieldTextBeforeColor: '--plasma-date-time-picker-textfield__before-text-color',
    textFieldTextAfterColor: '--plasma-date-time-picker-textfield__after-text-color',
    textFieldTextBeforeMargin: '--plasma-date-time-picker-textfield__before-text-margin',
    textFieldTextAfterMargin: '--plasma-date-time-picker-textfield__after-text-margin',
    textFieldContentSlotColor: '--plasma-date-time-picker-textfield__content-color',
    textFieldContentSlotColorHover: '--plasma-date-time-picker-textfield__content-color-hover',
    textFieldContentSlotColorActive: '--plasma-date-time-picker-textfield__content-color-active',
    textFieldContentRightSlotColor: '--plasma-date-time-picker-textfield__content-right-color',
    textFieldContentRightSlotColorHover: '--plasma-date-time-picker-textfield__content-right-color-hover',
    textFieldContentRightSlotColorActive: '--plasma-date-time-picker-textfield__content-right-color-active',
    textFieldContentSlotRightOpacityReadOnly: '--plasma-date-time-picker-textfield__content-right-opacity-readonly',

    /** Токены лейбла */
    labelColor: '--plasma-date-time-picker__label-color',
    labelColorReadOnly: '--plasma-date-time-picker__label-color-readonly',
    labelOffset: '--plasma-date-time-picker__label-offset',

    labelFontFamily: '--plasma-date-time-picker__label-font-family',
    labelFontStyle: '--plasma-date-time-picker__label-font-style',
    labelFontSize: '--plasma-date-time-picker__label-font-size',
    labelFontWeight: '--plasma-date-time-picker__label-font-weight',
    labelLetterSpacing: '--plasma-date-time-picker__label-letter-spacing',
    labelLineHeight: '--plasma-date-time-picker__label-line-height',

    /* label-placement-inner */
    labelInnerFontFamily: '--plasma-date-time-picker-placement_inner__label-font-family',
    labelInnerFontStyle: '--plasma-date-time-picker-placement_inner__label-font-style',
    labelInnerFontSize: '--plasma-date-time-picker-placement_inner__label-font-size',
    labelInnerFontWeight: '--plasma-date-time-picker-placement_inner__label-font-weight',
    labelInnerLetterSpacing: '--plasma-date-time-picker-placement_inner__label-letter-spacing',
    labelInnerLineHeight: '--plasma-date-time-picker-placement_inner__label-line-height',

    labelInnerPadding: '--plasma-date-time-picker-placement_inner__label-padding',
    contentLabelInnerPadding: '--plasma-date-time-picker-placement_inner__content-padding',

    /** Токены индикатора */
    indicatorColor: '--plasma-date-time-picker__indicator-color',

    indicatorSize: '--plasma-date-time-picker__indicator-size',
    indicatorSizeOuter: '--plasma-date-time-picker__indicator-size-outer',
    indicatorPlacement: '--plasma-date-time-picker__indicator-placement',
    indicatorPlacementRight: '--plasma-date-time-picker__indicator-placement-right',
    indicatorOuterPlacement: '--plasma-date-time-picker__indicator-placement-outer',
    indicatorOuterPlacementRight: '--plasma-date-time-picker__indicator-placement-outer-right',

    /** Токены вспомогательного текста */
    leftHelperColor: '--plasma-date-time-picker__left-helper-color',
    leftHelperColorError: '--plasma-date-time-picker__left-helper-color-error',
    leftHelperColorSuccess: '--plasma-date-time-picker__left-helper-color-success',
    leftHelperColorReadOnly: '--plasma-date-time-picker__left-helper-color-readonly',
    leftHelperOffset: '--plasma-date-time-picker__left-helper-offset',

    leftHelperFontFamily: '--plasma-date-time-picker__left-helper-font-family',
    leftHelperFontStyle: '--plasma-date-time-picker__left-helper-font-style',
    leftHelperFontSize: '--plasma-date-time-picker__left-helper-font-size',
    leftHelperFontWeight: '--plasma-date-time-picker__left-helper-font-weight',
    leftHelperLetterSpacing: '--plasma-date-time-picker__left-helper-letter-spacing',
    leftHelperLineHeight: '--plasma-date-time-picker__left-helper-line-height',

    /** Токены контейнера календаря */
    popoverShadow: '--plasma-date-time-picker-popover-shadow',
    popoverGap: '--plasma-date-time-picker-popover-gap',
    popoverBorderRadius: '--plasma-date-time-picker-popover-border-radius',
    popoverPadding: '--plasma-date-time-picker-popover-padding',
    // используется для корректного рассчета высоты для TimeGrid
    popoverVerticalPadding: '--plasma-date-time-picker-popover-vertical-padding',
    popoverBackgroundColor: '--plasma-date-time-picker-popover__background-color',
    popoverSeparatorBackground: '--plasma-date-time-picker-popover__separator-background',

    /** Токены календаря */
    calendarWidth: '--plasma-date-time-picker-calendar-width',
    calendarHeight: '--plasma-date-time-picker-calendar-height',
    calendarBorderWidth: '--plasma-date-time-picker-calendar-border-width',
    calendarBorderColor: '--plasma-date-time-picker-calendar-border-color',

    calendarYearsPadding: '--plasma-date-time-picker-calendar__years-padding',
    calendarYearItemBorderRadius: '--plasma-date-time-picker-calendar__year-item-border-radius',
    calendarYearFontFamily: '--plasma-date-time-picker-calendar__year-font-family',
    calendarYearFontSize: '--plasma-date-time-picker-calendar__year-font-size',
    calendarYearFontStyle: '--plasma-date-time-picker-calendar__year-font-style',
    calendarYearFontLetterSpacing: '--plasma-date-time-picker-calendar__year-letter-spacing',
    calendarYearFontLineHeight: '--plasma-date-time-picker-calendar__year-line-height',
    calendarYearFontWeight: '--plasma-date-time-picker-calendar__year-font-weight',
    calendarYearSelectedFontWeight: '--plasma-date-time-picker-calendar__year-selected-font-weight',

    calendarMonthsPadding: '--plasma-date-time-picker-calendar__months-padding',
    calendarMonthItemBorderRadius: '--plasma-date-time-picker-calendar__month-item-border-radius',
    calendarMonthFontFamily: '--plasma-date-time-picker-calendar__month-font-family',
    calendarMonthFontSize: '--plasma-date-time-picker-calendar__month-font-size',
    calendarMonthFontStyle: '--plasma-date-time-picker-calendar__month-font-style',
    calendarMonthFontLetterSpacing: '--plasma-date-time-picker-calendar__month-letter-spacing',
    calendarMonthFontLineHeight: '--plasma-date-time-picker-calendar__month-line-height',
    calendarMonthFontWeight: '--plasma-date-time-picker-calendar__month-font-weight',
    calendarMonthSelectedFontWeight: '--plasma-date-time-picker-calendar__month-selected-font-weight',

    calendarQuartersPadding: '--plasma-date-time-picker-calendar__quarters-padding',
    calendarQuarterItemBorderRadius: '--plasma-date-time-picker-calendar__quarter-item-border-radius',
    calendarQuarterFontFamily: '--plasma-date-time-picker-calendar__quarter-font-family',
    calendarQuarterFontSize: '--plasma-date-time-picker-calendar__quarter-font-size',
    calendarQuarterFontStyle: '--plasma-date-time-picker-calendar__quarter-font-style',
    calendarQuarterFontLetterSpacing: '--plasma-date-time-picker-calendar__quarter-letter-spacing',
    calendarQuarterFontLineHeight: '--plasma-date-time-picker-calendar__quarter-line-height',
    calendarQuarterFontWeight: '--plasma-date-time-picker-calendar__quarter-font-weight',
    calendarQuarterSelectedFontWeight: '--plasma-date-time-picker-calendar__quarter-selected-font-weight',

    calendarDaysPadding: '--plasma-date-time-picker-calendar__days-padding',
    calendarDayItemBorderRadius: '--plasma-date-time-picker-calendar__day-item-border-radius',
    calendarDayFontFamily: '--plasma-date-time-picker-calendar__day-font-family',
    calendarDayFontSize: '--plasma-date-time-picker-calendar__day-font-size',
    calendarDayFontStyle: '--plasma-date-time-picker-calendar__day-font-style',
    calendarDayFontLetterSpacing: '--plasma-date-time-picker-calendar__day-letter-spacing',
    calendarDayFontLineHeight: '--plasma-date-time-picker-calendar__day-line-height',
    calendarDayFontWeight: '--plasma-date-time-picker-calendar__day-font-weight',
    calendarDaySelectedFontWeight: '--plasma-date-time-picker-calendar__day-selected-font-weight',
    calendarDayOfWeekColor: '--plasma-date-time-picker-calendar__day-of-week-color',

    calendarEventItemBottom: '--plasma-date-time-picker-calendar__event-item-bottom',

    calendarHeaderWrapperPadding: '--plasma-date-time-picker-calendar__header-wrapper-padding',
    calendarHeaderArrowGap: '--plasma-date-time-picker-calendar__header-arrow-gap',
    calendarHeaderArrowPadding: '--plasma-date-time-picker-calendar__header-arrow-padding',
    calendarHeaderPadding: '--plasma-date-time-picker-calendar__header-padding',
    calendarHeaderDateGap: '--plasma-date-time-picker-calendar__header-date-gap',
    calendarHeaderFontFamily: '--plasma-date-time-picker-calendar__header-font-family',
    calendarHeaderFontSize: '--plasma-date-time-picker-calendar__header-font-size',
    calendarHeaderFontStyle: '--plasma-date-time-picker-calendar__header-font-style',
    calendarHeaderFontLetterSpacing: '--plasma-date-time-picker-calendar__header-letter-spacing',
    calendarHeaderFontLineHeight: '--plasma-date-time-picker-calendar__header-line-height',
    calendarHeaderFontWeight: '--plasma-date-time-picker-calendar__header-font-weight',
    calendarHeaderFontWeightBold: '--plasma-date-time-picker-calendar__header-font-weight-bold',
    calendarHeaderArrowColor: '--plasma-date-time-picker-calendar__header-arrow-color',
    calendarHeaderArrowCustomSize: '--plasma-date-time-picker-calendar__header-arrow-custom-size',

    iconButtonColor: '--plasma-date-time-picker-icon-button__color',
    iconButtonBackgroundColor: '--plasma-date-time-picker-icon-button__background-color',
    iconButtonColorHover: '--plasma-date-time-picker-icon-button__color-hover',
    iconButtonBackgroundColorHover: '--plasma-date-time-picker-icon-button__background-color-hover',
    iconButtonColorActive: '--plasma-date-time-picker-icon-button__color-active',
    iconButtonBackgroundColorActive: '--plasma-date-time-picker-icon-button__background-color-active',
    iconButtonHeight: '--plasma-date-time-picker-icon-button__height',
    iconButtonWidth: '--plasma-date-time-picker-icon-button__width',
    iconButtonPadding: '--plasma-date-time-picker-icon-button__padding',
    iconButtonRadius: '--plasma-date-time-picker-icon-button__radius',
    iconButtonFocusColor: '--plasma-date-time-picker-icon-button__focus-color',

    calendarSeparatorBackground: '--plasma-date-time-picker-calendar__separator-background',
    calendarSelectedItemBackground: '--plasma-date-time-picker-calendar__selected-item-background',
    calendarSelectedItemColor: '--plasma-date-time-picker-calendar__selected-item-color',
    calendarSelectableItemBackgroundHover: '--plasma-date-time-picker-calendar__selectable-item-background-hover',
    calendarCurrentItemBorderColor: '--plasma-date-time-picker-calendar__current-item-border-color',
    calendarCurrentItemBorderWidth: '--plasma-date-time-picker-calendar__current-item-border-width',
    calendarCurrentItemBackgroundHover: '--plasma-date-time-picker-calendar__current-item-background-hover',
    calendarCurrentItemColorHover: '--plasma-date-time-picker-calendar__current-item-color-hover',
    calendarCurrentItemChildBackgroundHover: '--plasma-date-time-picker-calendar__current-item-child-background-hover',
    calendarActiveItemBackground: '--plasma-date-time-picker-calendar__active-item-background',
    calendarActiveItemColor: '--plasma-date-time-picker-calendar__active-item-color',
    calendarHoveredItemBackground: '--plasma-date-time-picker-calendar__hovered-item-background',
    calendarHoveredItemColor: '--plasma-date-time-picker-calendar__hovered-item-color',
    calendarRangeBackground: '--plasma-date-time-picker-calendar__range-background',
    calendarOutlineFocusColor: '--plasma-date-time-picker-calendar__outline-focus-color',
    calendarContentPrimaryColor: '--plasma-date-time-picker-calendar__content-primary-color',
    calendarContentSecondaryColor: '--plasma-date-time-picker-calendar__content-secondary-color',
    calendarContentPrimaryDisabledColor: '--plasma-date-time-picker-calendar__content-primary-disabled-color',
    calendarContentSecondaryDisabledColor: '--plasma-date-time-picker-calendar__content-secondary-disabled-color',
    calendarDisabledOpacity: '--plasma-date-time-picker-calendar__disabled-opacity',

    /* Токены тултипа для событий */
    tooltipPaddingTop: '--plasma-date-time-picker-calendar-tooltip-padding-top',
    tooltipPaddingRight: '--plasma-date-time-picker-calendar-tooltip-padding-right',
    tooltipPaddingBottom: '--plasma-date-time-picker-calendar-tooltip-padding-bottom',
    tooltipPaddingLeft: '--plasma-date-time-picker-calendar-tooltip-padding-left',
    tooltipMinHeight: '--plasma-date-time-picker-calendar-tooltip-min-height',
    tooltipBackgroundColor: '--plasma-date-time-picker-calendar-tooltip-background-color',
    tooltipBoxShadow: '--plasma-date-time-picker-calendar-tooltip-box-shadow',
    tooltipBorderRadius: '--plasma-date-time-picker-calendar-tooltip-border-radius',
    tooltipColor: '--plasma-date-time-picker-calendar-tooltip-color',
    tooltipTextFontFamily: '--plasma-date-time-picker-calendar-tooltip-text-font-family',
    tooltipTextFontSize: '--plasma-date-time-picker-calendar-tooltip-text-font-size',
    tooltipTextFontStyle: '--plasma-date-time-picker-calendar-tooltip-text-font-style',
    tooltipTextFontWeight: '--plasma-date-time-picker-calendar-tooltip-text-font-weight',
    tooltipTextFontLetterSpacing: '--plasma-date-time-picker-calendar-tooltip-text-font-letter-spacing',
    tooltipTextFontLineHeight: '--plasma-date-time-picker-calendar-tooltip-text-font-line-height',
    tooltipContentLeftMargin: '--plasma-date-time-picker-calendar-tooltip-content-left-margin',
    tooltipArrowMaskWidth: '--plasma-date-time-picker-calendar-tooltip-arrow-mask-width',
    tooltipArrowMaskHeight: '--plasma-date-time-picker-calendar-tooltip-arrow-mask-height',
    tooltipArrowMaskImage: '--plasma-date-time-picker-calendar-tooltip-arrow-mask-image',
    tooltipArrowBackground: '--plasma-date-time-picker-calendar-tooltip-arrow-background',
    tooltipArrowHeight: '--plasma-date-time-picker-calendar-tooltip-arrow-height',
    tooltipArrowEdgeMargin: '--plasma-date-time-picker-calendar-tooltip-arrow-edge-margin',

    /** Токены сетки времени */
    timePickerColumnWidth: '--plasma-date-time-picker-grid-column-width',
    timePickerColumnGap: '--plasma-date-time-picker-grid-column-gap',
    timePickerColumnHeight: '--plasma-date-time-picker-grid-column-height',

    timePickerItemHeight: '--plasma-date-time-picker-grid-item-height',
    timePickerItemBorderRadius: '--plasma-date-time-picker-grid-item-border-radius',
    timePickerItemPadding: '--plasma-date-time-picker-grid-item-padding',
    timePickerItemBackgroundHover: '--plasma-date-time-picker-grid-item-hover-background',
    timePickerItemBackgroundActive: '--plasma-date-time-picker-grid-item-active-background',

    timePickerItemFontFamily: '--plasma-date-time-picker-grid-item-font-family',
    timePickerItemFontStyle: '--plasma-date-time-picker-grid-item-font-style',
    timePickerItemFontSize: '--plasma-date-time-picker-grid-item-font-size',
    timePickerItemFontWeight: '--plasma-date-time-picker-grid-item-font-weight',
    timePickerItemLetterSpacing: '--plasma-date-time-picker-grid-item-letter-spacing',
    timePickerItemLineHeight: '--plasma-date-time-picker-grid-item-line-height',

    timePickerScrollbarWidth: '--plasma-date-time-picker-grid-scrollbar-width',
    timePickerScrollbarColor: '--plasma-date-time-picker-grid-scrollbar-color',
    timePickerScrollbarTrackColor: '--plasma-date-time-picker-grid-scrollbar-track-color',
    timePickerScrollbarMargin: '--plasma-date-time-picker-grid-scrollbar-margin',

    /** Токены предустановленных дат */
    shortcutColor: '--plasma-date-time-picker-shortcut-item-color',
    shortcutBackground: '--plasma-date-time-picker-shortcut-item-background',
    shortcutBackgroundHover: '--plasma-date-time-picker-shortcut-item-background-hover',

    shortcutFontFamily: '--plasma-date-time-picker-shortcut-item-font-family',
    shortcutFontStyle: '--plasma-date-time-picker-shortcut-item-font-style',
    shortcutFontSize: '--plasma-date-time-picker-shortcut-item-font-size',
    shortcutFontWeight: '--plasma-date-time-picker-shortcut-item-font-weight',
    shortcutLetterSpacing: '--plasma-date-time-picker-shortcut-item-letter-spacing',
    shortcutLineHeight: '--plasma-date-time-picker-shortcut-item-line-height',

    shortcutPadding: '--plasma-date-time-picker-shortcut-item-padding',
    shortcutPaddingLeftContent: '--plasma-date-time-picker-shortcut-item-padding-left-content',
    shortcutPaddingContent: '--plasma-date-time-picker-shortcut-item-padding-content',
    shortcutPaddingRightContent: '--plasma-date-time-picker-shortcut-item-right-padding-content',
    shortcutGap: '--plasma-date-time-picker-shortcut-item-gap',
    shortcutBorderRadius: '--plasma-date-time-picker-shortcut-item-border-radius',

    /** Прозрачность для всего компонента в состоянии disabled */
    disabledOpacity: '--plasma-date-time-picker-disabled-opacity',
    outlineFocusColor: '--plasma-date-time-picker-outline-focus',
};
