export const classes = {
    styledInputClass: 'switch-input',
    styledContentWrapperClass: 'switch-content-wrapper',
    styledTriggerClass: 'switch-trigger',
};

export const tokens = {
    fontFamily: '--plasma-switch-font-family',
    fontStyle: '--plasma-switch-font-style',
    fontWeight: '--plasma-switch-font-weight',
    letterSpacing: '--plasma-switch-letter-spacing',
    lineHeight: '--plasma-switch-line-height',
    fontSize: '--plasma-switch-font-size',
    fontColor: '--plasma-switch-font-color',
    flexDirection: '--plasma-switch-flex-direction',
    justifyContent: '--plasma-switch-justify-content',
    switchOpacityDisabled: '--plasma-switch-opacity-disabled',
    switchFontColorDisabled: '--plasma-switch-font-color-disabled',
    switchFocusColor: '--plasma-switch-focus-color',
    switchTriggerWidth: '--plasma-switch-trigger-width',
    switchTriggerHeight: '--plasma-switch-trigger-height',
    switchTriggerBackground: '--plasma-switch-trigger-background',
    switchTriggerBackgroundHover: '--plasma-switch-trigger-background-hover',
    switchTriggerBackgroundDisabled: '--plasma-switch-trigger-background-disabled',
    switchTriggerBackgroundChecked: '--plasma-switch-trigger-background-checked',
    switchTriggerBackgroundCheckedHover: '--plasma-switch-trigger-background-checked-hover',
    switchTriggerBackgroundCheckedDisabled: '--plasma-switch-trigger-background-checked-disabled',
    switchTriggerBackgroundCheckedDisabledHover: '--plasma-switch-trigger-background-checked-disabled-hover',
    switchTriggerBorderRadius: '--plasma-switch-trigger-border-radius',
    switchEllipseSize: '--plasma-switch-ellipse-size',
    switchEllipseMargin: '--plasma-switch-ellipse-margin',
    switchEllipseBackground: '--plasma-switch-ellipse-background',
    switchEllipseBoxShadow: '--plasma-switch-ellipse-box-shadow',
    switchEllipseBoxShadowSize: '--plasma-switch-ellipse-box-shadow-size',
    switchEllipseBoxShadowChecked: '--plasma-switch-ellipse-box-shadow-checked',
    switchEllipseBoxShadowDisabled: '--plasma-switch-ellipse-box-shadow-disabled',
};
