import debug from 'debug';
import { Params } from './types';
export declare const log: debug.Debugger;
export declare const reArgPrefix: RegExp;
export declare const isDir: (pathname: string) => boolean;
export declare function asyncChain<T extends (...args: any) => any, Args>(callback: T, ...args: Args[]): () => Promise<ReturnType<T>>;
export declare function parseArg(arg: string): string[];
export declare function wrapPromise<T>(promiseGetter: () => Promise<T>): Promise<[T, null] | [null, Error]>;
export declare function readDir(pathname: string): Promise<string[]>;
export declare function getRunnerParams(): Params;
