"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.config = void 0;
var _styledComponents = /*#__PURE__*/require("@salutejs/plasma-new-hope/styled-components");
var _templateObject, _templateObject2, _templateObject3, _templateObject4, _templateObject5, _templateObject6, _templateObject7, _templateObject8, _templateObject9;
function _taggedTemplateLiteral(strings, raw) { if (!raw) { raw = strings.slice(0); } return Object.freeze(Object.defineProperties(strings, { raw: { value: Object.freeze(raw) } })); }
var config = exports.config = {
  defaults: {
    view: 'clear',
    size: 'xs'
  },
  variations: {
    view: {
      clear: /*#__PURE__*/(0, _styledComponents.css)(_templateObject || (_templateObject = /*#__PURE__*/_taggedTemplateLiteral(["\n                ", ": var(--plasma-colors-secondary);\n                ", ": transparent;\n                ", ": var(--plasma-colors-primary);\n                ", ": transparent;\n                ", ": var(--plasma-colors-primary);\n                ", ": transparent;\n                ", ": var(--plasma-colors-primary);\n                ", ": transparent;\n\n                ", ": var(--surface-accent);\n            "])), _styledComponents.segmentTokens.itemColor, _styledComponents.segmentTokens.itemBackgroundColor, _styledComponents.segmentTokens.itemColorHover, _styledComponents.segmentTokens.itemBackgroundColorHover, _styledComponents.segmentTokens.itemSelectedColor, _styledComponents.segmentTokens.itemSelectedBackgroundColor, _styledComponents.segmentTokens.itemSelectedColorHover, _styledComponents.segmentTokens.itemSelectedBackgroundColorHover, _styledComponents.segmentTokens.outlineFocusColor),
      "default": /*#__PURE__*/(0, _styledComponents.css)(_templateObject2 || (_templateObject2 = /*#__PURE__*/_taggedTemplateLiteral(["\n                ", ": var(--plasma-colors-primary);\n                ", ": transparent;\n                ", ": var(--plasma-colors-primary);\n                ", ": transparent;\n                ", ": var(--inverse-text-primary);\n                ", ": var(--plasma-colors-text);\n                ", ": var(--inverse-text-primary);\n                ", ": var(--plasma-colors-text);\n\n                ", ": var(--surface-accent);\n            "])), _styledComponents.segmentTokens.itemColor, _styledComponents.segmentTokens.itemBackgroundColor, _styledComponents.segmentTokens.itemColorHover, _styledComponents.segmentTokens.itemBackgroundColorHover, _styledComponents.segmentTokens.itemSelectedColor, _styledComponents.segmentTokens.itemSelectedBackgroundColor, _styledComponents.segmentTokens.itemSelectedColorHover, _styledComponents.segmentTokens.itemSelectedBackgroundColorHover, _styledComponents.segmentTokens.outlineFocusColor),
      secondary: /*#__PURE__*/(0, _styledComponents.css)(_templateObject3 || (_templateObject3 = /*#__PURE__*/_taggedTemplateLiteral(["\n                ", ": var(--plasma-colors-primary);\n                ", ": transparent;\n                ", ": var(--plasma-colors-primary);\n                ", ": transparent;\n                ", ": var(--plasma-colors-primary);\n                ", ": var(--plasma-colors-surface-card);\n                ", ": var(--plasma-colors-primary);\n                ", ": var(--plasma-colors-surface-card);\n\n                ", ": var(--surface-accent);\n            "])), _styledComponents.segmentTokens.itemColor, _styledComponents.segmentTokens.itemBackgroundColor, _styledComponents.segmentTokens.itemColorHover, _styledComponents.segmentTokens.itemBackgroundColorHover, _styledComponents.segmentTokens.itemSelectedColor, _styledComponents.segmentTokens.itemSelectedBackgroundColor, _styledComponents.segmentTokens.itemSelectedColorHover, _styledComponents.segmentTokens.itemSelectedBackgroundColorHover, _styledComponents.segmentTokens.outlineFocusColor)
    },
    size: {
      xs: /*#__PURE__*/(0, _styledComponents.css)(_templateObject4 || (_templateObject4 = /*#__PURE__*/_taggedTemplateLiteral(["\n                ", ": 0.375rem;\n                ", ": auto;\n                ", ": 1.5rem;\n                ", ": 0 0.625rem;\n                ", ": 0.125rem;\n\n                ", ": var(--plasma-typo-body-xs-font-family);\n                ", ": var(--plasma-typo-body-xs-font-size);\n                ", ": var(--plasma-typo-body-xs-font-style);\n                ", ": var(--plasma-typo-body-xs-font-weight);\n                ", ": var(--plasma-typo-body-xs-letter-spacing);\n                ", ": var(--plasma-typo-body-xs-line-height);\n            "])), _styledComponents.segmentTokens.itemBorderRadius, _styledComponents.segmentTokens.itemWidth, _styledComponents.segmentTokens.itemHeight, _styledComponents.segmentTokens.itemPadding, _styledComponents.segmentTokens.itemMarginLeft, _styledComponents.segmentTokens.fontFamily, _styledComponents.segmentTokens.fontSize, _styledComponents.segmentTokens.fontStyle, _styledComponents.segmentTokens.fontWeight, _styledComponents.segmentTokens.letterSpacing, _styledComponents.segmentTokens.lineHeight),
      s: /*#__PURE__*/(0, _styledComponents.css)(_templateObject5 || (_templateObject5 = /*#__PURE__*/_taggedTemplateLiteral(["\n                ", ": 0.5rem;\n                ", ": auto;\n                ", ": 2rem;\n                ", ": 0 0.75rem;\n                ", ": 0.125rem;\n\n                ", ": var(--plasma-typo-body-s-font-family);\n                ", ": var(--plasma-typo-body-s-font-size);\n                ", ": var(--plasma-typo-body-s-font-style);\n                ", ": var(--plasma-typo-body-s-font-weight);\n                ", ": var(--plasma-typo-body-s-letter-spacing);\n                ", ": var(--plasma-typo-body-s-line-height);\n            "])), _styledComponents.segmentTokens.itemBorderRadius, _styledComponents.segmentTokens.itemWidth, _styledComponents.segmentTokens.itemHeight, _styledComponents.segmentTokens.itemPadding, _styledComponents.segmentTokens.itemMarginLeft, _styledComponents.segmentTokens.fontFamily, _styledComponents.segmentTokens.fontSize, _styledComponents.segmentTokens.fontStyle, _styledComponents.segmentTokens.fontWeight, _styledComponents.segmentTokens.letterSpacing, _styledComponents.segmentTokens.lineHeight),
      m: /*#__PURE__*/(0, _styledComponents.css)(_templateObject6 || (_templateObject6 = /*#__PURE__*/_taggedTemplateLiteral(["\n                ", ": 0.625rem;\n                ", ": auto;\n                ", ": 2.5rem;\n                ", ": 0 0.875rem;\n                ", ": 0.125rem;\n\n                ", ": var(--plasma-typo-body-m-font-family);\n                ", ": var(--plasma-typo-body-m-font-size);\n                ", ": var(--plasma-typo-body-m-font-style);\n                ", ": var(--plasma-typo-body-m-font-weight);\n                ", ": var(--plasma-typo-body-m-letter-spacing);\n                ", ": var(--plasma-typo-body-m-line-height);\n            "])), _styledComponents.segmentTokens.itemBorderRadius, _styledComponents.segmentTokens.itemWidth, _styledComponents.segmentTokens.itemHeight, _styledComponents.segmentTokens.itemPadding, _styledComponents.segmentTokens.itemMarginLeft, _styledComponents.segmentTokens.fontFamily, _styledComponents.segmentTokens.fontSize, _styledComponents.segmentTokens.fontStyle, _styledComponents.segmentTokens.fontWeight, _styledComponents.segmentTokens.letterSpacing, _styledComponents.segmentTokens.lineHeight),
      l: /*#__PURE__*/(0, _styledComponents.css)(_templateObject7 || (_templateObject7 = /*#__PURE__*/_taggedTemplateLiteral(["\n                ", ": 0.75rem;\n                ", ": auto;\n                ", ": 3rem;\n                ", ": 0 1rem;\n                ", ": 0.125rem;\n\n                ", ": var(--plasma-typo-body-l-font-family);\n                ", ": var(--plasma-typo-body-l-font-size);\n                ", ": var(--plasma-typo-body-l-font-style);\n                ", ": var(--plasma-typo-body-l-font-weight);\n                ", ": var(--plasma-typo-body-l-letter-spacing);\n                ", ": var(--plasma-typo-body-l-line-height);\n            "])), _styledComponents.segmentTokens.itemBorderRadius, _styledComponents.segmentTokens.itemWidth, _styledComponents.segmentTokens.itemHeight, _styledComponents.segmentTokens.itemPadding, _styledComponents.segmentTokens.itemMarginLeft, _styledComponents.segmentTokens.fontFamily, _styledComponents.segmentTokens.fontSize, _styledComponents.segmentTokens.fontStyle, _styledComponents.segmentTokens.fontWeight, _styledComponents.segmentTokens.letterSpacing, _styledComponents.segmentTokens.lineHeight)
    },
    disabled: {
      "true": /*#__PURE__*/(0, _styledComponents.css)(_templateObject8 || (_templateObject8 = /*#__PURE__*/_taggedTemplateLiteral(["\n                ", ": 0.4;\n            "])), _styledComponents.segmentTokens.disabledOpacity)
    },
    pilled: {
      "true": /*#__PURE__*/(0, _styledComponents.css)(_templateObject9 || (_templateObject9 = /*#__PURE__*/_taggedTemplateLiteral(["\n                ", ": 1.5rem;\n            "])), _styledComponents.segmentTokens.itemPilledBorderRadius)
    }
  }
};