import { TokenType } from '../../../types';

export const shadowTokens: Array<TokenType> = [
    {
        type: 'shadow',
        name: 'down.soft.s',
        tags: ['down', 'soft', 's'],
        displayName: 'shadowDownSoftS',
        description: 'shadow down soft s',
        enabled: true,
    },
    {
        type: 'shadow',
        name: 'down.soft.m',
        tags: ['down', 'soft', 'm'],
        displayName: 'shadowDownSoftM',
        description: 'shadow down soft m',
        enabled: true,
    },
    {
        type: 'shadow',
        name: 'down.soft.l',
        tags: ['down', 'soft', 'l'],
        displayName: 'shadowDownSoftL',
        description: 'shadow down soft l',
        enabled: true,
    },
    {
        type: 'shadow',
        name: 'down.hard.s',
        tags: ['down', 'hard', 's'],
        displayName: 'shadowDownHardS',
        description: 'shadow down hard s',
        enabled: true,
    },
    {
        type: 'shadow',
        name: 'down.hard.m',
        tags: ['down', 'hard', 'm'],
        displayName: 'shadowDownHardM',
        description: 'shadow down hard m',
        enabled: true,
    },
    {
        type: 'shadow',
        name: 'down.hard.l',
        tags: ['down', 'hard', 'l'],
        displayName: 'shadowDownHardL',
        description: 'shadow down hard l',
        enabled: true,
    },
    {
        type: 'shadow',
        name: 'up.soft.s',
        tags: ['up', 'soft', 's'],
        displayName: 'shadowUpSoftS',
        description: 'shadow up soft s',
        enabled: true,
    },
    {
        type: 'shadow',
        name: 'up.soft.m',
        tags: ['up', 'soft', 'm'],
        displayName: 'shadowUpSoftM',
        description: 'shadow up soft m',
        enabled: true,
    },
    {
        type: 'shadow',
        name: 'up.soft.l',
        tags: ['up', 'soft', 'l'],
        displayName: 'shadowUpSoftL',
        description: 'shadow up soft l',
        enabled: true,
    },
    {
        type: 'shadow',
        name: 'up.hard.s',
        tags: ['up', 'hard', 's'],
        displayName: 'shadowUpHardS',
        description: 'shadow up hard s',
        enabled: true,
    },
    {
        type: 'shadow',
        name: 'up.hard.m',
        tags: ['up', 'hard', 'm'],
        displayName: 'shadowUpHardM',
        description: 'shadow up hard m',
        enabled: true,
    },
    {
        type: 'shadow',
        name: 'up.hard.l',
        tags: ['up', 'hard', 'l'],
        displayName: 'shadowUpHardL',
        description: 'shadow up hard l',
        enabled: true,
    },
];
