export const classes = {
    suggestionItemIsFocused: 'suggestion-item-is-focused',
};

export const tokens = {
    // Токены для TextField
    textFieldColor: '--plasma-autocomplete-textfield-color',
    textFieldBackgroundColor: '--plasma-autocomplete-textfield-background-color',
    textFieldBackgroundColorHover: '--plasma-autocomplete-textfield-background-color-hover',
    textFieldBackgroundColorFocus: '--plasma-autocomplete-textfield-background-color-focus',
    textFieldBorderColor: '--plasma-autocomplete-textfield-border-color',
    textFieldBorderColorHover: '--plasma-autocomplete-textfield-border-color-hover',
    textFieldBorderColorFocus: '--plasma-autocomplete-textfield-border-color-focus',
    textFieldColorReadOnly: '--plasma-autocomplete-textfield-color-readonly',
    textFieldBackgroundColorReadOnly: '--plasma-autocomplete-textfield-bg-color-readonly',
    textFieldBorderColorReadOnly: '--plasma-autocomplete-textfield-border-color-readonly',
    textFieldPlaceholderColorReadOnly: '--plasma-autocomplete-textfield__placeholder-color-readonly',
    textFieldCaretColor: '--plasma-autocomplete-textfield-caret-color',
    textFieldPlaceholderColor: '--plasma-autocomplete-textfield-placeholder-color',
    textFieldHeight: '--plasma-autocomplete-textfield-height',
    textFieldBorderWidth: '--plasma-autocomplete-textfield-border-width',
    textFieldBorderRadius: '--plasma-autocomplete-textfield-border-radius',
    textFieldPadding: '--plasma-autocomplete-textfield-padding',
    textFieldLeftContentMargin: '--plasma-autocomplete-textfield__left-content-margin',
    textFieldRightContentMargin: '--plasma-autocomplete-textfield__right-content-margin',
    textFieldFontFamily: '--plasma-autocomplete-textfield-font-family',
    textFieldFontStyle: '--plasma-autocomplete-textfield-font-style',
    textFieldFontSize: '--plasma-autocomplete-textfield-font-size',
    textFieldFontWeight: '--plasma-autocomplete-textfield-font-weight',
    textFieldLetterSpacing: '--plasma-autocomplete-textfield-letter-spacing',
    textFieldLineHeight: '--plasma-autocomplete-textfield-line-height',
    textFieldLabelColor: '--plasma-autocomplete-textfield-label-color',
    textFieldLabelColorReadOnly: '--plasma-autocomplete-textfield__label-color-readonly',
    textFieldLabelOffset: '--plasma-autocomplete-textfield__label-offset',
    textFieldLabelFontFamily: '--plasma-autocomplete-textfield__label-font-family',
    textFieldLabelFontStyle: '--plasma-autocomplete-textfield__label-font-style',
    textFieldLabelFontSize: '--plasma-autocomplete-textfield__label-font-size',
    textFieldLabelFontWeight: '--plasma-autocomplete-textfield__label-font-weight',
    textFieldLabelLetterSpacing: '--plasma-autocomplete-textfield__label-letter-spacing',
    textFieldLabelLineHeight: '--plasma-autocomplete-textfield__label-line-height',
    textFieldLabelInnerFontFamily: '--plasma-autocomplete-textfield-placement_inner__label-font-family',
    textFieldLabelInnerFontStyle: '--plasma-autocomplete-textfield-placement_inner__label-font-style',
    textFieldLabelInnerFontSize: '--plasma-autocomplete-textfield-placement_inner__label-font-size',
    textFieldLabelInnerFontWeight: '--plasma-autocomplete-textfield-placement_inner__label-font-weight',
    textFieldLabelInnerLetterSpacing: '--plasma-autocomplete-textfield-placement_inner__label-letter-spacing',
    textFieldLabelInnerLineHeight: '--plasma-autocomplete-textfield-placement_inner__label-line-height',
    textFieldLabelInnerPadding: '--plasma-autocomplete-textfield-placement_inner__label-padding',
    textFieldContentLabelInnerPadding: '--plasma-autocomplete-textfield-placement_inner__content-padding',
    textFieldLeftHelperColor: '--plasma-autocomplete-textfield__left-helper-color',
    textFieldLeftHelperColorReadOnly: '--plasma-autocomplete-textfield__left-helper-color-readonly',
    textFieldLeftHelperOffset: '--plasma-autocomplete-textfield__left-helper-offset',
    textFieldLeftHelperFontFamily: '--plasma-autocomplete-textfield__left-helper-font-family',
    textFieldLeftHelperFontStyle: '--plasma-autocomplete-textfield__left-helper-font-style',
    textFieldLeftHelperFontSize: '--plasma-autocomplete-textfield__left-helper-font-size',
    textFieldLeftHelperFontWeight: '--plasma-autocomplete-textfield__left-helper-font-weight',
    textFieldLeftHelperLetterSpacing: '--plasma-autocomplete-textfield__left-helper-letter-spacing',
    textFieldLeftHelperLineHeight: '--plasma-autocomplete-textfield__left-helper-line-height',
    textFieldTextBeforeColor: '--plasma-autocomplete-textfield__before-text-color',
    textFieldTextAfterColor: '--plasma-autocomplete-textfield__after-text-color',
    textFieldTextBeforeMargin: '--plasma-autocomplete-textfield__before-text-margin',
    textFieldTextAfterMargin: '--plasma-autocomplete-textfield__after-text-margin',
    textFieldDisabledOpacity: '--plasma-autocomplete-textfield-disabled-opacity',
    textFieldFocusColor: '--plasma-autocomplete-textfield-focus-color',
    textFieldContentSlotColor: '--plasma-autocomplete-content-color',

    // Токены для дропдауна
    background: '--plasma-autocomplete-background',
    boxShadow: '--plasma-autocomplete-box-shadow',
    borderRadius: '--plasma-autocomplete-border-radius',
    padding: '--plasma-autocomplete-padding',

    dropdownBorderColor: '--plasma-select-dropdown-border-color',
    dropdownBorderWidth: '--plasma-select-dropdown-border-width',

    itemPadding: '--plasma-autocomplete-item-padding',
    itemBorderRadius: '--plasma-autocomplete-item-border-radius',

    itemFontFamily: '--plasma-autocomplete-item-font-family',
    itemFontSize: '--plasma-autocomplete-item-font-size',
    itemFontStyle: '--plasma-autocomplete-item-font-style',
    itemFontWeight: '--plasma-autocomplete-item-font-weight',
    itemFontLetterSpacing: '--plasma-autocomplete-item-font-letter-spacing',
    itemFontLineHeight: '--plasma-autocomplete-item-font-line-height',

    itemBackground: '--plasma-autocomplete-item-background',
    itemBackgroundHover: '--plasma-autocomplete-item-background-hover',
    itemColor: '--plasma-autocomplete-item-color',

    focusColor: '--plasma-autocomplete-focus-color',

    infiniteLoaderSpinnerColor: '--plasma-autocomplete-infinite-loader-spinner-color',
    infiniteLoaderSpinnerSize: '--plasma-autocomplete-infinite-loader-spinner-size',
    infiniteLoaderGap: '--plasma-autocomplete-infinite-loader-gap',

    emptyStateGap: '--plasma-autocomplete-empty-state-gap',
    emptyStatePadding: '--plasma-autocomplete-empty-state-padding',
};
