export const classes = {
    labelPlacementOuter: 'slider-label-placement-outer',
    labelPlacementInner: 'slider-label-placement-inner',
    labelPlacementBottom: 'slider-label-placement-bottom',
    scalePlacementTop: 'slider-scale-placement-top',
    labelAlignLeft: 'slider-label-align-left',
    labelAlignCenter: 'slider-label-align-center',
    labelAlignRight: 'slider-label-align-right',
    labelAlignNone: 'slider-label-align-none',
    labelContentReversed: 'slider-label-content-reversed',
    rangeValuesPlacementOuter: 'slider-range-values-placement-outer',
    rangeValuesPlacementInner: 'slider-range-values-placement-inner',
    maxRangeValue: 'slider-max-range-value',
    hideMinValue: 'slider-hide-min-value',
    hideMaxValue: 'slider-hide-max-value',
    textFieldHovered: 'slider-text-field-hovered',
    textFieldFocused: 'slider-text-field-focused',
    firstTextField: 'slider-first-text-field',
    secondTextField: 'slider-second-text-field',
    activeRangeValue: 'slider-active-range-value',
    verticalOrientation: 'slider-vertical-orientation',
    valuePlacementTop: 'slider-value-placement-top',
    valuePlacementBottom: 'slider-value-placement-bottom',
    valuePlacementLeft: 'slider-value-placement-left',
    valuePlacementRight: 'slider-value-placement-right',
    valuePlacementNone: 'slider-value-placement-none',
    reversed: 'slider-reversed',
    pointerHidden: 'slider-pointer-hidden',
};

export const tokens = {
    size: '--plasma-slider-size',

    labelWrapperGap: '--plasma-slider-label-wrapper-gap',
    labelWrapperMarginBottom: '--plasma-slider-label-wrapper-margin-bottom',
    labelWrapperMarginRight: '--plasma-slider-label-wrapper-margin-right',
    labelWrapperOnlyIconMarginRight: '--plasma-slider-label-wrapper-only-icon-margin-right',
    labelWrapperVerticalMargin: '--plasma-slider-label-wrapper-vertical-margin',

    labelColor: '--plasma-slider-label-color',
    labelFontFamily: '--plasma-slider-label-font-family',
    labelFontSize: '--plasma-slider-label-font-size',
    labelFontStyle: '--plasma-slider-label-font-style',
    labelFontWeight: '--plasma-slider-label-font-weight',
    labelLetterSpacing: '--plasma-slider-label-letter-spacing',
    labelLineHeight: '--plasma-slider-label-line-height',

    rangeValueBottomOffset: '--plasma-slider-range-value-bottom-offset',
    rangeValueHorizontalMargin: '--plasma-slider-range-value-horizontal-margin',
    rangeValueHorizontalOffset: '--plasma-slider-range-value-horizontal-offset',
    rangeValueVerticalMargin: '--plasma-slider-range-value-vertical-margin',

    rangeValueColor: '--plasma-slider-range-value-color',
    valueFontFamily: '--plasma-slider-value-font-family',
    valueFontSize: '--plasma-slider-value-font-size',
    valueFontStyle: '--plasma-slider-value-font-style',
    valueFontWeight: '--plasma-slider-value-font-weight',
    valueLetterSpacing: '--plasma-slider-value-letter-spacing',
    valueLineHeight: '--plasma-slider-value-line-height',

    doubleWrapperGap: '--plasma-slider-double-wrapper-gap',
    doubleBoxShadow: '--plasma-slider-double-box-shadow',

    thumbSize: '--plasma-slider-thumb-size',
    thumbHeight: '--plasma-slider-thumb-height',
    thumbBorderStyle: '--plasma-slider-thumb-border-style',
    thumbBorderWidth: '--plasma-slider-thumb-border-width',
    thumbBorderRadius: '--plasma-slider-thumb-border-radius',
    thumbBorderColor: '--plasma-slider-thumb-border-color',
    thumbBackgroundColor: '--plasma-slider-thumb-background-color',
    thumbInnerContent: '--plasma-slider-thumb-inner-content',

    thumbFocusBorderColor: '--plasma-slider-thumb-focus-border-color',

    tickSize: '--plasma-slider-tick-size',
    tickDotColor: '--plasma-slider-tick-dot-color',
    tickDotFilledColor: '--plasma-slider-tick-dot-filled-color',
    tickDotOffset: '--plasma-slider-tick-dot-offset',

    currentValueTopOffset: '--plasma-slider-current-value-top-offset',

    railBackgroundColor: '--plasma-slider-rail-background-color',
    railThickness: '--plasma-slider-rail-thickness',
    railBorderRadius: '--plasma-slider-rail-border-radius',
    railIndent: '--plasma-slider-rail-indent',

    fillColor: '--plasma-slider-fill-color',

    textFieldWrapperGap: '--plasma-slider-text-field-wrapper-gap',

    textFieldFontFamily: '--plasma-slider-text-field-font-family',
    textFieldFontSize: '--plasma-slider-text-field-font-size',
    textFieldFontStyle: '--plasma-slider-text-field-font-style',
    textFieldFontWeight: '--plasma-slider-text-field-font-weight',
    textFieldLetterSpacing: '--plasma-slider-text-field-letter-spacing',
    textFieldLineHeight: '--plasma-slider-text-field-line-height',

    textFieldHeight: '--plasma-slider-text-field-height',
    textFieldPadding: '--plasma-slider-text-field-padding',
    textFieldBorderRadius: '--plasma-slider-text-field-border-radius',

    textFieldWebClipPath: '--plasma-slider-text-field-web-clip-path',
    textFieldWebReversedClipPath: '--plasma-slider-text-field-web-reversed-clip-path',
    textFieldWebMarginRight: '--plasma-slider-text-field-web-margin-right',
    textFieldColor: '--plasma-slider-text-field-color',
    textFiledFocusColor: '--plasma-slider-text-field-focus-color',
    textFieldCaretColor: '--plasma-slider-text-field-caret-color',
    textFieldPlaceholderColor: '--plasma-slider-text-field-placeholder-color',

    textFieldBackgroundColor: '--plasma-slider-text-field-background-color',
    textFieldBackgroundColorHover: '--plasma-slider-text-field-background-color-hover',
    textFieldBackgroundColorFocus: '--plasma-slider-text-field-background-color-focus',

    textFieldBorderWidth: '--plasma-slider-text-field-border-width',
    textFieldBorderColor: '--plasma-slider-text-field-border-color',
    textFieldBorderColorHover: '--plasma-slider-text-field-border-color-hover',
    textFieldBorderColorFocus: '--plasma-slider-text-field-border-color-focus',

    disabledOpacity: '--plasma-slider-disabled-opacity',
};
