export {
    addFocus,
    syntheticFocus,
    applyBlur,
    blurs,
    applyDisabled,
    applyEllipsis,
    applyHyphens,
    applyMaxLines,
    applyNoSelect,
    applyRoundness,
    radiuses,
    applyView,
    views,
    applyScrollSnap,
    shadows,
    applySpacing,
} from '@salutejs/plasma-core';

export type {
    FocusProps,
    OutlinedProps,
    BlurProps,
    DisabledProps,
    MaxLinesProps,
    RoundnessProps,
    Roundness,
    ViewProps,
    View,
    ScrollSnapProps,
    SpacingProps,
} from '@salutejs/plasma-core';
