export const classes = {
    dropdownRoot: 'dropdown-root',
    dropdownItemIsFocused: 'dropdown-item-is-focused',
    dropdownItemIsDisabled: 'dropdown-item-is-disabled',
    dropdownItemIsActive: 'dropdown-item-is-active',
    dropdownItemIsSelected: 'dropdownItemIsSelected',
};

export const tokens = {
    background: '--plasma-select-background',
    boxShadow: '--plasma-select-box-shadow',
    width: '--plasma-select-width',
    borderRadius: '--plasma-select-border-radius',
    padding: '--plasma-select-padding',
    disclosureIconColor: '--plasma-select-disclosure-icon-color',
    disabledOpacity: '--plasma-select-disabled-opacity',
    focusColor: '--plasma-select-focus-color',

    itemHeight: '--plasma-select-item-height',
    itemBackground: '--plasma-select-item-background',
    itemBackgroundHover: '--plasma-select-item-background-hover',
    itemColor: '--plasma-select-item-color',
    itemBorderRadius: '--plasma-select-item-border-radius',
    itemPaddingTop: '--plasma-select-item-padding-top',
    itemPaddingTopTight: '--plasma-select-item-padding-top-tight',
    itemPaddingRight: '--plasma-select-item-padding-right',
    itemPaddingBottom: '--plasma-select-item-padding-bottom',
    itemPaddingBottomTight: '--plasma-select-item-padding-bottom-tight',
    itemPaddingLeft: '--plasma-select-item-padding-left',
    itemFontFamily: '--plasma-select-item-font-family',
    itemFontSize: '--plasma-select-item-font-size',
    itemFontStyle: '--plasma-select-item-font-style',
    itemFontWeightBold: '--plasma-select-item-letter-spacing',
    itemFontLetterSpacing: '--plasma-select-item-line-height',
    itemFontLineHeight: '--plasma-select-item-font-weight',
    itemIconSize: '--plasma-select-item-icon-size',
    itemIconMargin: '--plasma-select-item-icon-margin',

    checkboxMargin: '--plasma-select-checkbox-margin',
    checkboxTriggerMargin: '--plasma-select-checkbox-trigger-margin',
    checkboxTriggerSize: '--plasma-select-checkbox-trigger-size',
    checkboxTriggerBorderRadius: '--plasma-select-checkbox-trigger-border-radius',
    checkboxFillColor: '--plasma-select-checkbox-fill-color',
    checkboxIconColor: '--plasma-select-checkbox-icon-color',
    checkboxTriggerBorderColor: '--plasma-select-checkbox-trigger-border-color',

    indicatorSize: '--plasma-select-indicator-size',
};
