"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.config = void 0;
var _styledComponents = /*#__PURE__*/require("@salutejs/plasma-new-hope/styled-components");
var _templateObject, _templateObject2, _templateObject3, _templateObject4, _templateObject5, _templateObject6, _templateObject7, _templateObject8, _templateObject9, _templateObject10, _templateObject11;
function _taggedTemplateLiteral(strings, raw) { if (!raw) { raw = strings.slice(0); } return Object.freeze(Object.defineProperties(strings, { raw: { value: Object.freeze(raw) } })); }
var config = exports.config = {
  defaults: {
    view: 'primary',
    focused: 'true'
  },
  variations: {
    view: {
      primary: /*#__PURE__*/(0, _styledComponents.css)(_templateObject || (_templateObject = /*#__PURE__*/_taggedTemplateLiteral(["\n                --plasma-link-font-family: var(--plasma-typo-text-m-font-family);\n                --plasma-link-color: var(--text-primary);\n                --plasma-link-color-hover: var(--text-primary-hover);\n                --plasma-link-color-active: var(--text-primary-active);\n                --plasma-link-color-visited: var(--text-primary);\n                --plasma-link-color-visited-hover: var(--text-primary-hover);\n                --plasma-link-color-visited-active: var(--text-primary-active);\n                --plasma-link-underline-border: 0;\n            "]))),
      secondary: /*#__PURE__*/(0, _styledComponents.css)(_templateObject2 || (_templateObject2 = /*#__PURE__*/_taggedTemplateLiteral(["\n                --plasma-link-font-family: var(--plasma-typo-text-m-font-family);\n                --plasma-link-color: var(--text-secondary);\n                --plasma-link-color-hover: var(--text-secondary-hover);\n                --plasma-link-color-active: var(--text-secondary-active);\n                --plasma-link-color-visited: var(--text-secondary);\n                --plasma-link-color-visited-hover: var(--text-secondary-hover);\n                --plasma-link-color-visited-active: var(--text-secondary-active);\n                --plasma-link-underline-border: 0;\n            "]))),
      tertiary: /*#__PURE__*/(0, _styledComponents.css)(_templateObject3 || (_templateObject3 = /*#__PURE__*/_taggedTemplateLiteral(["\n                --plasma-link-font-family: var(--plasma-typo-text-m-font-family);\n                --plasma-link-color: var(--text-tertiary);\n                --plasma-link-color-hover: var(--text-tertiary-hover);\n                --plasma-link-color-active: var(--text-tertiary-active);\n                --plasma-link-color-visited: var(--text-tertiary);\n                --plasma-link-color-visited-hover: var(--text-tertiary-hover);\n                --plasma-link-color-visited-active: var(--text-tertiary-active);\n                --plasma-link-underline-border: 0;\n            "]))),
      paragraph: /*#__PURE__*/(0, _styledComponents.css)(_templateObject4 || (_templateObject4 = /*#__PURE__*/_taggedTemplateLiteral(["\n                --plasma-link-font-family: var(--plasma-typo-text-m-font-family);\n                --plasma-link-color: var(--text-paragraph);\n                --plasma-link-color-hover: var(--text-paragraph-hover);\n                --plasma-link-color-active: var(--text-paragraph-active);\n                --plasma-link-color-visited: var(--text-paragraph);\n                --plasma-link-color-visited-hover: var(--text-paragraph-hover);\n                --plasma-link-color-visited-active: var(--text-paragraph-active);\n                --plasma-link-underline-border: 0;\n            "]))),
      accent: /*#__PURE__*/(0, _styledComponents.css)(_templateObject5 || (_templateObject5 = /*#__PURE__*/_taggedTemplateLiteral(["\n                --plasma-link-font-family: var(--plasma-typo-text-m-font-family);\n                --plasma-link-color: var(--text-accent);\n                --plasma-link-color-hover: var(--text-accent-hover);\n                --plasma-link-color-active: var(--text-accent-active);\n                --plasma-link-color-visited: var(--text-accent);\n                --plasma-link-color-visited-hover: var(--text-accent-hover);\n                --plasma-link-color-visited-active: var(--text-accent-active);\n                --plasma-link-underline-border: 0;\n            "]))),
      positive: /*#__PURE__*/(0, _styledComponents.css)(_templateObject6 || (_templateObject6 = /*#__PURE__*/_taggedTemplateLiteral(["\n                --plasma-link-font-family: var(--plasma-typo-text-m-font-family);\n                --plasma-link-color: var(--text-positive);\n                --plasma-link-color-hover: var(--text-positive-hover);\n                --plasma-link-color-active: var(--text-positive-active);\n                --plasma-link-color-visited: var(--text-positive);\n                --plasma-link-color-visited-hover: var(--text-positive-hover);\n                --plasma-link-color-visited-active: var(--text-positive-active);\n                --plasma-link-underline-border: 0;\n            "]))),
      warning: /*#__PURE__*/(0, _styledComponents.css)(_templateObject7 || (_templateObject7 = /*#__PURE__*/_taggedTemplateLiteral(["\n                --plasma-link-font-family: var(--plasma-typo-text-m-font-family);\n                --plasma-link-color: var(--text-warning);\n                --plasma-link-color-hover: var(--text-warning-hover);\n                --plasma-link-color-active: var(--text-warning-active);\n                --plasma-link-color-visited: var(--text-warning);\n                --plasma-link-color-visited-hover: var(--text-warning-hover);\n                --plasma-link-color-visited-active: var(--text-warning-active);\n                --plasma-link-underline-border: 0;\n            "]))),
      negative: /*#__PURE__*/(0, _styledComponents.css)(_templateObject8 || (_templateObject8 = /*#__PURE__*/_taggedTemplateLiteral(["\n                --plasma-link-font-family: var(--plasma-typo-text-m-font-family);\n                --plasma-link-color: var(--text-negative);\n                --plasma-link-color-hover: var(--text-negative-hover);\n                --plasma-link-color-active: var(--text-negative-active);\n                --plasma-link-color-visited: var(--text-negative);\n                --plasma-link-color-visited-hover: var(--text-negative-hover);\n                --plasma-link-color-visited-active: var(--text-negative-active);\n                --plasma-link-underline-border: 0;\n            "]))),
      clear: /*#__PURE__*/(0, _styledComponents.css)(_templateObject9 || (_templateObject9 = /*#__PURE__*/_taggedTemplateLiteral(["\n                --plasma-link-font-family: var(--plasma-typo-text-m-font-family);\n                --plasma-link-color: inherit;\n                --plasma-link-color-hover: inherit;\n                --plasma-link-color-active: inherit;\n                --plasma-link-color-visited: inherit;\n                --plasma-link-color-visited-hover: inherit;\n                --plasma-link-color-visited-active: inherit;\n                --plasma-link-underline-border: 0.063rem;\n            "])))
    },
    disabled: {
      "true": /*#__PURE__*/(0, _styledComponents.css)(_templateObject10 || (_templateObject10 = /*#__PURE__*/_taggedTemplateLiteral(["\n                --plasma-link-disabled-opacity: 0.4;\n            "])))
    },
    focused: {
      "true": /*#__PURE__*/(0, _styledComponents.css)(_templateObject11 || (_templateObject11 = /*#__PURE__*/_taggedTemplateLiteral(["\n                --plasma-link-focus-color: var(--text-primary);\n            "])))
    }
  }
};