export { IconApps } from './old/Icons/IconApps';
export { IconAvatar } from './old/Icons/IconAvatar';
export { IconCalendar } from './old/Icons/IconCalendar';
export { IconClock } from './old/Icons/IconClock';
export { IconClockFilled } from './old/Icons/IconClockFilled';
export { IconCross } from './old/Icons/IconCross';
export { IconCrossCircle } from './old/Icons/IconCrossCircle';
export { IconCrossSmall } from './old/Icons/IconCrossSmall';
export { IconDisclosureDown } from './old/Icons/IconDisclosureDown';
export { IconDisclosureLeft } from './old/Icons/IconDisclosureLeft';
export { IconDisclosureRight } from './old/Icons/IconDisclosureRight';
export { IconDisclosureUp } from './old/Icons/IconDisclosureUp';
export { IconEdit } from './old/Icons/IconEdit';
export { IconEvent } from './old/Icons/IconEvent';
export { IconHouse } from './old/Icons/IconHouse';
export { IconHouseSbol } from './old/Icons/IconHouseSbol';
export { IconMaximize } from './old/Icons/IconMaximize';
export { IconMoreHorizontal } from './old/Icons/IconMoreHorizontal';
export { IconMoreVertical } from './old/Icons/IconMoreVertical';
export { IconPersone } from './old/Icons/IconPersone';
export { IconPlusCircle } from './old/Icons/IconPlusCircle';
export { IconSettings } from './old/Icons/IconSettings';
export { IconSpinner } from './old/Icons/IconSpinner';
export { IconTrash } from './old/Icons/IconTrash';
export { IconTrashFilled } from './old/Icons/IconTrashFilled';
export { IconCart } from './old/Icons/IconCart';
export { IconCartAlt } from './old/Icons/IconCartAlt';
export { IconPercentStroke } from './old/Icons/IconPercentStroke';
// Action
export { IconAlarm } from './old/Icons/IconAlarm';
export { IconBankCard } from './old/Icons/IconBankCard';
export { IconBankCardAlt1 } from './old/Icons/IconBankCardAlt1';
export { IconHeart } from './old/Icons/IconHeart';
export { IconHeartStroke } from './old/Icons/IconHeartStroke';
export { IconLanguage } from './old/Icons/IconLanguage';
export { IconLock } from './old/Icons/IconLock';
export { IconReset } from './old/Icons/IconReset';
export { IconStar } from './old/Icons/IconStar';
export { IconTimerStroke } from './old/Icons/IconTimerStroke';
export { IconEye } from './old/Icons/IconEye';
export { IconShare } from './old/Icons/IconShare';
export { IconCloudUpload } from './old/Icons/IconCloudUpload';
export { IconRecord } from './old/Icons/IconRecord';
export { IconRecording } from './old/Icons/IconRecording';
export { IconRaisedHand } from './old/Icons/IconRaisedHand';
// Alert
export { IconBell } from './old/Icons/IconBell';
export { IconBellActive } from './old/Icons/IconBellActive';
export { IconHelp } from './old/Icons/IconHelp';
export { IconInfo } from './old/Icons/IconInfo';
export { IconWarning } from './old/Icons/IconWarning';
// AV
export { IconCamReverse } from './old/Icons/IconCamReverse';
export { IconCameraVideo } from './old/Icons/IconCameraVideo';
export { IconVideoOff } from './old/Icons/IconVideoOff';
export { IconMic } from './old/Icons/IconMic';
export { IconMicNone } from './old/Icons/IconMicNone';
export { IconMicOff } from './old/Icons/IconMicOff';
export { IconMusicMic } from './old/Icons/IconMusicMic';
export { IconVolumeAlt1 } from './old/Icons/IconVolumeAlt1';
export { IconVolumeAlt2 } from './old/Icons/IconVolumeAlt2';
export { IconVolumeDown } from './old/Icons/IconVolumeDown';
export { IconMute } from './old/Icons/IconMute';
export { IconVolumeOff } from './old/Icons/IconVolumeOff';
export { IconVolumeUp } from './old/Icons/IconVolumeUp';
export { IconVideoClip } from './old/Icons/IconVideoClip';
export { IconMusicAlbum } from './old/Icons/IconMusicAlbum';
export { IconMusic } from './old/Icons/IconMusic';
// Connection
export { IconEthernet } from './old/Icons/IconEthernet';
export { IconInputs } from './old/Icons/IconInputs';
export { IconNetwork } from './old/Icons/IconNetwork';
export { IconPowerWire } from './old/Icons/IconPowerWire';
export { IconWifi } from './old/Icons/IconWifi';
export { IconWifiOff } from './old/Icons/IconWifiOff';
export { IconWifiSignal0 } from './old/Icons/IconWifiSignal0';
export { IconWifiSignal1 } from './old/Icons/IconWifiSignal1';
export { IconWifiSignal2 } from './old/Icons/IconWifiSignal2';
export { IconWifiSignal3 } from './old/Icons/IconWifiSignal3';
export { IconWifiSignalLock } from './old/Icons/IconWifiSignalLock';
// Hardware
export { IconDevices } from './old/Icons/IconDevices';
export { IconDevicesAlt1 } from './old/Icons/IconDevicesAlt1';
export { IconDevice } from './old/Icons/IconDevice';
export { IconDeviceTv } from './old/Icons/IconDeviceTv';
export { IconDisplay } from './old/Icons/IconDisplay';
export { IconGamepad } from './old/Icons/IconGamepad';
export { IconGyro } from './old/Icons/IconGyro';
export { IconHeadphones } from './old/Icons/IconHeadphones';
export { IconKeyboard } from './old/Icons/IconKeyboard';
export { IconMobile } from './old/Icons/IconMobile';
export { IconMobileAutorotate } from './old/Icons/IconMobileAutorotate';
export { IconPhone } from './old/Icons/IconPhone';
export { IconPhoneStroke } from './old/Icons/IconPhoneStroke';
export { IconPhoneWiFi } from './old/Icons/IconPhoneWiFi';
export { IconRemotesAndAccessories } from './old/Icons/IconRemotesAndAccessories';
export { IconRemotesAndAccessoriesStroke } from './old/Icons/IconRemotesAndAccessoriesStroke';
export { IconSberBoxTime } from './old/Icons/IconSberBoxTime';
export { IconSberBoxTimeStroke } from './old/Icons/IconSberBoxTimeStroke';
export { IconSberBoxTop } from './old/Icons/IconSberBoxTop';
export { IconSberBoxTopFront } from './old/Icons/IconSberBoxTopFront';
export { IconSberBoxTopStroke } from './old/Icons/IconSberBoxTopStroke';
export { IconSberPortal } from './old/Icons/IconSberPortal';
export { IconSberPortalStroke } from './old/Icons/IconSberPortalStroke';
export { IconTv } from './old/Icons/IconTv';
export { IconTvAlt1 } from './old/Icons/IconTvAlt1';
export { IconTvChannel } from './old/Icons/IconTvChannel';
export { IconTvChannelAlt1 } from './old/Icons/IconTvChannelAlt1';
export { IconTvMode } from './old/Icons/IconTvMode';
export { IconTvModeWiFi } from './old/Icons/IconTvModeWiFi';
// Communication
export { IconAddToCall } from './old/Icons/IconAddToCall';
export { IconCall } from './old/Icons/IconCall';
export { IconCallCircle } from './old/Icons/IconCallCircle';
export { IconCallEnd } from './old/Icons/IconCallEnd';
export { IconCallEndCircle } from './old/Icons/IconCallEndCircle';
export { IconCallBlock } from './old/Icons/IconCallBlock';
export { IconCallDash } from './old/Icons/IconCallDash';
export { IconMessage } from './old/Icons/IconMessage';
export { IconFeedback } from './old/Icons/IconFeedback';
// Files
export { IconCardstack } from './old/Icons/IconCardstack';
export { IconCopy } from './old/Icons/IconCopy';
export { IconFolder } from './old/Icons/IconFolder';
// Map
export { IconLocation } from './old/Icons/IconLocation';
export { IconLocationFill } from './old/Icons/IconLocationFill';
export { IconNavigationArrow } from './old/Icons/IconNavigationArrow';
// Player
export { IconNext } from './old/Icons/IconNext';
export { IconPause } from './old/Icons/IconPause';
export { IconPlay } from './old/Icons/IconPlay';
export { IconPrevious } from './old/Icons/IconPrevious';
export { IconRepeat } from './old/Icons/IconRepeat';
export { IconShuffle } from './old/Icons/IconShuffle';
// Other
export { IconPicture } from './old/Icons/IconPicture';
export { IconPictureFilled } from './old/Icons/IconPictureFilled';
export { IconSleep } from './old/Icons/IconSleep';
export { IconPip1 } from './old/Icons/IconPip1';
export { IconStoreGamepad } from './old/Icons/IconStoreGamepad';
export { IconStoreRemote } from './old/Icons/IconStoreRemote';
export { IconTicket } from './old/Icons/IconTicket';
export { IconSberSpasibo } from './old/Icons/IconSberSpasibo';
// Logo
export { IconSalute } from './old/Icons/IconSalute';
export { IconSaluteCircle } from './old/Icons/IconSaluteCircle';
export { IconSberAlt } from './old/Icons/IconSberAlt';

export { IconRoot } from './old/IconRoot';
export type { IconProps, IconSize } from './old/IconRoot';

export { Icon, iconSectionsSet } from './old/Icon';
export type { IconName } from './old/Icon';

export * from './scalable';
