"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.TextXS = exports.TextS = exports.TextM = exports.TextL = exports.H5 = exports.H4 = exports.H3 = exports.H2 = exports.H1 = exports.DsplS = exports.DsplM = exports.DsplL = exports.BodyXXS = exports.BodyXS = exports.BodyS = exports.BodyM = exports.BodyL = void 0;
var _styledComponents = /*#__PURE__*/require("@salutejs/plasma-new-hope/styled-components");
var _Body = /*#__PURE__*/require("./Body.config");
var _Dspl = /*#__PURE__*/require("./Dspl.config");
var _Heading = /*#__PURE__*/require("./Heading.config");
var _Text = /*#__PURE__*/require("./Text.config");
var bodyMConfig = /*#__PURE__*/(0, _styledComponents.mergeConfig)(_styledComponents.bodyConfig, _Body.configM);
var BodyMComponent = /*#__PURE__*/(0, _styledComponents.component)(bodyMConfig);
var bodyLConfig = /*#__PURE__*/(0, _styledComponents.mergeConfig)(_styledComponents.bodyConfig, _Body.configL);
var BodyLComponent = /*#__PURE__*/(0, _styledComponents.component)(bodyLConfig);
var bodySConfig = /*#__PURE__*/(0, _styledComponents.mergeConfig)(_styledComponents.bodyConfig, _Body.configS);
var BodySComponent = /*#__PURE__*/(0, _styledComponents.component)(bodySConfig);
var bodyXSConfig = /*#__PURE__*/(0, _styledComponents.mergeConfig)(_styledComponents.bodyConfig, _Body.configXS);
var BodyXSComponent = /*#__PURE__*/(0, _styledComponents.component)(bodyXSConfig);
var bodyXXSConfig = /*#__PURE__*/(0, _styledComponents.mergeConfig)(_styledComponents.bodyConfig, _Body.configXXS);
var BodyXXSComponent = /*#__PURE__*/(0, _styledComponents.component)(bodyXXSConfig);
var dsplMConfig = /*#__PURE__*/(0, _styledComponents.mergeConfig)(_styledComponents.dsplConfig, _Dspl.configM);
var DsplMComponent = /*#__PURE__*/(0, _styledComponents.component)(dsplMConfig);
var dsplLConfig = /*#__PURE__*/(0, _styledComponents.mergeConfig)(_styledComponents.dsplConfig, _Dspl.configL);
var DsplLComponent = /*#__PURE__*/(0, _styledComponents.component)(dsplLConfig);
var dsplSConfig = /*#__PURE__*/(0, _styledComponents.mergeConfig)(_styledComponents.dsplConfig, _Dspl.configS);
var DsplSComponent = /*#__PURE__*/(0, _styledComponents.component)(dsplSConfig);
var heading1Config = /*#__PURE__*/(0, _styledComponents.mergeConfig)(_styledComponents.headingConfig, _Heading.configH1);
var Heading1Component = /*#__PURE__*/(0, _styledComponents.component)(heading1Config);
var heading2Config = /*#__PURE__*/(0, _styledComponents.mergeConfig)(_styledComponents.headingConfig, _Heading.configH2);
var Heading2Component = /*#__PURE__*/(0, _styledComponents.component)(heading2Config);
var heading3Config = /*#__PURE__*/(0, _styledComponents.mergeConfig)(_styledComponents.headingConfig, _Heading.configH3);
var Heading3Component = /*#__PURE__*/(0, _styledComponents.component)(heading3Config);
var heading4Config = /*#__PURE__*/(0, _styledComponents.mergeConfig)(_styledComponents.headingConfig, _Heading.configH4);
var Heading4Component = /*#__PURE__*/(0, _styledComponents.component)(heading4Config);
var heading5Config = /*#__PURE__*/(0, _styledComponents.mergeConfig)(_styledComponents.headingConfig, _Heading.configH5);
var Heading5Component = /*#__PURE__*/(0, _styledComponents.component)(heading5Config);
var textMConfig = /*#__PURE__*/(0, _styledComponents.mergeConfig)(_styledComponents.textConfig, _Text.configM);
var TextMComponent = /*#__PURE__*/(0, _styledComponents.component)(textMConfig);
var textLConfig = /*#__PURE__*/(0, _styledComponents.mergeConfig)(_styledComponents.textConfig, _Text.configL);
var TextLComponent = /*#__PURE__*/(0, _styledComponents.component)(textLConfig);
var textSConfig = /*#__PURE__*/(0, _styledComponents.mergeConfig)(_styledComponents.textConfig, _Text.configS);
var TextSComponent = /*#__PURE__*/(0, _styledComponents.component)(textSConfig);
var textXSConfig = /*#__PURE__*/(0, _styledComponents.mergeConfig)(_styledComponents.textConfig, _Text.configXS);
var TextXSComponent = /*#__PURE__*/(0, _styledComponents.component)(textXSConfig);
var BodyM = exports.BodyM = BodyMComponent;
var BodyL = exports.BodyL = BodyLComponent;
var BodyS = exports.BodyS = BodySComponent;
var BodyXS = exports.BodyXS = BodyXSComponent;
var BodyXXS = exports.BodyXXS = BodyXXSComponent;
var DsplM = exports.DsplM = DsplMComponent;
var DsplL = exports.DsplL = DsplLComponent;
var DsplS = exports.DsplS = DsplSComponent;
var H1 = exports.H1 = Heading1Component;
var H2 = exports.H2 = Heading2Component;
var H3 = exports.H3 = Heading3Component;
var H4 = exports.H4 = Heading4Component;
var H5 = exports.H5 = Heading5Component;
var TextM = exports.TextM = TextMComponent;
var TextL = exports.TextL = TextLComponent;
var TextS = exports.TextS = TextSComponent;
var TextXS = exports.TextXS = TextXSComponent;