name: 'Prepare Android environment'

description: 'Setup gradle with cache'

runs:
  using: "composite"
  steps:
    -   name: Cache Gradle
        uses: actions/cache@v4
        with:
            path: |
                ~/.m2/repository
                ./.gradle
                ~/.gradle/cache
            key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
            restore-keys: ${{ runner.os }}-gradle-

    -   name: Make Gradle executable
        shell: bash
        run: chmod +x ./native/sdds-android/gradlew
