import { ThemeConfig } from '@salutejs/plasma-tokens-utils';

import { AndroidTypographyToken } from '../types';

export const getAndroidTokens = (config: ThemeConfig): AndroidTypographyToken => ({
    'screen-s.display.l.normal': {
        fontFamilyRef: 'fontFamily.display',
        fontWeight: 300,
        fontStyle: 'normal',
        textSize: 88,
        lineHeight: 92,
        letterSpacing: 0,
    },
    'screen-s.display.l.bold': {
        fontFamilyRef: 'fontFamily.display',
        fontWeight: 600,
        fontStyle: 'normal',
        textSize: 88,
        lineHeight: 92,
        letterSpacing: 0,
    },
    'screen-s.display.m.normal': {
        fontFamilyRef: 'fontFamily.display',
        fontWeight: 300,
        fontStyle: 'normal',
        textSize: 56,
        lineHeight: 62,
        letterSpacing: 0,
    },
    'screen-s.display.m.bold': {
        fontFamilyRef: 'fontFamily.display',
        fontWeight: 600,
        fontStyle: 'normal',
        textSize: 56,
        lineHeight: 62,
        letterSpacing: 0,
    },
    'screen-s.display.s.normal': {
        fontFamilyRef: 'fontFamily.display',
        fontWeight: 300,
        fontStyle: 'normal',
        textSize: 40,
        lineHeight: 46,
        letterSpacing: 0,
    },
    'screen-s.display.s.bold': {
        fontFamilyRef: 'fontFamily.display',
        fontWeight: 600,
        fontStyle: 'normal',
        textSize: 40,
        lineHeight: 46,
        letterSpacing: 0,
    },
    'screen-s.header.h1.normal': {
        fontFamilyRef: 'fontFamily.display',
        fontWeight: 400,
        fontStyle: 'normal',
        textSize: 28,
        lineHeight: 34,
        letterSpacing: 0,
    },
    'screen-s.header.h1.bold': {
        fontFamilyRef: 'fontFamily.display',
        fontWeight: 600,
        fontStyle: 'normal',
        textSize: 28,
        lineHeight: 34,
        letterSpacing: 0,
    },
    'screen-s.header.h2.normal': {
        fontFamilyRef: 'fontFamily.display',
        fontWeight: 400,
        fontStyle: 'normal',
        textSize: 24,
        lineHeight: 30,
        letterSpacing: 0,
    },
    'screen-s.header.h2.bold': {
        fontFamilyRef: 'fontFamily.display',
        fontWeight: 600,
        fontStyle: 'normal',
        textSize: 24,
        lineHeight: 30,
        letterSpacing: 0,
    },
    'screen-s.header.h3.normal': {
        fontFamilyRef: 'fontFamily.display',
        fontWeight: 400,
        fontStyle: 'normal',
        textSize: 20,
        lineHeight: 26,
        letterSpacing: 0,
    },
    'screen-s.header.h3.bold': {
        fontFamilyRef: 'fontFamily.display',
        fontWeight: 600,
        fontStyle: 'normal',
        textSize: 20,
        lineHeight: 26,
        letterSpacing: 0,
    },
    'screen-s.header.h4.normal': {
        fontFamilyRef: 'fontFamily.display',
        fontWeight: 400,
        fontStyle: 'normal',
        textSize: 18,
        lineHeight: 24,
        letterSpacing: 0,
    },
    'screen-s.header.h4.bold': {
        fontFamilyRef: 'fontFamily.display',
        fontWeight: 600,
        fontStyle: 'normal',
        textSize: 18,
        lineHeight: 24,
        letterSpacing: 0,
    },
    'screen-s.header.h5.normal': {
        fontFamilyRef: 'fontFamily.display',
        fontWeight: 400,
        fontStyle: 'normal',
        textSize: 16,
        lineHeight: 22,
        letterSpacing: 0,
    },
    'screen-s.header.h5.bold': {
        fontFamilyRef: 'fontFamily.display',
        fontWeight: 600,
        fontStyle: 'normal',
        textSize: 16,
        lineHeight: 22,
        letterSpacing: 0,
    },
    'screen-s.body.l.normal': {
        fontFamilyRef: 'fontFamily.text',
        fontWeight: 400,
        fontStyle: 'normal',
        textSize: 18,
        lineHeight: 22,
        letterSpacing: -0.02,
    },
    'screen-s.body.l.bold': {
        fontFamilyRef: 'fontFamily.text',
        fontWeight: 600,
        fontStyle: 'normal',
        textSize: 18,
        lineHeight: 22,
        letterSpacing: -0.02,
    },
    'screen-s.body.m.normal': {
        fontFamilyRef: 'fontFamily.text',
        fontWeight: 400,
        fontStyle: 'normal',
        textSize: 16,
        lineHeight: 20,
        letterSpacing: -0.02,
    },
    'screen-s.body.m.bold': {
        fontFamilyRef: 'fontFamily.text',
        fontWeight: 600,
        fontStyle: 'normal',
        textSize: 16,
        lineHeight: 20,
        letterSpacing: -0.02,
    },
    'screen-s.body.s.normal': {
        fontFamilyRef: 'fontFamily.text',
        fontWeight: 400,
        fontStyle: 'normal',
        textSize: 14,
        lineHeight: 18,
        letterSpacing: -0.02,
    },
    'screen-s.body.s.bold': {
        fontFamilyRef: 'fontFamily.text',
        fontWeight: 600,
        fontStyle: 'normal',
        textSize: 14,
        lineHeight: 18,
        letterSpacing: -0.02,
    },
    'screen-s.body.xs.normal': {
        fontFamilyRef: 'fontFamily.text',
        fontWeight: 400,
        fontStyle: 'normal',
        textSize: 12,
        lineHeight: 14,
        letterSpacing: -0.02,
    },
    'screen-s.body.xs.bold': {
        fontFamilyRef: 'fontFamily.text',
        fontWeight: 600,
        fontStyle: 'normal',
        textSize: 12,
        lineHeight: 14,
        letterSpacing: -0.02,
    },
    'screen-s.body.xxs.normal': {
        fontFamilyRef: 'fontFamily.text',
        fontWeight: 400,
        fontStyle: 'normal',
        textSize: 10,
        lineHeight: 12,
        letterSpacing: -0.02,
    },
    'screen-s.body.xxs.bold': {
        fontFamilyRef: 'fontFamily.text',
        fontWeight: 600,
        fontStyle: 'normal',
        textSize: 10,
        lineHeight: 12,
        letterSpacing: -0.02,
    },
    'screen-s.text.l.normal': {
        fontFamilyRef: 'fontFamily.text',
        fontWeight: 400,
        fontStyle: 'normal',
        textSize: 18,
        lineHeight: 26,
        letterSpacing: -0.02,
    },
    'screen-s.text.l.bold': {
        fontFamilyRef: 'fontFamily.text',
        fontWeight: 600,
        fontStyle: 'normal',
        textSize: 18,
        lineHeight: 26,
        letterSpacing: -0.02,
    },
    'screen-s.text.m.normal': {
        fontFamilyRef: 'fontFamily.text',
        fontWeight: 400,
        fontStyle: 'normal',
        textSize: 16,
        lineHeight: 24,
        letterSpacing: -0.02,
    },
    'screen-s.text.m.bold': {
        fontFamilyRef: 'fontFamily.text',
        fontWeight: 600,
        fontStyle: 'normal',
        textSize: 16,
        lineHeight: 24,
        letterSpacing: -0.02,
    },
    'screen-s.text.s.normal': {
        fontFamilyRef: 'fontFamily.text',
        fontWeight: 400,
        fontStyle: 'normal',
        textSize: 14,
        lineHeight: 20,
        letterSpacing: -0.02,
    },
    'screen-s.text.s.bold': {
        fontFamilyRef: 'fontFamily.text',
        fontWeight: 600,
        fontStyle: 'normal',
        textSize: 14,
        lineHeight: 20,
        letterSpacing: -0.02,
    },
    'screen-s.text.xs.normal': {
        fontFamilyRef: 'fontFamily.text',
        fontWeight: 400,
        fontStyle: 'normal',
        textSize: 12,
        lineHeight: 16,
        letterSpacing: -0.02,
    },
    'screen-s.text.xs.bold': {
        fontFamilyRef: 'fontFamily.text',
        fontWeight: 600,
        fontStyle: 'normal',
        textSize: 12,
        lineHeight: 16,
        letterSpacing: -0.02,
    },
    'screen-m.display.l.normal': {
        fontFamilyRef: 'fontFamily.display',
        fontWeight: 300,
        fontStyle: 'normal',
        textSize: 112,
        lineHeight: 112,
        letterSpacing: 0,
    },
    'screen-m.display.l.bold': {
        fontFamilyRef: 'fontFamily.display',
        fontWeight: 600,
        fontStyle: 'normal',
        textSize: 112,
        lineHeight: 112,
        letterSpacing: 0,
    },
    'screen-m.display.m.normal': {
        fontFamilyRef: 'fontFamily.display',
        fontWeight: 300,
        fontStyle: 'normal',
        textSize: 72,
        lineHeight: 76,
        letterSpacing: 0,
    },
    'screen-m.display.m.bold': {
        fontFamilyRef: 'fontFamily.display',
        fontWeight: 600,
        fontStyle: 'normal',
        textSize: 72,
        lineHeight: 76,
        letterSpacing: 0,
    },
    'screen-m.display.s.normal': {
        fontFamilyRef: 'fontFamily.display',
        fontWeight: 300,
        fontStyle: 'normal',
        textSize: 48,
        lineHeight: 54,
        letterSpacing: 0,
    },
    'screen-m.display.s.bold': {
        fontFamilyRef: 'fontFamily.display',
        fontWeight: 600,
        fontStyle: 'normal',
        textSize: 48,
        lineHeight: 54,
        letterSpacing: 0,
    },
    'screen-m.header.h1.normal': {
        fontFamilyRef: 'fontFamily.display',
        fontWeight: 400,
        fontStyle: 'normal',
        textSize: 40,
        lineHeight: 46,
        letterSpacing: 0,
    },
    'screen-m.header.h1.bold': {
        fontFamilyRef: 'fontFamily.display',
        fontWeight: 600,
        fontStyle: 'normal',
        textSize: 40,
        lineHeight: 46,
        letterSpacing: 0,
    },
    'screen-m.header.h2.normal': {
        fontFamilyRef: 'fontFamily.display',
        fontWeight: 400,
        fontStyle: 'normal',
        textSize: 28,
        lineHeight: 34,
        letterSpacing: 0,
    },
    'screen-m.header.h2.bold': {
        fontFamilyRef: 'fontFamily.display',
        fontWeight: 600,
        fontStyle: 'normal',
        textSize: 28,
        lineHeight: 34,
        letterSpacing: 0,
    },
    'screen-m.header.h3.normal': {
        fontFamilyRef: 'fontFamily.display',
        fontWeight: 400,
        fontStyle: 'normal',
        textSize: 20,
        lineHeight: 26,
        letterSpacing: 0,
    },
    'screen-m.header.h3.bold': {
        fontFamilyRef: 'fontFamily.display',
        fontWeight: 600,
        fontStyle: 'normal',
        textSize: 20,
        lineHeight: 26,
        letterSpacing: 0,
    },
    'screen-m.header.h4.normal': {
        fontFamilyRef: 'fontFamily.display',
        fontWeight: 400,
        fontStyle: 'normal',
        textSize: 18,
        lineHeight: 24,
        letterSpacing: 0,
    },
    'screen-m.header.h4.bold': {
        fontFamilyRef: 'fontFamily.display',
        fontWeight: 600,
        fontStyle: 'normal',
        textSize: 18,
        lineHeight: 24,
        letterSpacing: 0,
    },
    'screen-m.header.h5.normal': {
        fontFamilyRef: 'fontFamily.display',
        fontWeight: 400,
        fontStyle: 'normal',
        textSize: 16,
        lineHeight: 22,
        letterSpacing: 0,
    },
    'screen-m.header.h5.bold': {
        fontFamilyRef: 'fontFamily.display',
        fontWeight: 600,
        fontStyle: 'normal',
        textSize: 16,
        lineHeight: 22,
        letterSpacing: 0,
    },
    'screen-m.body.l.normal': {
        fontFamilyRef: 'fontFamily.text',
        fontWeight: 400,
        fontStyle: 'normal',
        textSize: 18,
        lineHeight: 22,
        letterSpacing: -0.02,
    },
    'screen-m.body.l.bold': {
        fontFamilyRef: 'fontFamily.text',
        fontWeight: 600,
        fontStyle: 'normal',
        textSize: 18,
        lineHeight: 22,
        letterSpacing: -0.02,
    },
    'screen-m.body.m.normal': {
        fontFamilyRef: 'fontFamily.text',
        fontWeight: 400,
        fontStyle: 'normal',
        textSize: 16,
        lineHeight: 20,
        letterSpacing: -0.02,
    },
    'screen-m.body.m.bold': {
        fontFamilyRef: 'fontFamily.text',
        fontWeight: 600,
        fontStyle: 'normal',
        textSize: 16,
        lineHeight: 20,
        letterSpacing: -0.02,
    },
    'screen-m.body.s.normal': {
        fontFamilyRef: 'fontFamily.text',
        fontWeight: 400,
        fontStyle: 'normal',
        textSize: 14,
        lineHeight: 18,
        letterSpacing: -0.02,
    },
    'screen-m.body.s.bold': {
        fontFamilyRef: 'fontFamily.text',
        fontWeight: 600,
        fontStyle: 'normal',
        textSize: 14,
        lineHeight: 18,
        letterSpacing: -0.02,
    },
    'screen-m.body.xs.normal': {
        fontFamilyRef: 'fontFamily.text',
        fontWeight: 400,
        fontStyle: 'normal',
        textSize: 12,
        lineHeight: 14,
        letterSpacing: -0.02,
    },
    'screen-m.body.xs.bold': {
        fontFamilyRef: 'fontFamily.text',
        fontWeight: 600,
        fontStyle: 'normal',
        textSize: 12,
        lineHeight: 14,
        letterSpacing: -0.02,
    },
    'screen-m.body.xxs.normal': {
        fontFamilyRef: 'fontFamily.text',
        fontWeight: 400,
        fontStyle: 'normal',
        textSize: 10,
        lineHeight: 12,
        letterSpacing: -0.02,
    },
    'screen-m.body.xxs.bold': {
        fontFamilyRef: 'fontFamily.text',
        fontWeight: 600,
        fontStyle: 'normal',
        textSize: 10,
        lineHeight: 12,
        letterSpacing: -0.02,
    },
    'screen-m.text.l.normal': {
        fontFamilyRef: 'fontFamily.text',
        fontWeight: 400,
        fontStyle: 'normal',
        textSize: 20,
        lineHeight: 28,
        letterSpacing: -0.02,
    },
    'screen-m.text.l.bold': {
        fontFamilyRef: 'fontFamily.text',
        fontWeight: 600,
        fontStyle: 'normal',
        textSize: 20,
        lineHeight: 28,
        letterSpacing: -0.02,
    },
    'screen-m.text.m.normal': {
        fontFamilyRef: 'fontFamily.text',
        fontWeight: 400,
        fontStyle: 'normal',
        textSize: 16,
        lineHeight: 24,
        letterSpacing: -0.02,
    },
    'screen-m.text.m.bold': {
        fontFamilyRef: 'fontFamily.text',
        fontWeight: 600,
        fontStyle: 'normal',
        textSize: 16,
        lineHeight: 24,
        letterSpacing: -0.02,
    },
    'screen-m.text.s.normal': {
        fontFamilyRef: 'fontFamily.text',
        fontWeight: 400,
        fontStyle: 'normal',
        textSize: 14,
        lineHeight: 20,
        letterSpacing: -0.02,
    },
    'screen-m.text.s.bold': {
        fontFamilyRef: 'fontFamily.text',
        fontWeight: 600,
        fontStyle: 'normal',
        textSize: 14,
        lineHeight: 20,
        letterSpacing: -0.02,
    },
    'screen-m.text.xs.normal': {
        fontFamilyRef: 'fontFamily.text',
        fontWeight: 400,
        fontStyle: 'normal',
        textSize: 12,
        lineHeight: 16,
        letterSpacing: -0.02,
    },
    'screen-m.text.xs.bold': {
        fontFamilyRef: 'fontFamily.text',
        fontWeight: 600,
        fontStyle: 'normal',
        textSize: 12,
        lineHeight: 16,
        letterSpacing: -0.02,
    },
    'screen-l.display.l.normal': {
        fontFamilyRef: 'fontFamily.display',
        fontWeight: 300,
        fontStyle: 'normal',
        textSize: 128,
        lineHeight: 128,
        letterSpacing: 0,
    },
    'screen-l.display.l.bold': {
        fontFamilyRef: 'fontFamily.display',
        fontWeight: 600,
        fontStyle: 'normal',
        textSize: 128,
        lineHeight: 128,
        letterSpacing: 0,
    },
    'screen-l.display.m.normal': {
        fontFamilyRef: 'fontFamily.display',
        fontWeight: 300,
        fontStyle: 'normal',
        textSize: 88,
        lineHeight: 92,
        letterSpacing: 0,
    },
    'screen-l.display.m.bold': {
        fontFamilyRef: 'fontFamily.display',
        fontWeight: 600,
        fontStyle: 'normal',
        textSize: 88,
        lineHeight: 92,
        letterSpacing: 0,
    },
    'screen-l.display.s.normal': {
        fontFamilyRef: 'fontFamily.display',
        fontWeight: 300,
        fontStyle: 'normal',
        textSize: 64,
        lineHeight: 68,
        letterSpacing: 0,
    },
    'screen-l.display.s.bold': {
        fontFamilyRef: 'fontFamily.display',
        fontWeight: 600,
        fontStyle: 'normal',
        textSize: 64,
        lineHeight: 68,
        letterSpacing: 0,
    },
    'screen-l.header.h1.normal': {
        fontFamilyRef: 'fontFamily.display',
        fontWeight: 400,
        fontStyle: 'normal',
        textSize: 48,
        lineHeight: 54,
        letterSpacing: 0,
    },
    'screen-l.header.h1.bold': {
        fontFamilyRef: 'fontFamily.display',
        fontWeight: 600,
        fontStyle: 'normal',
        textSize: 48,
        lineHeight: 54,
        letterSpacing: 0,
    },
    'screen-l.header.h2.normal': {
        fontFamilyRef: 'fontFamily.display',
        fontWeight: 400,
        fontStyle: 'normal',
        textSize: 32,
        lineHeight: 38,
        letterSpacing: 0,
    },
    'screen-l.header.h2.bold': {
        fontFamilyRef: 'fontFamily.display',
        fontWeight: 600,
        fontStyle: 'normal',
        textSize: 32,
        lineHeight: 38,
        letterSpacing: 0,
    },
    'screen-l.header.h3.normal': {
        fontFamilyRef: 'fontFamily.display',
        fontWeight: 400,
        fontStyle: 'normal',
        textSize: 24,
        lineHeight: 30,
        letterSpacing: 0,
    },
    'screen-l.header.h3.bold': {
        fontFamilyRef: 'fontFamily.display',
        fontWeight: 600,
        fontStyle: 'normal',
        textSize: 24,
        lineHeight: 30,
        letterSpacing: 0,
    },
    'screen-l.header.h4.normal': {
        fontFamilyRef: 'fontFamily.display',
        fontWeight: 400,
        fontStyle: 'normal',
        textSize: 20,
        lineHeight: 26,
        letterSpacing: 0,
    },
    'screen-l.header.h4.bold': {
        fontFamilyRef: 'fontFamily.display',
        fontWeight: 600,
        fontStyle: 'normal',
        textSize: 20,
        lineHeight: 26,
        letterSpacing: 0,
    },
    'screen-l.header.h5.normal': {
        fontFamilyRef: 'fontFamily.display',
        fontWeight: 400,
        fontStyle: 'normal',
        textSize: 18,
        lineHeight: 24,
        letterSpacing: 0,
    },
    'screen-l.header.h5.bold': {
        fontFamilyRef: 'fontFamily.display',
        fontWeight: 600,
        fontStyle: 'normal',
        textSize: 18,
        lineHeight: 24,
        letterSpacing: 0,
    },
    'screen-l.body.l.normal': {
        fontFamilyRef: 'fontFamily.text',
        fontWeight: 400,
        fontStyle: 'normal',
        textSize: 18,
        lineHeight: 22,
        letterSpacing: -0.02,
    },
    'screen-l.body.l.bold': {
        fontFamilyRef: 'fontFamily.text',
        fontWeight: 600,
        fontStyle: 'normal',
        textSize: 18,
        lineHeight: 22,
        letterSpacing: -0.02,
    },
    'screen-l.body.m.normal': {
        fontFamilyRef: 'fontFamily.text',
        fontWeight: 400,
        fontStyle: 'normal',
        textSize: 16,
        lineHeight: 20,
        letterSpacing: -0.02,
    },
    'screen-l.body.m.bold': {
        fontFamilyRef: 'fontFamily.text',
        fontWeight: 600,
        fontStyle: 'normal',
        textSize: 16,
        lineHeight: 20,
        letterSpacing: -0.02,
    },
    'screen-l.body.s.normal': {
        fontFamilyRef: 'fontFamily.text',
        fontWeight: 400,
        fontStyle: 'normal',
        textSize: 14,
        lineHeight: 18,
        letterSpacing: -0.02,
    },
    'screen-l.body.s.bold': {
        fontFamilyRef: 'fontFamily.text',
        fontWeight: 600,
        fontStyle: 'normal',
        textSize: 14,
        lineHeight: 18,
        letterSpacing: -0.02,
    },
    'screen-l.body.xs.normal': {
        fontFamilyRef: 'fontFamily.text',
        fontWeight: 400,
        fontStyle: 'normal',
        textSize: 12,
        lineHeight: 14,
        letterSpacing: -0.02,
    },
    'screen-l.body.xs.bold': {
        fontFamilyRef: 'fontFamily.text',
        fontWeight: 600,
        fontStyle: 'normal',
        textSize: 12,
        lineHeight: 14,
        letterSpacing: -0.02,
    },
    'screen-l.body.xxs.normal': {
        fontFamilyRef: 'fontFamily.text',
        fontWeight: 400,
        fontStyle: 'normal',
        textSize: 10,
        lineHeight: 12,
        letterSpacing: -0.02,
    },
    'screen-l.body.xxs.bold': {
        fontFamilyRef: 'fontFamily.text',
        fontWeight: 600,
        fontStyle: 'normal',
        textSize: 10,
        lineHeight: 12,
        letterSpacing: -0.02,
    },
    'screen-l.text.l.normal': {
        fontFamilyRef: 'fontFamily.text',
        fontWeight: 400,
        fontStyle: 'normal',
        textSize: 24,
        lineHeight: 32,
        letterSpacing: -0.02,
    },
    'screen-l.text.l.bold': {
        fontFamilyRef: 'fontFamily.text',
        fontWeight: 600,
        fontStyle: 'normal',
        textSize: 24,
        lineHeight: 32,
        letterSpacing: -0.02,
    },
    'screen-l.text.m.normal': {
        fontFamilyRef: 'fontFamily.text',
        fontWeight: 400,
        fontStyle: 'normal',
        textSize: 18,
        lineHeight: 26,
        letterSpacing: -0.02,
    },
    'screen-l.text.m.bold': {
        fontFamilyRef: 'fontFamily.text',
        fontWeight: 600,
        fontStyle: 'normal',
        textSize: 18,
        lineHeight: 26,
        letterSpacing: -0.02,
    },
    'screen-l.text.s.normal': {
        fontFamilyRef: 'fontFamily.text',
        fontWeight: 400,
        fontStyle: 'normal',
        textSize: 14,
        lineHeight: 20,
        letterSpacing: -0.02,
    },
    'screen-l.text.s.bold': {
        fontFamilyRef: 'fontFamily.text',
        fontWeight: 600,
        fontStyle: 'normal',
        textSize: 14,
        lineHeight: 20,
        letterSpacing: -0.02,
    },
    'screen-l.text.xs.normal': {
        fontFamilyRef: 'fontFamily.text',
        fontWeight: 400,
        fontStyle: 'normal',
        textSize: 12,
        lineHeight: 16,
        letterSpacing: -0.02,
    },
    'screen-l.text.xs.bold': {
        fontFamilyRef: 'fontFamily.text',
        fontWeight: 600,
        fontStyle: 'normal',
        textSize: 12,
        lineHeight: 16,
        letterSpacing: -0.02,
    },
});
