import { ThemeConfig } from '@salutejs/plasma-tokens-utils';

import { IOSTypographyToken } from '../types';

export const getIOSTokens = (config: ThemeConfig): IOSTypographyToken => ({
    'screen-s.display.l.normal': {
        fontFamilyRef: 'fontFamily.display',
        weight: 'semibold',
        style: 'normal',
        size: 88,
        lineHeight: 92,
        kerning: 0,
    },
    'screen-s.display.l.bold': {
        fontFamilyRef: 'fontFamily.display',
        weight: 'light',
        style: 'normal',
        size: 88,
        lineHeight: 92,
        kerning: 0,
    },
    'screen-s.display.m.normal': {
        fontFamilyRef: 'fontFamily.display',
        weight: 'semibold',
        style: 'normal',
        size: 56,
        lineHeight: 62,
        kerning: 0,
    },
    'screen-s.display.m.bold': {
        fontFamilyRef: 'fontFamily.display',
        weight: 'light',
        style: 'normal',
        size: 56,
        lineHeight: 62,
        kerning: 0,
    },
    'screen-s.display.s.normal': {
        fontFamilyRef: 'fontFamily.display',
        weight: 'semibold',
        style: 'normal',
        size: 40,
        lineHeight: 46,
        kerning: 0,
    },
    'screen-s.display.s.bold': {
        fontFamilyRef: 'fontFamily.display',
        weight: 'light',
        style: 'normal',
        size: 40,
        lineHeight: 46,
        kerning: 0,
    },
    'screen-s.header.h1.normal': {
        fontFamilyRef: 'fontFamily.display',
        weight: 'regular',
        style: 'normal',
        size: 28,
        lineHeight: 34,
        kerning: 0,
    },
    'screen-s.header.h1.bold': {
        fontFamilyRef: 'fontFamily.display',
        weight: 'light',
        style: 'normal',
        size: 28,
        lineHeight: 34,
        kerning: 0,
    },
    'screen-s.header.h2.normal': {
        fontFamilyRef: 'fontFamily.display',
        weight: 'regular',
        style: 'normal',
        size: 24,
        lineHeight: 30,
        kerning: 0,
    },
    'screen-s.header.h2.bold': {
        fontFamilyRef: 'fontFamily.display',
        weight: 'light',
        style: 'normal',
        size: 24,
        lineHeight: 30,
        kerning: 0,
    },
    'screen-s.header.h3.normal': {
        fontFamilyRef: 'fontFamily.display',
        weight: 'regular',
        style: 'normal',
        size: 20,
        lineHeight: 26,
        kerning: 0,
    },
    'screen-s.header.h3.bold': {
        fontFamilyRef: 'fontFamily.display',
        weight: 'light',
        style: 'normal',
        size: 20,
        lineHeight: 26,
        kerning: 0,
    },
    'screen-s.header.h4.normal': {
        fontFamilyRef: 'fontFamily.display',
        weight: 'regular',
        style: 'normal',
        size: 18,
        lineHeight: 24,
        kerning: 0,
    },
    'screen-s.header.h4.bold': {
        fontFamilyRef: 'fontFamily.display',
        weight: 'light',
        style: 'normal',
        size: 18,
        lineHeight: 24,
        kerning: 0,
    },
    'screen-s.header.h5.normal': {
        fontFamilyRef: 'fontFamily.display',
        weight: 'regular',
        style: 'normal',
        size: 16,
        lineHeight: 22,
        kerning: 0,
    },
    'screen-s.header.h5.bold': {
        fontFamilyRef: 'fontFamily.display',
        weight: 'light',
        style: 'normal',
        size: 16,
        lineHeight: 22,
        kerning: 0,
    },
    'screen-s.body.l.normal': {
        fontFamilyRef: 'fontFamily.text',
        weight: 'regular',
        style: 'normal',
        size: 18,
        lineHeight: 22,
        kerning: -0.02,
    },
    'screen-s.body.l.bold': {
        fontFamilyRef: 'fontFamily.text',
        weight: 'light',
        style: 'normal',
        size: 18,
        lineHeight: 22,
        kerning: -0.02,
    },
    'screen-s.body.m.normal': {
        fontFamilyRef: 'fontFamily.text',
        weight: 'regular',
        style: 'normal',
        size: 16,
        lineHeight: 20,
        kerning: -0.02,
    },
    'screen-s.body.m.bold': {
        fontFamilyRef: 'fontFamily.text',
        weight: 'light',
        style: 'normal',
        size: 16,
        lineHeight: 20,
        kerning: -0.02,
    },
    'screen-s.body.s.normal': {
        fontFamilyRef: 'fontFamily.text',
        weight: 'regular',
        style: 'normal',
        size: 14,
        lineHeight: 18,
        kerning: -0.02,
    },
    'screen-s.body.s.bold': {
        fontFamilyRef: 'fontFamily.text',
        weight: 'light',
        style: 'normal',
        size: 14,
        lineHeight: 18,
        kerning: -0.02,
    },
    'screen-s.body.xs.normal': {
        fontFamilyRef: 'fontFamily.text',
        weight: 'regular',
        style: 'normal',
        size: 12,
        lineHeight: 14,
        kerning: -0.02,
    },
    'screen-s.body.xs.bold': {
        fontFamilyRef: 'fontFamily.text',
        weight: 'light',
        style: 'normal',
        size: 12,
        lineHeight: 14,
        kerning: -0.02,
    },
    'screen-s.body.xxs.normal': {
        fontFamilyRef: 'fontFamily.text',
        weight: 'regular',
        style: 'normal',
        size: 10,
        lineHeight: 12,
        kerning: -0.02,
    },
    'screen-s.body.xxs.bold': {
        fontFamilyRef: 'fontFamily.text',
        weight: 'light',
        style: 'normal',
        size: 10,
        lineHeight: 12,
        kerning: -0.02,
    },
    'screen-s.text.l.normal': {
        fontFamilyRef: 'fontFamily.text',
        weight: 'regular',
        style: 'normal',
        size: 18,
        lineHeight: 26,
        kerning: -0.02,
    },
    'screen-s.text.l.bold': {
        fontFamilyRef: 'fontFamily.text',
        weight: 'light',
        style: 'normal',
        size: 18,
        lineHeight: 26,
        kerning: -0.02,
    },
    'screen-s.text.m.normal': {
        fontFamilyRef: 'fontFamily.text',
        weight: 'regular',
        style: 'normal',
        size: 16,
        lineHeight: 24,
        kerning: -0.02,
    },
    'screen-s.text.m.bold': {
        fontFamilyRef: 'fontFamily.text',
        weight: 'light',
        style: 'normal',
        size: 16,
        lineHeight: 24,
        kerning: -0.02,
    },
    'screen-s.text.s.normal': {
        fontFamilyRef: 'fontFamily.text',
        weight: 'regular',
        style: 'normal',
        size: 14,
        lineHeight: 20,
        kerning: -0.02,
    },
    'screen-s.text.s.bold': {
        fontFamilyRef: 'fontFamily.text',
        weight: 'light',
        style: 'normal',
        size: 14,
        lineHeight: 20,
        kerning: -0.02,
    },
    'screen-s.text.xs.normal': {
        fontFamilyRef: 'fontFamily.text',
        weight: 'regular',
        style: 'normal',
        size: 12,
        lineHeight: 16,
        kerning: -0.02,
    },
    'screen-s.text.xs.bold': {
        fontFamilyRef: 'fontFamily.text',
        weight: 'light',
        style: 'normal',
        size: 12,
        lineHeight: 16,
        kerning: -0.02,
    },
    'screen-m.display.l.normal': {
        fontFamilyRef: 'fontFamily.display',
        weight: 'semibold',
        style: 'normal',
        size: 112,
        lineHeight: 112,
        kerning: 0,
    },
    'screen-m.display.l.bold': {
        fontFamilyRef: 'fontFamily.display',
        weight: 'light',
        style: 'normal',
        size: 112,
        lineHeight: 112,
        kerning: 0,
    },
    'screen-m.display.m.normal': {
        fontFamilyRef: 'fontFamily.display',
        weight: 'semibold',
        style: 'normal',
        size: 72,
        lineHeight: 76,
        kerning: 0,
    },
    'screen-m.display.m.bold': {
        fontFamilyRef: 'fontFamily.display',
        weight: 'light',
        style: 'normal',
        size: 72,
        lineHeight: 76,
        kerning: 0,
    },
    'screen-m.display.s.normal': {
        fontFamilyRef: 'fontFamily.display',
        weight: 'semibold',
        style: 'normal',
        size: 48,
        lineHeight: 54,
        kerning: 0,
    },
    'screen-m.display.s.bold': {
        fontFamilyRef: 'fontFamily.display',
        weight: 'light',
        style: 'normal',
        size: 48,
        lineHeight: 54,
        kerning: 0,
    },
    'screen-m.header.h1.normal': {
        fontFamilyRef: 'fontFamily.display',
        weight: 'regular',
        style: 'normal',
        size: 40,
        lineHeight: 46,
        kerning: 0,
    },
    'screen-m.header.h1.bold': {
        fontFamilyRef: 'fontFamily.display',
        weight: 'light',
        style: 'normal',
        size: 40,
        lineHeight: 46,
        kerning: 0,
    },
    'screen-m.header.h2.normal': {
        fontFamilyRef: 'fontFamily.display',
        weight: 'regular',
        style: 'normal',
        size: 28,
        lineHeight: 34,
        kerning: 0,
    },
    'screen-m.header.h2.bold': {
        fontFamilyRef: 'fontFamily.display',
        weight: 'light',
        style: 'normal',
        size: 28,
        lineHeight: 34,
        kerning: 0,
    },
    'screen-m.header.h3.normal': {
        fontFamilyRef: 'fontFamily.display',
        weight: 'regular',
        style: 'normal',
        size: 20,
        lineHeight: 26,
        kerning: 0,
    },
    'screen-m.header.h3.bold': {
        fontFamilyRef: 'fontFamily.display',
        weight: 'light',
        style: 'normal',
        size: 20,
        lineHeight: 26,
        kerning: 0,
    },
    'screen-m.header.h4.normal': {
        fontFamilyRef: 'fontFamily.display',
        weight: 'regular',
        style: 'normal',
        size: 18,
        lineHeight: 24,
        kerning: 0,
    },
    'screen-m.header.h4.bold': {
        fontFamilyRef: 'fontFamily.display',
        weight: 'light',
        style: 'normal',
        size: 18,
        lineHeight: 24,
        kerning: 0,
    },
    'screen-m.header.h5.normal': {
        fontFamilyRef: 'fontFamily.display',
        weight: 'regular',
        style: 'normal',
        size: 16,
        lineHeight: 22,
        kerning: 0,
    },
    'screen-m.header.h5.bold': {
        fontFamilyRef: 'fontFamily.display',
        weight: 'light',
        style: 'normal',
        size: 16,
        lineHeight: 22,
        kerning: 0,
    },
    'screen-m.body.l.normal': {
        fontFamilyRef: 'fontFamily.text',
        weight: 'regular',
        style: 'normal',
        size: 18,
        lineHeight: 22,
        kerning: -0.02,
    },
    'screen-m.body.l.bold': {
        fontFamilyRef: 'fontFamily.text',
        weight: 'light',
        style: 'normal',
        size: 18,
        lineHeight: 22,
        kerning: -0.02,
    },
    'screen-m.body.m.normal': {
        fontFamilyRef: 'fontFamily.text',
        weight: 'regular',
        style: 'normal',
        size: 16,
        lineHeight: 20,
        kerning: -0.02,
    },
    'screen-m.body.m.bold': {
        fontFamilyRef: 'fontFamily.text',
        weight: 'light',
        style: 'normal',
        size: 16,
        lineHeight: 20,
        kerning: -0.02,
    },
    'screen-m.body.s.normal': {
        fontFamilyRef: 'fontFamily.text',
        weight: 'regular',
        style: 'normal',
        size: 14,
        lineHeight: 18,
        kerning: -0.02,
    },
    'screen-m.body.s.bold': {
        fontFamilyRef: 'fontFamily.text',
        weight: 'light',
        style: 'normal',
        size: 14,
        lineHeight: 18,
        kerning: -0.02,
    },
    'screen-m.body.xs.normal': {
        fontFamilyRef: 'fontFamily.text',
        weight: 'regular',
        style: 'normal',
        size: 12,
        lineHeight: 14,
        kerning: -0.02,
    },
    'screen-m.body.xs.bold': {
        fontFamilyRef: 'fontFamily.text',
        weight: 'light',
        style: 'normal',
        size: 12,
        lineHeight: 14,
        kerning: -0.02,
    },
    'screen-m.body.xxs.normal': {
        fontFamilyRef: 'fontFamily.text',
        weight: 'regular',
        style: 'normal',
        size: 10,
        lineHeight: 12,
        kerning: -0.02,
    },
    'screen-m.body.xxs.bold': {
        fontFamilyRef: 'fontFamily.text',
        weight: 'light',
        style: 'normal',
        size: 10,
        lineHeight: 12,
        kerning: -0.02,
    },
    'screen-m.text.l.normal': {
        fontFamilyRef: 'fontFamily.text',
        weight: 'regular',
        style: 'normal',
        size: 20,
        lineHeight: 28,
        kerning: -0.02,
    },
    'screen-m.text.l.bold': {
        fontFamilyRef: 'fontFamily.text',
        weight: 'light',
        style: 'normal',
        size: 20,
        lineHeight: 28,
        kerning: -0.02,
    },
    'screen-m.text.m.normal': {
        fontFamilyRef: 'fontFamily.text',
        weight: 'regular',
        style: 'normal',
        size: 16,
        lineHeight: 24,
        kerning: -0.02,
    },
    'screen-m.text.m.bold': {
        fontFamilyRef: 'fontFamily.text',
        weight: 'light',
        style: 'normal',
        size: 16,
        lineHeight: 24,
        kerning: -0.02,
    },
    'screen-m.text.s.normal': {
        fontFamilyRef: 'fontFamily.text',
        weight: 'regular',
        style: 'normal',
        size: 14,
        lineHeight: 20,
        kerning: -0.02,
    },
    'screen-m.text.s.bold': {
        fontFamilyRef: 'fontFamily.text',
        weight: 'light',
        style: 'normal',
        size: 14,
        lineHeight: 20,
        kerning: -0.02,
    },
    'screen-m.text.xs.normal': {
        fontFamilyRef: 'fontFamily.text',
        weight: 'regular',
        style: 'normal',
        size: 12,
        lineHeight: 16,
        kerning: -0.02,
    },
    'screen-m.text.xs.bold': {
        fontFamilyRef: 'fontFamily.text',
        weight: 'light',
        style: 'normal',
        size: 12,
        lineHeight: 16,
        kerning: -0.02,
    },
    'screen-l.display.l.normal': {
        fontFamilyRef: 'fontFamily.display',
        weight: 'semibold',
        style: 'normal',
        size: 128,
        lineHeight: 128,
        kerning: 0,
    },
    'screen-l.display.l.bold': {
        fontFamilyRef: 'fontFamily.display',
        weight: 'light',
        style: 'normal',
        size: 128,
        lineHeight: 128,
        kerning: 0,
    },
    'screen-l.display.m.normal': {
        fontFamilyRef: 'fontFamily.display',
        weight: 'semibold',
        style: 'normal',
        size: 88,
        lineHeight: 92,
        kerning: 0,
    },
    'screen-l.display.m.bold': {
        fontFamilyRef: 'fontFamily.display',
        weight: 'light',
        style: 'normal',
        size: 88,
        lineHeight: 92,
        kerning: 0,
    },
    'screen-l.display.s.normal': {
        fontFamilyRef: 'fontFamily.display',
        weight: 'semibold',
        style: 'normal',
        size: 64,
        lineHeight: 68,
        kerning: 0,
    },
    'screen-l.display.s.bold': {
        fontFamilyRef: 'fontFamily.display',
        weight: 'light',
        style: 'normal',
        size: 64,
        lineHeight: 68,
        kerning: 0,
    },
    'screen-l.header.h1.normal': {
        fontFamilyRef: 'fontFamily.display',
        weight: 'regular',
        style: 'normal',
        size: 48,
        lineHeight: 54,
        kerning: 0,
    },
    'screen-l.header.h1.bold': {
        fontFamilyRef: 'fontFamily.display',
        weight: 'light',
        style: 'normal',
        size: 48,
        lineHeight: 54,
        kerning: 0,
    },
    'screen-l.header.h2.normal': {
        fontFamilyRef: 'fontFamily.display',
        weight: 'regular',
        style: 'normal',
        size: 32,
        lineHeight: 38,
        kerning: 0,
    },
    'screen-l.header.h2.bold': {
        fontFamilyRef: 'fontFamily.display',
        weight: 'light',
        style: 'normal',
        size: 32,
        lineHeight: 38,
        kerning: 0,
    },
    'screen-l.header.h3.normal': {
        fontFamilyRef: 'fontFamily.display',
        weight: 'regular',
        style: 'normal',
        size: 24,
        lineHeight: 30,
        kerning: 0,
    },
    'screen-l.header.h3.bold': {
        fontFamilyRef: 'fontFamily.display',
        weight: 'light',
        style: 'normal',
        size: 24,
        lineHeight: 30,
        kerning: 0,
    },
    'screen-l.header.h4.normal': {
        fontFamilyRef: 'fontFamily.display',
        weight: 'regular',
        style: 'normal',
        size: 20,
        lineHeight: 26,
        kerning: 0,
    },
    'screen-l.header.h4.bold': {
        fontFamilyRef: 'fontFamily.display',
        weight: 'light',
        style: 'normal',
        size: 20,
        lineHeight: 26,
        kerning: 0,
    },
    'screen-l.header.h5.normal': {
        fontFamilyRef: 'fontFamily.display',
        weight: 'regular',
        style: 'normal',
        size: 18,
        lineHeight: 24,
        kerning: 0,
    },
    'screen-l.header.h5.bold': {
        fontFamilyRef: 'fontFamily.display',
        weight: 'light',
        style: 'normal',
        size: 18,
        lineHeight: 24,
        kerning: 0,
    },
    'screen-l.body.l.normal': {
        fontFamilyRef: 'fontFamily.text',
        weight: 'regular',
        style: 'normal',
        size: 18,
        lineHeight: 22,
        kerning: -0.02,
    },
    'screen-l.body.l.bold': {
        fontFamilyRef: 'fontFamily.text',
        weight: 'light',
        style: 'normal',
        size: 18,
        lineHeight: 22,
        kerning: -0.02,
    },
    'screen-l.body.m.normal': {
        fontFamilyRef: 'fontFamily.text',
        weight: 'regular',
        style: 'normal',
        size: 16,
        lineHeight: 20,
        kerning: -0.02,
    },
    'screen-l.body.m.bold': {
        fontFamilyRef: 'fontFamily.text',
        weight: 'light',
        style: 'normal',
        size: 16,
        lineHeight: 20,
        kerning: -0.02,
    },
    'screen-l.body.s.normal': {
        fontFamilyRef: 'fontFamily.text',
        weight: 'regular',
        style: 'normal',
        size: 14,
        lineHeight: 18,
        kerning: -0.02,
    },
    'screen-l.body.s.bold': {
        fontFamilyRef: 'fontFamily.text',
        weight: 'light',
        style: 'normal',
        size: 14,
        lineHeight: 18,
        kerning: -0.02,
    },
    'screen-l.body.xs.normal': {
        fontFamilyRef: 'fontFamily.text',
        weight: 'regular',
        style: 'normal',
        size: 12,
        lineHeight: 14,
        kerning: -0.02,
    },
    'screen-l.body.xs.bold': {
        fontFamilyRef: 'fontFamily.text',
        weight: 'light',
        style: 'normal',
        size: 12,
        lineHeight: 14,
        kerning: -0.02,
    },
    'screen-l.body.xxs.normal': {
        fontFamilyRef: 'fontFamily.text',
        weight: 'regular',
        style: 'normal',
        size: 10,
        lineHeight: 12,
        kerning: -0.02,
    },
    'screen-l.body.xxs.bold': {
        fontFamilyRef: 'fontFamily.text',
        weight: 'light',
        style: 'normal',
        size: 10,
        lineHeight: 12,
        kerning: -0.02,
    },
    'screen-l.text.l.normal': {
        fontFamilyRef: 'fontFamily.text',
        weight: 'regular',
        style: 'normal',
        size: 24,
        lineHeight: 32,
        kerning: -0.02,
    },
    'screen-l.text.l.bold': {
        fontFamilyRef: 'fontFamily.text',
        weight: 'light',
        style: 'normal',
        size: 24,
        lineHeight: 32,
        kerning: -0.02,
    },
    'screen-l.text.m.normal': {
        fontFamilyRef: 'fontFamily.text',
        weight: 'regular',
        style: 'normal',
        size: 18,
        lineHeight: 26,
        kerning: -0.02,
    },
    'screen-l.text.m.bold': {
        fontFamilyRef: 'fontFamily.text',
        weight: 'light',
        style: 'normal',
        size: 18,
        lineHeight: 26,
        kerning: -0.02,
    },
    'screen-l.text.s.normal': {
        fontFamilyRef: 'fontFamily.text',
        weight: 'regular',
        style: 'normal',
        size: 14,
        lineHeight: 20,
        kerning: -0.02,
    },
    'screen-l.text.s.bold': {
        fontFamilyRef: 'fontFamily.text',
        weight: 'light',
        style: 'normal',
        size: 14,
        lineHeight: 20,
        kerning: -0.02,
    },
    'screen-l.text.xs.normal': {
        fontFamilyRef: 'fontFamily.text',
        weight: 'regular',
        style: 'normal',
        size: 12,
        lineHeight: 16,
        kerning: -0.02,
    },
    'screen-l.text.xs.bold': {
        fontFamilyRef: 'fontFamily.text',
        weight: 'light',
        style: 'normal',
        size: 12,
        lineHeight: 16,
        kerning: -0.02,
    },
});
