import { TokenType } from '../../../types';

export const typographyTokens: Array<TokenType> = [
    {
        type: 'typography',
        name: 'screen-s.display.l.normal',
        tags: ['screen-s', 'display', 'l', 'normal'],
        displayName: 'screenSDisplayL',
        description: 'typography s display-l',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-s.display.l.bold',
        tags: ['screen-s', 'display', 'l', 'bold'],
        displayName: 'screenSDisplayLBold',
        description: 'typography s display-l-bold',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-s.display.m.normal',
        tags: ['screen-s', 'display', 'm', 'normal'],
        displayName: 'screenSDisplayM',
        description: 'typography s display-m',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-s.display.m.bold',
        tags: ['screen-s', 'display', 'm', 'bold'],
        displayName: 'screenSDisplayMBold',
        description: 'typography s display-m-bold',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-s.display.s.normal',
        tags: ['screen-s', 'display', 's', 'normal'],
        displayName: 'screenSDisplayS',
        description: 'typography s display-s',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-s.display.s.bold',
        tags: ['screen-s', 'display', 's', 'bold'],
        displayName: 'screenSDisplaySBold',
        description: 'typography s display-s-bold',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-s.header.h1.normal',
        tags: ['screen-s', 'header', 'h1', 'normal'],
        displayName: 'screenSHeaderH1',
        description: 'typography s header-h1',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-s.header.h1.bold',
        tags: ['screen-s', 'header', 'h1', 'bold'],
        displayName: 'screenSHeaderH1Bold',
        description: 'typography s header-h1-bold',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-s.header.h2.normal',
        tags: ['screen-s', 'header', 'h2', 'normal'],
        displayName: 'screenSHeaderH2',
        description: 'typography s header-h2',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-s.header.h2.bold',
        tags: ['screen-s', 'header', 'h2', 'bold'],
        displayName: 'screenSHeaderH2Bold',
        description: 'typography s header-h2-bold',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-s.header.h3.normal',
        tags: ['screen-s', 'header', 'h3', 'normal'],
        displayName: 'screenSHeaderH3',
        description: 'typography s header-h3',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-s.header.h3.bold',
        tags: ['screen-s', 'header', 'h3', 'bold'],
        displayName: 'screenSHeaderH3Bold',
        description: 'typography s header-h3-bold',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-s.header.h4.normal',
        tags: ['screen-s', 'header', 'h4', 'normal'],
        displayName: 'screenSHeaderH4',
        description: 'typography s header-h4',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-s.header.h4.bold',
        tags: ['screen-s', 'header', 'h4', 'bold'],
        displayName: 'screenSHeaderH4Bold',
        description: 'typography s header-h4-bold',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-s.header.h5.normal',
        tags: ['screen-s', 'header', 'h5', 'normal'],
        displayName: 'screenSHeaderH5',
        description: 'typography s header-h5',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-s.header.h5.bold',
        tags: ['screen-s', 'header', 'h5', 'bold'],
        displayName: 'screenSHeaderH5Bold',
        description: 'typography s header-h5-bold',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-s.body.l.normal',
        tags: ['screen-s', 'body', 'l', 'normal'],
        displayName: 'screenSBodyL',
        description: 'typography s body-l',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-s.body.l.bold',
        tags: ['screen-s', 'body', 'l', 'bold'],
        displayName: 'screenSBodyLBold',
        description: 'typography s body-l-bold',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-s.body.m.normal',
        tags: ['screen-s', 'body', 'm', 'normal'],
        displayName: 'screenSBodyM',
        description: 'typography s body-m',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-s.body.m.bold',
        tags: ['screen-s', 'body', 'm', 'bold'],
        displayName: 'screenSBodyMBold',
        description: 'typography s body-m-bold',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-s.body.s.normal',
        tags: ['screen-s', 'body', 's', 'normal'],
        displayName: 'screenSBodyS',
        description: 'typography s body-s',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-s.body.s.bold',
        tags: ['screen-s', 'body', 's', 'bold'],
        displayName: 'screenSBodySBold',
        description: 'typography s body-s-bold',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-s.body.xs.normal',
        tags: ['screen-s', 'body', 'xs', 'normal'],
        displayName: 'screenSBodyXs',
        description: 'typography s body-xs',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-s.body.xs.bold',
        tags: ['screen-s', 'body', 'xs', 'bold'],
        displayName: 'screenSBodyXsBold',
        description: 'typography s body-xs-bold',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-s.body.xxs.normal',
        tags: ['screen-s', 'body', 'xxs', 'normal'],
        displayName: 'screenSBodyXxs',
        description: 'typography s body-xxs',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-s.body.xxs.bold',
        tags: ['screen-s', 'body', 'xxs', 'bold'],
        displayName: 'screenSBodyXxsBold',
        description: 'typography s body-xxs-bold',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-s.text.l.normal',
        tags: ['screen-s', 'text', 'l', 'normal'],
        displayName: 'screenSTextL',
        description: 'typography s text-l',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-s.text.l.bold',
        tags: ['screen-s', 'text', 'l', 'bold'],
        displayName: 'screenSTextLBold',
        description: 'typography s text-l-bold',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-s.text.m.normal',
        tags: ['screen-s', 'text', 'm', 'normal'],
        displayName: 'screenSTextM',
        description: 'typography s text-m',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-s.text.m.bold',
        tags: ['screen-s', 'text', 'm', 'bold'],
        displayName: 'screenSTextMBold',
        description: 'typography s text-m-bold',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-s.text.s.normal',
        tags: ['screen-s', 'text', 's', 'normal'],
        displayName: 'screenSTextS',
        description: 'typography s text-s',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-s.text.s.bold',
        tags: ['screen-s', 'text', 's', 'bold'],
        displayName: 'screenSTextSBold',
        description: 'typography s text-s-bold',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-s.text.xs.normal',
        tags: ['screen-s', 'text', 'xs', 'normal'],
        displayName: 'screenSTextXs',
        description: 'typography s text-xs',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-s.text.xs.bold',
        tags: ['screen-s', 'text', 'xs', 'bold'],
        displayName: 'screenSTextXsBold',
        description: 'typography s text-xs-bold',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-m.display.l.normal',
        tags: ['screen-m', 'display', 'l', 'normal'],
        displayName: 'screenMDisplayL',
        description: 'typography m display-l',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-m.display.l.bold',
        tags: ['screen-m', 'display', 'l', 'bold'],
        displayName: 'screenMDisplayLBold',
        description: 'typography m display-l-bold',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-m.display.m.normal',
        tags: ['screen-m', 'display', 'm', 'normal'],
        displayName: 'screenMDisplayM',
        description: 'typography m display-m',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-m.display.m.bold',
        tags: ['screen-m', 'display', 'm', 'bold'],
        displayName: 'screenMDisplayMBold',
        description: 'typography m display-m-bold',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-m.display.s.normal',
        tags: ['screen-m', 'display', 's', 'normal'],
        displayName: 'screenMDisplayS',
        description: 'typography m display-s',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-m.display.s.bold',
        tags: ['screen-m', 'display', 's', 'bold'],
        displayName: 'screenMDisplaySBold',
        description: 'typography m display-s-bold',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-m.header.h1.normal',
        tags: ['screen-m', 'header', 'h1', 'normal'],
        displayName: 'screenMHeaderH1',
        description: 'typography m header-h1',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-m.header.h1.bold',
        tags: ['screen-m', 'header', 'h1', 'bold'],
        displayName: 'screenMHeaderH1Bold',
        description: 'typography m header-h1-bold',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-m.header.h2.normal',
        tags: ['screen-m', 'header', 'h2', 'normal'],
        displayName: 'screenMHeaderH2',
        description: 'typography m header-h2',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-m.header.h2.bold',
        tags: ['screen-m', 'header', 'h2', 'bold'],
        displayName: 'screenMHeaderH2Bold',
        description: 'typography m header-h2-bold',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-m.header.h3.normal',
        tags: ['screen-m', 'header', 'h3', 'normal'],
        displayName: 'screenMHeaderH3',
        description: 'typography m header-h3',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-m.header.h3.bold',
        tags: ['screen-m', 'header', 'h3', 'bold'],
        displayName: 'screenMHeaderH3Bold',
        description: 'typography m header-h3-bold',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-m.header.h4.normal',
        tags: ['screen-m', 'header', 'h4', 'normal'],
        displayName: 'screenMHeaderH4',
        description: 'typography m header-h4',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-m.header.h4.bold',
        tags: ['screen-m', 'header', 'h4', 'bold'],
        displayName: 'screenMHeaderH4Bold',
        description: 'typography m header-h4-bold',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-m.header.h5.normal',
        tags: ['screen-m', 'header', 'h5', 'normal'],
        displayName: 'screenMHeaderH5',
        description: 'typography m header-h5',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-m.header.h5.bold',
        tags: ['screen-m', 'header', 'h5', 'bold'],
        displayName: 'screenMHeaderH5Bold',
        description: 'typography m header-h5-bold',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-m.body.l.normal',
        tags: ['screen-m', 'body', 'l', 'normal'],
        displayName: 'screenMBodyL',
        description: 'typography m body-l',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-m.body.l.bold',
        tags: ['screen-m', 'body', 'l', 'bold'],
        displayName: 'screenMBodyLBold',
        description: 'typography m body-l-bold',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-m.body.m.normal',
        tags: ['screen-m', 'body', 'm', 'normal'],
        displayName: 'screenMBodyM',
        description: 'typography m body-m',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-m.body.m.bold',
        tags: ['screen-m', 'body', 'm', 'bold'],
        displayName: 'screenMBodyMBold',
        description: 'typography m body-m-bold',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-m.body.s.normal',
        tags: ['screen-m', 'body', 's', 'normal'],
        displayName: 'screenMBodyS',
        description: 'typography m body-s',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-m.body.s.bold',
        tags: ['screen-m', 'body', 's', 'bold'],
        displayName: 'screenMBodySBold',
        description: 'typography m body-s-bold',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-m.body.xs.normal',
        tags: ['screen-m', 'body', 'xs', 'normal'],
        displayName: 'screenMBodyXs',
        description: 'typography m body-xs',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-m.body.xs.bold',
        tags: ['screen-m', 'body', 'xs', 'bold'],
        displayName: 'screenMBodyXsBold',
        description: 'typography m body-xs-bold',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-m.body.xxs.normal',
        tags: ['screen-m', 'body', 'xxs', 'normal'],
        displayName: 'screenMBodyXxs',
        description: 'typography m body-xxs',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-m.body.xxs.bold',
        tags: ['screen-m', 'body', 'xxs', 'bold'],
        displayName: 'screenMBodyXxsBold',
        description: 'typography m body-xxs-bold',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-m.text.l.normal',
        tags: ['screen-m', 'text', 'l', 'normal'],
        displayName: 'screenMTextL',
        description: 'typography m text-l',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-m.text.l.bold',
        tags: ['screen-m', 'text', 'l', 'bold'],
        displayName: 'screenMTextLBold',
        description: 'typography m text-l-bold',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-m.text.m.normal',
        tags: ['screen-m', 'text', 'm', 'normal'],
        displayName: 'screenMTextM',
        description: 'typography m text-m',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-m.text.m.bold',
        tags: ['screen-m', 'text', 'm', 'bold'],
        displayName: 'screenMTextMBold',
        description: 'typography m text-m-bold',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-m.text.s.normal',
        tags: ['screen-m', 'text', 's', 'normal'],
        displayName: 'screenMTextS',
        description: 'typography m text-s',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-m.text.s.bold',
        tags: ['screen-m', 'text', 's', 'bold'],
        displayName: 'screenMTextSBold',
        description: 'typography m text-s-bold',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-m.text.xs.normal',
        tags: ['screen-m', 'text', 'xs', 'normal'],
        displayName: 'screenMTextXs',
        description: 'typography m text-xs',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-m.text.xs.bold',
        tags: ['screen-m', 'text', 'xs', 'bold'],
        displayName: 'screenMTextXsBold',
        description: 'typography m text-xs-bold',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-l.display.l.normal',
        tags: ['screen-l', 'display', 'l', 'normal'],
        displayName: 'screenLDisplayL',
        description: 'typography l display-l',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-l.display.l.bold',
        tags: ['screen-l', 'display', 'l', 'bold'],
        displayName: 'screenLDisplayLBold',
        description: 'typography l display-l-bold',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-l.display.m.normal',
        tags: ['screen-l', 'display', 'm', 'normal'],
        displayName: 'screenLDisplayM',
        description: 'typography l display-m',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-l.display.m.bold',
        tags: ['screen-l', 'display', 'm', 'bold'],
        displayName: 'screenLDisplayMBold',
        description: 'typography l display-m-bold',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-l.display.s.normal',
        tags: ['screen-l', 'display', 's', 'normal'],
        displayName: 'screenLDisplayS',
        description: 'typography l display-s',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-l.display.s.bold',
        tags: ['screen-l', 'display', 's', 'bold'],
        displayName: 'screenLDisplaySBold',
        description: 'typography l display-s-bold',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-l.header.h1.normal',
        tags: ['screen-l', 'header', 'h1', 'normal'],
        displayName: 'screenLHeaderH1',
        description: 'typography l header-h1',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-l.header.h1.bold',
        tags: ['screen-l', 'header', 'h1', 'bold'],
        displayName: 'screenLHeaderH1Bold',
        description: 'typography l header-h1-bold',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-l.header.h2.normal',
        tags: ['screen-l', 'header', 'h2', 'normal'],
        displayName: 'screenLHeaderH2',
        description: 'typography l header-h2',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-l.header.h2.bold',
        tags: ['screen-l', 'header', 'h2', 'bold'],
        displayName: 'screenLHeaderH2Bold',
        description: 'typography l header-h2-bold',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-l.header.h3.normal',
        tags: ['screen-l', 'header', 'h3', 'normal'],
        displayName: 'screenLHeaderH3',
        description: 'typography l header-h3',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-l.header.h3.bold',
        tags: ['screen-l', 'header', 'h3', 'bold'],
        displayName: 'screenLHeaderH3Bold',
        description: 'typography l header-h3-bold',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-l.header.h4.normal',
        tags: ['screen-l', 'header', 'h4', 'normal'],
        displayName: 'screenLHeaderH4',
        description: 'typography l header-h4',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-l.header.h4.bold',
        tags: ['screen-l', 'header', 'h4', 'bold'],
        displayName: 'screenLHeaderH4Bold',
        description: 'typography l header-h4-bold',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-l.header.h5.normal',
        tags: ['screen-l', 'header', 'h5', 'normal'],
        displayName: 'screenLHeaderH5',
        description: 'typography l header-h5',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-l.header.h5.bold',
        tags: ['screen-l', 'header', 'h5', 'bold'],
        displayName: 'screenLHeaderH5Bold',
        description: 'typography l header-h5-bold',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-l.body.l.normal',
        tags: ['screen-l', 'body', 'l', 'normal'],
        displayName: 'screenLBodyL',
        description: 'typography l body-l',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-l.body.l.bold',
        tags: ['screen-l', 'body', 'l', 'bold'],
        displayName: 'screenLBodyLBold',
        description: 'typography l body-l-bold',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-l.body.m.normal',
        tags: ['screen-l', 'body', 'm', 'normal'],
        displayName: 'screenLBodyM',
        description: 'typography l body-m',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-l.body.m.bold',
        tags: ['screen-l', 'body', 'm', 'bold'],
        displayName: 'screenLBodyMBold',
        description: 'typography l body-m-bold',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-l.body.s.normal',
        tags: ['screen-l', 'body', 's', 'normal'],
        displayName: 'screenLBodyS',
        description: 'typography l body-s',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-l.body.s.bold',
        tags: ['screen-l', 'body', 's', 'bold'],
        displayName: 'screenLBodySBold',
        description: 'typography l body-s-bold',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-l.body.xs.normal',
        tags: ['screen-l', 'body', 'xs', 'normal'],
        displayName: 'screenLBodyXs',
        description: 'typography l body-xs',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-l.body.xs.bold',
        tags: ['screen-l', 'body', 'xs', 'bold'],
        displayName: 'screenLBodyXsBold',
        description: 'typography l body-xs-bold',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-l.body.xxs.normal',
        tags: ['screen-l', 'body', 'xxs', 'normal'],
        displayName: 'screenLBodyXxs',
        description: 'typography l body-xxs',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-l.body.xxs.bold',
        tags: ['screen-l', 'body', 'xxs', 'bold'],
        displayName: 'screenLBodyXxsBold',
        description: 'typography l body-xxs-bold',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-l.text.l.normal',
        tags: ['screen-l', 'text', 'l', 'normal'],
        displayName: 'screenLTextL',
        description: 'typography l text-l',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-l.text.l.bold',
        tags: ['screen-l', 'text', 'l', 'bold'],
        displayName: 'screenLTextLBold',
        description: 'typography l text-l-bold',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-l.text.m.normal',
        tags: ['screen-l', 'text', 'm', 'normal'],
        displayName: 'screenLTextM',
        description: 'typography l text-m',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-l.text.m.bold',
        tags: ['screen-l', 'text', 'm', 'bold'],
        displayName: 'screenLTextMBold',
        description: 'typography l text-m-bold',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-l.text.s.normal',
        tags: ['screen-l', 'text', 's', 'normal'],
        displayName: 'screenLTextS',
        description: 'typography l text-s',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-l.text.s.bold',
        tags: ['screen-l', 'text', 's', 'bold'],
        displayName: 'screenLTextSBold',
        description: 'typography l text-s-bold',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-l.text.xs.normal',
        tags: ['screen-l', 'text', 'xs', 'normal'],
        displayName: 'screenLTextXs',
        description: 'typography l text-xs',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-l.text.xs.bold',
        tags: ['screen-l', 'text', 'xs', 'bold'],
        displayName: 'screenLTextXsBold',
        description: 'typography l text-xs-bold',
        enabled: true,
    },
];
