import { ThemeConfig } from '@salutejs/plasma-tokens-utils';

import { WebTypographyToken } from '../types';

export const getWebTokens = (config: ThemeConfig): WebTypographyToken => ({
    'screen-s.display.l.normal': {
        fontFamilyRef: 'fontFamily.display',
        fontWeight: '300',
        fontStyle: 'normal',
        fontSize: '5.5rem',
        lineHeight: '5.75rem',
        letterSpacing: 'normal',
    },
    'screen-s.display.l.bold': {
        fontFamilyRef: 'fontFamily.display',
        fontWeight: '600',
        fontStyle: 'normal',
        fontSize: '5.5rem',
        lineHeight: '5.75rem',
        letterSpacing: 'normal',
    },
    'screen-s.display.m.normal': {
        fontFamilyRef: 'fontFamily.display',
        fontWeight: '300',
        fontStyle: 'normal',
        fontSize: '3.5rem',
        lineHeight: '3.875rem',
        letterSpacing: 'normal',
    },
    'screen-s.display.m.bold': {
        fontFamilyRef: 'fontFamily.display',
        fontWeight: '600',
        fontStyle: 'normal',
        fontSize: '3.5rem',
        lineHeight: '3.875rem',
        letterSpacing: 'normal',
    },
    'screen-s.display.s.normal': {
        fontFamilyRef: 'fontFamily.display',
        fontWeight: '300',
        fontStyle: 'normal',
        fontSize: '2.5rem',
        lineHeight: '2.875rem',
        letterSpacing: 'normal',
    },
    'screen-s.display.s.bold': {
        fontFamilyRef: 'fontFamily.display',
        fontWeight: '600',
        fontStyle: 'normal',
        fontSize: '2.5rem',
        lineHeight: '2.875rem',
        letterSpacing: 'normal',
    },
    'screen-s.header.h1.normal': {
        fontFamilyRef: 'fontFamily.display',
        fontWeight: '400',
        fontStyle: 'normal',
        fontSize: '1.75rem',
        lineHeight: '2.125rem',
        letterSpacing: 'normal',
    },
    'screen-s.header.h1.bold': {
        fontFamilyRef: 'fontFamily.display',
        fontWeight: '600',
        fontStyle: 'normal',
        fontSize: '1.75rem',
        lineHeight: '2.125rem',
        letterSpacing: 'normal',
    },
    'screen-s.header.h2.normal': {
        fontFamilyRef: 'fontFamily.display',
        fontWeight: '400',
        fontStyle: 'normal',
        fontSize: '1.5rem',
        lineHeight: '1.875rem',
        letterSpacing: 'normal',
    },
    'screen-s.header.h2.bold': {
        fontFamilyRef: 'fontFamily.display',
        fontWeight: '600',
        fontStyle: 'normal',
        fontSize: '1.5rem',
        lineHeight: '1.875rem',
        letterSpacing: 'normal',
    },
    'screen-s.header.h3.normal': {
        fontFamilyRef: 'fontFamily.display',
        fontWeight: '400',
        fontStyle: 'normal',
        fontSize: '1.25rem',
        lineHeight: '1.625rem',
        letterSpacing: 'normal',
    },
    'screen-s.header.h3.bold': {
        fontFamilyRef: 'fontFamily.display',
        fontWeight: '600',
        fontStyle: 'normal',
        fontSize: '1.25rem',
        lineHeight: '1.625rem',
        letterSpacing: 'normal',
    },
    'screen-s.header.h4.normal': {
        fontFamilyRef: 'fontFamily.display',
        fontWeight: '400',
        fontStyle: 'normal',
        fontSize: '1.125rem',
        lineHeight: '1.5rem',
        letterSpacing: 'normal',
    },
    'screen-s.header.h4.bold': {
        fontFamilyRef: 'fontFamily.display',
        fontWeight: '600',
        fontStyle: 'normal',
        fontSize: '1.125rem',
        lineHeight: '1.5rem',
        letterSpacing: 'normal',
    },
    'screen-s.header.h5.normal': {
        fontFamilyRef: 'fontFamily.display',
        fontWeight: '400',
        fontStyle: 'normal',
        fontSize: '1rem',
        lineHeight: '1.375rem',
        letterSpacing: 'normal',
    },
    'screen-s.header.h5.bold': {
        fontFamilyRef: 'fontFamily.display',
        fontWeight: '600',
        fontStyle: 'normal',
        fontSize: '1rem',
        lineHeight: '1.375rem',
        letterSpacing: 'normal',
    },
    'screen-s.body.l.normal': {
        fontFamilyRef: 'fontFamily.text',
        fontWeight: '400',
        fontStyle: 'normal',
        fontSize: '1.125rem',
        lineHeight: '1.375rem',
        letterSpacing: '-0.02em',
    },
    'screen-s.body.l.bold': {
        fontFamilyRef: 'fontFamily.text',
        fontWeight: '600',
        fontStyle: 'normal',
        fontSize: '1.125rem',
        lineHeight: '1.375rem',
        letterSpacing: '-0.02em',
    },
    'screen-s.body.m.normal': {
        fontFamilyRef: 'fontFamily.text',
        fontWeight: '400',
        fontStyle: 'normal',
        fontSize: '1rem',
        lineHeight: '1.25rem',
        letterSpacing: '-0.02em',
    },
    'screen-s.body.m.bold': {
        fontFamilyRef: 'fontFamily.text',
        fontWeight: '600',
        fontStyle: 'normal',
        fontSize: '1rem',
        lineHeight: '1.25rem',
        letterSpacing: '-0.02em',
    },
    'screen-s.body.s.normal': {
        fontFamilyRef: 'fontFamily.text',
        fontWeight: '400',
        fontStyle: 'normal',
        fontSize: '0.875rem',
        lineHeight: '1.125rem',
        letterSpacing: '-0.02em',
    },
    'screen-s.body.s.bold': {
        fontFamilyRef: 'fontFamily.text',
        fontWeight: '600',
        fontStyle: 'normal',
        fontSize: '0.875rem',
        lineHeight: '1.125rem',
        letterSpacing: '-0.02em',
    },
    'screen-s.body.xs.normal': {
        fontFamilyRef: 'fontFamily.text',
        fontWeight: '400',
        fontStyle: 'normal',
        fontSize: '0.75rem',
        lineHeight: '0.875rem',
        letterSpacing: '-0.02em',
    },
    'screen-s.body.xs.bold': {
        fontFamilyRef: 'fontFamily.text',
        fontWeight: '600',
        fontStyle: 'normal',
        fontSize: '0.75rem',
        lineHeight: '0.875rem',
        letterSpacing: '-0.02em',
    },
    'screen-s.body.xxs.normal': {
        fontFamilyRef: 'fontFamily.text',
        fontWeight: '400',
        fontStyle: 'normal',
        fontSize: '0.625rem',
        lineHeight: '0.75rem',
        letterSpacing: '-0.02em',
    },
    'screen-s.body.xxs.bold': {
        fontFamilyRef: 'fontFamily.text',
        fontWeight: '600',
        fontStyle: 'normal',
        fontSize: '0.625rem',
        lineHeight: '0.75rem',
        letterSpacing: '-0.02em',
    },
    'screen-s.text.l.normal': {
        fontFamilyRef: 'fontFamily.text',
        fontWeight: '400',
        fontStyle: 'normal',
        fontSize: '1.125rem',
        lineHeight: '1.625rem',
        letterSpacing: '-0.02em',
    },
    'screen-s.text.l.bold': {
        fontFamilyRef: 'fontFamily.text',
        fontWeight: '600',
        fontStyle: 'normal',
        fontSize: '1.125rem',
        lineHeight: '1.625rem',
        letterSpacing: '-0.02em',
    },
    'screen-s.text.m.normal': {
        fontFamilyRef: 'fontFamily.text',
        fontWeight: '400',
        fontStyle: 'normal',
        fontSize: '1rem',
        lineHeight: '1.5rem',
        letterSpacing: '-0.02em',
    },
    'screen-s.text.m.bold': {
        fontFamilyRef: 'fontFamily.text',
        fontWeight: '600',
        fontStyle: 'normal',
        fontSize: '1rem',
        lineHeight: '1.5rem',
        letterSpacing: '-0.02em',
    },
    'screen-s.text.s.normal': {
        fontFamilyRef: 'fontFamily.text',
        fontWeight: '400',
        fontStyle: 'normal',
        fontSize: '0.875rem',
        lineHeight: '1.25rem',
        letterSpacing: '-0.02em',
    },
    'screen-s.text.s.bold': {
        fontFamilyRef: 'fontFamily.text',
        fontWeight: '600',
        fontStyle: 'normal',
        fontSize: '0.875rem',
        lineHeight: '1.25rem',
        letterSpacing: '-0.02em',
    },
    'screen-s.text.xs.normal': {
        fontFamilyRef: 'fontFamily.text',
        fontWeight: '400',
        fontStyle: 'normal',
        fontSize: '0.75rem',
        lineHeight: '1rem',
        letterSpacing: '-0.02em',
    },
    'screen-s.text.xs.bold': {
        fontFamilyRef: 'fontFamily.text',
        fontWeight: '600',
        fontStyle: 'normal',
        fontSize: '0.75rem',
        lineHeight: '1rem',
        letterSpacing: '-0.02em',
    },
    'screen-m.display.l.normal': {
        fontFamilyRef: 'fontFamily.display',
        fontWeight: '300',
        fontStyle: 'normal',
        fontSize: '7rem',
        lineHeight: '7rem',
        letterSpacing: 'normal',
    },
    'screen-m.display.l.bold': {
        fontFamilyRef: 'fontFamily.display',
        fontWeight: '600',
        fontStyle: 'normal',
        fontSize: '7rem',
        lineHeight: '7rem',
        letterSpacing: 'normal',
    },
    'screen-m.display.m.normal': {
        fontFamilyRef: 'fontFamily.display',
        fontWeight: '300',
        fontStyle: 'normal',
        fontSize: '4.5rem',
        lineHeight: '4.75rem',
        letterSpacing: 'normal',
    },
    'screen-m.display.m.bold': {
        fontFamilyRef: 'fontFamily.display',
        fontWeight: '600',
        fontStyle: 'normal',
        fontSize: '4.5rem',
        lineHeight: '4.75rem',
        letterSpacing: 'normal',
    },
    'screen-m.display.s.normal': {
        fontFamilyRef: 'fontFamily.display',
        fontWeight: '300',
        fontStyle: 'normal',
        fontSize: '3rem',
        lineHeight: '3.375rem',
        letterSpacing: 'normal',
    },
    'screen-m.display.s.bold': {
        fontFamilyRef: 'fontFamily.display',
        fontWeight: '600',
        fontStyle: 'normal',
        fontSize: '3rem',
        lineHeight: '3.375rem',
        letterSpacing: 'normal',
    },
    'screen-m.header.h1.normal': {
        fontFamilyRef: 'fontFamily.display',
        fontWeight: '400',
        fontStyle: 'normal',
        fontSize: '2.5rem',
        lineHeight: '2.875rem',
        letterSpacing: 'normal',
    },
    'screen-m.header.h1.bold': {
        fontFamilyRef: 'fontFamily.display',
        fontWeight: '600',
        fontStyle: 'normal',
        fontSize: '2.5rem',
        lineHeight: '2.875rem',
        letterSpacing: 'normal',
    },
    'screen-m.header.h2.normal': {
        fontFamilyRef: 'fontFamily.display',
        fontWeight: '400',
        fontStyle: 'normal',
        fontSize: '1.75rem',
        lineHeight: '2.125rem',
        letterSpacing: 'normal',
    },
    'screen-m.header.h2.bold': {
        fontFamilyRef: 'fontFamily.display',
        fontWeight: '600',
        fontStyle: 'normal',
        fontSize: '1.75rem',
        lineHeight: '2.125rem',
        letterSpacing: 'normal',
    },
    'screen-m.header.h3.normal': {
        fontFamilyRef: 'fontFamily.display',
        fontWeight: '400',
        fontStyle: 'normal',
        fontSize: '1.25rem',
        lineHeight: '1.625rem',
        letterSpacing: 'normal',
    },
    'screen-m.header.h3.bold': {
        fontFamilyRef: 'fontFamily.display',
        fontWeight: '600',
        fontStyle: 'normal',
        fontSize: '1.25rem',
        lineHeight: '1.625rem',
        letterSpacing: 'normal',
    },
    'screen-m.header.h4.normal': {
        fontFamilyRef: 'fontFamily.display',
        fontWeight: '400',
        fontStyle: 'normal',
        fontSize: '1.125rem',
        lineHeight: '1.5rem',
        letterSpacing: 'normal',
    },
    'screen-m.header.h4.bold': {
        fontFamilyRef: 'fontFamily.display',
        fontWeight: '600',
        fontStyle: 'normal',
        fontSize: '1.125rem',
        lineHeight: '1.5rem',
        letterSpacing: 'normal',
    },
    'screen-m.header.h5.normal': {
        fontFamilyRef: 'fontFamily.display',
        fontWeight: '400',
        fontStyle: 'normal',
        fontSize: '1rem',
        lineHeight: '1.375rem',
        letterSpacing: 'normal',
    },
    'screen-m.header.h5.bold': {
        fontFamilyRef: 'fontFamily.display',
        fontWeight: '600',
        fontStyle: 'normal',
        fontSize: '1rem',
        lineHeight: '1.375rem',
        letterSpacing: 'normal',
    },
    'screen-m.body.l.normal': {
        fontFamilyRef: 'fontFamily.text',
        fontWeight: '400',
        fontStyle: 'normal',
        fontSize: '1.125rem',
        lineHeight: '1.375rem',
        letterSpacing: '-0.02em',
    },
    'screen-m.body.l.bold': {
        fontFamilyRef: 'fontFamily.text',
        fontWeight: '600',
        fontStyle: 'normal',
        fontSize: '1.125rem',
        lineHeight: '1.375rem',
        letterSpacing: '-0.02em',
    },
    'screen-m.body.m.normal': {
        fontFamilyRef: 'fontFamily.text',
        fontWeight: '400',
        fontStyle: 'normal',
        fontSize: '1rem',
        lineHeight: '1.25rem',
        letterSpacing: '-0.02em',
    },
    'screen-m.body.m.bold': {
        fontFamilyRef: 'fontFamily.text',
        fontWeight: '600',
        fontStyle: 'normal',
        fontSize: '1rem',
        lineHeight: '1.25rem',
        letterSpacing: '-0.02em',
    },
    'screen-m.body.s.normal': {
        fontFamilyRef: 'fontFamily.text',
        fontWeight: '400',
        fontStyle: 'normal',
        fontSize: '0.875rem',
        lineHeight: '1.125rem',
        letterSpacing: '-0.02em',
    },
    'screen-m.body.s.bold': {
        fontFamilyRef: 'fontFamily.text',
        fontWeight: '600',
        fontStyle: 'normal',
        fontSize: '0.875rem',
        lineHeight: '1.125rem',
        letterSpacing: '-0.02em',
    },
    'screen-m.body.xs.normal': {
        fontFamilyRef: 'fontFamily.text',
        fontWeight: '400',
        fontStyle: 'normal',
        fontSize: '0.75rem',
        lineHeight: '0.875rem',
        letterSpacing: '-0.02em',
    },
    'screen-m.body.xs.bold': {
        fontFamilyRef: 'fontFamily.text',
        fontWeight: '600',
        fontStyle: 'normal',
        fontSize: '0.75rem',
        lineHeight: '0.875rem',
        letterSpacing: '-0.02em',
    },
    'screen-m.body.xxs.normal': {
        fontFamilyRef: 'fontFamily.text',
        fontWeight: '400',
        fontStyle: 'normal',
        fontSize: '0.625rem',
        lineHeight: '0.75rem',
        letterSpacing: '-0.02em',
    },
    'screen-m.body.xxs.bold': {
        fontFamilyRef: 'fontFamily.text',
        fontWeight: '600',
        fontStyle: 'normal',
        fontSize: '0.625rem',
        lineHeight: '0.75rem',
        letterSpacing: '-0.02em',
    },
    'screen-m.text.l.normal': {
        fontFamilyRef: 'fontFamily.text',
        fontWeight: '400',
        fontStyle: 'normal',
        fontSize: '1.25rem',
        lineHeight: '1.75rem',
        letterSpacing: '-0.02em',
    },
    'screen-m.text.l.bold': {
        fontFamilyRef: 'fontFamily.text',
        fontWeight: '600',
        fontStyle: 'normal',
        fontSize: '1.25rem',
        lineHeight: '1.75rem',
        letterSpacing: '-0.02em',
    },
    'screen-m.text.m.normal': {
        fontFamilyRef: 'fontFamily.text',
        fontWeight: '400',
        fontStyle: 'normal',
        fontSize: '1rem',
        lineHeight: '1.5rem',
        letterSpacing: '-0.02em',
    },
    'screen-m.text.m.bold': {
        fontFamilyRef: 'fontFamily.text',
        fontWeight: '600',
        fontStyle: 'normal',
        fontSize: '1rem',
        lineHeight: '1.5rem',
        letterSpacing: '-0.02em',
    },
    'screen-m.text.s.normal': {
        fontFamilyRef: 'fontFamily.text',
        fontWeight: '400',
        fontStyle: 'normal',
        fontSize: '0.875rem',
        lineHeight: '1.25rem',
        letterSpacing: '-0.02em',
    },
    'screen-m.text.s.bold': {
        fontFamilyRef: 'fontFamily.text',
        fontWeight: '600',
        fontStyle: 'normal',
        fontSize: '0.875rem',
        lineHeight: '1.25rem',
        letterSpacing: '-0.02em',
    },
    'screen-m.text.xs.normal': {
        fontFamilyRef: 'fontFamily.text',
        fontWeight: '400',
        fontStyle: 'normal',
        fontSize: '0.75rem',
        lineHeight: '1rem',
        letterSpacing: '-0.02em',
    },
    'screen-m.text.xs.bold': {
        fontFamilyRef: 'fontFamily.text',
        fontWeight: '600',
        fontStyle: 'normal',
        fontSize: '0.75rem',
        lineHeight: '1rem',
        letterSpacing: '-0.02em',
    },
    'screen-l.display.l.normal': {
        fontFamilyRef: 'fontFamily.display',
        fontWeight: '300',
        fontStyle: 'normal',
        fontSize: '8rem',
        lineHeight: '8rem',
        letterSpacing: 'normal',
    },
    'screen-l.display.l.bold': {
        fontFamilyRef: 'fontFamily.display',
        fontWeight: '600',
        fontStyle: 'normal',
        fontSize: '8rem',
        lineHeight: '8rem',
        letterSpacing: 'normal',
    },
    'screen-l.display.m.normal': {
        fontFamilyRef: 'fontFamily.display',
        fontWeight: '300',
        fontStyle: 'normal',
        fontSize: '5.5rem',
        lineHeight: '5.75rem',
        letterSpacing: 'normal',
    },
    'screen-l.display.m.bold': {
        fontFamilyRef: 'fontFamily.display',
        fontWeight: '600',
        fontStyle: 'normal',
        fontSize: '5.5rem',
        lineHeight: '5.75rem',
        letterSpacing: 'normal',
    },
    'screen-l.display.s.normal': {
        fontFamilyRef: 'fontFamily.display',
        fontWeight: '300',
        fontStyle: 'normal',
        fontSize: '4rem',
        lineHeight: '4.25rem',
        letterSpacing: 'normal',
    },
    'screen-l.display.s.bold': {
        fontFamilyRef: 'fontFamily.display',
        fontWeight: '600',
        fontStyle: 'normal',
        fontSize: '4rem',
        lineHeight: '4.25rem',
        letterSpacing: 'normal',
    },
    'screen-l.header.h1.normal': {
        fontFamilyRef: 'fontFamily.display',
        fontWeight: '400',
        fontStyle: 'normal',
        fontSize: '3rem',
        lineHeight: '3.375rem',
        letterSpacing: 'normal',
    },
    'screen-l.header.h1.bold': {
        fontFamilyRef: 'fontFamily.display',
        fontWeight: '600',
        fontStyle: 'normal',
        fontSize: '3rem',
        lineHeight: '3.375rem',
        letterSpacing: 'normal',
    },
    'screen-l.header.h2.normal': {
        fontFamilyRef: 'fontFamily.display',
        fontWeight: '400',
        fontStyle: 'normal',
        fontSize: '2rem',
        lineHeight: '2.375rem',
        letterSpacing: 'normal',
    },
    'screen-l.header.h2.bold': {
        fontFamilyRef: 'fontFamily.display',
        fontWeight: '600',
        fontStyle: 'normal',
        fontSize: '2rem',
        lineHeight: '2.375rem',
        letterSpacing: 'normal',
    },
    'screen-l.header.h3.normal': {
        fontFamilyRef: 'fontFamily.display',
        fontWeight: '400',
        fontStyle: 'normal',
        fontSize: '1.5rem',
        lineHeight: '1.875rem',
        letterSpacing: 'normal',
    },
    'screen-l.header.h3.bold': {
        fontFamilyRef: 'fontFamily.display',
        fontWeight: '600',
        fontStyle: 'normal',
        fontSize: '1.5rem',
        lineHeight: '1.875rem',
        letterSpacing: 'normal',
    },
    'screen-l.header.h4.normal': {
        fontFamilyRef: 'fontFamily.display',
        fontWeight: '400',
        fontStyle: 'normal',
        fontSize: '1.25rem',
        lineHeight: '1.625rem',
        letterSpacing: 'normal',
    },
    'screen-l.header.h4.bold': {
        fontFamilyRef: 'fontFamily.display',
        fontWeight: '600',
        fontStyle: 'normal',
        fontSize: '1.25rem',
        lineHeight: '1.625rem',
        letterSpacing: 'normal',
    },
    'screen-l.header.h5.normal': {
        fontFamilyRef: 'fontFamily.display',
        fontWeight: '400',
        fontStyle: 'normal',
        fontSize: '1.125rem',
        lineHeight: '1.5rem',
        letterSpacing: 'normal',
    },
    'screen-l.header.h5.bold': {
        fontFamilyRef: 'fontFamily.display',
        fontWeight: '600',
        fontStyle: 'normal',
        fontSize: '1.125rem',
        lineHeight: '1.5rem',
        letterSpacing: 'normal',
    },
    'screen-l.body.l.normal': {
        fontFamilyRef: 'fontFamily.text',
        fontWeight: '400',
        fontStyle: 'normal',
        fontSize: '1.125rem',
        lineHeight: '1.375rem',
        letterSpacing: '-0.02em',
    },
    'screen-l.body.l.bold': {
        fontFamilyRef: 'fontFamily.text',
        fontWeight: '600',
        fontStyle: 'normal',
        fontSize: '1.125rem',
        lineHeight: '1.375rem',
        letterSpacing: '-0.02em',
    },
    'screen-l.body.m.normal': {
        fontFamilyRef: 'fontFamily.text',
        fontWeight: '400',
        fontStyle: 'normal',
        fontSize: '1rem',
        lineHeight: '1.25rem',
        letterSpacing: '-0.02em',
    },
    'screen-l.body.m.bold': {
        fontFamilyRef: 'fontFamily.text',
        fontWeight: '600',
        fontStyle: 'normal',
        fontSize: '1rem',
        lineHeight: '1.25rem',
        letterSpacing: '-0.02em',
    },
    'screen-l.body.s.normal': {
        fontFamilyRef: 'fontFamily.text',
        fontWeight: '400',
        fontStyle: 'normal',
        fontSize: '0.875rem',
        lineHeight: '1.125rem',
        letterSpacing: '-0.02em',
    },
    'screen-l.body.s.bold': {
        fontFamilyRef: 'fontFamily.text',
        fontWeight: '600',
        fontStyle: 'normal',
        fontSize: '0.875rem',
        lineHeight: '1.125rem',
        letterSpacing: '-0.02em',
    },
    'screen-l.body.xs.normal': {
        fontFamilyRef: 'fontFamily.text',
        fontWeight: '400',
        fontStyle: 'normal',
        fontSize: '0.75rem',
        lineHeight: '0.875rem',
        letterSpacing: '-0.02em',
    },
    'screen-l.body.xs.bold': {
        fontFamilyRef: 'fontFamily.text',
        fontWeight: '600',
        fontStyle: 'normal',
        fontSize: '0.75rem',
        lineHeight: '0.875rem',
        letterSpacing: '-0.02em',
    },
    'screen-l.body.xxs.normal': {
        fontFamilyRef: 'fontFamily.text',
        fontWeight: '400',
        fontStyle: 'normal',
        fontSize: '0.625rem',
        lineHeight: '0.75rem',
        letterSpacing: '-0.02em',
    },
    'screen-l.body.xxs.bold': {
        fontFamilyRef: 'fontFamily.text',
        fontWeight: '600',
        fontStyle: 'normal',
        fontSize: '0.625rem',
        lineHeight: '0.75rem',
        letterSpacing: '-0.02em',
    },
    'screen-l.text.l.normal': {
        fontFamilyRef: 'fontFamily.text',
        fontWeight: '400',
        fontStyle: 'normal',
        fontSize: '1.5rem',
        lineHeight: '2rem',
        letterSpacing: '-0.02em',
    },
    'screen-l.text.l.bold': {
        fontFamilyRef: 'fontFamily.text',
        fontWeight: '600',
        fontStyle: 'normal',
        fontSize: '1.5rem',
        lineHeight: '2rem',
        letterSpacing: '-0.02em',
    },
    'screen-l.text.m.normal': {
        fontFamilyRef: 'fontFamily.text',
        fontWeight: '400',
        fontStyle: 'normal',
        fontSize: '1.125rem',
        lineHeight: '1.625rem',
        letterSpacing: '-0.02em',
    },
    'screen-l.text.m.bold': {
        fontFamilyRef: 'fontFamily.text',
        fontWeight: '600',
        fontStyle: 'normal',
        fontSize: '1.125rem',
        lineHeight: '1.625rem',
        letterSpacing: '-0.02em',
    },
    'screen-l.text.s.normal': {
        fontFamilyRef: 'fontFamily.text',
        fontWeight: '400',
        fontStyle: 'normal',
        fontSize: '0.875rem',
        lineHeight: '1.25rem',
        letterSpacing: '-0.02em',
    },
    'screen-l.text.s.bold': {
        fontFamilyRef: 'fontFamily.text',
        fontWeight: '600',
        fontStyle: 'normal',
        fontSize: '0.875rem',
        lineHeight: '1.25rem',
        letterSpacing: '-0.02em',
    },
    'screen-l.text.xs.normal': {
        fontFamilyRef: 'fontFamily.text',
        fontWeight: '400',
        fontStyle: 'normal',
        fontSize: '0.75rem',
        lineHeight: '1rem',
        letterSpacing: '-0.02em',
    },
    'screen-l.text.xs.bold': {
        fontFamilyRef: 'fontFamily.text',
        fontWeight: '600',
        fontStyle: 'normal',
        fontSize: '0.75rem',
        lineHeight: '1rem',
        letterSpacing: '-0.02em',
    },
});
