import path from 'path';
import {
    writeGeneratedToFS,
    ThemeTokenDataGroups,
    getThemeContent,
    generateThemesCSSFromContent,
} from '@salutejs/plasma-tokens-utils';
import type { CreateVariablesByArcheTypeProps } from '@salutejs/plasma-typo';

export const createCSSStyles = (
    srcDir: string,
    themeTokens: Record<string, ThemeTokenDataGroups>,
    typoTokens: CreateVariablesByArcheTypeProps,
) => {
    const themesDir = path.join(srcDir, 'css');
    const withKebabCase = true;
    const withDesignPrefix = true;
    const ROBO_COMMENT = '/* Generated by robots, do not change this manually! */\n';

    const content = getThemeContent(themeTokens, typoTokens, undefined, withKebabCase, withDesignPrefix);
    const result = generateThemesCSSFromContent(content);

    writeGeneratedToFS(themesDir, result, ROBO_COMMENT);
};
