export const classes = {
    dayOfWeek: 'day-of-week',
    dayDisabled: 'day-disabled',
    dayDisabledCurrent: 'day-disabled-current',
    daySideInRange: 'day-side-in-range',
    dayInRange: 'day-in-range',
    daySideLeft: 'day-side-left',
    daySideRight: 'day-side-right',
    selectableItem: 'item-selectable',
    selectedItem: 'item-selected',
    currentItem: 'item-current',
    hoveredItem: 'item-hovered',
};

export const tokens = {
    calendarBackgroundColor: '--plasma-calendar-background',
    calendarHeaderArrowContainerWidth: '--plasma-calendar-arrow-container-width',
    calendarItemBorderRadius: '--plasma-calendar-item-border-radius',
    calendarSelectedItemBackground: '--plasma-calendar-selected-item-background',
    calendarSelectedItemColor: '--plasma-calendar-selected-item-color',
    calendarSelectableItemBackgroundHover: '--plasma-calendar-selecable-item-bg-hover',
    calendarCurrentItemBorderColor: '--plasma-calendar-current-item-border-color',
    calendarCurrentItemBackgroundHover: '--plasma-calendar-current-item-bg-hover',
    calendarCurrentItemColorHover: '--plasma-calendar-current-item-color-hover',
    calendarCurrentItemChildBackgroundHover: '--plasma-calendar-current-item-child-bg-hover',
    calendarActiveItemBackground: '--plasma-calendar-active-item-bg',
    calendarActiveItemColor: '--plasma-calendar-active-item-color',
    calendarHoveredItemBackground: '--plasma-calendar-hovered-item-bg',
    calendarHoveredItemColor: '--plasma-calendar-hovered-item-color',
    calendarSeparatorBackground: '--plasma-calendar-separator-background',
    calendarRangeBackground: '--plasma-calendar-range-background',
    calendarOutlineFocusColor: '--plasma-calendar-outline-focus-color',
    calendarContentPrimaryColor: '--plasma-calendar-content-primary-color',
    calendarContentSecondaryColor: '--plasma-calendar-content-secondary-color',
};
