export {
    BodyL,
    BodyM,
    BodyS,
    BodyXS,
    BodyXXS,
    DsplL,
    DsplM,
    DsplS,
    H1,
    H2,
    H3,
    H4,
    H5,
    H6,
    TextL,
    TextM,
    TextS,
    TextXS,
} from './Typography';
export {
    addTypographRule,
    afterShortWord,
    applyQuotes,
    createTypograph,
    cyrillicTypographRules,
    dash,
    defaultTypographRules,
    detypograph,
    getTypographLocale,
    latinTypographRules,
    quotes,
    setTypographLocale,
    setTypographRules,
    typograph,
} from './typograph';
export { withTypograph } from './typograph/withTypograph';
export type { QuotesState, TypographProps, TypographRule } from './typograph';
