export const classes = {
    dropdownItemIsSelected: 'dropdown-item-is-selected',
};

export const tokens = {
    background: '--plasma-dropdown-background',
    width: '--plasma-dropdown-width',
    height: '--plasma-dropdown-height',
    borderRadius: '--plasma-dropdown-border-radius',
    paddingTop: '--plasma-dropdown-padding-top',
    paddingRight: '--plasma-dropdown-padding-right',
    paddingBottom: '--plasma-dropdown-padding-bottom',
    paddingLeft: '--plasma-dropdown-padding-left',

    itemBackground: '--plasma-dropdown-item-background',
    itemBackgroundHover: '--plasma-dropdown-item-background-hover',
    itemBackgroundSelected: '--plasma-dropdown-item-background-selected',
    itemColorSelected: '--plasma-dropdown-item-color-selected',
    itemWidth: '--plasma-dropdown-item-width',
    itemHeight: '--plasma-dropdown-item-height',
    itemPaddingTop: '--plasma-dropdown-item-padding-top',
    itemPaddingRight: '--plasma-dropdown-item-padding-right',
    itemPaddingBottom: '--plasma-dropdown-item-padding-bottom',
    itemPaddingLeft: '--plasma-dropdown-item-padding-left',
    itemMarginTop: '--plasma-dropdown-item-margin-top',
    itemMarginRight: '--plasma-dropdown-item-margin-right',
    itemMarginBottom: '--plasma-dropdown-item-margin-bottom',
    itemMarginLeft: '--plasma-dropdown-item-margin-left',

    footerBackground: '--plasma-dropdown-footer-background',
    footerWidth: '--plasma-dropdown-footer-width',
    footerHeight: '--plasma-dropdown-footer-height',
    footerPaddingTop: '--plasma-dropdown-footer-padding-top',
    footerPaddingRight: '--plasma-dropdown-footer-padding-right',
    footerPaddingBottom: '--plasma-dropdown-footer-padding-bottom',
    footerPaddingLeft: '--plasma-dropdown-footer-padding-left',
    footerMarginTop: '--plasma-dropdown-footer-margin-top',
    footerMarginRight: '--plasma-dropdown-footer-margin-right',
    footerMarginBottom: '--plasma-dropdown-footer-margin-bottom',
    footerMarginLeft: '--plasma-dropdown-footer-margin-left',

    headerBackground: '--plasma-dropdown-header-background',
    headerWidth: '--plasma-dropdown-header-width',
    headerHeight: '--plasma-dropdown-header-height',
    headerPaddingTop: '--plasma-dropdown-header-padding-top',
    headerPaddingRight: '--plasma-dropdown-header-padding-right',
    headerPaddingBottom: '--plasma-dropdown-header-padding-bottom',
    headerPaddingLeft: '--plasma-dropdown-header-padding-left',
    headerMarginTop: '--plasma-dropdown-header-margin-top',
    headerMarginRight: '--plasma-dropdown-header-margin-right',
    headerMarginBottom: '--plasma-dropdown-header-margin-bottom',
    headerMarginLeft: '--plasma-dropdown-header-margin-left',

    dividerColor: '--plasma-dropdown-divider-color',
    dividerWidth: '--plasma-dropdown-divider-width',
    dividerHeight: '--plasma-dropdown-divider-height',
    dividerMarginTop: '--plasma-dropdown-divider-margin-top',
    dividerMarginRight: '--plasma-dropdown-divider-margin-right',
    dividerMarginBottom: '--plasma-dropdown-divider-margin-bottom',
    dividerMarginLeft: '--plasma-dropdown-divider-margin-left',

    groupBackground: '--plasma-dropdown-group-background',
    groupWidth: '--plasma-dropdown-group-width',
    groupHeight: '--plasma-dropdown-group-height',
    groupPaddingTop: '--plasma-dropdown-group-padding-top',
    groupPaddingRight: '--plasma-dropdown-group-padding-right',
    groupPaddingBottom: '--plasma-dropdown-group-padding-bottom',
    groupPaddingLeft: '--plasma-dropdown-group-padding-left',
    groupMarginTop: '--plasma-dropdown-group-margin-top',
    groupMarginRight: '--plasma-dropdown-group-margin-right',
    groupMarginBottom: '--plasma-dropdown-group-margin-bottom',
    groupMarginLeft: '--plasma-dropdown-group-margin-left',
    groupLabelFontFamily: '--plasma-dropdown-group-label-font-family',
    groupLabelFontSize: '--plasma-dropdown-group-label-font-size',
    groupLabelFontStyle: '--plasma-dropdown-group-label-font-style',
    groupLabelFontWeight: '--plasma-dropdown-group-label-font-weight',
    groupLabelLetterSpacing: '--plasma-dropdown-group-label-letter-spacing',
    groupLabelLineHeight: '--plasma-dropdown-group-label-line-height',

    disabledOpacity: '--plasma-dropdown-disabled-opacity',
};
