name: Reusable workflow (Authorize)

on:
  workflow_call:

jobs:
  authorize:
    name: Approved
    runs-on: ubuntu-latest
    environment: ${{ github.event_name == 'pull_request_target' && github.event.pull_request.head.repo.full_name != github.repository && 'external' || 'internal' }}
    
    steps:
      - name: Echo
        run: |
          echo "External pull request approved by code owners"
