name: Cypress component testing

on:
  push:

jobs:
  cypress:
    runs-on: ubuntu-latest
    env:
      NPM_REGISTRY_TOKEN: ${{ secrets.NPM_REGISTRY_TOKEN }}
      COVERAGE: true
    steps: 
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'

    - name: Setup packages
      run: |
        npm install npm@6.14.17 -g
        npm i
        npx lerna bootstrap

    - name: Run Cypress CT for Plasma UI
      if: ${{ always() }}
      run: |
        npm run cy:ui:run-ct

    - name: Run Cypress CT for Plasma Web
      if: ${{ always() }}
      run: |
        npm run cy:web:run-ct

    - name: Run Cypress CT for Plasma Web B2B
      if: ${{ always() }}
      run: |
        npm run cy:b2b:run-ct

    - name: Run Cypress CT for Plasma Web B2C
      if: ${{ always() }}
      run: |
        npm run cy:b2c:run-ct

    - name: Run Cypress CT for Plasma temple
      if: ${{ always() }}
      run: |
        npm run cy:temple:run-ct

    - name: Save artifacts
      if: ${{ failure() }}
      uses: actions/upload-artifact@v2
      with:
        name: Test Artifacts
        path: /home/runner/work/plasma/plasma/cypress

    - name: Code Coverage UI
      if: ${{ always() }}
      uses: codecov/codecov-action@v2
      with:
        directory: cypress/plasma-ui-coverage
        flags: plasma-ui,plasma-core

    - name: Code Coverage WEB
      if: ${{ always() }}
      uses: codecov/codecov-action@v2
      with:
        directory: cypress/plasma-web-coverage
        flags: plasma-web,plasma-core

    - name: Code Coverage B2C
      if: ${{ always() }}
      uses: codecov/codecov-action@v2
      with:
        directory: cypress/plasma-b2c-coverage
        flags: plasma-b2c,plasma-core

    - name: Code Covarege Temple
      if: ${{ always() }}
      uses: codecov/codecov-action@v2
      with:
        directory: cypress/plasma-temple-coverage
        flags: plasma-temple
