name: 'Component performance testing result processing'

on:
  workflow_call:

jobs:
  run:
    runs-on: ubuntu-latest

    env:
      NPM_REGISTRY_TOKEN: ${{ secrets.NPM_REGISTRY_TOKEN }}
      PR_NAME: pr-${{ github.event.number }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Cache dependencies
        id: cache-npm
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            ~/.cache
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            npm-${{ hashFiles('package-lock.json') }}
            npm-

      - name: Setup packages
        if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        run: npm ci --no-progress

      - name: Download a artifact by pr
        uses: actions/download-artifact@v3
        with:
          name: perftest-artifact-pr-${{ github.head_ref }}
          path: /home/runner/work/plasma/plasma/perftest

      - name: Download a artifact by ${{ github.event.pull_request.base.ref }}
        uses: actions/download-artifact@v3
        with:
          name: perftest-artifact-base-${{ github.head_ref }}
          path: /home/runner/work/plasma/plasma/perftest

      - name: Compare test results
        run: >
          npx perftool-compare
          -o perftest/comparison.json
          perftest/pr-result.json
          perftest/base-result.json

      - name: Save comparison result
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: Component performance comparison result
          path: /home/runner/work/plasma/plasma/perftest/*.json

      - name: Post result comment
        if: always()
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GH_TOKEN}}
          script: |
            let report = require('/home/runner/work/plasma/plasma/perftest/comparison.json');
            let result = report.hasSignificantNegativeChanges
                ? '🔴 Fail'
                : '🟢 Success'
            let commentBody = `
            **Component performance testing**

            Result: **${result}**

            Check out report in job artifacts!
            `;

            const resultsByMetric = Object.entries(report.result).reduce((acc, [key, item]) => {
                const metrics = Object.entries(item);

                metrics.forEach(([metricName, metric]) => {
                    if (!metric.mean.change || metric.mean.change.significanceRank !== 'high') {
                        return;
                    }

                    if (acc[metricName]) {
                        acc[metricName].push({
                            report: `${key}: ${metric.mean.change.percentage.toFixed(2)}%`,
                            percentage: metric.mean.change.percentage,
                        });

                        return;
                    }

                    acc[metricName] = [
                        {
                            report: `${key}: ${metric.mean.change.percentage.toFixed(2)}%`,
                            percentage: metric.mean.change.percentage,
                        },
                    ];
                });

                return acc;
            }, {});

            const metrics = Object.values(resultsByMetric);

            metrics.forEach((item) => item.sort((a, b) => Math.abs(b.percentage) - Math.abs(a.percentage)).splice(5));

            const metricsReport = Object.entries(resultsByMetric).reduce((acc, [name, item]) => {
                if (item.length > 0) {
                    acc += `\nTop 5 significant ${name} changes:\n`;
                    acc += item.map((it) => it.report).join('\n');
                }

                return acc;
            }, '');

            commentBody += metricsReport;

            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: commentBody,
            });

      - name: Send report
        run: >
          ./scripts/perftool-send-report.js
          --reportPath /home/runner/work/plasma/plasma/perftest/comparison.json
        env:
          GITHUB_SHA: ${{ github.sha }}
