name: Release SBCOM next branch

on:
  workflow_dispatch:
    inputs:
      branch:
          description: "Branch for next tag"
          required: true
          default: 'next-sbcom'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    name: Release SBCOM next branch
    if: github.ref == 'refs/heads/next-sbcom'
    uses: ./.github/workflows/publish-common.yml
    with:
      auto-options: '--no-changelog'
    secrets:
      gh_token: ${{ secrets.GH_TOKENS }}
      npm_registry_token: ${{ secrets.NPM_REGISTRY_TOKEN }}
