name: Release INSOL next branch

on:
  workflow_dispatch:
    inputs:
      branch:
          description: "Branch for next tag"
          required: true
          default: 'next-insol'

jobs:
  publish:
    name: Publish feature version
    if: github.ref == 'refs/heads/next-insol'
    uses: ./.github/workflows/publish-common.yml
    with:
      auto-options: '--no-changelog'
    secrets:
      gh_token: ${{ secrets.GH_TOKEN }}
      npm_registry_token: ${{ secrets.NPM_REGISTRY_TOKEN }}
