name: Build theme-builder

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      NPM_REGISTRY_TOKEN: ${{ secrets.NPM_REGISTRY_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - name: Prepare repository
        run: git fetch --unshallow --tags

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Cache dependencies
        id: cache-npm
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            ~/.cache
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            npm-${{ hashFiles('package-lock.json') }}
            npm-

      # ToDo: https://github.com/salute-developers/plasma/issues/255
      - name: Setup packages
        if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        run: npm ci --no-progress

      - name: Prepare directory build
        run: mkdir -p s3_build

      # 2 папки, так как названия разные - в первом случае нужно для replace
      - name: Build Theme Builder
        env:
          REACT_APP_APPLICATION_CLIENT_ID: ${{ secrets.REACT_APP_APPLICATION_CLIENT_ID }}
          REACT_APP_AUTH_SERVER_URL: ${{ secrets.REACT_APP_AUTH_SERVER_URL }}
        run: |
          npm i --no-progress --prefix="./website/plasma-theme-builder"
          npm run build --prefix="./website/plasma-theme-builder"
          cp -R ./website/plasma-theme-builder/build ./s3_build/plasma-theme-builder-next

      - name: Install s3cmd
        run: |
          pip3 install s3cmd

      - name: s3 Upload build
        run: >
          s3cmd
          --access_key ${{ secrets.AWS_ACCESS_KEY_ID }}
          --secret_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          --host ${{ secrets.AWS_ENDPOINT }}
          --host-bucket ${{ secrets.AWS_ENDPOINT }}
          --bucket-location ${{ secrets.AWS_REGION }}
          --signature-v2
          --delete-removed
          --no-mime-magic
          sync
          ./s3_build/plasma-theme-builder-next/
          s3://${{ secrets.AWS_S3_BUCKET_2 }}/plasma-theme-builder/
