export const GENERATE_MESSAGE_FOR_CSS = '/* Generated by robots, do not change this manually! */\n';

export const webBreakpoints = {
    screenS: {
        from: 559,
        to: undefined,
    },
    screenM: {
        from: 560,
        to: 959,
    },
    screenL: {
        from: undefined,
        to: 960,
    },
};
